### ISSUE TITLE
One EKS cluster not clickable in the UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#10043]
Internal reference: SURE-7035
Reported in 2.7.6

Issue description:
The cluster EKS eks-entsvcs-pci-dev (cluster ID: c-nqdv4) is not clickable from the explorer after Rancher upgrade from 2.6.12 to 2.7.6

Business impact:
The user can't click on that cluster from the explorer

Troubleshooting steps:
    reviewed the rancher pods and cluster agent logs
    rolling restart of rancher pods
    re-deployed the cluster agents

Repro steps:
Support was not able to reproduce it, but the user wants to know what is causing this behavior 

Workaround:
None

Using the cluster management or directly accessing the link for that cluster with something like this https://hostname/dashboard/c/c-xxxxx/explorer

Actual behavior:
A cluster is not clickable from the explorer

Expected behavior:
A cluster should be and clickable when it is Active in Rancher

Addenda:
- Logs & HAR files available via the SURE ID.

**Comment by realhuseyn** [comment]
Any updates? I have faced this issue

**Comment by aalves08** [comment]
Going through the code in 2.7.6 and looking at the json file (which I believe it represents the cluster in question - provided via SURE ID) there's one condition that is missing there, which is the property `status.clusterName`, which is important to control the disable/enable of the side menu links.

![Screenshot 2023-12-18 at 17 04 28](https://github.com/rancher/dashboard/assets/97888974/95ed6c84-fc02-47f4-95d7-3acf8601bb34)


We start off by checking which property controls the enable/disable of the side menu, which is the property `ready`:
![Screenshot 2023-12-18 at 16 51 13](https://github.com/rancher/dashboard/assets/97888974/9049cdbf-7e0c-47b4-82c8-db83ca13b6bf)

The `ready` depends on the `isReady` model property and if the provisioning cluster has errors `hasError`:
![Screenshot 2023-12-18 at 16 54 14](https://github.com/rancher/dashboard/assets/97888974/f8dff07a-6795-4b36-8ff2-ce6c55669980)

The `isReady` is basically the `isReady` of it's management counterpart, but in order to fetch the `mgmt` counterpart, we need the `status.clusterName` as stated on line 294:
 
![Screenshot 2023-12-18 at 16 54 34](https://github.com/rancher/dashboard/assets/97888974/b7cd8e8f-799e-44ed-bee0-4576725e874c)

Going through the available json file that represents the cluster (check SURE ID), I cannot find any `clusterName` property, thus making the link not available from the main menu (disabled).

It seems that the workaround works (direct link to https://hostname/dashboard/c/c-xxxxx/explorer) because the management cluster exists and the `isReady` condition is verified there:

```
get isReady() {
    // If the Connected condition exists, use that (2.6+)
    if ( this.hasCondition('Connected') ) {
      return this.isCondition('Connected');
    }

    // Otherwise use Ready (older)
    return this.isCondition('Ready');
  }
```

The only thing that is missing is the connection between the provisioning cluster and the management cluster, which is missing from the `status` property (`clusterName`). I guess that since this was running in a fairly older version of Rancher the spec of the provisioning cluster must have evolved during the time since it was first generated.

Is there any action point to take out of this issue for the UI team @gaktive, @nwmac or @richard-cox ?

**Comment by aalves08** [comment]
Going through the code in 2.7.6 and checking the objects provided in the JSON and HAR files for both the `management` and `provisioning` clusters, the homepage and side menu links are disabled because the `management` object has a `condition` with `error: true` there which is needed for enabling the homepage link https://github.com/rancher/dashboard/blob/release-2.7.6/shell/models/management.cattle.io.cluster.js#L173-L181 and the side menu https://github.com/rancher/dashboard/blob/release-2.7.6/shell/models/provisioning.cattle.io.cluster.js#L863-L865.

The workaround (direct link to `/explorer`) works because the authenticated middleware is just checking for `isReady` on the management cluster https://github.com/rancher/dashboard/blob/release-2.7.6/shell/models/management.cattle.io.cluster.js#L173-L181, which in turn has the correct checks for it to work.

The question here is: which is correct set of condition for us to check for both links?

**Comment by aalves08** [comment]
The `explore` button on `Cluster Managament` should also be disabled since:

`row.mgmt && row.mgmt.isReady && !row.hasError` where `row` is of type `provisioning cluster`=> fails because prov cluster has a `status.condition` with `error: true` => side menu https://github.com/rancher/dashboard/blob/release-2.7.6/shell/models/provisioning.cattle.io.cluster.js#L863-L865. 🛑   fails on `row.hasError`

**Comment by izaac** [comment]
@yonasberhe23 the test coverage looks good to me, the scenario is really hard to reproduce for a manual validation after going through the issue comments. We can move to done.
