### ISSUE TITLE
UI does not get updated when upgrading the local RKE2 cluster w/ AWS external tree provider config

### ISSUE THREAD

**Issue by IsaSih** [rancher/dashboard#10414]
**Setup**
- Rancher version: v2.7.11-798b3da89d6c71f8a30994c0bd7303a755ae55a8-head

- Browser type & version: Chrome 120.0.6099.199 (Official Build) (arm64)

**Describe the bug**
Rancher UI is not updating when upgrading local RKE2 clusters to Kubernetes version 1.27+ (version 1.27.8 precisely).

**To Reproduce**
1. Install Rancher on a 3-node v.1.24.17+rke2r1 cluster (Amazon EC2 nodes) via helm
2. From the UI, go to **Cluster Management** > Select the local cluster from the 3-dot button, select **Edit Config**
3. Upgrade the local cluster from version 1.24.17 to 1.27.8 and observe the UI behavior.

**Result**
The UI does NOT display any warning messages and does not update when the Kubernetes version is upgraded to 1.27+
**Expected Result**
 It is expected that the UI displays a warning message instructing the user to configure a cloud-controller manager for the out-of-tree architecture, as the in-tree architecture is no longer supported for Kubernetes versions higher than 1.27, with a link to the docs that explain how to configure the cloud-controller manager. 
Docs: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/migrate-to-an-out-of-tree-cloud-provider/migrate-to-out-of-tree-amazon

**Additional Info**:
The local cluster successfully restarts with the upgrade and doesn't seem to be malfunctioning.

**Comment by IsaSih** [comment]
Found while testing https://github.com/rancher/dashboard/issues/9204

**Comment by gaktive** [comment]
@mantis-toboggan-md let me know if we have to backport this to 2.7.patch1 and/or 2.8.next1

**Comment by gaktive** [comment]
Possible duplicate to https://github.com/rancher/dashboard/issues/10290 though rereading

**Comment by rak-phillip** [comment]
For the record, we've deployed a Rancher instance to AWS on RKE2 with the in-tree provider configured, targeting v1.24.17+rke2r1. I would expect to see something to indicate that the in-tree cloud provider has been configured in `/v3/clusters/local`, but nothing is present here. We will need to sync with somebody on the backend team to see if it's possible to retrieve the data we need to satisfy this issue. I'm moving this to backend blocked for the time being, until we've had this opportunity to discuss further.

Alternatively, we can consider displaying a generic message based solely on the selected kubernetes version. This might not be the ideal solution, but it could allow us to communicate that there could be issues associated with upgrading to 1.27+ if an in-tree cloud provider had been configured in the past.

@IsaSih @izaac @gaktive

**Comment by rak-phillip** [comment]
Following up on this issue with conversations that we had out of bound.

We have confirmed that the local cluster will have no way to display the information that we need to satisfy this request. Since the local cluster is an imported cluster, Rancher will not be able to retrieve details that will allow us to determine if it is using an in-tree cloud provider.

We will move forward with the alternative approach described in my previous comment. The goal is to check the current version and compare with the target version. If the current version is less than 1.27 and the target version is greater than or equal to 1.27, we will display a informational message to help users determine if they need to take action. If the current version is 1.27 or above, this message will not display.
