### ISSUE TITLE
Allow switching between down stream clusters with a dropdown menu

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10452]
Internal Reference: SURE-3657

Proposal is to make a change so that when changing cluster via the side bar, if the user holds down the Shift key, we will keep the current view - i.e. if you are looking at secrets, we will take you to the secrets view of the new cluster.

Should be able to write automated tests if we have a fake 2nd cluster.

**Comment by aalves08** [comment]
Some questions regarding this issue:

@nwmac @scures how can we check for `We try to navigate to the cluster's route (replacing cluster_id). If this fails because the cluster does not have the same route (different type of cluster) we default to c/CLS_ID/explorer and we display a Toast explaining the reasons`? 🤔 

There's this whole mechanism around `fail-whale`, which is handled by vue router, which would need to be circumvented to handle this in case of a "click" in the main nav menu (which is a "normal" vue link). Can this even be achieved? Is it a must have for this issue?

**Comment by yonasberhe23** [comment]
e2e test coverage LGTM @izaac
