### ISSUE TITLE
Cluster Tools: Remove support for installing legacy v1 tools

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10488]
v1 tools (monitoring etc) are being removed.

With the `legacy` feature flag enabled, Cluster Tools shows card for installing legacy v1 tools:

<img width="1159" alt="image" src="https://github.com/rancher/dashboard/assets/1955897/c96cfe65-8dee-45ec-b100-6f8a0604b031">

(this shows `Monitoring (Legacy)`)

We should:

- Not show the legacy cards to install v1 tools any longer
- Continue to show the legacy cards ONLY when the v1 tool is already installed - to allow the user to uninstall the v1 tool in preparation for installing the v2 tool

**Comment by codyrancher** [comment]
@nwmac the legacy monitoring management in ember is entirely broken. If we want to "_Continue to show the legacy cards ONLY when the v1 tool is already installed - to allow the user to uninstall the v1 tool in preparation for installing the v2 tool_" it looks like we'll actually need to fix a handful of things including backend changes.

I'm going to outline the issues that I found and suggest that we remote the legacy monitoring option all together (If we haven't heard complaints I doubt anyone is using it anymore since management isn't functional)

1. We currently tell the user that they aren't authenticated to manage monitoring even if it's an admin account. And we link to the wrong docs.

https://github.com/rancher/dashboard/assets/55104481/82add18a-2942-4784-92b7-280d9f88354c

2. We don't show the correct docs in vue on the cluster tools page either

https://github.com/rancher/dashboard/assets/55104481/9ae18354-ab8f-4ba6-aaf9-a430e6a75f82

3. We disable the "contemporary" monitoring install button without explanation as to why

https://github.com/rancher/dashboard/assets/55104481/532421f1-67ea-4c70-a1fb-d2c335e87877

4. The reason the UI thinks we don't have permission to manage legacy monitoring and why we would need backend changes is because in previous versions of rancher we provided these cluster actions 'disableMonitoring', 'editMonitoring', 'viewMonitoring'.
  - v2.5-head
![Screenshot 2024-03-02 213923](https://github.com/rancher/dashboard/assets/55104481/67001bf1-fe87-433a-9232-f3b4ed4da576)
  - v2.9-head
![Screenshot 2024-03-01 115928](https://github.com/rancher/dashboard/assets/55104481/a80a6f36-e015-49ed-9b9d-83e7337ab00b)

If you'd like me to remove legacy let me know and I'll publish a PR. Otherwise I think we're going to need to coordinate with backend (prolly need to just to have a workaround).

**Comment by nwmac** [comment]
@codyrancher I think we just remove legacy. The backend support is completely gone and there are no charts, so I'd just say remove.

**Comment by yonasberhe23** [comment]
@nwmac I don't see any e2e test for this but maybe it's not necessary since we're just removing legacy apps? lmk if we need tests, I can take it on. In the meantime, I'll move this to 'To Test' for quick sanity check @izaac

**Comment by IsaSih** [comment]
Tests pass on v2.9-3a426b5ba059358f8874573c0a98d01bfda25a47-head
