### ISSUE TITLE
EKS: Validate node group min/max/desired values

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#10510]
Internal Reference: SURE-5957

When creating an EKS cluster, it's possible to define an invalid amount of min/desired, this creates the cluster, but fails due with validation from the AWS API.{}

This will be done as part of the port of EKS to Vue.

**Comment by cpinjani** [comment]
Validation for nodegroup ASG size is missing on build `v2.9-81337b95660cba868629d6fe769bd7e8242b5aee-head, Dashboard - master 3da1205`
Hence cluster provisioning is allowed with invalid values and it eventually fails:

![image](https://github.com/user-attachments/assets/0ca5d8e6-b69c-4500-81f2-20c33656d5c0)

**Comment by thehejik** [comment]
**Test report**

Validated on rancher `v2.9-637346f76ea2bb71a82ea6e00a2779f61610a2a4-head`

The problem seems to be fixed for EKS provisioning.

**Before** the change on dashboard `v2.9.0-alpha7` there is no import field validation involved:
![pasted_image008](https://github.com/user-attachments/assets/9d103833-94de-43e2-aff3-09f19ba71d0e)

**After** the change on dashboard `master ddd2dee` the validation seems to be in place and it won't let user create a cluster with wrong values.

![pasted_image007](https://github.com/user-attachments/assets/1e8ed6c2-5aea-464f-a6b2-4f667b74bfa9)

![pasted_image006](https://github.com/user-attachments/assets/7189b4ce-6959-430e-b775-7992c1d20b29)
