### ISSUE TITLE
Unable to cancel request for *client.addQuery\n","stream":"stderr"

### ISSUE THREAD

**Issue by nanited** [rancher/dashboard#10769]
Hi Team,

Which is the suitable version where we can avoid this issue, I have observed that UI slowness issue was there in multiple versions. 

I have observed in 2.6.x versions.
and the recent post: https://github.com/rancher/dashboard/issues/10735

Will you help me with that please ?

Thank you in advance.

**Comment by richard-cox** [comment]
There have been many different performance improvements since 2.6, both core and optional (in the new Settings --> Performance tab) throughout many different parts of the UI. More are coming in 2.9 and planned for afterwards.

Please can you open separate gh issues detailing each of the performance issues you're seeing? Please can you provide as much information as you can, the more detail the more likely we can address them.
