### ISSUE TITLE
Modal shown whilst waiting for Rancher to restart given Feature Flag change is broken

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11087]
**Setup**
- Rancher version: pre 2.9.0

**Describe the bug**
- Feature Flags that require rancher to restart show a warning modal before changing the setting
- Upon executing the change the modal should remain open until Rancher comes back up
- The modal however goes away i think once FF api request completes
- UI is unresponsive given Rancher is restarting
- When rancher comes back up it looks like we continue polling
- User is unable to activate/deactive any other FF (guessing because it thinks the modal is shown) without refreshing

**To Reproduce**
- Global Settings --> Feature Flags
- `Activate` `provisioningv2-fleet-workspace-back-population`
  - This shows modal

**Result**
- as per description

**Expected Result**
- Modal remains until rancher comes back up, and then polling stops

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/18697775/ba24257c-b2a2-4050-b77e-a254cc47ad1d)

**Additional context**
- Could be a regression in 2.9.0... or before

**Comment by rak-phillip** [comment]
I'm finding that the modal is dismissed because we get a 200 response from the backend in the method `waitForBackend()`

https://github.com/rancher/dashboard/blob/6e939ba4f80f150fcf452d3a13a89f8260a85ba4/shell/list/management.cattle.io.feature.vue#L158-L175

It might just be that the Rancher Backend is taking longer to stop. I'm finding that increasing the timeout to 5 seconds appears to resolve the issue, but that solution sounds kind of arbitrary to me..

**Comment by rak-phillip** [comment]
Based on the nature of the root cause for this issue, I'm removing the `QA/dev-automation` label. I think that e2e tests will be too time consuming since we require waiting for the Rancher backend to restart. 

I'm willing to investigate alternative approaches if we feel that they would benefit this issue.

**Comment by IsaSih** [comment]
When testing the issue, the modal hangs in a loading state with the UI frozen. According to the logs, there are repeated errors that the certificate is invalid ERR_CERT_AUTHORITY_INVALID, as seen in the screenshot. By logging out and logging back into Rancher, the UI is interactive and the feature flag is enabled. Same behavior occurs when disabling the feature flag. However, this is not the expected behavior. I'm moving the issue back to To do.

![Image](https://github.com/rancher/dashboard/assets/70187881/3a43985a-ae03-4041-a9be-e383b0649eca)

**Comment by IsaSih** [comment]
retried it in a new env with valid certificate and modal is working as expected. Tested on v2.9-3ae1c6ac8d3524f8ded4544f1db75fc9e07911a5-head.
