### ISSUE TITLE
Unable to add extension tab to Edit Storage Class page

### ISSUE THREAD

**Issue by sumeetsethy** [rancher/dashboard#11122]
I am developing a new extension for Portworx and as a usecase, i need to add a new tab in StorageClass tabSection.
<img width="1512" alt="Screenshot 2024-05-25 at 12 03 21 AM" src="https://github.com/rancher/dashboard/assets/170758832/4587ef5b-c1f7-4f31-98fd-9d530132f17a">

I have added the below code in my index.ts

<img width="822" alt="image" src="https://github.com/rancher/dashboard/assets/170758832/420119f3-63de-4ec8-b933-17b9bb8da70b">

The same code is able to add a new tab when i give resourceType as persistentvolumeclaim or some other resource type. but for storageClass it fails.

<img width="1512" alt="image" src="https://github.com/rancher/dashboard/assets/170758832/9968f7d1-03fc-4958-80c8-d1ef97796faa">

Let me know if i am missing anything.

**Comment by aalves08** [comment]
Gm @sumeetsethy . 

The documentation for adding Tabs through Extensions is clear on what is the expected location where those tabs will be added https://extensions.rancher.io/extensions/api/tabs , which is the details page of the given resource(s) you've defined on the function.

Currently we don't support adding Tabs for edit views, but for sure it's a good enhancement to the Extensions api. 

Thank you for filling this issue. I'll mark this as an `enhancement` request so that we can add this new location.

**Comment by sumeetsethy** [comment]
Thanks @aalves08 
Please do keep me in loop on the progress of this ticket.

**Comment by richard-cox** [comment]
When investigating https://github.com/rancher/dashboard/issues/12069 the answer isn't clear

- ResourceDetails page controls both view and edit of components. Components with custom forms will contain an edit component 
- Some edit components contain ResourceTabs
  - ResourceTabs pulls in the extension points for TabLocation.RESOURCE_DETAIL
    - https://github.com/rancher/dashboard/blob/master/shell/components/form/ResourceTabs/index.vue#L80
    - https://github.com/rancher/dashboard/blob/master/shell/components/form/ResourceTabs/index.vue#L251-L268
  - I couldn't see where we discern between view and edit though
  - So for resources like persistentvolumeclaim tabs meant for just a detail page we also also shown them in edit views
- Some edit components, like shell/edit/storage.k8s.io.storageclass/index.vue don't pull in ResourceTabs, just Tabbed (i don't think this extension points)
