### ISSUE TITLE
UI for backup-restore-operator Backup CRD

### ISSUE THREAD

**Issue by mrajashree** [rancher/dashboard#1124]
In order to perform backup, user needs to create an instance/CR of the Backup CRD. When a backup CR is created, the backup controller will start processing it and create a backup by gathering all resources specified in the backup CR's ResourceSet.

Header / Label Name | k8s YAML | Input | Default | Required
-- | -- | -- | -- | -- 
StorageLocation | spec.storageLocation | See Storage location (defined below) | nil |
ResourceSetName | spec.resourceSetName | String | nil | ✅  
EncryptionConfigName | spec.encryptionConfigName | String | nil |
Schedule | spec.schedule | String | nil |
RetentionCount | spec.retentionCount | Integer | 10 |

**StorageLocation**
Header / Label Name | k8s YAML | Input | Default
-- | -- | -- | --
S3 | spec.s3 | See S3ObjectStore | nil

**S3ObjectStore**
Header / Label Name | k8s YAML | Input | Default 
-- | -- | -- | --
Endpoint | spec.s3.endpoint | String | nil
EndpointCA | spec.s3.endpointCA | String | nil 
InsecureTLSSkipVerify | spec.s3.insecureTLSSkipVerify | Boolean | nil
CredentialSecretName | spec.s3.credentialSecretName | String | nil
BucketName | spec.s3.bucketName | String | nil
Region | spec.s3.region | String | nil
Folder | spec.s3.folder | String | nil

The `EncryptionConfigName` field on Backup spec, is the name of a kubernetes Secret, that contains the encryptionConfig file. This same encryptionFile is needed while restoring from a backup. It is up to the user to save their encryptionConfig file contents properly, as it will not be stored by the backup-restore-operator. So if user looses this encryptionConfig file, restore will fail. We should add a warning above this field in the UI indicating that user is responsible for saving contents of the encryptionConfig file, and must use the same file when restoring from this backup.
NOTE: The secret that contains this encryption config file can be named something else, the contents must stay same

**Comment by lvuch** [comment]
https://xd.adobe.com/view/c1f410d5-d7d1-471b-ba03-ab47267604e3-94a7/

**Comment by mrajashree** [comment]
The encryptionConfig field, is the name of a kubernetes Secret, that contains the [encryptionConfig file](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/). This same encryptionFile is needed while restoring from a backup. It is up to the user to save their encryptionConfig file properly, as it will not be stored by the backup-restore-operator. So if user looses this encryptionConfig file, restore will fail. We should add a warning above this field in the UI indicating that user is responsible for saving contents of the encryptionConfig file, and must use the same file when restoring from this backup.

**Comment by mrajashree** [comment]
Can we remove the "Description" Box, and "Labels and Annotations" section for this CRD too?
The fields we want to display for sure are:
<img width="693" alt="Screen Shot 2020-09-03 at 4 00 31 PM" src="https://user-images.githubusercontent.com/10672776/92181772-ea80b100-edfe-11ea-9bcb-841dd12c6cb3.png">
In the "Schedule" field, either in it or below it, can we show examples of what is allowed? So can the schedule field have `'@midnight'` and `'* * * * ?'` as examples?

S3 details are not a required field. The way this operator works is, user can configure a global backup location while launching/upgrading the operator (helm chart).
OR
User can specify a particular s3 bucket to restore from/backup to. So, after the first set of fields, this is what I think we should have

Select Storage Location
(Radio buttons)
* Option 1: Use the Backup location configured at the operator level. (Note: Right now there is no way of displaying the exact value in UI)
* Option 2: Specify details of the s3 compatible storage provider where the backup file should get stored (s3/minio)
   If this option is selected, then we show the fields to configure s3.

**Comment by mrajashree** [comment]
On master-head 6a6f13cec

1. The "Schedule" field should not have the increment/decrement arrows, because if I click on it it just sets schedule to an integer, thus setting it to an invalid cron value so operator can't parse it
<img width="597" alt="Screen Shot 2020-09-11 at 10 44 14 AM" src="https://user-images.githubusercontent.com/10672776/92956698-31ccfa00-f41c-11ea-9f8a-da927ab16171.png">

2. "Encrypt backups using an encryption config secret" does not show a dropdown for secrets. I also see this error in the console
<img width="1034" alt="Screen Shot 2020-09-11 at 10 48 18 AM" src="https://user-images.githubusercontent.com/10672776/92956844-6ccf2d80-f41c-11ea-9f46-32c20b1458dd.png">



These are some changes I'd like to request, that aren't causing bugs but would be good to have:
1. Can we show the "Retention Count" field only if the "Schedule" field is filled?

**Comment by deniseschannon** [comment]
*Create Page*  
- [ ] When creating the first backup, a red error shows up about no having resourceset, but then disappears when it's finally loaded. On other pages that load inputs from resources, it's not so slow. How are you handling it compared to others?
- [ ] If there is only 1 resourceset, default to have that one selected. 
- [ ] Since schedule is optional, the schedule concept should convert to an option for one time backup and scheduled backups. Is a one time backup an empty schedule @mrajashree 
```
* One Time Backup 
* Schedule Backups
```
- [ ] What is supposed to happen if I select encrypt backups? Does the encryption configuration need to already exist? Maybe we should add *(Recommended)* to the encrypt option. 
- [ ] If i've selected ("Encrypt backups"), then the options for storage location don't show/hide the S3 fields correctly. 


*Detail Page*
- [ ] Radio buttons are still editable

**Comment by mrajashree** [comment]
> Since schedule is optional, the schedule concept should convert to an option for one time backup and scheduled backups. Is a one time backup an empty schedule

yes, if the schedule field is not set at all then its a one-time backup

**Comment by mrajashree** [comment]
validated on master-head sept 21
I can see all changes discussed above are included, and the yaml fields are filled correctly too.
One small bug, clicking on `Encryption Config Secret` does not open the k8s docs page that the link 
<img width="506" alt="Screen Shot 2020-09-21 at 11 00 20 PM" src="https://user-images.githubusercontent.com/10672776/93848405-587e0280-fc5e-11ea-868c-2798f798e5f6.png">

**Comment by mrajashree** [comment]
Encrypting backups works now. But while configuring s3, the field "Endpoint CA" "Read from File" does not get the contents of the file. I can directly copy-paste and that works @mantis-toboggan-md

**Comment by mrajashree** [comment]
I was able to perform backups using the form. And then after sometime whenever I go to Create Backup page I see this, although the default resource-set does exist
<img width="1436" alt="Screen Shot 2020-09-22 at 2 49 07 PM" src="https://user-images.githubusercontent.com/10672776/93941237-dedc2800-fce2-11ea-91fd-89dea96061ce.png">

**Comment by sowmyav27** [comment]
**On** master-head- commit id: `2229f5cd`

Issues seen: 

**Issue#1**
- From this issue's original comments, we need a warning on theUI - `We should add a warning above this field in the UI indicating that user is responsible for saving contents of the encryptionConfig file, and must use the same file when restoring from this backup.` Currently this is NOT available

**Issue#2**
- For `Encryption Config Secret` to be listed in the dropdown, the secret has to be created with key “encryption-provider-config.yaml”. This should be made obvious on the UI. Can we add a note in the UI ? 
<img width="911" alt="Screen Shot 2020-09-23 at 10 06 52 AM" src="https://user-images.githubusercontent.com/26032343/94046135-23b89b00-fd85-11ea-8c62-62d65d3e854f.png">

Blocked because of the other issue - https://github.com/rancher/dashboard/issues/1019

**Comment by deniseschannon** [comment]
Closing this in favor of the individual issues logged
