### ISSUE TITLE
Replace vue-virtual-scroll-list with a Vue3 compatible library

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#11486]
# Description

The `vue-virtual-scroll-list` dependency is not Vue3 savvy and needs to be replaced. The Vue3 fork seems to actually not work properly.
Proposed: https://primevue.org/virtualscroller/

**Comment by eva-vashkevich** [comment]
primeVue doesn't have virtual scroller in Vue 2.
I ended up using https://github.com/Akryum/vue-virtual-scroller/tree/v1/packages/vue-virtual-scroller but it has some differences with the package we are using now, so I am still working on replacement.

**Comment by eva-vashkevich** [comment]
Hi @cnotv and @nwmac, I don't think there is an adequate library that works with both Vue2 and Vue3. I have a draft PR that uses vue-virtual-scroller, but the follow behavior makes it laggy. Is it okay to revisit this after Vue 3 migration since that will give up more options? (ie primevue virtualscroller)?

**Comment by cnotv** [comment]
It would be more convenient to work directly with Vue3, since we are close to merge next week.
You could try to add it to [this branch](https://github.com/rancher/dashboard/tree/vue3-depth-first) for now with what you have. This candidate will be merged to `master` and can be switched later.
