### ISSUE TITLE
v2.9: Validation required to check at least one nodegroup is present while editing cluster

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#11570]
**Rancher version:**
Rancher version: v2.9-d2fa8a7d6116c48a814ee7983af522d614461e49-head
eks-operator: v1.9.0-rc.9

Cluster Type: Downstream EKS cluster

**Describe the bug:**
Validation required to check atleast one nodegroup is present in cluster, same as in 2.8 below
![image](https://github.com/rancher/eks-operator/assets/73099870/7ac5ded1-6ad7-4f87-9ba1-6fbf2a0878cd)

**Steps**
- Provision EKS cluster from Rancher with one nodegroup
- Edit cluster and remove all nodegroup and Save the config
- eksConfig shows `nodeGroups: null`

**Comment by gaktive** [comment]
This may not be a true regression. @mantis-toboggan-md to dig into things more here.

**Comment by mantis-toboggan-md** [comment]
I'm not sure that we can validate this in the UI any longer because the eks operator now supports importing clusters with exclusively self-managed nodes https://github.com/rancher/eks-operator/issues/301 - these clusters would have `eksConfig.nodeGroups: null` . I wasn't able to determine a way of distinguishing between imported EKS clusters with self-managed nodes and incorrectly rancher-provisioned clusters with no managed nodes defined.

**Comment by gaktive** [comment]
@mjura based on the most recent comment, is there a way for the UI to tell the difference with those node types in the new import model?

**Comment by mjura** [comment]
> @mjura based on the most recent comment, is there a way for the UI to tell the difference with those node types in the new import model?

This can be verified by checking `spec.eksConfig.imported`  `true` when EKS cluster was imported

**Comment by yonasberhe23** [comment]
unit tests are sufficient. moving to done
