### ISSUE TITLE
Vue3: Yaml editor and other codemirror components' theme rendering is off

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#11701]
**To Reproduce**

1. Navigate to local cluster
2. View details of any given resource that doesn't have a custom detail view
  - For example:  `apiregistration.k8s.io.apiservice`

**Result**
Yaml editor shows strange theme rendering

**Expected Result**

Theme should render properly 

**Screenshots**

![yaml](https://github.com/user-attachments/assets/f214e011-eac0-4a00-a757-24fcaf9a08c3)

**Additional context**
Other areas with likely broken styling are:
- KeyValue when used in configmaps
- Workload storage detail view (volumes)
- Monitoring's alerting rule and recording rule edit components
- JSON annotation display

Error in console:
```console
resize nullpx nullpx codemirror-editor-vue3.js:405
```

**Comment by rak-phillip** [comment]
To add some context wrt the regression: we did pivot from `vue-codemirror` to `codemirror-editor-vue3` in order to get a functioning editor in the vue3 branch. https://github.com/rak-phillip/dashboard/commit/1f6a726c9a64f18fdecc8eb50b5b12e1e766eedd. There's a high probability that whatever custom styling or themes that we previously implemented will need to be updated.

**Comment by mantis-toboggan-md** [comment]
The display issue with the yaml editor is indeed the result of the codemirror library change. The library is used in a few other components as well; we should make sure their styling is fixed while fixing the yaml editor styling.

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

Opening different resources Edit YAML page triggers a proper YAML rendering and there aren't errors observed in the browser console.
