### ISSUE TITLE
Vue3: Role Detail page table is duped

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11741]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- Duplicate role table is shown in detail page of role
- Duplicate template element?

**To Reproduce**
Users & Authentication --> Role Templates --> click on Administrator 

**Result**
![image](https://github.com/user-attachments/assets/23c37649-d85c-4c9c-9e9c-9642e57e69bb)

**Expected Result**
no table bottom right

**Comment by rak-phillip** [comment]
This is most likely related to #11716. We have some tricky slot usage from Vue2 that we will need to translate for Vue3.

**Comment by izaac** [comment]
Could a `should.have.length` test added to validate this?

**Comment by rak-phillip** [comment]
I believe you are correct 🙂

We've marked a lot of these Vue3 regressions as dev-validate to maintain velocity up while managing the transition. I think that we'll want to track testing requirements in a separate issue from the core vue3 regressions so that we'll have a view of how the overall migration is progressing.

**Comment by izaac** [comment]
I can't reproduce on `v2.10-13c7bae82c64b32ea68eb8981ee27dd7647c26ec-head`
UI: `master 49829da`
