### ISSUE TITLE
[2.9] Update Azure Availability Zone Region List

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#11816]
The list of available AKS regions is not hardcoded, but whether or not they support availability zones (enforced in the UI through form validation) is hardcoded here: https://github.com/rancher/dashboard/blob/master/pkg/aks/util/aks.ts#L7. We need to update this list to include southcentralus and any other regions missing from https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support#azure-regions-with-availability-zone-support

Ensure we check and add all missing regions.

**Comment by gaktive** [comment]
For QA's attention, this may have to be tested before what should be 2.9.2/2.9.next1. cc @rancher-max

**Comment by IsaSih** [comment]
According to https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support#azure-regions-with-availability-zone-support, I could observe that the UI lists more regions than the ones mentioned in the list of availability zone support, and some do not even make geographical sense. e.g. the region Brazil US

https://github.com/user-attachments/assets/a223a7c2-1e5a-42dc-aba7-145d95a4a496

**Comment by IsaSih** [comment]
Same is observed in RKE2. 
<img width="1728" alt="Screenshot 2024-09-05 at 15 37 50" src="https://github.com/user-attachments/assets/c85b3bce-1ba5-4b76-9927-502700a4f804">

**Comment by IsaSih** [comment]
we're listing this region as without availability zones e.g. South Central US, but according to https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support#azure-regions-with-availability-zone-support it does.
<img width="1728" alt="Screenshot 2024-09-05 at 15 48 27" src="https://github.com/user-attachments/assets/8fab6887-8a6a-47e4-8aeb-d9e96d6579ec">

**Comment by IsaSih** [comment]
From the regions with availability zones support mentioned in https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support#azure-regions-with-availability-zone-support, these are not being listed in the UI:
US Gov Virginia - I believe it is because the credentials used for testing belong to the public cloud environment, not the Azure US Government Cloud
Japan West - which is marked with a star in the Microsoft docs and listed in our UI as a region with no support for Availability Zones
China North 3 - I believe it is because the credentials used for testing belong to the public cloud environment, not the Azure China Cloud 
New Zealand North - Is not listed at all as a region in our region

**Comment by IsaSih** [comment]
provisioned AKS cluster in region South Central US in 3 availability zones. Found non-blocker related-issue https://github.com/rancher/dashboard/issues/11841.  The scope of this issue is working as expected.
