### ISSUE TITLE
Vue3: Node Detail Page: Refresh shows edit page instead, errors in console

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11815]
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- edit page shows instead of detail page when refreshing on node detail page

**To Reproduce**
- Cluster Explorer --> Cluster --> Nodes --> specific node --> refresh

**Result**
![image](https://github.com/user-attachments/assets/d202c6f8-fadf-4810-8ffd-959b042aed6c)

**Expected Result**
as per if navigating from nodes list --> node

**Additional context**
- not reproduible for other types (tried pods, services, random resource only showng yaml page endpointslice)

**Comment by izaac** [comment]
E2E test looks good, there's however one a nit.

https://github.com/rancher/dashboard/pull/11976/files#diff-f39f7d783658a9d1dec392326f3ce1853cd30515de39a4c5753c94f1022c0dd5R28-R34

Those `get()` should be moved to a page object as methods. 

Otherwise the logic is enough to cover this scenario.

Moving to re-open
