### ISSUE TITLE
Several issues on Pod detail view

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#11905]
# Description

Several issues have been found in the Pod details page.

1. Extra editor tab
2. Extra Namespace column in the table
3. Tiny cosmetic issue: the space is trimmed

2.10
<img width="1917" alt="Screenshot 2024-09-12 at 21 11 24" src="https://github.com/user-attachments/assets/286cfaa4-b076-47bd-8cc6-dd619fab6e97">

2.9
<img width="959" alt="Screenshot 2024-09-12 at 21 10 49" src="https://github.com/user-attachments/assets/c77305dd-9309-4b1f-a719-0890d3f8b59f">

**Comment by gaktive** [comment]
@richard-cox believes this is tied to the inherent attributes being missing, so it needs to be added to the components.

**Comment by aalves08** [comment]
1- There's a PR that fixes the problem with the lack of spacing in the restart counts.

2 - The namespace col is not appearing anymore... Couldn't repro that.

**2.9**
![Image](https://github.com/user-attachments/assets/d85cad5e-34c2-4512-8698-c2b9e8663680)

**2.10**
![Image](https://github.com/user-attachments/assets/7b8816a1-869b-478a-bf55-ab6ed437fcf5)

3- The YAML button part:

**in 2.9:**
https://github.com/rancher/dashboard/blob/release-2.9/shell/components/ResourceDetail/index.vue#L389
https://github.com/rancher/dashboard/blob/release-2.9/shell/components/ResourceDetail/Masthead.vue#L31-L88 -> note that there is no prop `canViewYaml` hence why the button is not appearing, because all of the plumbing was there already…

**master:**
https://github.com/rancher/dashboard/blob/master/shell/components/ResourceDetail/index.vue#L392 -> same prop being passed
https://github.com/rancher/dashboard/blob/master/shell/components/ResourceDetail/Masthead.vue#L89-L92 -> Phil added the missing prop…. Now it’s connected, therefore the YAML button appears -----> part of vue3 migration PR

This is now a global problem.... Either we display it or we don't. I think that the lack of `prop` was on "purpose" to avoid lengthy changes in configs for individual resources and all.
If the decision is to not show it, maybe we can "fix" it by explicitly defining the `canYaml` as `false` in the `resource-class` model. Food for thought 🤔

**Comment by aalves08** [comment]
@richard-cox , regarding the YAML button part, what is the best course of action? I am only missing that part to move this PR out of draft 🙏

**Comment by richard-cox** [comment]
Seems like this is an issue as old as time. Can you bring it up in the sync? i have a feeling then the visibility of the YAML button should remain

**Comment by yonasberhe23** [comment]
Did a quick manual check in 2.10. issue resolved. moving to done.
![Image](https://github.com/user-attachments/assets/21d9ab91-b70b-4a06-b82b-c5e96815d3d7)
