### ISSUE TITLE
Update `master` to use `head` rancher image in e2e tests

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#12082]
- Think this is just https://github.com/rancher/dashboard/blob/master/scripts/e2e-docker-start#L10
- This will affect
  - Extension tests
  - check-plugin tests

**Comment by aalves08** [comment]
**clock extension test:**
_installs a version not latest -> let's call it `V1`_
https://github.com/rancher/dashboard/blob/master/cypress/e2e/tests/pages/extensions/extensions.spec.ts#L221-L245

_upgrades to latest -> let's call it `V2`_
https://github.com/rancher/dashboard/blob/master/cypress/e2e/tests/pages/extensions/extensions.spec.ts#L261-L280 

_rollback  -> going back to`V1`_
https://github.com/rancher/dashboard/blob/master/cypress/e2e/tests/pages/extensions/extensions.spec.ts#L282-L301

TODO ::: We need to publish another version of clock compatible with Vue3/2.10

**extension larger than 20mb**
https://github.com/rancher/dashboard/blob/master/cypress/e2e/tests/pages/extensions/extensions.spec.ts#L303-L330
Test should be fine, since it's picking up latest

**uk-locale**
https://github.com/rancher/dashboard/blob/master/cypress/e2e/tests/pages/extensions/extensions.spec.ts#L332-L369
Test should be fine, since it's picking up latest

**Comment by cnotv** [comment]
Related to https://github.com/rancher/dashboard/issues/12080 but let's not mix them as they are covering different areas.

**Comment by richard-cox** [comment]
@cnotv they're duplicates. this one though has additional information on which tests will fail, and also the correct rancher image to update to (`master` should now track `head` rather than the lastest `-head` build). Can we close #12080?

**Comment by cnotv** [comment]
We can close it if you want, no problem. I just differentiated the 2 since one is for the Rancher Dashboard and the other for the Extension. If both can be achieved at the same time, it's fine for me.
A PR was already opened too: https://github.com/rancher/dashboard/pull/12081

**Comment by cnotv** [comment]
Sure, I just remembered to update also [this line](https://github.com/rancher/dashboard/pull/12081/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L29-R29), as it's not mentioned in the description of the issue.

**Comment by aalves08** [comment]
Just merged https://github.com/rancher/ui-plugin-examples/pull/55 which should be the only dependency needed to re-enable the e2e for extensions (extensions.spec)
