### ISSUE TITLE
Namespace list table is not correctly displayed

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#12162]
# Description

This is a regression from an unclear commit (not https://github.com/rancher/dashboard/issues/12007), not exactly Vue3.

2.10
<img width="1604" alt="Screenshot 2024-10-07 at 23 27 09" src="https://github.com/user-attachments/assets/02b16d89-2562-4121-8c07-5ee9a1deb821">
<img width="1593" alt="Screenshot 2024-10-07 at 23 27 18" src="https://github.com/user-attachments/assets/a4bfb09f-7a68-44f1-9097-661a40753cc0">

2.9
![Screenshot 2024-10-08 at 10 38 57](https://github.com/user-attachments/assets/44a0516c-0ebe-499a-bd10-5feb9db3e4c1)
![Screenshot 2024-10-08 at 10 39 04](https://github.com/user-attachments/assets/4eec936c-2b93-405f-9ff1-a15315c1d11b)

**Comment by richard-cox** [comment]
@cnotv can you include screenshots of the expected behaviour and list the items that are broken? This is primarily for QA but it will also assist whoever picks this up.

It looks like the header buttons, the project's create namespace button + project actions button wrap expanding the group header and the focus background of the action button might be different?

Could be related to https://github.com/rancher/dashboard/pull/12109

**Comment by izaac** [comment]
Validated on Rancher version: `v2.10-5d66d49d7a72b4c439a33043007e9bb0223c8693-head`
UI: `master cf8c6d1`

This is now rendered properly on this rancher version. No errors in the browser console. This was also compared to the latest `2.9-head` to check it was still consistent.
