### ISSUE TITLE
Apps deployed do not have an option to rollback to a previous version

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1231]
**On master-head - commit id: `31d7ad327`**

Currently there is no option for the user to rollback to an older version of an app (which has been upgraded)say backup-restore
<img width="1676" alt="Screen Shot 2020-09-11 at 4 43 21 PM" src="https://user-images.githubusercontent.com/26032343/92981253-edf2e880-f44d-11ea-983d-526ca7e9ce44.png">

**Comment by deniseschannon** [comment]
@vincent99 Are we allowing rollback or is it just "upgrade" to an older version?

**Comment by vincent99** [comment]
There should be be a rollback, but it's not really a thing in the API yet.  Darren is redoing the api for releases first and that will include it.  You acn also upgrade to an older version, but that's different.

**Comment by catherineluse** [comment]
I'm closing this issue due to its age and the fact that it is pending updates from employees who haven't worked here for some time. Also, as Vince noted above, it is already possible to select an older chart version in the UI when updating an app, but Steve does not support the same rollback feature as Norman.

As far as I know, there is no plan to support a catalog app rollback in Steve. If needed, this issue can be reopened, but if it is, we need a more detailed specification of the requirements and a link to a backend ticket.

Screenshot of an app being changed to a previous version:
<img width="991" alt="Screenshot 2022-11-05 at 1 51 15 PM" src="https://user-images.githubusercontent.com/20599230/200140883-7317d259-fac8-49af-aecd-cbcb50dcd81e.png">
