### ISSUE TITLE
RKE2 cluster provision: Data Directories enhancement in the Advanced tab

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#12405]
**Is your feature request related to a problem? Please describe.**

Based on the work done for https://github.com/rancher/dashboard/issues/11560 -> more concretely PR https://github.com/rancher/dashboard/pull/12367

If you toggle between default dirs and specific dirs, it should set the values for the specific dirs - at the moment if you create a cluster with a base dir, when you edit it, you see the 3 dirs, but if you toggle to use default and back again, you lose the values.

**Describe the solution you'd like**

On edit, values should persist even if you toggle the radio button

**Describe alternatives you've considered**

**Additional context**

**Comment by yonasberhe23** [comment]
@aalves08 as part of this enhancement should we also grey out the fields in edit mode since the user cannot update the directory after cluster creation anyway?  (that is the behavior in 2.9.x)

![image](https://github.com/user-attachments/assets/dca6d5b2-b591-44e2-9e32-9f79146f2ef0)

**Comment by yonasberhe23** [comment]
as part of this enhancement, we should grey out the fields after creation to make it clear to the user what is expected behavior (that's the behavior 2.9.x)

**2.9 - fields are NOT editable in edit mode (expected)**
![image](https://github.com/user-attachments/assets/4715cf0a-b3e7-4f4a-ae49-22a37b77a40e)

**2.10 - fields are editable in edit mode**
![image](https://github.com/user-attachments/assets/143ecbca-a525-4721-922a-ba7901ea47a9)

**Comment by nwmac** [comment]
Created https://github.com/rancher/dashboard/issues/12455 for the edit issue
