### ISSUE TITLE
Fleet - Error when editing gitrepos.fleet.cattle.io  the object has been modified; please apply your changes to the latest version and try again

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1250]
This is working using helm 3 but is failing from Dashboard

```
gitrepos.fleet.cattle.io "simple"  the object has been modified; please apply your changes to the latest version and try again
```

I see an HTTP 409 response from the server

- Add a GitRepo object (I used Create as YAML)
- Try editing it it as Form or as YAML -- `This may need to be attempted a couple of times (try add/remove directories and saving)`
- Click save

![Screen Shot 2020-09-15 at 11 48 57 AM](https://user-images.githubusercontent.com/27659/93251858-9902eb00-f749-11ea-97d5-611acad87dcc.png)

Rancher version: `master-head (09/15/2020)` _0f691dc70f86bbda3d6563af11779300a6191584_ HA k8s

**Comment by vincent99** [comment]
I'll think any if there's anything we can do for this but isn't really new or specific to fleet or caused by the UI.. 

When you start editing something, a clone of all the data is made so that you have a stable set of data to edit.  If the underlying object changes in the meantime, then on save the server might reject it because there are newer conflicting changes from someone else (probably Fleet itself in this case).

**Comment by vincent99** [comment]
This is a general problem with editing a resource that's changed from underneath you.. https://github.com/rancher/dashboard/issues/1324
