### ISSUE TITLE
Can't tell cluster explorer is selected when I click on app drop-down

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1272]
Steps:
1.  Click on Application drop-down in upper left corner

Results:
Can't tell that Cluster Explorer is selected.  It make it look like Cluster Manger is selected and that is confusing.
![image](https://user-images.githubusercontent.com/11514927/93429177-96051900-f875-11ea-8969-913375248f32.png)

Expected: Cluster Explorer should be highlighted when I click on the drop-down.  I also think we have to change either Cluster Manager or Cluster Explorer.  It's confusing & they aren't different enough to prevent accidental clicking.

**Comment by deniseschannon** [comment]
After looking at this, I think the highlighted is supposed to be what you select and the white text is the one that is already selected. 

But I agree that I'd prefer Cluster Explorer at the top. 

Let's discuss what the order of these 4 should be. I keep clicking on Cluster Manager, when I want to go to Cluster Explorer.

@tfiduccia 

What do you think of it being
```
Cluster Explorer
Apps & Marketplace
----
Cluster Manager
Fleet 
----
Any other apps that were deployed
```

Is the division obvious or would we want some kind of heading?

**Comment by vincent99** [comment]
The active product doesn't stand out enough (and needs an icon that's the same color of the text, and probably shouldn't use exactly the same text color as the hover but with no background because that's part of why it doesn't stand out).

I like the idea of explorer on top because I click it too, but 

```
Things for the selected cluster
---
Things that are global
---
More things for the selected cluster, but you can remove them if you go to a different product
```

Seems like a weird order.  

I don't really know why cluster manager is even in the dropdown at all at this point.  It behaves completely different than the other options and there's another button in the header for it all the time.

And `Cluster Manager` vs `Cluster Explorer` are just not very different sounding so that doesn't help.

**Comment by tfiduccia** [comment]
Adding Lauren, her and I discussed drop-down today.

**Comment by deniseschannon** [comment]
For 2.5, let's make the active product more prominent.

**Comment by tfiduccia** [comment]
Fixed
