### ISSUE TITLE
Update "Overview" for workloads to be aligned with other types and show a count

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1273]
Issue - We have a global Overview page that contains information about the cluster.  We also have an Overview page under workloads that is just a list of resources.  This is confusing... Can we:

- [x] Change the Global Overview page to be "Dashboard"

- [x] Indent the Overview under workloads, so it lines up with the Deployments text underneath it.  Should we have the folder icon next to it cause it does have a namespace view as well.

- [ ] ~Can we have a total count associated with Overview?~

**Comment by deniseschannon** [comment]
Looks like the "Cluster Overview" was updated to "Cluster Dashboard"

The other 2 will be in the backlog for now.

**Comment by vincent99** [comment]
Added the icon, and moved Pods to the bottom of the list so that all the things that go into the Overview page are in a contiguous group intead of Pods being in between Jobs/StatefulSets.

Showing a count on overview is not practical.  How many there are going to be in the table is not known from the `counts` data, because it depends on knowing stuff about every individual workload.  Only the "top level" workloads are shown in the Overview table.  i.e. if you make just a Job it's shown.  But if you make a CronJob, that creates some Jobs but those are not shown.  (Similar for Deployment->RepliaSet, etc).

**Comment by tfiduccia** [comment]
Fixed
