### ISSUE TITLE
Select text highlighting is not working in kubectl shell in dashboard

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1314]
**On master-head - commit id: `8fd81a9b4`**

In Dashboard, in kubectl shell, Select text highlighting is not working.
User is not able to select text in the shell

**Comment by sowmyav27** [comment]
**On 2.5-head - commit id: `bebfe0d`**
in kubectl shell, Select text highlighting is not working.

**Comment by maggieliu** [comment]
@sowmyav27 Can you provide more details as to which browser?

**Comment by sowmyav27** [comment]
This was on chrome browser. 

- Launch Dashboard
- Launch kubectl shell
- Select text highlighting is not working

**Comment by codyrancher** [comment]
@sowmyav27 can you attempt to reproduce this in incognito or with extensions disabled? I am not able to reproduce this.

![Kapture 2020-10-29 at 10 49 57](https://user-images.githubusercontent.com/55104481/97612396-9cd68e00-19d4-11eb-82f1-bb001a5123e5.gif)

**Comment by sadiapoddar** [comment]
Couldn't reproduce with 2.5.1 with incognito and normal mode.

**Comment by sadiapoddar** [comment]
Tried to reproduce with 2.5-head and couldn't reproduce it.
Steps,
1. Click on the ">_ shell" in UI
2. wait for the command prompt of the shell
2. once you get the kubectl prompt, type some texts and select those texts.
3. the text at the prompt is selectable
<img width="305" alt="Screen Shot 2020-10-30 at 12 02 42 PM" src="https://user-images.githubusercontent.com/72409237/97747715-a2ea6e80-1aa9-11eb-87c9-2fb0c7656ed7.png">

Seems like the issue is fixed.

**Comment by sowmyav27** [comment]
Closing the issue based on [this](https://github.com/rancher/dashboard/issues/1314#issuecomment-719747490)
