### ISSUE TITLE
Inconsistent CIS v2 CR names

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1340]
**On master-head - commit id: `ed2749841`**

- Deploy CIS v2 app on a cluster in dashboard
- The CIS CRs names seem inconsistent

<img width="284" alt="Screen Shot 2020-09-21 at 10 30 22 PM" src="https://user-images.githubusercontent.com/26032343/93846883-32eefa00-fc5a-11ea-90c2-cc5affa37ac8.png">

- Can we have them as -
```
- ClusterScanBenchmarkVersions
- ClusterScanProfiles
- ClusterScanReports
- ClusterScans
```
- Because if these CRs are `Starred` then there will be no `Header` To indicate that these are related to CIS/cluster scans
<img width="274" alt="Screen Shot 2020-09-21 at 10 33 48 PM" src="https://user-images.githubusercontent.com/26032343/93847033-a7299d80-fc5a-11ea-8ae8-54d6e44f4e23.png">

**Comment by vincent99** [comment]
I asked for these to be remapped because I'd rather have types that are concise and not-redundant shown for the primary way people see them, in the product-specific UI.  Or in the regular nav tree, under their Apigroup.

Even among the built-in standard k8s types, several names are ambiguous or exist in more than one API group.  So the problem with starred items being ambiguous exists irrespective of CIS.

Starring is an optional and relatively obscure feature, so my thinking is if a user has chosen to star a type they probably did it for a reason and will know which type it meant to them.

(ClusterScanReports could be remapped too, but hasn't been just because they aren't shown as a type in the CIS UI)

**Comment by deniseschannon** [comment]
For now, let's not change this and if it becomes confusing to end users later, we can always update it.
