### ISSUE TITLE
Need to add Image to Workload screens & List pages

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1358]
Issue:  On details pages for workloads, there is no image info in the main info box?  Have to find the pods to see it?
![image](https://user-images.githubusercontent.com/11514927/93942318-07652180-fce5-11ea-871a-8b5f95958c05.png)

**Comment by deniseschannon** [comment]
This is technically how a workload works. A deployment contains a pod. A pod is comprised of container(s) and each container has 1 image, so workloads can have more than 1 image associated with them. 

In most uses cases, there is only 1 container in the pod, but since we want to extend support to multiple containers within a pod, adding image on workload detail doesn't makes sense.

**Comment by vincent99** [comment]
That makes zero sense. The image is important enough that it should be on the *list* view (as it is in ember) without even having to look at details, let alone having to follow an extra level of indirection beyond that.

We flatten pod vs workload down to one level on purpose while defining, and it should do the same to show the image for the 90%+ cases where there's one container.  For the exception, say "multiple" or "[first image].. + N others".

**Comment by tfiduccia** [comment]
The image is still not on the details page for the workloads:
![image](https://user-images.githubusercontent.com/11514927/94523147-a312f800-01e5-11eb-9a01-60ccfdd24913.png)

**Comment by tfiduccia** [comment]
Fixed
