### ISSUE TITLE
Refresh is required for the latest recurring backup to be listed in "backup filename " during a restore

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1386]
**On master-head - commit id: `e9a98a323`**

PV using storage class is configured on the local EKS cluster.

- Create a recurring backup with retention count 10 and schedule - `@every 1m`
- Go to Restore page, select this recurring backup in the target backup dropdown.
- the user has to refresh for the latest recurring backup file to reflect in the dropdown of filename.

**Expected:**
User should be able to list the latest backup filename related to the recurring backup without a refresh of the page.

**Comment by Ellenqs** [comment]
The issue is reproduced.

**Test environment:**
Rancher version:  HA setup  v2.5.4-rc8
Provider: aws

**Steps:**
Go to cluster explorer
Go to secrets-> create a secret, give in the following as Key/value pairs
accesskey=<aws accesskey>
secretKey=<aws secretKey>
Click on create
Go to Apps
Deploy rancher backups
When it is deployed go to rancher Backups, from top left dropdown
Go to Backup ->Create a backup
Give in a name, Storage Location: S3
Give in credential Secret: created in Step 6, Bucket Name: <create on in s3 and give its name> , region: where you create S3 bucket, Endpoint: s3.<region>.amazonaws.com, create
Go to restore, and create a Restore CR 
Try to reproduce the issue

**Result:**
Backup Filename is now shown unless refresh.

**Comment by Ellenqs** [comment]
Test on v2.5-head (65a15b9):

Steps:

Go to cluster explorer
Go to secrets-> create a secret, give in the following as Key/value pairs
accessKey=
secretKey=
Click on create
Go to Apps
Deploy rancher backups
When it is deployed go to rancher Backups, from top left dropdown
Go to Backup ->Create a backup
Give in a name, Storage Location: S3
Give in credential Secret: created in Step 6, Bucket Name: , region: where you create S3 bucket, Endpoint: s3..amazonaws.com, create
Go to restore, and create a Restore CR
See if when creating restore, the latest backup file name is shown in the field of "backup filename".

Result:
Backup Filename is shown directly.

Closed.
