### ISSUE TITLE
[Monitoring V2 UI] Monitoring pane appears even if Monitoring V2 is not installed

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1430]
If you spin up a brand new cluster from Cluster Manager and go to the Dashboard view, the Monitoring pane is available / accessible even if the `rancher-monitoring` V2 chart is not installed onto the cluster.

The Monitoring pane should only be accessible if the user has installed `rancher-monitoring` within the `cattle-monitoring-system` namespace.

**Comment by westlywright** [comment]
The issue here is that ECM by default installs the CRDs for `monitoring.coreos.com.alertmanagers`, `monitoring.coreos.com.prometheuses`, `monitoring.coreos.com.prometheusrules`, `monitoring.coreos.com.servicemonitors`. My solution was to only add the `monitoring.coreos.com.servicemonitors` to https://github.com/rancher/dashboard/blob/master/config/product/monitoring.js#L20

**Comment by jiaqiluo** [comment]
this is validated on master-head ec04f78 with the latest UI

the Monitoring overview page shows only when the monitoring v2 is installed via the dashboard.
