### ISSUE TITLE
In Secret: Create, clean up the key field if file name has non-UTF8 character set

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1499]
Steps:
1.  Go to Secrets: Create
2.  Give it a valid name
3.  Add a file that has a space or parens or any other non-UTF8 characters
4.  Click Create

Results:  Get an error saying Key field is invalid.  The Key field needs to be cleaned up on upload for files.
![image](https://user-images.githubusercontent.com/11514927/94528447-47e50380-01ed-11eb-80c2-266c6d0348ff.png)

**Comment by codyrancher** [comment]
@tfiduccia it seems like you want us to modify the filename . I don't think it's appropriate for us to modify it for the user at the very least without notifying them.

Is there anything else we could do to improve the experience?

**Comment by vincent99** [comment]
It's not a "filename" anymore; it's a map key which allows a limited character set, and putting in something invalid for them is not helpful.

**Comment by codyrancher** [comment]
@vincent99 I understand that it's a key. However, there are other places where we seem to like pretending the keys are filenames.

![Screen Shot 2020-10-19 at 2 01 05 PM](https://user-images.githubusercontent.com/55104481/96511173-8c275a80-1213-11eb-9efa-c6b1b785c921.png)

I also think it's helpful to users to know which value corresponds to which file they uploaded if they uploaded multiple files.

With that said, if you'll define what you mean by clean up I'll go ahead and make the change. Do you just want to leave the key blank? Strip only characters that violate the regex?

**Comment by vincent99** [comment]
They often are "file-like names" because secrets are as a volume in a workload and if you pick an entire secret a directory is created and the keys become the actual names of files created within it.  That fluentd secret is probably mounted as `/etc/fluentd` and results in `/etc/fluentd/devnull.conf`, `/etc/fluentd/fluent.conf`, etc being available in the deployment.

But they still are restricted to the allowed character set, which is `a-z`, `0-9`, `.`, `-`, and `_`.  And I don't like us actively filling an invalid value for you that the API will reject, with no indication until you click save.

The three choices I see are:
1) If any part of the filename is invalid, leave the key blank.  `cron copy (1).yaml` => (empty string)
2) Replace invalid characters with something that is valid, like underscore. `cron copy (1).yaml` => `cron_copy__1_.yaml`
3) Strip invalid characters out entirely.  `cron copy (1).yaml` => `croncopy1.yaml`

I would vote for 2, because 1 completely loses the context of what the name originally was (particularly if you select multiple files at once you could end up with multiple rows with no key to correlate back together) and 2 is more obvious than 3 that some substitution has occurred.

**Comment by codyrancher** [comment]
Alright, I'll go with 2.

**Comment by tfiduccia** [comment]
Fixed
