### ISSUE TITLE
Spacing between Head Title, Dividing lines, Section titles, Control Titles, and controls are inconsistent across the application

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1578]
Issue: spacing inconsistent, some examples
- [x]  In Deployments, the space between the title and first control in Port Section, Environment Variables & Pod Labels/Annotations are all different.  Also there is a difference between the top and bottom of dividing line.
![image](https://user-images.githubusercontent.com/11514927/94874868-011f2580-0408-11eb-9539-bb4998c90425.png)

- [x] ~Secret & Persistent Volume Claim are examples of the Main section and data, that isn't in tables, are different:~ - Secret needs to be re-done for cru resource layout changes and PVC doesn't actually exist anymore. 
![image](https://user-images.githubusercontent.com/11514927/94974695-31c49500-04c4-11eb-8cb4-a3580961432f.png)
![image](https://user-images.githubusercontent.com/11514927/94974711-3ab56680-04c4-11eb-9e73-78caf5cffb4a.png)

- [x] Where the tabbed section starts is also inconsistent.. Ingress Create & Deployment Create
![image](https://user-images.githubusercontent.com/11514927/94975163-a21fe600-04c5-11eb-8ca1-33ebc5588fa0.png)
![image](https://user-images.githubusercontent.com/11514927/94975173-a9df8a80-04c5-11eb-9318-1b1a5ac275a7.png)

**Comment by deniseschannon** [comment]
@lvuch We should make a base template for our create/edit pages that layout masthead, namensdescription, and then the tabs so that they are all spaced out together. 

For the ones that @tfiduccia has identified, can you fix all but the secret/PVC? Secret will be addressed when we move Secret to cruResource and PVC create was an accidental mis-routing for the workload. I twas never meant to be a standalone form.

**Comment by tfiduccia** [comment]
ok so issue 1 & 3 are still in master?

**Comment by tfiduccia** [comment]
closing this as all spacing is going to be reviewed
