### ISSUE TITLE
Cluster scan results in error "Resource is current"

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#1613]
I provisioned an EC2 cluster in Rancher using v2.5.0-rc7. Then I created a cluster scan using the default profile. The cluster showed in the scan list as active:
<img width="760" alt="Screen Shot 2020-10-03 at 6 21 03 PM" src="https://user-images.githubusercontent.com/20599230/95004863-af140680-05a5-11eb-9ce1-26ec94f5d4fc.png">

But it was stuck in active state and I couldn't see the report. The error looked like this:
<img width="682" alt="Screen Shot 2020-10-03 at 6 21 15 PM" src="https://user-images.githubusercontent.com/20599230/95004868-bd622280-05a5-11eb-8476-b426213b6307.png">

**Comment by prachidamle** [comment]
@catherineluse did the cluster scan ever progress? Do you happen to know how it reproduces - I will have to see the cis-operator logs when we hit this

**Comment by sowmyav27** [comment]
- This happens when a scan is run and immediate click on the report when its seen in Active state (scan is still running)
<img width="544" alt="Screen Shot 2020-10-07 at 2 00 20 PM" src="https://user-images.githubusercontent.com/26032343/95387870-3ca56e00-08a6-11eb-991f-2c4e69c40595.png">

- if automatic refresh of state happens (currently have an issue for this), cluster scan will be seen in Running state, And while in running state if you click on the report you seen -- Scan is running message
<img width="477" alt="Screen Shot 2020-10-07 at 2 02 10 PM" src="https://user-images.githubusercontent.com/26032343/95387927-521a9800-08a6-11eb-9115-08bdb7a089a1.png">

- User will have to manually refresh the page to see the scan state change.

**Comment by catherineluse** [comment]
@prachidamle The cluster scan didn't progress. I don't have the Rancher instance anymore

**Comment by prachidamle** [comment]
Seems like an intermittent state and this should work fine once auto refresh of states work

**Comment by sowmyav27** [comment]
If the page is manually refreshed, the scan will be in Running/Pass/Fail state

**Comment by prachidamle** [comment]
Can we link this with the auto-refresh bug if there is one @sowmyav27

**Comment by sowmyav27** [comment]
Auto refresh issue -- https://github.com/rancher/rancher/issues/29183

**Comment by maggieliu** [comment]
@sowmyav27 Can you check if this is still an issue?

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `71da1569`**

- Create a scan CR, When the scan is running, click on the scan to go to the details page.
- "Scan is running" is seen without a refresh of the page
