### ISSUE TITLE
"This page could not be found" error when when user clicks "back" on Dashboard page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1635]
**On 2.5.0**

- Install a HA setup.
- On the cluster manager UI, click on "Cluster explorer" for say local cluster from Global Clusters page.
- User is navigated to Dashboard.
- Click "back" in the web browser.
- User sees this error

<img width="530" alt="Screen Shot 2020-10-06 at 9 56 33 AM" src="https://user-images.githubusercontent.com/26032343/95234317-40f45d00-07ba-11eb-960a-7c9f8f3e2964.png">

- Click on Go back home --> Cluster Manager to navigate back to Ember UI.

**Comment by vincent99** [comment]
(You're still going to briefly see the 404 but it will reload and go back to ember)

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `cc777ebf`**

- Deploy a single node rancher
- Deploy a 1 node DO cluster
- On Ember UI, Global --> CLusters --> Click on Explorer of the `local`/DO cluster.
- User is redirected to Dashboard page
- Click on `back` in the browser, user is navigated to Ember UI briefly seeing 404 on the page.
- Click on Click on Explorer of the `local`/DO cluster.
- Click on `back` in the browser, User sees a "Page cannot be found" error.
<img width="380" alt="Screen Shot 2020-10-30 at 9 26 08 AM" src="https://user-images.githubusercontent.com/26032343/97744948-54d36c00-1aa5-11eb-8c87-a1901f88fa1a.png">

**Comment by kravciak** [comment]
Reproduced on 2.5.8-rc17

**Comment by nwmac** [comment]
Note: Doesn't have to be an HA system - but I see this on he 2nd back and forth - i.e. Cluster Manager -> Cluster Explorer -> (back) -> Cluster Explorer -> (back)

**Comment by kravciak** [comment]
Fix works fine for links in Global -> Clusters -> link.

There are two other links to Explorer in cluster view:
 - cluster view -> `Cluster Explorer` link on the top navigation 
 - cluster view -> `Try out the Cluster Explorer` info box 

Those links point to `../dashboard/c/local` instead of `../dashboard/c/local/explorer`, which results in second redirect.
When use them to access explorer going back in browser navigation has random result, for example:
 - redirects to explorer home page
 - going back button is disabled
 - navigates to dashboard login page
 - navigates to random page in explorer 

To reproduce:
On Ember UI, Global -> Custers -> local -> Click on `Cluster Explorer` of the top navigation
User is redirected to Dashboard page ( first dashboard/c/local then dashboard/c/local/explorer)
Click on back in the browser (can be clicked multiple times)

Should I create separate issue for that or it can be fixed as part of this one?

Tested on master-head (3dae3e2)

**Comment by nwmac** [comment]
@kravciak Its fine in re-opened - I will take a look. I may create a separate issue once I understand more.

**Comment by nwmac** [comment]
@kravciak We're removing Cluster Manager going forward, so I don't believe this will be an issue any longer.

**Comment by sowmyav27** [comment]
@kravciak Please log a new issue if the original one is fixed. The cluster Manager will be available on an upgrade rancher server from 2.5.8 to 2.6.

**Comment by kravciak** [comment]
> @kravciak We're removing Cluster Manager going forward, so I don't believe this will be an issue any longer.

Closing based on the comment, thanks.
