### ISSUE TITLE
[ Istio V2 ] Add warning message / info message for Kiali Dashboard link

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#1646]
Need to add a warning or info message (not sure which would be best)

**Background:** The Rancher Istio chart has the following chart annotation `catalog.cattle.io/requires-gvr: monitoring.coreos.com.prometheus/v1` which points to a prometheus CRD and expects it to be there before installing istio. The purpose of this was to ensure that monitoring was installed prior to istio getting installed to ensure kiali would have data to display. Unfortunately, this CRD can be installed by other charts and is not a required crd for all prometheus setups. 

**Solution:** I will be removing this annotation from the chart, but still need to inform / warn the user that they need to setup monitoring if they want kiali to work. 

Add a warning / info banner (potentially inside link box with kiali) that says "For Kiali to display data, you need prometheus in the cluster or to install monitoring"

It would be nice to have a link to rancher-monitoring on the "install monitoring" wording to make it easier for users install if they need to

![Screen Shot 2020-10-07 at 4 35 34 PM](https://user-images.githubusercontent.com/19455540/95398691-5309f480-08bb-11eb-87ec-9bb47a36ca34.png)

**Comment by deniseschannon** [comment]
Append to the text:

For Kiali to display data, you need Prometheus installed. If you need a monitoring solution, install Rancher's monitoring. 

The words `Rancher's monitoring` should link to the instlal page for our monitoring.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head 9d38821

* The warning/info text is correct, but the link takes the user to the cluster's v1 Monitoring page: `https://url/c/cluster-id/monitoring` instead of the v2 Monitoring install page
* The link should instead take the user to `https://url/dashboard/c/cluster-id/apps/install?repo-type=cluster&repo=rancher-charts&chart=rancher-monitoring&version=9.4.201#readme` (or whatever the latest version is)

![Screen Shot 2020-10-19 at 10 25 01 PM](https://user-images.githubusercontent.com/21316915/96543977-74bf9000-125a-11eb-9485-70ac7d0e37ab.png)

**Comment by bmdepesa** [comment]
rancher/rancher:v2.5-head cc777eb

The monitoring link now correctly takes the user to the Dashboard Monitoring page.
