### ISSUE TITLE
Run Rancher Dashboard standalone?

### ISSUE THREAD

**Issue by hjacobs** [rancher/dashboard#1674]
Is it possible to run Rancher Dashboard standalone, i.e. without the Rancher control plane?

**Comment by vincent99** [comment]
Not currently; we sort of had this during development and it will probably come up again as part of other efforts in the future.  It needs to talk to a separate API (which is called [steve](https://github.com/rancher/steve)).  This handles a bunch of things that would otherwise be inefficient for the UI to do on its own, such as aggregating watch calls into one websocket and keeping track of "counts" info for how many of each type of resource there are in each namespace and state (which is used to draw the left nav, among other things.. and that's why no other k8s dashboards tell you how many things there are there in their nav).

**Comment by hjacobs** [comment]
Thanks for the answer! Just for context, I was asking this question for our KubeCon talk about Kubernetes UIs: https://www.youtube.com/watch?v=lsrB21rjSok
