### ISSUE TITLE
In Create Service when I add a port the default cursor should go into the port name field

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1732]
Actually there are two bugs here:

- [x] Removing all ports, then adding one, default cursor gets lost

- [x] When adding a second port the default cursor goes to listening port first.  Should always go to Port Name, the first available field in the row.

![image](https://user-images.githubusercontent.com/11514927/97513432-7cadbd00-1949-11eb-8f9b-5b6a7b0e381c.png)

**Comment by sadiapoddar** [comment]
Reproduced the issue with 2.5.3

1. If all ports are removed, then adding one, default cursor got lost

Cursor is lost

<img width="1812" alt="Screen Shot 2020-12-28 at 5 41 33 PM" src="https://user-images.githubusercontent.com/72409237/103253269-50a4bd00-4935-11eb-930b-7ba6f5faf532.png">


2. When adding a second port the default cursor goes to the listening port first instead of the "port name" of the first add port.

The cursor is not at the "Port Name" test box but at the "Listening Port" test box
<img width="1859" alt="Screen Shot 2020-12-28 at 5 41 52 PM" src="https://user-images.githubusercontent.com/72409237/103253086-91500680-4934-11eb-946b-de9f959af2bb.png">

**Comment by sadiapoddar** [comment]
Verified on master-head, commit 5da52c0
1. If all ports are removed, then adding one, default cursor is now on the expected port name test box


<img width="1764" alt="Screen Shot 2020-12-28 at 5 35 35 PM" src="https://user-images.githubusercontent.com/72409237/103253170-e25ffa80-4934-11eb-8335-72d5c6954f2e.png">

2. When adding a second port the default cursor doesn't go to the listening but it's at the "port name" test box 
<img width="1076" alt="Screen Shot 2020-12-28 at 5 36 11 PM" src="https://user-images.githubusercontent.com/72409237/103253023-3ae2c800-4934-11eb-9b0a-d42b30b704f8.png">
