### ISSUE TITLE
Container Form: Add environment variables from source missing ConfigMap entry

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#1813]
When you add an environment variable from source in the container form, the "Type" dropdown is missing the option to reference a complete ConfigMap. You can reference a single key of a ConfigMap and a complete Secret though.

![Bildschirmfoto 2020-11-10 um 15 25 37](https://user-images.githubusercontent.com/243056/98686876-66e8c080-2369-11eb-80d8-a0c35395e6f8.png)

**Comment by aaronRancher** [comment]
This issue is verified with Rancher server `rancher\rancher:master-head` `version f39eb6c` and `rancher\rancher:v2.5-head` `version eacc4b8`

ConfigMap is added to environment variables dropdown:
![Screen Shot 2020-11-19 at 4 37 22 PM](https://user-images.githubusercontent.com/57409052/99738256-49ada380-2a87-11eb-9a5b-4d9516012ccd.png)
![Screen Shot 2020-11-19 at 4 40 24 PM](https://user-images.githubusercontent.com/57409052/99738258-4aded080-2a87-11eb-91a0-336945624616.png)
