### ISSUE TITLE
Monitoring Metrics on Workload

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1879]
Need to add monitoring graphs on workload details for certain types of workloads.
* Pods
* Deployments
* Statefulsets
* Daemonsets

**Comment by maggieliu** [comment]
https://xd.adobe.com/view/866862d9-4ac5-4962-a026-0c716a335cb7-d33b/

**Comment by gaktive** [comment]
This is for v2 monitoring to bring feature parity to what was in v1. This would allow people to not rely on other cloud monitoring services.

**Comment by gaktive** [comment]
We should leverage Grafana instead of our own widgets. We should ensure we're clear what the gaps are so we need to review the Ember v1 monitoring and understand what dashboards to be created.

@codyrancher should get one of the newer UI folks up to speed and work with Arvind to get the dashboards created.

**Comment by codyrancher** [comment]
We're waiting on https://github.com/rancher/rancher/issues/35340 before we move forward.

**Comment by codyrancher** [comment]
For testing you will have to test this on a local cluster unless you have your cluster setup behind a domain with a valid certificate due to https://github.com/rancher/rancher/issues/31891

![Screenshot from 2021-11-10 15-55-33.png](https://zube.io/files/rancher/4ed26136ce5041dd28cc10500cbbe90b-screenshot-from-2021-11-10-15-55-33.png)![Screenshot from 2021-11-10 15-55-46.png](https://zube.io/files/rancher/d0dc99453243254a61694017990bc973-screenshot-from-2021-11-10-15-55-46.png)![Screenshot from 2021-11-10 15-56-41.png](https://zube.io/files/rancher/a4327a485243f5800c220174f6c861f4-screenshot-from-2021-11-10-15-56-41.png)![Screenshot from 2021-11-10 15-56-30.png](https://zube.io/files/rancher/dc00c15fb48c59023cc6b9aa88e16d34-screenshot-from-2021-11-10-15-56-30.png)

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Feature Validation**
- Rancher Version: v2.6-head (e322f8f)
- Install type: Docker 

**Validation Steps**
1. Install Monitoring onto your local cluster. 
2. Navigate to the local cluster from the cluster explorer
3. Go to Workload
4. Go to pods and select one. (I selected the calico kube controllers pod) 
5. Select Metrics

From here you shall see a graph similar to the following: 

![MetricsDashboard.png](https://zube.io/files/rancher/5373618d608837edaf494dde43bc2c6b-metricsdashboard.png)

**Further Testing**
I did the validation steps for the following workloads
- Pods - Pass
- Daemonsets - Pass
- Statefulsets - Pass
- Deployments - Pass
I also checked the other workloads to make sure graphs weren't present.

The validation passed in both RKE1 and RKE2 clusters.
