### ISSUE TITLE
Cronjob is not counting successful amount in details

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1940]
Steps:
1.  Create a cronjob that will fire every few minutes.
2.  After about 10 minutes go to the details page

Results:  The job fires successfully, but the count still says 0
![image](https://user-images.githubusercontent.com/11514927/100771586-d0ce1600-33bb-11eb-95c6-8a812668bed9.png)

**Comment by vincent99** [comment]
@mantis-toboggan-md I might have broken this combining merge conflicts

**Comment by tfiduccia** [comment]
Job tab keeps disappearing and flashing between saying Jobs & Pods.  The runs count is still not updating and if I go in when nothing is running they disappear completely.  

This details page is from the same deployment, I just refresh the page:
![image](https://user-images.githubusercontent.com/11514927/101707444-73d00100-3a48-11eb-82d7-5727812be088.png)
![image](https://user-images.githubusercontent.com/11514927/101707472-821e1d00-3a48-11eb-9224-3d56d5f6dd5b.png)
![image](https://user-images.githubusercontent.com/11514927/101707478-864a3a80-3a48-11eb-8119-73dac3e33357.png)

**Comment by tfiduccia** [comment]
![image](https://user-images.githubusercontent.com/11514927/102146806-e107db80-3e26-11eb-8e7c-14031a4672a2.png)
Still says 0

**Comment by nickgerace** [comment]
Going to test this with v2.5.3 for reproduction since the original milestone was v2.5.4.

**Comment by nickgerace** [comment]
## Summary

The issue appears to have been resolved. The issue was reproduced with a v2.5.3 install, with the cluster overview not displaying active/past jobs properly. In v2.5-head (a85f4d1), the issue no longer appears, as indicated below with the job counter working as intended.

- Steps taken to reproduce the issue: installed with the following configuration...
  - Installation option (single install/HA): single
  - Browser: Chrome 88.0.4324.182
  - OS: macOS Big Sur 11.2.1
  - Arch: amd64
- Rancher version on which the issue was reproduced: n/a
- 2.5-head commit id: a85f4d1
- Steps taken to see the issue fixed: installed v2.5-head and resized the window repeatably to try to recreate the issue.
- Check PR to see if anything else is fixed: done.
- Validate everything in the PR: done.

## Result
Rancher version: v2.5-head

![cronjob](https://user-images.githubusercontent.com/39320683/108889206-1c1e4c00-75da-11eb-9fea-ee7801efa393.png)

**Comment by sowmyav27** [comment]
**On 2.5.6-rc6**
<img width="1193" alt="Screen Shot 2021-02-26 at 7 29 08 PM" src="https://user-images.githubusercontent.com/26032343/109374274-ecd13e80-7868-11eb-988d-6cd212a9562c.png">
