### ISSUE TITLE
SecretSelect namespace filtering

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#1979]
- [x] Choices in the dropdown aren't sorted

- [x] The secrets are shown from all namespaces.  Most/all uses of this should only be offering secrets in a single selected (from NameNsDescription usually) namespace.  Should take a prop for the namespace and filter the choices down to those.

IF choosing from among all namespaces is needed somewhere (I don't think it is, since it won't work right now):

- [ ] The emitted info needs to include the namespace, right now only the bare name is emitted so there's no way to identify the namespace.

- [ ] The select shows no indication of what namespace each item is in.  Should have something like the equivalent of `<optgroup>`s to delineate, or at least prefix each one.

- [ ] Blows up with duplicate (vue v-for) keys (I'm assuming this won't be a problem if filtered down to one NS since names can't be duplicated):
![image](https://user-images.githubusercontent.com/753917/101073848-458c8600-355d-11eb-830f-2c09d689289e.png)

**Comment by codyrancher** [comment]
It shouldn't need access to all namespace so I took care of the first two items.

**Comment by sadiapoddar** [comment]
As I consulted with @codyrancher, verifying this fix is relevant to the "logging" app's output creation and how the secret select was a problem.
On branch 2.5.1,
When you try to create a logging output there was no selector available
<img width="1783" alt="Screen Shot 2020-12-13 at 2 17 59 PM" src="https://user-images.githubusercontent.com/72409237/102025780-14773700-3d4f-11eb-8156-99875c4428b2.png">

Verified on 2.5-master, e971e07
With fix the secrets are filtered by namespaces and show secrets in that namespace and so that users can't select from another namespace. 

<img width="1792" alt="Screen Shot 2020-12-13 at 2 19 04 PM" src="https://user-images.githubusercontent.com/72409237/102025796-2953ca80-3d4f-11eb-9383-5b6340ed042c.png">
