### ISSUE TITLE
Alerting v2 - when creating receiver, inputs are lost when switching to edit as YAML

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#2018]
on v2.5-head 395b4

we have 2 issues When creating a new receiver:
1. we need to click the `Edit as YAML` button twice to switch to the YAML format
2. the content is lost after switching to YAML 

Those two are related because after the 1st click we are still at the form page but all inputs are already gone.

![image](https://user-images.githubusercontent.com/6218999/101426574-7b619f80-38ba-11eb-9563-fc0c22cdc441.png)

**Comment by vincent99** [comment]
While I was near here, I fixed the diff view to show the changes from the original state of the resource instead of only the ones while you were in yaml view i.e. if you:
 - Edit a resource as form
  - Change some stuff in the form
  - Go to edit as yaml from within the form
  - Change some more stuff in the yaml
Then the "Show Diff" view should include both sets of changes, not just the latter one like it did before.

**Comment by jiaqiluo** [comment]
The bugfix is validated on rancher:v2.5-head 182e3de

The two problems in the issue are fixed.
