### ISSUE TITLE
Block component in light version need polishing

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#2105]
Steps:
1.  Go to Create deployment
2. Go to Pod Scheduling
3. Click on Add Pod Selector

Results:  The block component need polishing.  It's all one color, you can't see the suggestion text, and spacing for the Add Rule fields in this particular page are too close together.

![image](https://user-images.githubusercontent.com/11514927/102538096-1996f780-4069-11eb-8568-69bae3d92205.png)

**Comment by sadiapoddar** [comment]
Verified the fix on master-head, commit 5da52c0
1. Went to cluster explorer "Deployment"
2. During create a new deployment added pod scheduling and verified that the block component in the light version how has color tones instead of the one color.  
<img width="1620" alt="Screen Shot 2020-12-28 at 2 55 18 PM" src="https://user-images.githubusercontent.com/72409237/103247970-9b1a3f80-491d-11eb-9ea4-3ee75da9ec30.png">

The same verification was to create deploymentset and add pod scheduling. 

<img width="1617" alt="Screen Shot 2020-12-28 at 3 03 56 PM" src="https://user-images.githubusercontent.com/72409237/103248057-f815f580-491d-11eb-8478-f60b83c7d956.png">
