### ISSUE TITLE
[Dashboard UI] Add global.dockerRootDirectory to Logging v2

### ISSUE THREAD

**Issue by nickgerace** [rancher/dashboard#2199]
~~From `values.yaml`, `fluentbit.mountPath` should be exposed for Logging v2 configuration. This should be an optional field for a string.~~

EDIT: only `global.dockerRootDirectory` should be available now.

Backend Issue: rancher/rancher#30329

Backend PR: https://github.com/rancher/charts/pull/926

**Comment by izaac** [comment]
We need this issue to be address to complete E2E testing of https://github.com/rancher/rancher/issues/30329

**Comment by izaac** [comment]
Rancher version: `v2.5-head (01/27/2021)` _2ec02e7_

The field is getting blanked if I click outside its area or the Install button

I tried latest Chrome and Firefox browsers on OS X

![field-remove](https://user-images.githubusercontent.com/27659/106027951-9a91d780-6088-11eb-8a68-6c67fa8a83ac.gif)

**Comment by nickgerace** [comment]
This will need to be changed based on https://github.com/rancher/charts/pull/977.

**Comment by izaac** [comment]
Changes coming in that will require code changed. Reopening

**Comment by nickgerace** [comment]
As indicated by https://github.com/rancher/dashboard/issues/2199#issuecomment-774169210 and https://github.com/rancher/dashboard/issues/2199#issuecomment-774314964, the Dashboard UI design will need to change. Fortunately, this should be more straightforward from a UX perpective.

All references to `mountPath` have been removed in a new PR (https://github.com/rancher/charts/pull/977) and now only `global.dockerRootDirectory` is exposed as an optional string in `values.yaml`. The user should be able to optionally add path for this field (as a raw string).

**Comment by nickgerace** [comment]
This is now ready to be changed. rancher/charts#977 has been merged.
@codyrancher

**Comment by pulberg** [comment]
Why is a UI component even needed if the info exists as a known value for the cluster in Rancher?

```
# 
# Cluster Config
#
...
docker_root_dir: /mnt/dockerdata
```

**Comment by nickgerace** [comment]
@pulberg thank you for the comment! Not every kind of cluster will have this value populated. The logging chart should have the value exposed regardless, but you raise a good point that sometimes this value will be populated.

**Comment by codyrancher** [comment]
Just a note. This is the new relevant backend pr https://github.com/rancher/charts/pull/977

**Comment by izaac** [comment]
Rancher version `v2.5.6-rc5`
Logging v2 chart version: `3.9.000-rc08`

- RKE EC2 cluster k8s `v1.19.8-rancher1-1`  Ubuntu 18.04
  - 1 etcd, 1 ControlPlane, 3 Workers
- Docker 19.03


I see both logs (containers and rke) flowing and stored in the output.
Everything was configured from the Dashboard UI.
There's a difference from the [scenario](https://github.com/rancher/rancher/issues/30329#issuecomment-745459815) I tested. I set the `mountPath` to `/opt/docker` instead of `/opt/docker/containers` as there's a rule in place for the path to not end with `/` or `containers`

`Error: execution error at (rancher-logging/templates/validate-install.yaml:3:5): global.dockerRootDirectory must not end with suffix: '/' or '/containers' `

Everything else is the same `docker-root` was set to `/opt/docker` and the cluster `dockerRootDir` to the same value.

Volumes are properly picked and set by helm for fluentbit

![Screen Shot 2021-02-22 at 12 08 28 PM](https://user-images.githubusercontent.com/27659/108757178-bd3bd280-7506-11eb-93c6-62f73eb89ed6.png)
![Screen Shot 2021-02-22 at 12 08 23 PM](https://user-images.githubusercontent.com/27659/108757183-bdd46900-7506-11eb-8dc9-ededf42407b8.png)

https://github.com/rancher/rancher/issues/30329#issuecomment-783604927
