### ISSUE TITLE
ui refinement

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#2209]
- [ ] User Avatar: cursor should be set to pointer and have and onClick not onHover (@richard-cox has an in progress change for this)
- [x] Dropdowns: the visual style of the dropdown should be the same regardless of role/component. Audit dropdowns with icons. They should be consistent (pick left or right) or be removed.
- [x] Buttons: Should they all be the same size and use other element of style to indicate role/heirarchy?
- [ ] Dashboard page: Revisit summary boxes (provisioning mock as reference https://xd.adobe.com/view/e3bb89da-81d9-4d56-940c-a7c12f6c5021-b6e8/)
-  [x] Top right app menu: dropdown could possibly be style different to indicate that you will be switching contexts.
-  [x] Top nav bar: Why are the buttons in the order that they are in? Can we remove the "apps" button as it is redundant and clutter.

related:
https://github.com/rancher/dashboard/issues/2238

**Comment by lvuch** [comment]
I've made all buttons the same height (	I found no cases of btn-xs or -lg and removed those references from the style sheets). It'd be nice to make inputs and dropdowns match that height so if they are inline they abide to the same height rule. As it is with the label inside inputs/selects I can't take the height down that much. We also have some cases where they are outside (default and aren't (table/add row style).

<img width="423" alt="Screen Shot 2021-01-19 at 3 43 35 PM" src="https://user-images.githubusercontent.com/3013118/105103053-2003ff00-5a6d-11eb-95ce-4a9496576ac1.png">
<img width="1040" alt="Screen Shot 2021-01-19 at 3 43 31 PM" src="https://user-images.githubusercontent.com/3013118/105103057-21352c00-5a6d-11eb-8582-9d1e5734f9b5.png">

**Comment by lvuch** [comment]
Concept for <ProductSwitcher> menu
<img width="350" alt="Screen Shot 2021-01-22 at 3 51 46 PM" src="https://user-images.githubusercontent.com/3013118/105557554-c2202300-5cc9-11eb-965b-1418abb58c2c.png">

**Comment by vincent99** [comment]
- What does the active state for the selected app look like?
- Hover state?
- Dark theme? (current icons are 1-bit, would prefer to avoid having separate light vs dark images because that makes adding more themes painful)
- The app names appear to be quite small
- How will this scale out as more apps are added (wider vs taller); Most will be Cluster-level, the two sections will rarely really be balanced.
- The example apps aren't in the right sections and don't use the right names, which will be a distraction when shown to other people unless you're intending to really display shorter names (which is a marketing argument).

Currently defined products are:
  - Cluster:
    - Apps & Marketplace
    - CIS Benchmark
    - Cluster Explorer
    - OPA Gatekeeper
    - Istio
    - Logging
    - Longhorn
    - Monitoring
    - Rio
    - Rancher Backups
  - Global: 
    - Users & Authentication
    - Continuous Delivery (artist formerly known as Fleet)
    - Cluster Manager (in master with certain conditions; not really named yet)
    - Settings (coming soon; or System Config, or something; not named yet)

**Comment by lvuch** [comment]
Here are some more options for product switcher menu 
![image](https://user-images.githubusercontent.com/3013118/105757546-50cfb280-5f0b-11eb-8b23-3ef23f0d971c.png)

**Comment by nwmac** [comment]
I think we're all good on this now.
