### ISSUE TITLE
Port Global Settings from Ember UI

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2216]
Advanced Settings
Feature Flags

**Comment by jiaqiluo** [comment]
#### Issue 1: Change any setting to `use the default value` in dashboard UI causes the value to be `none` in Cluster Manager UI
 
example 1:
- on the dashboard, edit `engine-iso-url` -> choose `use a custom value` -> save -> edit it again -> choose `use the default value` -> save 

Result 1:
- on the dashboard UI, the value of `engine-iso-url` is `https://releases.rancher.com/os/latest/rancheros-vmware.iso` 
- on the Cluster Manager UI, the value of `engine-iso-url` becomes `None`
 
example 2:
- on the Cluster Manager UI, edit `engine-install-url`  -> set the vaule to `rancher-test-abc` -> Save
- goto the dashboard UI -> edit `engine-install-url` ->  choose `use the default value` -> Save 

Result 2:
-  on the Cluster Manager UI, the value of `engine-install-url` becomes `None` 

#### Issue 2: The setting is marked as `Modified` even the custom value is the same as the default

Steps:
- on the dashboard, edit `ingress-ip-domain` -> choose `use a custom value` -> keep the value `xip.io` ->  save

Result:
- the setting is marked as `Modified` 
![image](https://user-images.githubusercontent.com/6218999/108917717-6957e900-75ed-11eb-975a-b8b1d680616a.png)

#### Issue 3: Change `ui-banners` cause the failure of opening the Cluster Manager UI
Steps:
- on the dashboard, edit `ui-banners` -> choose `use a custom value` -> keep the value `{}` ->  save -> edit it again -> choose `use the default value` -> save 
- on the Cluster Manager UI, refresh the page 

Results:
- the Cluster Manager UI can not be loaded properly because the value of `banner` is null  
<img width="712" alt="Screen Shot 2021-02-23 at 3 57 36 PM" src="https://user-images.githubusercontent.com/6218999/108919433-40852300-75f0-11eb-90cc-959b744bd3d5.png">
 

#### Issue 4: the state of feature flags stays as `Active` after deactivating the feature
Steps:
- on the dashboard, deactivate the feature flag "istio-virtual-service-ui"

Results:
- the state of the feature flag "istio-virtual-service-ui" stays as `Active` although its value is false in API 
- also, after deactivating the feature flag "istio-virtual-service-ui" in Cluster Manager UI, the dashboard still shows it active  

Notes:
- the state of the feature flag `unsupported-storage-drivers` is reflected the changes properly on both UIs

**Comment by nwmac** [comment]
Issues addressed in PR: https://github.com/rancher/dashboard/pull/2413

**Comment by jiaqiluo** [comment]
The fixe for issues mentioned in my previous [comment](https://github.com/rancher/dashboard/issues/2216#issuecomment-784586382) is validated on v2.5-head 87006de with the latest UI.

New issues are logged separated here: 
- https://github.com/rancher/dashboard/issues/2417
- https://github.com/rancher/dashboard/issues/2418
- https://github.com/rancher/dashboard/issues/2421

This issue can be closed.
