### ISSUE TITLE
Continuous Delivery: Configuration is lost when cloning GitRepo

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#2233]
**Steps to reproduce:**

1.  Create a GitRepo resource and configure target type "Advanced" while entering something like:
```
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
```
2. After the GitRepo was created, open Context Menu -> Clone

**Expected:**

The Target type configuration is not lost while cloning

**Actual:**

Target type of cloned repo is set to "All Clusters"

Version: Rancher 2.5.5

**Comment by Ellenqs** [comment]
**1.** Tested on Rancher `v2.5.5`, the issue is reproduced.

**Steps :**

- Deploy rancher.
- Create a downstream cluster.
- Go to cluster explorer ->continuous delivery.
- Go to cluster "Edit config", add label (evn: prod) to the cluster.
- Create a GitRepo, configure target type "Advanced" while entering something like below:
- After the GitRepo was created, open Context Menu -> Clone

```
- name: dev
  clusterSelector:
      matchLabels:
        env: dev
```

<img width="507" alt="Screen Shot 2021-02-04 at 11 36 03 AM" src="https://user-images.githubusercontent.com/75277058/106950112-c47b7780-66e2-11eb-94fe-d18bbe657c7f.png">


**Results:** 
Target type is not cloned and the repo is set to "All Clusters" :
<img width="515" alt="Screen Shot 2021-02-04 at 11 38 11 AM" src="https://user-images.githubusercontent.com/75277058/106950007-a3b32200-66e2-11eb-8961-a2487b7cb131.png">


**2.** Validation on Rancher `v2.5-head (8201e08)`:

Same **steps** as above^^^.

**Results:**

The target type configuration is cloned successfully:
![Screen Shot 2021-02-04 at 10 48 04 AM](https://user-images.githubusercontent.com/75277058/106949931-82523600-66e2-11eb-8c18-426bbb5a349f.png)
