### ISSUE TITLE
Category filter on Apps page has visual rendering issues

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2278]
Go to the Apps & Marketplace view.

In the top-right, the 'All Categories' drop down has no border and the refresh icon overlaps with the drop-down arrow:

<img width="500" alt="Screenshot 2021-02-02 at 16 37 13" src="https://user-images.githubusercontent.com/1955897/106631745-f1aa1780-6574-11eb-8848-5288e7b970ee.png">

**Comment by nickgerace** [comment]
## Summary

The issue appears to have been resolved. I could not reproduce the issue with a v2.5.5 install, but the overlap does not occur.

- Steps taken to reproduce the issue: installed with the following configuration...
  - Installation option (single install/HA): single
  - Browser: Chrome 88.0.4324.182
  - OS: macOS Big Sur 11.2.1
  - Arch: amd64
- Rancher version on which the issue was reproduced: n/a
- 2.5-head commit id: 96dc206
- Steps taken to see the issue fixed: installed v2.5-head and resized the window repeatably to try to recreate the issue.
- Check PR to see if anything else is fixed: done.
- Validate everything in the PR: done.

## Result
Rancher version: v2.5-head

<img width="1517" alt="Screen Shot 2021-02-19 at 5 11 04 PM" src="https://user-images.githubusercontent.com/39320683/108567051-7915bb80-72d5-11eb-9429-d67d0646e78a.png">
