### ISSUE TITLE
Rancher Cluster Explorer shows wrong Deployment number of Active Pods

### ISSUE THREAD

**Issue by asemen2608** [rancher/dashboard#2283]
**What kind of request is this:**   bug 

Rancher Cluster Explorer shows the wrong Deployment number.

The total amount of all deployments with the same deployment name like **rancher-demo**  even from different namespaces are shown.

**Steps to reproduce:**

- Create several deployments, all named rancher-demo on two different namespaces.
- The view shows the total number of all active pods from all namespaces. But the number should be only the amount of pods in the selected namespace.
- The pods list shows correctly only the pods from the selected namespace. (But the amount of pods is less than shown total number).

In the screenshot below, for example, all deployments are called `rancher-demo` in two different namespaces `rancher-demo-pv-nfs` and `rancher-demo-pv-vscan`

**Result:**

The amount of active pods is higher than the pods listed.

The amount active pods should be the same as pods are listed.

**Other details that may be helpful:**

**Environment information**
- Rancher version Rancher v2.5.5  image tag or shown bottom left in the UI):

![screenshot1_](https://user-images.githubusercontent.com/61939253/106153260-a3fd6b80-617e-11eb-9c6b-7b3dce281648.png)

gz#14331

**Comment by Ellenqs** [comment]
Tested on Rancher `v2.5-head (5f3fcb8)`
The issue can not be reproduced.

**Steps:**

- Deploy rancher.
- Create some projects and namespaces, deploy some workloads in different namespaces.
- Go to cluster explorer, select target namespace.
- Go to Deployments and StatefulSets, click the app, check if the pod number is correct and if the pods are in correct namespace.

**Results**
The pods number is correct and they are in the correct namespaces.

<img width="377" alt="Screen Shot 2021-02-03 at 6 21 22 PM" src="https://user-images.githubusercontent.com/75277058/106836707-859be200-664e-11eb-92f4-b6e5b5dd860f.png">
<img width="413" alt="Screen Shot 2021-02-03 at 7 08 06 PM" src="https://user-images.githubusercontent.com/75277058/106843883-ee3d8b80-665b-11eb-9f5a-1f5d6d6a0465.png">
<img width="303" alt="Screen Shot 2021-02-03 at 8 13 43 PM" src="https://user-images.githubusercontent.com/75277058/106844064-6b690080-665c-11eb-9ee9-cc6319c56f41.png">
<img width="326" alt="Screen Shot 2021-02-03 at 8 13 31 PM" src="https://user-images.githubusercontent.com/75277058/106844135-9bb09f00-665c-11eb-8146-8c3144701b18.png">

**Comment by Ellenqs** [comment]
**1.** The issue is reproduced on Rancher `v2.5.5`
**Steps:**
- Deploy rancher in single install mode.
- Create 2 namespaces `ns1` and `ns2`
- Use the following kubectl commands to deploy workloads into namespaces `default`, `ns1`, `ns2` 
- Notice that all workloads share the same name `my-dep`
```
kubectl create deployment my-dep --image=nginx --namespace default
deployment.apps/my-dep created
kubectl create deployment my-dep --image=nginx --namespace ns1
deployment.apps/my-dep created
kubectl create deployment my-dep --image=nginx --namespace ns2
deployment.apps/my-dep created
```
<img width="471" alt="Screen Shot 2021-02-04 at 3 42 57 PM" src="https://user-images.githubusercontent.com/75277058/106969461-b38d2f00-66ff-11eb-8c4e-19021eb5b454.png">
- In Dashboard, go to the detail page of the deployment `my-dep` in the namespace `default`.
  
 **Results:**
- The number of pods under the deployment should be 1, but the UI shows 3, and 2 of them are actually from the other 2 deployments in the other 2 namespaces.
<img width="367" alt="Screen Shot 2021-02-04 at 3 44 37 PM" src="https://user-images.githubusercontent.com/75277058/106969653-17175c80-6700-11eb-9449-9f9d980aff9e.png">

**2.** The bugfix is validated on Rancher `v2.5-head` single-install.

The steps are the same as above^^^. 

**Results:**
-  Only 1 pod shows in the deployment's detail page as expected. 
<img width="405" alt="Screen Shot 2021-02-04 at 3 54 34 PM" src="https://user-images.githubusercontent.com/75277058/106970403-a113f500-6701-11eb-99ec-d4b6ba5e59d6.png">
