### ISSUE TITLE
Loading indicator remains when clicking on Auth Provider whilst already there

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2321]
- Navigate to the `Auth Provider` page in the  `Users & Authentication` product
- Click the `Auth Provider` side nave menu icon again
- The Loading indicator remains, user has to refresh page to continue
- More info in https://github.com/rancher/dashboard/pull/2309#issuecomment-778326620

**Comment by richard-cox** [comment]
It looks like Nuxt isn't calling `finish` in our custom loading component (`GlobalLoading`). Clicking on the link will take users to the root auth provider page, there in asyncData we redirect to the enabled auth provider (if present). The redirect happens before the original route transition completes though, so maybe Nuxt is getting confused. There is a closed issue in Nuxt (https://github.com/nuxt/nuxt.js/issues/4456) but further investigation is required to understand if it is their bug and if so how we work around it. Worth checking out what i think is the nuxt code that should call our loading component's finish - https://github.com/nuxt/nuxt.js/blob/9d33456e69a3bc74734461fa2eb866d2ceac490f/packages/vue-app/template/App.js

**Comment by ryansann** [comment]
Tested on `v2.5.6-rc5`

Steps:
- Navigate to Cluster Explorer > Users and Authentication 
- Click Auth Provider (observe no loading indicator)
- Click Auth Provider again (observe no loading indicator)
- Enable an auth provider (I used Github)
- Navigate back to Users and Authentication > Auth Provider (observe no loading indicator)
- Click on Auth Provider again (observe no loading indicator)

This issue is fixed in `v2.5.6-rc5` ✅
