### ISSUE TITLE
Dashboard Auth[FreeIPA/AD/OpenLDAP] Users shouldn't be allowed to enable multiple auth in dashboard

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2338]
Rancher | v2.5-05fbcbb75ba84a80c5aaa243985e892c52b9ac32-head
User Interface | v2.5-dev
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher51

From the dashboard auth providers, can enable AD, FreeLDAP, OpenIPA at the same time. This shouldn't be allowed from the dashboard.
From the ember UI, users are allowed to add one auth at a time. 

On dashboard:
<img width="100" height="150" alt="Screen Shot 2021-02-17 at 8 59 23 AM" src="https://user-images.githubusercontent.com/38144301/108239515-d7d50c80-70fe-11eb-87b4-bb33c6136361.png">

**Comment by anupama2501** [comment]
https://github.com/rancher/dashboard/issues/2114

**Comment by vincent99** [comment]
This has never been _actually_ been true; The API and Ui both work with multiple on, but it is generally confusing so the navigation to the others are hidden if something other than local is on in Ember, which is why it appears to allow only one.

Showing them all in Vue was at one point intentional because I wanted to solve some of that confusion, but there is API work needed so I thought I gave up and set the left nav item up to go straight to the one enabled non-local driver if there is one; @mantis-toboggan-md ?

**Comment by mantis-toboggan-md** [comment]
Navigating via `/auth/config` redirects to whatever third-party provider is enabled, but there's also an auto-generated list view under `/c/<cluster>/explorer/management.cattle.io.authconfig`.
I left the list view alone because it's easier to tell what's going on when multiple providers are enabled, which, yes, can be done by navigating to a config page directly.

**Comment by nwmac** [comment]
This is by design - navigating to Cluster Explorer -> More Resources -> Rancher -> Auth Providers will always show all providers and from there you could enable multiple - this is for advanced users/use cases only - the normal 'Users and Authentication' views do not let you do this.

**Comment by anupama2501** [comment]
@nwmac "Can you please validate that this is the way you were able to enable multiple and that you can not do this via 'Users & Authentication -> Auth Providers'." --> Can you let me know if this is through ember UI? I did not find this option on dashboard. 
I'm on the v2.5-b4be2b22879d85f268dff655206b8e515d803142-head
