### ISSUE TITLE
Enhancement: find the pods matching the selector and show their ports as options in the dropdown

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2363]
We should make finding the pods that match the selector and then show their ports as options in the correspond dropdown. As I understand it, the service doesn't pick up the container port from the selected object. It used to be faster to set this up in a previous version since all the helpful relevant information was there.

**Comment by catherineluse** [comment]
Is this about the service create/edit form? Is this saying that if you have a service selecting some pods on one tab, then you should see the ports as options on the other tab?

In that case, should the selectors and ports be on the same tab so that it's possible to see the connection?
<img width="1309" alt="Screenshot 2022-11-05 at 11 58 48 AM" src="https://user-images.githubusercontent.com/20599230/200136590-c465540a-8da1-4430-b899-4c00271b4faf.png">
<img width="1309" alt="Screenshot 2022-11-05 at 11 58 48 AM" src="https://user-images.githubusercontent.com/20599230/200136596-689b4fc5-102e-42c0-92a3-0b6bf673e894.png">
