### ISSUE TITLE
Node -List, Details page

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#241]

**Comment by lvuch** [comment]
https://xd.adobe.com/view/4064e2e5-6616-4284-7081-c99e9314f431-3655/

**Comment by tfiduccia** [comment]
Current list of node ui issues: https://github.com/rancher/dashboard/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fnode

**Comment by deniseschannon** [comment]
**Note about cordoning nodes**
Cordoning nodes is adding `{"spec":{"unschedulable":true}}` to the node itself

# List Nodes Page

[ ] Add ability to cordon node in menu for each individual node
[ ] Add Cordon button as a bulk action item. Design Note: Ember UI used a pause icon to indicate cordon and should do the same in this UI.
[ ] Custom Header Columns should be:
 Header Name |  Notes on Value in Row
---|---
   State |  Remains the same 
Name |  Remains the same, which links to detail view page
Roles |  Can we edit the content so that there is a space between the roles. If all 3 roles, can we say all?
Version | Make sure this is coming from kubelet version
   Internal/External IP | `<internal IP>/<external IP>` - If IP exists, can we have ability to copy it?
CPU | CPU comes from `capacity` in the resource
RAM | RAM comes from `memory` in the resource

# Detail Node Page

[ ] Add a `State` label next to the menu hamburger

Example from Ember: 
<img width="276" alt="Screen Shot 2020-04-24 at 4 29 37 PM" src="https://user-images.githubusercontent.com/11410997/80264381-d951b780-8648-11ea-81fe-7cf1a877c99a.png">

[ ] Add ability to cordon node in menu
[ ] **DetailTop** Info: Remove `Description`
[ ] Update the DetailTop to these fields:

Name | Notes
---|---
IP Address | keep as is
Version | Confirm that Kubernetes version is derived from kubelet. Remove copy ability
OS | From `nodeInfo: osImage`  Not from `nodeInfo: operatingSystem`. Remove copy ability
Container Runtime | From `nodeInfo: containerRuntimeVersion`. If prefixed with `docker://`, show Docker icon and then the actual version. If prefixed with `containerd`, show containerd icon and then version. See example below.

Container Runtime Example:
<img width="68" alt="Screen Shot 2020-04-24 at 4 32 37 PM" src="https://user-images.githubusercontent.com/11410997/80264522-46654d00-8649-11ea-8459-44927f7298d4.png">

Other Notes from https://github.com/rancher/dashboard/issues/508

[ ] Node details info for conditions (i.e PID Pressure, Disk Pressure, etc) should use checkmark when green and `x` when red. 

![image](https://user-images.githubusercontent.com/11514927/79806597-a5f7eb80-831d-11ea-800a-e427eb613ad1.png)

[ ] Spacing could be minimized in this section and the line dividing conditions and CPU/Memory/Pods doesn't need to connect DetailTop

![image](https://user-images.githubusercontent.com/11514927/79807872-05a3c600-8321-11ea-83a6-24150a3e5d9a.png)

[ ] Tab Name Updates
    * Rename `Status` tab to `Conditions` tab - Reason: This is what it's called in the yaml
    * Rename `System` tab to `Info` tab  - Reason: This is what it's called in the yaml

[ ] Tab Updates

Tab Name | Content Notes 
---|---
Conditions | `Type` should come from `Conditions: Type` in the yaml. Is it possible to adjust the spacing of the table? Status and Last update shouldn't be so wide. 
Info | This is not a traditional "key/value" pair and shouldn't use the key/value as a header component. Can we just remove the header? For the "keys", can we take the text and convert from camel case to proper english words and capitalized? For the "values", can the content be stretched out so that it's not cut off when we have so much space? 
Address (new tab) | `Hostname`, `Internal IP`, `External IP` are available in `Addresses` in the yaml. For IP, there could be more than 1 IP so the display should accommodate that flexibility. Let me know if you need a mock. 
Images (new tab) | See mockup -> Top part is gauge of how much space ALL the images take up compared to `capacity -> ephermeral-storage` bottom part is table with header of Image Name and Size. 
Taints (new tab)| KeyValue component 
Labels | Should this use the new `ResourceTabs` component that Nancy made? https://github.com/rancher/dashboard/pull/551
Annotations | Should this use the new `ResourceTabs` component that Nancy made? https://github.com/rancher/dashboard/pull/551

**Comment by codyrancher** [comment]
@vincent99 how should we handle something like cordon?
- Will steve be adding actions to the api?
- Should we use norman instead?
- Should we just modify each node in the UI to `{"spec":{"unschedulable":true}} `?

**Comment by codyrancher** [comment]
@deniseschannon can you provide a little more information on the CPU and Memory headers?

The mock shows that these should be displayed as usage PercentageBars but it doesn't look like there's enough information coming back in the API to show CPU usage. I believe there's enough information to determine memory usage but I just wanted to confirm. Is allocatable memory the amount that can still be used while capacity is total available?

Here's the section of the API that I believe you were referring to:
![Screen Shot 2020-04-27 at 3.10.14 PM.png](https://zube.io/files/rancher/c5a30f45d5f4a40a043a37ecf03bfd35-screen-shot-2020-04-27-at-3-10-14-pm.png)

**Comment by lvuch** [comment]
play, pause, docker icons: https://github.com/rancher/icons/pull/25

**Comment by lvuch** [comment]
play, pause, docker icons: https://github.com/rancher/dashboard/pull/574

**Comment by vincent99** [comment]
Node metrics for live  CPU/RAM usage (like "top" shows) are a separate resource that is sometimes available (depending on the cluster), see the cluster overview page which aggregates them.

What you're showing there is scheduler information, how much pods have `reserved` ("used", as far as scheduling goes), how much `capacity` there physically is, and how much of that is`allocatable` in total (some capacity is held back for the OS and such).

**Comment by deniseschannon** [comment]
## Detail Page

- [ ] Move `State` out of DetailTop - We're going to move state into `masthead`. Filed a separate issue https://github.com/rancher/dashboard/issues/628 
- [ ] Create a copy clipboard link for IP in DetailTop
- [ ] Remove Filter from `Conditions`, `Info`, `Taints` tab

**Comment by deniseschannon** [comment]
When a node is cordoned, we should update the status in the UI from `Active` to `Cordoned` to indicate that the node is in a "cordoned" state. 

In the list page, the cordoned nodes should be indicated as their status. 

In the detail page, we need to reflect if the nodes is cordoned or not. 

@lvuch can you think of where we could indicate if a node is in cordoned state in the mock? We need the word `Cordoned` displayed somewhere.

<img width="772" alt="Screen Shot 2020-05-09 at 10 19 37 AM" src="https://user-images.githubusercontent.com/11410997/81480438-b691d800-91de-11ea-8956-52a136b266b7.png">

**Comment by lvuch** [comment]
<img width="583" alt="Screen Shot 2020-05-12 at 9 12 45 PM" src="https://user-images.githubusercontent.com/3013118/81770517-5aa4a900-9495-11ea-8c7d-b328a44b3716.png">

Badge placed to right of Name, I believe <BadgeState> can be used for this

**Comment by codyrancher** [comment]
I changed the way we cordon/uncordon work since it wasn't updating the the badge on the detail page. Unfortunately this uncovered a backend issue (https://github.com/rancher/dashboard/issues/646) which causes the cordon/uncordon options to be removed from the action dropdown after the first usage. Once the backend issue is resolved this should work as intended.

![cordon](https://user-images.githubusercontent.com/55104481/81862791-178f1800-951f-11ea-9dc3-bc17f25de342.PNG)
![missing-cordon](https://user-images.githubusercontent.com/55104481/81862792-178f1800-951f-11ea-8e7c-acdb734986e1.PNG)

**Comment by lvuch** [comment]
@codyrancher the `info` styling can be used for this badge

**Comment by codyrancher** [comment]
@lvuch in that case I'll update the info styling. Right now the info styling is warning.

**Comment by izaac** [comment]
Node list testing was performed in `release-2.4` and `latest` dashboard index.
