### ISSUE TITLE
Rancher Cluster Explorer Node View Does Not Correctly Show Pod Count

### ISSUE THREAD

**Issue by soriaj** [rancher/dashboard#2475]
In Rancher 2.5.5 Cluster Explorer navigating to Cluster Explorer > Nodes > Select any node will result in PODS 0 of X used. This does not reflect the correct number of PODS used in comparison to the Cluster Manager > Nodes > Select any node view. This can be seen in the screenshots provided.  

![image](https://user-images.githubusercontent.com/8506882/109189853-55c19500-7749-11eb-94ed-e7f97537ae7a.png)

gz#15215

**Comment by mantis-toboggan-md** [comment]
This appears to have been fixed when the graph design was updated here: https://github.com/rancher/dashboard/pull/2150

**Comment by aaronRancher** [comment]
This issue is reproduced on Rancher `v2.5.5`
Used pods are not reflected in dashboard:
![Screen Shot 2021-03-12 at 2 48 28 PM](https://user-images.githubusercontent.com/57409052/111003296-13e93f00-8344-11eb-8579-f44d2f02982c.png)
Ember UI:
![Screen Shot 2021-03-12 at 2 49 34 PM](https://user-images.githubusercontent.com/57409052/111003634-bdc8cb80-8344-11eb-8364-fc8bca47077a.png)

The bug fix is validated on Rancher `master-head` `version 3809c80`
Graph design has been updated and pod usage is accurately reflected:
![Screen Shot 2021-03-12 at 3 02 18 PM](https://user-images.githubusercontent.com/57409052/111003542-93770e00-8344-11eb-86ee-a1369845844c.png)
Ember UI:
![Screen Shot 2021-03-12 at 3 01 48 PM](https://user-images.githubusercontent.com/57409052/111003613-b43f6380-8344-11eb-9067-0deba10f3f07.png)
