### ISSUE TITLE
Hide installed apps with the hidden annotation, add option to toggle seeing hidden

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#2489]
- Charts currently support a `catalog.cattle.io/hidden` annotation which makes them not show up in the catalog launch screen.
- The backend will be changing to copy that annotation from the chart to the installed "app" instance (@ibuildthecloud)
- The UI should hide apps that have this annotation by default so that they are not seen.  This will be primarily used on the "*-crd" apps for the CRDs of a tool separate from the tool itself.
- The UI should add an option to toggle seeing the now normally-hidden apps (and the charts screen, while we're at)

**Comment by gaktive** [comment]
Need to track down where the backend related work here is.

**Comment by catherineluse** [comment]
Closing due to a lack of activity - it seems there is no plan to add a 'hide' annotation in the near future.

However, even if there is no longer a plan to add a 'hidden' annotation, we should still explore other options for allowing some apps to be hidden. We've had several Rancher users request that admins could hide some apps from project owners, with the biggest reason that those users don't have permission to install most apps, so if they try to install them, they see the installation fail.

Future work in this area can be tracked in https://github.com/rancher/dashboard/issues/6667
