### ISSUE TITLE
2.6 UX: Implement new top-level navigation

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2499]
- Implement new top-level navigation to replace the current product selector
- Menu icon moved to far left to reflect top-most context setting, menu full-height to reflect same
- All in-cluster applications moved into Cluster Explorer
- Cluster selection moved into outer navigation menu

**Comment by anupama2501** [comment]
Verified on master-head commit 629146a

1. Product selector replaced with top-level navigation
2. Hamburger menu icon placed at tope left for context-setting
3. All cluster applications moved inside of the cluster
4. Cluster selection in the outer navigation

@nwmac can we move `Users & authentication`, `global settings`  to Global APPS rather than under Configuration as they are Global APPS similar to what we have on 2.5.x ?

<img width="254" alt="Screen Shot 2021-05-26 at 11 47 45 AM" src="https://user-images.githubusercontent.com/38144301/119715639-1292c300-be19-11eb-9eb8-a58c22819f2d.png">

**Comment by anupama2501** [comment]
Logged an enhancement ticket and closing this ticket
