### ISSUE TITLE
Navigating to deprecated catalog app resource breaks UI

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#2502]
1. Deploy `cost-analyzer` app from partner catalog
2. Navigate to Apps&Marketplace  -> Installed Apps
3. Click `kubecost` 
4. Find the one resource that is missing the type value and click it

**Expected:**

Ingress detail page is shown

**Actual:**

UI stuck on loading screen and navigation menu broken

<img width="1168" alt="Screenshot 2021-03-10 at 14 18 49" src="https://user-images.githubusercontent.com/3813921/110638998-7d841480-81af-11eb-8550-6e76e8cce845.png">
<img width="434" alt="Screenshot 2021-03-10 at 14 15 41" src="https://user-images.githubusercontent.com/3813921/110639025-8379f580-81af-11eb-81c4-0c902422d001.png">

<img width="569" alt="Screenshot 2021-03-10 at 14 43 39" src="https://user-images.githubusercontent.com/3813921/110639337-e5d2f600-81af-11eb-8628-3fb938a6f003.png">

Rancher 2.5.6

**Comment by mantis-toboggan-md** [comment]
I'm unable to reproduce this with kubecost myself and I think it's fixed; can you confirm that you're still seeing this issue and if so, can I get more detail about your kubecost configuration? Just looking at the code, the logic behind that table was updated to exclude entries with `type` undefined.

**Comment by davidnuzik** [comment]
Needs a milestone set on this issue (am I checking in v2.5-head for 2.5.10 or v2.6-head for 2.6.1?) @gaktive

**Comment by gaktive** [comment]
@davidnuzik I'd start with 2.5.6 as reported, then checking if 2.5.9 or 2.5-head has the behaviour. As for 2.6.x, I'd look at 2.6.1 (aka master). Again, we couldn't repro this back in March and have not heard any reports since so it may have been a one-off.

**Comment by davidnuzik** [comment]
**I could not reproduce (nor could others as mentioned in prior comments)**
My understanding is that at this point I should close out this issue. Should anyone identify an issue like this again please re-open and we can investigate.
 
**Reproduction Environment:**

Rancher version: v2.5.6 and v2.5-head and v2.6-head
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke1
Downstream K8s version: various - latest defaults on the cluster creation form
 
**Reproduction steps:**

1. Create a downstream RKE1 cluster. Once it's ready open the cluster explorer in the ember UI (so we switch to dashboard).
2. Go to the Apps & Marketplace page. I don't see an app named cost-analyzer. I installed the Kubecost app (1.89.101) looks like this is the same as the old cost-analyzer entry (probably just due to updated chart repo). Note I couldn't get any persistent volumes to work even with cloud provider set up properly - I just unchecked any boxes in the chart for persistent storage. It shouldn't have an impact.
The app installs successfully without any errors.
3. Go to Apps & Marketplace -> Installed Apps
4. click kubecost
5. I could not reproduce. I get no TypeErrors.
 
**Additional Info:**
