### ISSUE TITLE
2.6 UX: Create new support page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2505]
Move the footer links into the app slide-in and create a new page for support information.

This should use a setting to store an entered license key - when licensed, the presentation of the support page changes.

**Comment by kravciak** [comment]
Notes for support page, please take them as suggestions since I don't know what's expected at this point:
 - I can not click `Save` after entering SUSE Subscription ID, is this just UI without backend for now? This means I can't see presentation of support page of registered rancher
 - `Community Support` is a box on home page, but side-text on support page, first impression is inconsistent
 - `Note: This will not effect your subscription.` on the PR - I am not native speaker but I think `effect` should be `affect`.
 - banner height is bigger when compared to home page

**Comment by nwmac** [comment]
The subscription ID must adhere to the format for subscription IDs, so if you enter something that does not, the save button will not be enabled.

I've fixed the typo.

We'll take the other two items as feedback for consideration

**Comment by kravciak** [comment]
> The subscription ID must adhere to the format for subscription IDs, so if you enter something that does not, the save button will not be enabled.

We also have `INTERNAL-....` keys, if they work we should add them to the regex filter.
Please check on https://scc.suse.com/subscriptions/4608017 for specific format, or I can share in direct message if you don't have access.

**Comment by kravciak** [comment]
I noticed subscription ID input field is saved after I remove it.
- click `add subscription ID` 
- fill subscriptionID -> save
- remove subscriptionID -> remove
- click `add subscription ID`

At this point subscriptionID is pre-filled with last used value. Pre-filled value disappears after page reload.
Is subscription ID sensitive information or it's fine this way?

**Comment by nwmac** [comment]
I don't believe it is sensitive, but I think we should clear the last value - I'll take a look

**Comment by nwmac** [comment]
The key is now blanked out on re-add

**Comment by kravciak** [comment]
Tested on master-head (97ca638)
