### ISSUE TITLE
2.6 UX: Create SUSE Rancher theme and switch to this when license key supplied

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2506]
Add a 2nd light/dark theme pair, with different logo/images and with small colour changes.

Choose the theme to used, based on if a license key has been provided.

**Comment by nwmac** [comment]
Let's discuss how to approach this ticket before starting.

The goal is to be able to change the brand theming when the user has indicated that they have a valid SUSE Rancher subscription. We should think about this in context with supporting white labelling and allowing people to custom some aspects of the UI for their own brand.

**Comment by mantis-toboggan-md** [comment]
There are a few parts to this issue: tracking that a license key has been provided, switching brand name, switching brand images, and switching brand colors.

License key
Eventually it'd be good to validate the key, but for now we'll just have a  on/linked from the support page to enter the key, which will update a global setting boolean, `hasSupport` or similar.

Brand Name / Images 
The branding functionality should be made in such a way that it can be expanded to arbitrary user-defined brands, but for now the UI will just be pre-loaded with the SUSE Rancher brand images.
The cluster manager already has some private label functionality described [here](https://github.com/rancher/ui/blob/8e07c492673171731f3b26af14c978bc103d1828/public/assets/images/logos/README.md). `ui-pl` isn't used in the cluster explorer right now, but I think it can be leveraged for this purpose as well. I think we would do something similar to this in the cluster explorer, leverage a directory with the same filenames for brand-specific images, but rather than asking users to replace a directory of images we'll want something like an `/assets/brands/<your_brand_setting>` folder and some kinda `BrandImages` component which checks the brand global setting and loads images from the associated directory, defaulting back to the Rancher images in `/assets/images/pl`.  This image folder can also have a metadata json describing the color(s) to be used and maybe a display name for the brand since using the brand setting as a folder name imposes some restrictions on that string. 

Brand color(s)
We can save color information in the same place as brand images, in a metadata json. For a start, we only need to change the `primary` color variable. One potential option is to overwrite the css custom properties defined in the light and dark [theme files] (https://github.com/rancher/dashboard/blob/master/assets/styles/themes/_light.scss#L37), though it would be preferable to overwrite the `$primary` scss variable than to overwrite every css property created referencing `$primary`. More research needed to see how doable that is.

Eventually we may want to store this branding info (name, colors, images) in kubernetes so they can be added/modified from the UI.

**Comment by izaac** [comment]
Rancher version `v2.6 master-head (05/18/2021)` _55f0bb2_

Styling is loading, I see some colors changed in text other web elements but the logo is still the Rancher logo not the SUSE Rancher logo for the SUSE branding after enabling with support key.

![Screen Shot 2021-05-18 at 4 20 29 PM](https://user-images.githubusercontent.com/27659/118735381-2f197480-b7f5-11eb-9b00-b734e6567569.png)

**Comment by izaac** [comment]
Rancher version `v2.6 master-head (05/25/2021)` _979d2ba_

Branding switch looks good when providing the expected Subscription string.

## Not in validation scope

- **License key validation**
- `ui-pl` and other Branding fields. https://github.com/rancher/dashboard/issues/2896
- Branding logic for other fields like `ui-pl`, logos, etc will be done on other issues
