### ISSUE TITLE
2.6 UX: Monitoring: Improve 2nd-level navigation

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2510]
Review the current navigation structure for Monitoring - this needs to be refactored given that this will now be combined into the Cluster Explorer nav.

Example below:

![image](https://user-images.githubusercontent.com/1955897/110765038-aa860500-824b-11eb-8b44-eb99038293d3.png)

The main tasks:

- Combine Service and Pod Monitors into one single nav item and use horizontal tabs as per the example
- Combine Routes and Receivers into one single nav item and use horizontal tabs as per the example

The create button should create the resource for the active tab

**Comment by slickwarren** [comment]
tested on master-head (3e89bb8)
<img width="1333" alt="Screen Shot 2021-05-12 at 9 16 14 AM" src="https://user-images.githubusercontent.com/16691014/118009212-b8ffa400-b302-11eb-87ea-b3233a54c5dc.png">
<img width="1339" alt="Screen Shot 2021-05-12 at 9 15 28 AM" src="https://user-images.githubusercontent.com/16691014/118009219-bb61fe00-b302-11eb-9c48-40ca72a31f16.png">
<img width="1376" alt="Screen Shot 2021-05-12 at 9 13 31 AM" src="https://user-images.githubusercontent.com/16691014/118009223-bbfa9480-b302-11eb-949a-b8871a32c2b9.png">
<img width="1344" alt="Screen Shot 2021-05-12 at 9 13 11 AM" src="https://user-images.githubusercontent.com/16691014/118009227-bc932b00-b302-11eb-8db0-58da44ff3f96.png">

after creating any of the resources, user is directed to a non-embedded page of that resource. 
**would expect them to be brought back to the new tab with horizontal tabs**

**Comment by slickwarren** [comment]
When editing `pod monitors` or `service monitors` via yaml, the following occurs:
<img width="1792" alt="Screen Shot 2021-05-19 at 9 53 09 AM" src="https://user-images.githubusercontent.com/16691014/118853531-b663f800-b888-11eb-9dcc-1050b778c95e.png">
<img width="1552" alt="Screen Shot 2021-05-19 at 9 53 05 AM" src="https://user-images.githubusercontent.com/16691014/118853583-c2e85080-b888-11eb-8153-02cfea418297.png">

when editing/creating a `route` as yaml, user is redirected to the `recievers` tab instead of `route` tab (when editing through config, the user is sent back to the appropriate page, `route`)

this was on master-head (55f0bb2)

**Comment by slickwarren** [comment]
on master-head (629146a):
* create, edit, clone, delete each of the following
  * pod monitor (yaml only) -- pass
  * service monitor (yaml only) -- pass
  * routes (config and yaml) -- pass
  * receivers (config and yaml) -- pass
