### ISSUE TITLE
Dashboard - Users Creation "ask users to change password" is not requesting to change password on re-login

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2524]
Rancher v2.5-a420b5195dd1d0a23411b0aeb17713f291e90e10-head

From cluster explorer --> Users and Authentication --> create users

Fill in the details and click on the check box "Ask user to change their password on first login"
Signout and sign in with the above created user 
Verify the user is not requested to change password

After creating the user, if we edit the user and enable the checkbox again, the user is requested to change password

<img width="1054" alt="Screen Shot 2021-03-11 at 2 50 58 PM" src="https://user-images.githubusercontent.com/38144301/110866061-6a3d7b80-8279-11eb-9801-f57806602f88.png">

https://github.com/rancher/dashboard/issues/2204

**Comment by anupama2501** [comment]
Verified on v2.5-b2a34d7cef440e3ed1de7d506233aa3a332649ae-head
Steps:
From cluster explorer --> Users and Authentication --> Users --> Create a users as standard user with "Ask user to change their password on first login" and "Generate a random password" selected
Upon the initial login, users are allowed to change the password
Edit the same user and select "Ask user to change their password on first login" 
Upon the next login, users are allowed to change the password

**Comment by anupama2501** [comment]
Seeing an issue when:

- From cluster explorer --> Users and Authentication --> Users --> Create a users as standard user with "Ask user to change their password on first login" and "Generate a random password" selected
- Re-login to see the user is allowed to change the password
- Now, from the cluster explorer --> Users and Authentication --> Users --> edit the user created in the step above and select both "Ask user to change their password on first login" and "Generate a random password"
- While saving, we see 1 put call and 1 post call and when we try to re-login, user is not prompted to change the password
- In the put call, we see the mustchangePassword set to True, but in the post call, mustchangePassword is changed to false
<img width="200" alt="Screen Shot 2021-03-30 at 1 13 56 PM" src="https://user-images.githubusercontent.com/38144301/113051174-889ce580-915a-11eb-802c-8d82d4ac72c7.png">
<img width="200" alt="Screen Shot 2021-03-30 at 1 13 50 PM" src="https://user-images.githubusercontent.com/38144301/113051170-876bb880-915a-11eb-8619-94b2d0c67d57.png">

**Comment by richard-cox** [comment]
At first I thought this issue was due to editing the steve user and then calling a norman user action, however I've changed it locally so both user requests (update and change password) use norman and the problem persists. This matches how the old ember ui works, which also shows the bug,

Rough summary of what's happening...

PUT v3/users/u-kjr6n
- properties name, description and mustChangePassword are correctly persisted and shown correctly in response
POST v3/users/u-kjr6n?action=setpassword
- name and description are correct in response
- mustChangePassword is incorrect (stale false value) in response
- password change correctly applied (can log in with altered password)

I tried swapping the order for these requests and get even stranger results

POST v3/users/u-kjr6n?action=setpassword
- password change correctly applied (can log in with altered password)
PUT v3/users/u-kjr6n
- properties name, description and mustChangePassword are not persisted (not in  GET v3/users/u-kjr6n)... even though they are correct in the response

I think this is an API bug and have reached out to them

**Comment by richard-cox** [comment]
It looks like the API resets `mustChangePassword` during the `setpassword` action (https://github.com/rancher/rancher/blob/692a9507ebeec70118aa8496999e89d0dfa1cc18/pkg/auth/api/user/user_actions.go#L140), so the password must be changed first.

There's a PR incoming that changes changes the user update from steve to norman (to simplify things). This also contains a horrible hack to get this working (wait for 10s). The crux of the problem seems to be some kind of race condition between applying changes to the user from the setpassword action and then the update.

**Comment by anupama2501** [comment]
v2.5-2f2cfe636f0846abb1e3e751d3aae4c4ae34d291-head

- From cluster explorer --> Users and Authentication --> Users --> Create a users as standard user with "Ask user to change their password on first login" and "Generate a random password" selected
- Re-login to see the user is allowed to change the password
- Now, from the cluster explorer --> Users and Authentication --> Users --> edit the user created in the step above and select both "Ask user to change their password on first login" and "Generate a random password"
- Re-login and verify the mustchangePassword set to True and users are prompted to change password upon login.
- Created a cluster as a standard user and the cluster comes up fine.
