### ISSUE TITLE
UI Issues in Groups

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2540]
**On 2.5-head commit id: `38649e228`**

### **Issue 1**

- Local cluster --> Users & Authentication --> Group --> Click on Assign global Roles
- Dropdown for "Select Member" is too _tall_.

<img width="1650" alt="Screen Shot 2021-03-15 at 3 13 32 PM" src="https://user-images.githubusercontent.com/26032343/111229260-d9c9a880-85a2-11eb-8d38-538ee717cdf4.png">

### **Issue 2**
- Local cluster --> Users & Authentication --> Group --> Click on Assign global Roles
- User is not able to select from Global Permissions/Built In roles unless user selects from the "Select Member" dropdown

### **Issue 3**
The built In roles are NOT sorted, can we sort them Alphabetically or in any way? 

### **Issue 4**
Can we have some form of demarcation in the Global Permissions/Built In roles/Custom roles section?
<img width="1657" alt="Screen Shot 2021-03-15 at 3 31 28 PM" src="https://user-images.githubusercontent.com/26032343/111229684-902d8d80-85a3-11eb-8fa6-5e985fcc8b1d.png">

**Comment by richard-cox** [comment]
Issue 1 - This is by design. The larger input field will contain the selected group. If the size is reduced it would lead to bobbling when the field expanded to accommodate the selection.
Issue 2 - This is also by design and differs from the Ember implementation. In the old ui it would ignore existing bound roles so didn't need a group before roles could be checked. This led to bugs like being able to bind the same role multiple times. In the new ui we now take into account these existing roles and provide different checkbox behaviour. This has been improved in #2569
Issue 3 - Will be fixed by #2569
Issue 4 - Will be fixed by #2569

**Comment by sowmyav27** [comment]
**On 2.5-head commit id: `118f999`**

- Enable AD With TLS auth in rancher server setup
- Cluster explorer --> Top left menu dropdown --> Users and Authentication --> Group
- Issue3 and Issue4 are seen fixed
<img width="1153" alt="Screen Shot 2021-03-30 at 8 41 09 PM" src="https://user-images.githubusercontent.com/26032343/113087368-5316ed00-9198-11eb-927a-cd7eb6b61be8.png">
