### ISSUE TITLE
Config Map - List/Detail & Create/Edit

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#265]
Use this wireframe from rancher/dashboard#256 for list of Config Map/Config Map detail/create Config Map pages:

https://xd.adobe.com/view/5bfd9046-4985-4203-68ec-57f7f0a7eae2-2dcc/

**Comment by lvuch** [comment]
the values header in this mock is incorrect and should be larger and white (20px)

**Comment by tfiduccia** [comment]
The Labels and Annotations section is still missing.

**Comment by codyrancher** [comment]
@vincent99 what's the most appropriate way to get workloads related to a config map?

Do I need to search through the spec of deployments to find the related "configMapKeyRefs"?

**Comment by vincent99** [comment]
Yes, but it's impractical, you'd need to load and search all 7 workload types + standalone pods, then look through each spec.

I talked to @ibuildthecloud about adding a something to Steve to handle this, either as a one-time API call (like `GET /v1/related/<type>/<namespace>/<id>`) or as additional info directly in the resource metadata of types we want to track it on (which implies change events would fire).  The backend already essentially has all the types loaded in memory and watched so this can be done much more efficiently there.

So @codyrancher hold off on this until there's an API available.  In the meantime it would be nice to get rid of the hardcoded fake data and just drop the section entirely, or make it say coming soon...

**Comment by codyrancher** [comment]
I went ahead and did a coming soon.

**Comment by deniseschannon** [comment]
Feedback on Config Maps based on convo with @ibuildthecloud 

Notes:
* Instead of `Values` call it `Data`
* The main section of this resource should be `Data`  instead of `Values`. This should not be in a tab.
*  Toggling between View and Edit page should mimic each other as much as possible. 

# List Page

Column Header Changes
[ ] Remove `State`
[ ] Update the header from `Detail` -> `Data`

Column Headers will be `Name`, `Data`, `Age`.

# Create/Edit Page

When moving the components into tabs, remove the titles from the KeyValue component as they will be the Tab label.

[ ] Rename  title from `Binary Values` to `Binary Data` and move KeyValue component into a tab with no title 
[ ] Move `Labels` into a tab with KeyValue component inside tab with no title
[ ] Move `Annotations` into a tab with `KeyValue` component inside tab with no title

After changes, the layout of the page will be 

Main Section:
`Data`

Tabs Section:
`Binary Data`, `Labels`, `Annotations`

# View Page

When moving the components into tabs, remove the titles from the KeyValue component as they will be the Tab label.

[ ] Remove Related Workloads section - Tracking the ability to add this to this page in https://github.com/rancher/dashboard/issues/498. Since this is dependent on backend, let's remove it until backend is available. 
[ ] Move the `Data` section from a tab into directly under DetailTop. This allows the detail view and create/edit page to look similar.
[ ] Update name of tab from `Binary Values` to `Binary Data`. Make sure there is no title on the KeyValue component.
[ ] Split `Labels and Annotations` into 2 tabs `Labels` and `Annotations`. Inside each tab, use the `KeyValue` component with no title.

After changes, the layout of the page will be 

Main Section:
`Data`

Tabs Section:
`Binary Data`, `Labels`, `Annotations`

**Comment by deniseschannon** [comment]
## Edit and Detail Page
- [ ] Remove the spacer between DetailTop and the KeyValue component.

<img width="318" alt="Screen Shot 2020-04-30 at 6 02 38 PM" src="https://user-images.githubusercontent.com/11410997/80772915-1f0cf500-8b0d-11ea-9fac-1d391df284a7.png">

- [ ] Span the KeyValue table to the entire width of the section. It's currently only taking up half the space and should take the whole width.

**Comment by soumyalj** [comment]
Tested with master-head build(dd102af17, 7248f0966) using dashboard UI. 
Tested creation, editing and deleting of Config maps with all the options. 
Config maps feature is functional using the dashboard UI.
