### ISSUE TITLE
Add Create/Edit/View/Detail Pages for RBAC Role and ClusterRole

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2663]
- This was split out from rancher/dashboard#2111
- The RBAC Role and Cluster Role resources in Cluster Explorer should have similar create/edit/detail experience as the Users & Authentication Roles resources except..
  - Cluster Roles form should only contain name and description, and grant resources
  - Roles form should only contain name, description and namespace, and grant resources

**Comment by slickwarren** [comment]
API Groups are marked as required, but user can save without entering by entering any text, then removing it -- I don't think this is supposed to be a required field, it is not required in the `Users and Authentication` roles section.  Maybe this was supposed to be the default for apiGroups  `*`, since that's what it is in v1
<img width="978" alt="Screen Shot 2021-04-13 at 12 26 22 PM" src="https://user-images.githubusercontent.com/16691014/114609324-8440f400-9c53-11eb-9519-13494d61c4f1.png">
<img width="1524" alt="Screen Shot 2021-04-13 at 12 19 17 PM" src="https://user-images.githubusercontent.com/16691014/114609331-860ab780-9c53-11eb-8ec7-517597fc5feb.png">

**Comment by slickwarren** [comment]
once a user enters something in the non-resourceURL field, user is unable to create the role/clusterRole

<img width="1532" alt="Screen Shot 2021-04-14 at 9 35 41 AM" src="https://user-images.githubusercontent.com/16691014/114746750-eefe3800-9d04-11eb-9381-1a905a38182c.png">
<img width="1535" alt="Screen Shot 2021-04-14 at 9 35 32 AM" src="https://user-images.githubusercontent.com/16691014/114746753-f02f6500-9d04-11eb-930f-ab1742faf274.png">
<img width="1520" alt="Screen Shot 2021-04-14 at 9 35 49 AM" src="https://user-images.githubusercontent.com/16691014/114746740-ec9bde00-9d04-11eb-86a8-c9a4fa9a60ae.png">

**Comment by slickwarren** [comment]
tested on v2.5-head (7002499):
* view role shows name, description and namespace, and grant resources -- pass
* view clusterRole shows name, description, and grant resources -- pass
* edit role shows name, description and namespace, and grant resources -- pass
* edit clusterRole shows name, description, and grant resources -- pass
* create role shows name, description and namespace, and grant resources -- pass
* create clusterRole shows name, description, and grant resources -- pass
* detail of role shows name, description and namespace, and grant resources -- pass
* detail of clusterRole shows name, description, and grant resources -- pass
I will file the above 2 bugs in an improvements ticket, since this one is not particularly focused on the `grant resources` page
