### ISSUE TITLE
2.6 UX: Apps & Marketplace Improvements: Charts List

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2668]
- Change the header text from 'Deploy Chart' to 'Charts'
- Move repo checkboxes into a multi-select drop down (?)

**Comment by nwmac** [comment]
Sync with @richard-cox for details

The goal here is to change the Apps & Marketplace Charts page and change the checkboxes that let you filter the charts by repository to be a multi-select drop-down.

Note, we may want to create a multi-select drop down with checkboxes, similar to the Material Design one (https://material.angular.io/components/select/overview#multiple-selection) - rather than use the one we currently have.

**Comment by aaronRancher** [comment]
Currently blocked by this issue: https://github.com/rancher/rancher/issues/32943

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version 3d465ee`
A repo dropdown and categories dropdown have been added:
![Screen Shot 2021-06-08 at 2 05 38 PM](https://user-images.githubusercontent.com/57409052/121264691-6b784780-c86c-11eb-8525-a98cd02b3fb8.png)
![Screen Shot 2021-06-08 at 2 05 44 PM](https://user-images.githubusercontent.com/57409052/121264692-6c10de00-c86c-11eb-913a-39cccd3a11a8.png)

After adding a new repo, a new entry is added to the drop down list.
![Screen Shot 2021-06-08 at 2 49 03 PM](https://user-images.githubusercontent.com/57409052/121263877-26074a80-c86b-11eb-8f2b-f19b24a97804.png)
@richard-cox When a new repo is added, are the new charts excluded from the `Categories` dropdown?

I did also notice that I was unable to search for `OPA Gatekeeper` using the search bar.
![Screen Shot 2021-06-08 at 2 06 11 PM](https://user-images.githubusercontent.com/57409052/121263933-37505700-c86b-11eb-9be6-549b72e675a2.png)

**Comment by aaronRancher** [comment]
PR: https://github.com/rancher/dashboard/pull/3003

**Comment by aaronRancher** [comment]
Tested on Rancher `master-head` `version e546ffe`

- Header has been changed from `Deploy Charts` to `Charts`
- A repo dropdown can be used to sort charts.
![Screen Shot 2021-06-30 at 12 23 52 PM](https://user-images.githubusercontent.com/57409052/124019584-15478180-d99e-11eb-802b-2a6d75160767.png)
- `categories` are Rancher specific. it looks at the chart's keywords and matches them against a known list.
![Screen Shot 2021-06-30 at 12 31 04 PM](https://user-images.githubusercontent.com/57409052/124020368-0e6d3e80-d99f-11eb-9f8f-4ac7d74186c6.png)
```
  'Storage',
  'Monitoring',
  'Database',
  'Repository',
  'Security',
  'Networking',
  'PaaS',
  'Infrastructure',
  'Applications',
```
`Monitoring` used as an example. Charts from the `https://prometheus-community.github.io/helm-charts` repo are sorted into `Monitoring`
![Screen Shot 2021-06-30 at 12 26 27 PM](https://user-images.githubusercontent.com/57409052/124019851-69526600-d99e-11eb-8faf-dc14364e4826.png)
- The search bar now uses the chart display name instead of the ID name.
![Screen Shot 2021-06-30 at 12 32 30 PM](https://user-images.githubusercontent.com/57409052/124020539-3f4d7380-d99f-11eb-9a9f-fb01426abd24.png)
