### ISSUE TITLE
Apps & Marketplace Improvements: Installed App Details Page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2672]
- Current only shows resource, values.yaml, readme and release notes
- Page should be expanded to show more chart and install info, and state

Also
- Ensure the chart version is in a prominent place
- To discuss
  - The generic 'YAML' options will confuse with helm values YAML. Discuss the removal of YAML from toggle. Keep option in menu. Where will the actual view yaml component live?
  - Move 'edit/upgrade' to a more prominent position. Keep option in menu. Should this apply to all generic detail pages?

**Comment by nwmac** [comment]
@richard-cox I think this is done?

**Comment by richard-cox** [comment]
@nwmac You're thinking of https://github.com/rancher/dashboard/issues/2669 , this is the update to the page for an existing app

**Comment by catherineluse** [comment]
The UI has changed somewhat since this issue was created. For example, the "Edit/Upgrade" button is now called "Update." And the version of an installed app appears in two places, the header and in the chart version dropdown:
<img width="1015" alt="Screenshot 2022-11-04 at 2 54 57 PM" src="https://user-images.githubusercontent.com/20599230/200080866-7bdd453e-6e94-4100-ab3e-16fb42319021.png">
 
I think the issue description should be updated and expanded with more details based on the latest version.

**Comment by richard-cox** [comment]
This issue relates to the `installed app` page, not `install app`. I've added a screenshot to make this clearer

**Comment by kwwii** [comment]
@manuelecarlini What is the state of this issue? Do we have a solution ready? If yes, where can it be found and what are the next steps?

**Comment by manuelecarlini** [comment]
After the latest discussion, this would be the proposed solution for a first iteration, it's included in the general epic for Apps and Marketplace, but it would be ok to implement it separately as it doesn't have any dependencies
https://xd.adobe.com/view/f027b934-be05-4f21-a99f-38d17c86d417-a574/screen/bad80c7c-a8ea-4abd-a361-47ccbbfffcb8
