### ISSUE TITLE
Security/Roles - List/Detail & Create/Edit

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#271]
Use this wireframe from rancher/dashboard#158 for list of roles,  role detail pages and create roles:
https://xd.adobe.com/view/411d4b53-b8fd-4cb6-77dd-d41a1dc50173-372c/

**Comment by westlywright** [comment]
Adding a couple notes for future reference re: design differences: 

1. Filter exists inside the tab as the search component is built into the table component
2. State doesn't have icons (needs to be implemented at the component level)
3. Built-in, Locked, or Creator Defaults props don't exist on global or cluster roles
4. Add
.. 1. since this is a tabbed view I've removed the radio selector and the create button will send you to the right role create based on your tab
.. 2. Rancher doesn't include an inherit concept any longer, does it make sense to include it here? (detail as well)

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/dashboard/issues/2111
