### ISSUE TITLE
[Cluster Explorer] Cannot scale down deployment to 0 

### ISSUE THREAD

**Issue by mscbpi** [rancher/dashboard#2717]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Use GUI Cluster Explorer to scale down a deployment to `replica: 0`. Works with yaml or kubectl.

**Result:**

It asks for a value greater or equal than 0, while 0 is a valid value.
BTW a negative value can be filled in the Replica field, just by scrolling down.
![image](https://user-images.githubusercontent.com/28528210/109949699-f5e46480-7cdb-11eb-9e43-d763ebdbec07.png)

**Other details that may be helpful:**
Rancher 2.5.6

**Comment by thehejik** [comment]
Validated as fixed in master-head `91a6f51`

* Value 0 is now accepted 
* Scaling works with 0 and positive values
* Negative values are not allowed with error message: `Deployment.apps "nginx" is invalid: spec.replicas: Invalid value: -1: must be greater than or equal to 0`
* Scrolling down stops at value 0 but negative value can be still entered manually - anyway the value is not accepted after clicking Save with the error above

Closing as fixed.
