### ISSUE TITLE
Ingress - List/Detail & Create/Edit

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#272]
Need Design

**Comment by lvuch** [comment]
https://xd.adobe.com/view/76f2934d-e161-49b8-7074-5a78aeb068e0-00c3/

**Comment by lvuch** [comment]
https://xd.adobe.com/view/76f2934d-e161-49b8-7074-5a78aeb068e0-00c3/

**Comment by tfiduccia** [comment]
Reference for fields that should be included:
1.  Ember UI for Ingress
2.  https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#ingress-v1beta1-networking-k8s-io.

**Comment by deniseschannon** [comment]
Feedback on Ingress based on convo with @ibuildthecloud 
 
Note about Ingress:
There can only be 1 default backend in a kubernetes clusters, so it doesn’t make sense to have ability to add multiple default backends per ingress. 

# List Page

[ ] Custom Header Columns should be:

 Header Name |  
---|
State |
Name |  
Hosts | 
Target |  
Age | 

# Create/Edit Page 

[ ] Main Component Updates:

  * In each `Rule`, remove the radio button option. The only options should be `Request Host`, `Path`, `Service`, `Port`. `Backend default` is moving into a tab. 
  * For some reason, the label `Target` isn't showing up in the dropdown. It shows up in other pages for the `LabeledSelect`, so not sure why it's not showing up on this page. 

> Note: In k8s 1.18, there is now a `pathType` that we need to add in. Need to incorporate path type in for k8s 1.18+ clusters.

[ ] Tabs Section

Tab Name | Tab Content Notes 
---|---
Certificates | For some reason, the label `Certificate` isn't showing up in the dropdown. It shows up in other pages for the `LabeledSelect`, so not sure why it's not showing up on this page. Instead of disabling the dropdown, can we hide it when selecting `use default ingress controller certificate`?
Default Backend | There can only be 1 default backend for an ingress for the entire Kubernetes cluster. Inside the tab, there should be a `Target` dropdown and `port` text box. These fields are what was in the `Rule` section. We should put a warning label above the `Target` dropdown and `port` text box. The warning text should be `Warning: Default backend is used globally for the entire cluster.`
Labels | Use KeyValue component
Annotations | Use KeyValue component


# Detail Page

Last time I looked, the detail page wasn't loading, so this is based on changes of the create/edit page.

[ ] DetailTop Info: No fields

[ ] Main Component Updates:

For each rule, create rules/rulepaths based on mock. 

[ ] Tabs Section

Tab Name | Tab Content Notes 
---|---
Certificates | 
Default Backend | We should keep the warning label. The warning text should be `Warning: Default backend is used globally for the entire cluster.`
Labels | Use KeyValue component
Annotations | Use KeyValue component

**Comment by deniseschannon** [comment]
## List View

### When to create links:
* Whenever displaying a target service, make it a link to the detail view of the target. 
* Whenever displaying the hostname/path of a rule, make it a link directing to that specific hostname/path. 

### How to list in Targets

1. Default Backend: Always show the default backend. If there are rules, add the rules as well, but anytime a default backend is defined, let's add it into the list of targets.

Variable Form:
Default Backend: `<TARGET_SERVICE_A>`

Example:
```
Default Backend: targetservicea
```

2. For every rule, show the target host/path and the service name. Expand it out if there are more paths in a rule. 

**Example: 1 Rule with 1 hostname, 1 path**

`<TARGET_HOST_1>`/`<TARGET_PATH_1>` > `<TARGET_SERVICE_A>`

```
hostname1/path1 > targetservicea
```

**Example: 1 Rule with 1 hostname & 2 paths/services**

`<TARGET_HOST_1>`/`<TARGET_PATH_1>` > `<TARGET_SERVICE_A>`
`<TARGET_HOST_1>`/`<TARGET_PATH_2>` >  `<TARGET_SERVICE_B>`

```
hostname1/path1 > targetservicea
hostname1/path2 > targetserviceb
```

**Example: 2 Rules -  Rule1: 1 hostname & 2 paths/services, Rule 2: 1 hostname and 1 path**


`<TARGET_HOST_1>`/`<TARGET_PATH_1>` > `<TARGET_SERVICE_A>`
`<TARGET_HOST_1>`/`<TARGET_PATH_2>` > `<TARGET_SERVICE_B>`
`<TARGET_HOST_2>`/`<TARGET_PATH_3>` > `<TARGET_SERVICE_C>`

```
hostname1/path1 > targetservicea
hostname1/path2 > targetserviceb
hostname2/path3 > targetservicec
```

**Comment by deniseschannon** [comment]
- [ ] Clone as Form doesn't work

# Edit Page

## Rules Section

**Text Changes**
- [ ] Update `Target` to `Target Service` in the `path` section. 
- [ ] Update example text in `port` to be `e.g. 80 or http`. It can be a port number or name.  

**Other Changes**
- [ ] Since you can add multiple paths, can we change the field names to be using headers in columns instead of the field name in each textbox? 
<img width="1036" alt="Screen Shot 2020-05-18 at 10 33 16 AM" src="https://user-images.githubusercontent.com/11410997/82242686-20069a80-98f3-11ea-98dc-7d8d72c9b96a.png">

- [ ] When I add a `Path`, it seems like it's added above and the page moves up which is weird. Can the page move down?

- [ ] For the `Target Service` dropdown in the `path` section, you should be able to type in your own service name even if it doesn't exist. So it should be a dropdown that allows free form text to be used or pick one of the services. If you use free form text to type in a non-existent service, can we warn the user that this is not a service that is selected. @lvuch to help with design on this one. 

- [ ] For the `Target Service` dropdown in the `path` section, if you select a service, change the textbox for `port` to a dropdown of the port options that are in that particular service under `spec.ports.port` associated with the selected service.

## Certificates Tab

> Note: You could use a certificate but not specify `hosts` so if no hosts are added, don't add it as part of the spec. 

- [ ] Only show `Add Certificate` button when we first go to the page. There doesn't need to be a certificate, so this is purely optional. It shouldn't try to make one if no certificates are chosen.

- [ ] The radio buttons are still weird, so let's move to a single certificate dropdown with an option `Default Ingress Controller Certificate`. 

- [ ] Update from `Certificate` field name to `Certificate - Secret Name`

## Default Backend Tab
- [ ] Update example text in `port` to be `e.g. 80 or http`. It can be a port number or name.  

- [ ] For the `Target Service` dropdown, if you select a service, change the textbox for `port` to a dropdown of the port options that are in that particular service under `spec.ports.port` associated with the selected service.

# Detail Page

## Rules Section
- [ ] Update `Target` to `Target Service` in Column Header

**Comment by codyrancher** [comment]
@lvuch Denise added this requirement 
>For the Target Service dropdown in the path section, you should be able to type in your own service name even if it doesn't exist. So it should be a dropdown that allows free form text to be used or pick one of the services. If you use free form text to type in a non-existent service, can we warn the user that this is not a service that is selected. @lvuch to help with design on this one.

Do you have any thoughts for the warning?

**Comment by codyrancher** [comment]
@deniseschannon 
> Since I can add multiple hosts, can we make Host a header outside of the textboxes instead of a label on each input?

I don't think that will look all that great with the new design
![image](https://user-images.githubusercontent.com/55104481/83460588-9c34ce00-a41b-11ea-982b-830770b66346.png)

I think we should leave the labels as is but if you insist on moving it I think we should move "Certificate - Secret name" to be a header as well.

**Comment by vincent99** [comment]
The target of an Ingress is a Service.  Workloads are not a "real" thing, in norman/ember when you create a workload it creates both the Deployment (or other type) and a corresponding Service of the same name.

**Comment by codyrancher** [comment]
@vincent99 has this "worked" thus far because the corresponding service has the same name as the "workload"? If they share the same name should I really just load all the services as the options instead of the workloads?

**Comment by vincent99** [comment]
Yes, none of this magic exists when you create a "workload" in steve/vue.

The dropdown should be showing a list of service names which are in the same namespace as the ingress being created/edited.  (+ `taggable`;  being able to type in the name of a service that doesn't exist yet is valid and occasionally useful)

**Comment by vincent99** [comment]
No, that is done by Rancher controllers that won't necessarily be present.

(We could do something similar to how the on-rio domains work as an optional feature...)

**Comment by deniseschannon** [comment]
New Additions

## Default Backend Tab
- [ ] Convert warning into banner style (See https://github.com/rancher/dashboard/issues/634 for look and feel and example in the service pages)


# Edit Page

- [ ] For the Target Service dropdown in the default backend tab, you should be able to type in your own service name even if it doesn't exist. So it should be a dropdown that allows free form text to be used or pick one of the services. If you use free form text to type in a non-existent service, can we warn the user that this is not a service that is selected. 

- [ ] For Target Service in either the paths section of rules or in the default backend section, if the user types in a target service that doesn't exist, can we highlight the box as a warning that this service doesn't exist? Maybe with a yellow border? 

- [ ] The `Port` dropdown in default backend tab is missing the header for `Port`

# Detail Page

- [ ] In the default backend tab, update the text from `No default backend is configured.` to `There is no default backend configured.`. This keeps it more consistent with other text that is being added in other detail pages to start with `There is no blah configured`. 


# Clone Issue
- [ ] When cloning an ingress from form, if i remove the certificate, when I create the ingress, the certificate is still added. It doesn't seem we are clearing the data inputted into the form when we remove it from the view.

**Comment by aaronRancher** [comment]
Issues found testing on `master-head b6a3dc962`:
#756 
#753
#757
#758

**Comment by aaronRancher** [comment]
Validated additional updates to ingress page (https://github.com/rancher/dashboard/pull/816) with Rancher server `rancher\rancher:master-head` `version d5e1b21b`

User can now search for target service:
![Screen Shot 2020-08-27 at 4 30 00 PM](https://user-images.githubusercontent.com/57409052/91504823-1215cd80-e883-11ea-9ade-e7e7987f4a07.png)
User must hit `enter` to search for service. If field is clicked away while typing, field will return to previous entered value.  
If service does not exist, user will be given a warning:
![Screen Shot 2020-08-27 at 4 32 15 PM](https://user-images.githubusercontent.com/57409052/91504819-104c0a00-e883-11ea-99c2-687c9a718520.png)
