### ISSUE TITLE
AKS Provisioning (iFrame)

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2738]
Need to use the new `aks-v2` ID

**Comment by sowmyav27** [comment]
To validate:
User should be able to provision and edit, add nodepools and save a
- AKS v2 hosted cluster
- AKSv2 - Register cluster or import clusters

**Comment by thehejik** [comment]
**Test report:**
Tested on `rancher/rancher:master-head cf5a75f`

* Hosted AKS was succesfully provisioned and updated over Rancher - resources ok
  - I was unable to test adding nodepools and scaling pools due reached quota in Azure `The maximum node count you can select is 1 due to the remaining quota in the selected subscription (0 cores).`

* Imported AKS was succesfully imported into Rancher (selected from dropdown) but the update failed - resources were ok
  - https://github.com/rancher/rancher/issues/33534 
  - https://github.com/rancher/rancher/issues/33536

As the bugs are open I'm closing this one.
