### ISSUE TITLE
Enhancement needed for node IPs of cluster to be visible in cluster management

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2957]
On master-8c014efa85314ab1cb1cb79261d2db9251ccf31d-head

1. Create a cluster with 1 node, all roles.
2. Once the cluster is active, nodes can be viewed/accessed from EXPLORE CLUSTER --> select the cluster --> cluster dropdown nodes.

Can we have an enhancement for the nodes' IPs to be displayed from the cluster management --> cluster page for easier access?

**Comment by vincent99** [comment]
This is not present in the API.

**Comment by jiaqiluo** [comment]
Hi UI team,
could you look at [this comment ](https://github.com/rancher/rancher/issues/32759#issuecomment-1015772532)to see if it is doable for UI?

**Comment by gaktive** [comment]
@Shavindra was this fixed as part of your recent work tied to adding node IPs to the table?

**Comment by sowmyav27** [comment]
**on latest 2.6head - commit id: `2c21373`**

The node IPs are available in CLuster Management --> Cluster details page, like stated in the original Issue's description. (i agree the title of the issue is slightly misleading)

Since it's already available in Cluster details page, can we _not_ have those in CLuster Management page also. 

**Reasons:**
- If a cluster has a lot of Nodes, the page is going to look a bit messy
- It's redundant data, since the Node IPs are available in cluster detail's page.
<img width="1141" alt="Screen Shot 2022-07-14 at 8 18 16 AM" src="https://user-images.githubusercontent.com/26032343/179042910-6f8789b8-6554-452d-8608-3e997469115b.png">
