### ISSUE TITLE
[Monitoring V2 UI] Add link to docs when Monitoring V1 is detected

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#2967]
Need to add a link to Rancher docs at https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/migrating/#migrating-from-monitoring-v1-to-monitoring-v2 whenever we show that Monitoring V1 is deployed.

e.g.

https://github.com/rancher/dashboard/blob/6fa3c247a3e7450f2d8dbc2623503b5c9967642a/assets/translations/en-us.yaml#L1647

https://github.com/rancher/dashboard/blob/6fa3c247a3e7450f2d8dbc2623503b5c9967642a/assets/translations/en-us.yaml#L1711

**Comment by nwmac** [comment]
This is now shown on the install page for monitoring and also in the card on Cluster Tools, when v1 tools are already installed.

**Comment by slickwarren** [comment]
tested on master-head (d44698d):
**prerequisite:** monitoring v1 is installed

* user tries to install `monitoring v2 -> apps & marketplace -> monitoring`, or via `apps & marketplace -> installed apps -> upgradable button for monitoring v1` install or via `apps & marketplace -> installed apps -> edit monitoring v1`
  * user is shown screen below to uninstall monitoring
  * docs link works
![Screen Shot 2021-06-23 at 2 51 21 PM](https://user-images.githubusercontent.com/16691014/123172947-baa8a580-d432-11eb-9d5f-2b6ae70a6b57.png)
### * **Blocking on the following:** 
* clicking `uninstall` from the previous case should give a warning to the user before actually installing (similar to what happens if a user tries to delete a node through rancher UI) i.e. screenshot below. currently, monitoring v1 immediately begins to uninstall
![Screen Shot 2021-06-23 at 3 14 13 PM](https://user-images.githubusercontent.com/16691014/123174886-b5008f00-d435-11eb-8724-e577914b0647.png)

* after uninstall, previous button does nothing (should hide from user, or make it go back to the chart readme page)

![Screen Shot 2021-06-23 at 2 52 08 PM](https://user-images.githubusercontent.com/16691014/123172941-b8dee200-d432-11eb-9c30-bc6b74949a4a.png)

### need clarification on:
` and also in the card on Cluster Tools, when v1 tools are already installed.` is this through vue? if so, could you help me find where `cluster tools` are?

**Comment by nwmac** [comment]
@richard-cox Can you take a look

**Comment by richard-cox** [comment]
#3365 covers first two blocking issues. @slickwarren `Cluster Tools` are reachable via the button at the bottom of the resource menu at the side when viewing a cluster
![image](https://user-images.githubusercontent.com/18697775/123985605-821e4400-d9bd-11eb-9032-9a3b9f2ec948.png)

**Comment by slickwarren** [comment]
on master-head (d3ad5d3):
* when monitoring v1 is installed and user tries to install v2, docs show up properly
  * `previous` button was removed after uninstalling v1 via v2 install 
  * a warning window appears to delay uninstall of v1 to ensure docs have been followed by user
