### ISSUE TITLE
Related resources page does not load

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3010]
To reproduce:
 - Import rke2 cluster in dashboard
 - Open Cluster Management -> <Cluster Name> -> Related resources -> Refers to -> Name link

![Screenshot from 2021-05-28 10-46-04](https://user-images.githubusercontent.com/538604/119956979-f3736d00-bfa1-11eb-8008-9eadcc775aab.png)

Result: Redirects to page that's either stack on `Loading...` or blank

Error in developer console:
```
app.803519b80434c8d3523d.js:2 GET https://crancher.hopto.org/k8s/clusters/c-m-3c4d0096/v1/management.cattle.io.clusters/c-m-3c4d0096 404 (Not Found)

TypeError: Cannot read property 'doneOverride' of null
    at f.r (index.vue?6fea:1)
    at f.t._render (app.803519b80434c8d3523d.js:2)
    at f.r (app.803519b80434c8d3523d.js:2)
    at _n.get (app.803519b80434c8d3523d.js:2)
    at _n.run (app.803519b80434c8d3523d.js:2)
    at gn (app.803519b80434c8d3523d.js:2)
    at Array.<anonymous> (app.803519b80434c8d3523d.js:2)
    at ie (app.803519b80434c8d3523d.js:2)
```

Tested on master-head (5d2b7ac)

**Comment by gaktive** [comment]
@kravciak can you confirm on this cluster that other apps are in a similar position? This doesn't sound possible but I'm curious if there's something else happening here.

**Comment by kravciak** [comment]
I tried related resources from Nodes, Deployments, Workloads, Pods, .... and they all work fine, only resources from cluster view are broken. I added more information to the issue description.

**Comment by vincent99** [comment]
This was because when you switch to Cluster Manager, we remember what cluster you were previously connected to and keep that connected (so that whole state is preserved if you end up going back to that cluster.. you can see the URL still has c-xxxxx in it instead of switching to say 'local').

But the links for related resources were going to that cluster, when the resources being shown are for the management cluster (local).  So you're looking in a downstream cluster for a mgmt cluster resource that doesn't exist.

Changed related resources to generate links to the right/local cluster, which will switch to the local cluster if you follow them.

**Comment by kravciak** [comment]
Works fine on master-head (d44698d)
