### ISSUE TITLE
ui-pl issues

### ISSUE THREAD

**Issue by cloudnautique** [rancher/dashboard#3029]
Found a couple of issues with the branding updates:

There needs to be a way to remove/not show the "get support" link from the nav menu. 
The commercial support link on the home page should not be shown.
Community support links on the homepage should also be optionally hidden from a setting on the branding page. We should allow only showing the user-defined support link.

A possible solution would be to place the support links on the branding page.

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (06/25/2021)` _c7f3cce_

❌  - Needs Fix
ℹ️  - Needs information
✅  - Working as expected

- The `Get Support` link is visible in the Nav Bar with or without a Subscription ID. ❌ 
- The Community Support Box in the Dashboard Home is visible always even if we uncheck the `Show Rancher community support links` in Branding (See screenshot). ❌ 

<img width="1175" alt="Screen Shot 2021-06-25 at 12 36 44 PM" src="https://user-images.githubusercontent.com/27659/123477426-e6eb3000-d5b2-11eb-8fe3-7bb2d0ddbdf1.png">

- Should we force hiding that Support Box if a Subscription ID exists and it was never removed from home? ℹ️  
- With `Show Rancher community support links` checked I only see the File an Issue link in `/dashboard/support` ✅

**Comment by mantis-toboggan-md** [comment]
There is [a PR](https://github.com/rancher/dashboard/pull/3425) up for this now, copying over an explanation of expected behavior:

This pr addresses remaining issues in #3029 with the exception of the 'Get Support' link visibility; there are conflicting requirements in https://github.com/rancher/dashboard/issues/2895. As per discussion with @nwmac this PR hides the support link for non-admins regardless of subscription status, and changes the label from 'Get Support' to 'Support' when a subscription key has been added. We've opted not to hide the link entirely in supported mode because the page still has utility. Other issues from #3029 :

> The Community Support Box in the Dashboard Home is visible always even if we uncheck the Show Rancher community support links in Branding (See screenshot)

This should work correctly now, *but* if a custom issue-reporting url has been provided, it will be shown in the box regardless of whether `show rancher community support links` is checked or not.

>Should we force hiding that Support Box if a Subscription ID exists and it was never removed from home? ℹ️

We've opted not to hide the Community Support box when a subscription id is present because those resources are still helpful; eg a user may choose to read docs or peruse open issues before contacting support.

**Comment by izaac** [comment]
Rancher version: `v2.6 master-head (07/19/2021)` _d3ad5d3_

Validated the remaining issues fixed and described [here](https://github.com/rancher/dashboard/issues/3029#issuecomment-876489931).
I am missing the standard user validation due to issues accessing the dashboard. Probably related to RBAC WIP https://github.com/rancher/rancher/issues/32414

**Comment by izaac** [comment]
Rancher version: `v2.6 master-head (07/20/2021)` _cfbd0d3_

Validated the Standard user requirement of hiding the support link for non-admins. 
Standard User has no Support Links available.
