### ISSUE TITLE
V2 cluster cloud credentials API key shouldn't be in clear text

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3043]
master-head commit d8acb21
1. From cluster management --> cloud credentials --> create a cloud credential --> Once created on the UI, API key is in clear text - should be masked or not displayed
2. When cloning a cloud credential, Provider name is missing in the cloned cloud credential
3. Once the cloud credential is cloned and if we edit the config --> API key is missing in the config but can be seen from the edit as yaml 
4. If we click on edit as yaml on an existing cloud credential and click cancel --> users are redirected to the screen with secrets from all namespaces :

https://user-images.githubusercontent.com/38144301/118923780-f3fc6b80-b8f0-11eb-81d8-d6f68bce5652.mov

**Comment by gaktive** [comment]
For reference: the video only covers Item 1 since this seems to be multiple tickets in one (in the future, please split these out).
Item 1: Seems OK now
Item 2 & 3: confirmed that clone is broken
Item 4: To be looked at

**Comment by vincent99** [comment]
1) Viewing a cloud cred is the same as the regular secret view; there's a toggle to decide if the plaintext is shown or not at the top.

2/3: Fixed cloning cloud creds.

4: Fixed

**Comment by anupama2501** [comment]
Verified on master-head e756276

Created a cloud credential for digital ocean from cluster management --> cloud credentials

- Issue2:

Verified that upon cloning the cloud credential, the provider name is displayed.

- Issue3:

Verified upon editing the cloned cloud credential, the API key is not missing from edit config as well as yaml.

- Issue4:

Verified clicking cancel on edit as yaml page, os redirected to the cloud crendentials page.

**Comment by anupama2501** [comment]
@vincent99 the API key is masked only when we click on the credential but the first few characters are still in plain text. Can that be masked as well?


For the toggling, on ember UI, secrets are masked and we do not have the option to show them in plain text but on explorer we have an option to show it as a plain text. Wanted to know if this change is OK as some sensitive information might be revealed with the toggling?

**Comment by vincent99** [comment]
The portion shown in the table is intentional so you have some idea what key you're looking at.  Each provider implementation can make a different decision to show a whole field (e.g. AWS has an Access Key that's all not-secret), a prefix (DO only has one field so we do this), or a suffix (in some providers the prefix might always be a fixed string, e.g. AWS always starts with `AKIA` so that wouldn't be useful to show).

Ember _does_ let you see the plaintext, but it's undiscoverable (you click on the •••••'s).  The explicit toggle to show/hide is intentional (and has been there since I think 2.5.0), we're not blindly copying what Ember did for the sake of copying.

**Comment by anupama2501** [comment]
Verified issue1 on master-head e756276:

From cluster management --> cloud credentials --> create a cloud credential --> Once created on the UI, some part of API key is visible for the users to chose among multiple same provider keys.
