### ISSUE TITLE
Issues when Theme is set to Auto

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3088]
**On master-head commit id: `f90b36e `**

By default the Theme is set to Auto on rancher login

**Issue 1**

- Navigate to RKE1 cloud credentials page in Dashboard
- The page is seen in dark mode.
<img width="1670" alt="Screen Shot 2021-05-25 at 12 30 55 PM" src="https://user-images.githubusercontent.com/26032343/119557744-6d62e680-bd55-11eb-822e-087d505094c7.png">

**Issue 2**

- Navigate to Dashboard --> Preferences
- By default the Theme is set to Auto on rancher login
- Rancher Text on top left is not visible. 

<img width="674" alt="Screen Shot 2021-05-25 at 12 31 26 PM" src="https://user-images.githubusercontent.com/26032343/119557984-b87cf980-bd55-11eb-9880-9217bb8db9c3.png">

**Comment by sowmyav27** [comment]
**On master-head commit id: `5715b8a ` This issue is seen in this page now**

- From Ember UI navigate to Explorer of a downstream cluster
- Click on `Legacy` from the left panel
<img width="1141" alt="Screen Shot 2021-06-13 at 5 12 52 PM" src="https://user-images.githubusercontent.com/26032343/121826085-cc3bc180-cc6a-11eb-9ea6-1dc5b1a5e56e.png">

Issue 1 and Issue 2 are seen fixed.
Reopening the same issue.
@mantis-toboggan-md Please let me know if this is a different issu.

**Comment by westlywright** [comment]
@sowmyav27 can you retest? I was investigating and am seeing the correct themes applied on the alerts page. Side note, Lauren is working on a PR to make the dark and light colors match close to the Dashboard colors so that should be resolved soon. 


![Screen Shot 2021-06-18 at 12 19 53 PM](https://user-images.githubusercontent.com/858614/122607564-a11ced80-d02f-11eb-850f-f8858e58ee17.png)
![Screen Shot 2021-06-18 at 12 20 09 PM](https://user-images.githubusercontent.com/858614/122607569-a37f4780-d02f-11eb-9074-51399c4569fb.png)

**Comment by sowmyav27** [comment]
**On master-head commit id: `a11f947 `** 

- Upgrade from 2.5.8 to master
- Legacy --> Alerts page still has the theme color issue

<img width="1290" alt="Screen Shot 2021-06-19 at 7 39 35 PM" src="https://user-images.githubusercontent.com/26032343/122660412-31ddf100-d136-11eb-9730-f5324cb8051a.png">

**Comment by sowmyav27** [comment]
**On master-head commit :`e546ffe`**


I see this issue fixed.
<img width="1304" alt="Screen Shot 2021-07-01 at 10 43 32 AM" src="https://user-images.githubusercontent.com/26032343/124167843-328d5600-da59-11eb-8c3e-668f06f3210b.png">
