### ISSUE TITLE
Dashboard use high CPU when open some page

### ISSUE THREAD

**Issue by sida-khalibre** [rancher/dashboard#3203]
When using Dashboard and go through some pages such as Ingress, browser using high CPU and sometimes get hangout. I tested on both Chrome and Firefox. 

![image](https://user-images.githubusercontent.com/9067408/121466031-e7939c00-c9e0-11eb-9ec3-31e313a72f09.png)

**Comment by vincent99** [comment]
https://github.com/rancher/dashboard/pull/4264

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Environment:**

Rancher version: v2.6.0
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2
Downstream K8s version: v1.21.4+rke2r2
 
**Reproduction steps:**

1. I was able to reproduce. I'm on Linux but the situation should be quite similar and indeed appears to be:
![image](https://user-images.githubusercontent.com/45179589/135125973-0550a17b-afd5-41c4-869d-e7cb46aca93b.png)

However, I will mention that I saw similar spikes just browsing any webpage just about anywhere. A google search results in about 100% CPU utilization (per 1 cpu thread) for a few moments, worse than browsing most dashboard pages. If I recall correctly, in the Windows task manager, on the Processes tab, it will sum up all threads for a process so seeing 30.5% in the task manager actually looks really good, that's for the whole process and all threads I believe. Now if it's sustained there (not doing anything in the browser and none of the tabs are super resource intensive) that's another thing. 

So, we should be mindful that I'm just testing for this periodic peak of cpu utilization during page loading. I do not see any significant sustained CPU utilization. Sustained (~idle) CPU utilization for firefox for me is quite low maybe 10% or less with dozens of tabs open. When I test I'll see if this peak is decreased.

 
-----
 
**Validation Environment:**

Rancher version: v2.6-head `4df101e` 9/28/21
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2
Downstream K8s version: v1.21.5+rke2r1
 
**Validation steps:**

1. Run the same steps as in the Reproduction steps above.
2. I don't really notice much of a difference in my case - my cpu utilization is approximately the same perhaps slightly lower. I think most of the cpu cycles are spent rendering the page and doing stuff in the DOM. I noticed no decrease in performance, and perhaps a slight increase. I wasn't sure a better way to measure this. Page load times are nearly the same and CPU utilization is perhaps slightly less. I did notice we don't seem to use as much CPU for quite so long, in fact it made it harder to capture a screenshot in time. I'm going to call this a win.
![image](https://user-images.githubusercontent.com/45179589/135171641-27bb5b19-3d12-4645-9dfe-674b98abb6f1.png)

My sustained (idle) CPU utilization with firefox might be slightly lower. It was around 10% before it's now around 4 or 5%. This could be due to other factors such as any browser tabs I might have closed before.
