### ISSUE TITLE
Charts in Cluster tools view doesn't let users select version of the chart

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3217]
**On master-head commit id: `5715b8a`**

- On a downstream cluster, go to cluster explorer.
- From the left menu, select Cluster Tools from bottom
- CIS Benchmark `v 100.0.0` is only available to install
- User does not have the option to install another version of the chart that is seen under Apps & Marketplace --> Charts

**Expected:**
User should be presented with all available chart versions

**Comment by thehejik** [comment]
This is fixed in `rancher/rancher:master-head 3dae3e2` dev-v2.6 repo `commit: ed3d4f771f80b9790b335123c1f0e7d08b6e8c57`

Screenshot when using `Cluster Tools`, the version selector looks a bit differently when installing from `Apps & Marketplace`.
![cluster_tools_versions](https://user-images.githubusercontent.com/12828077/122415411-31075c80-cf88-11eb-990e-34cd740ff072.png)

I was able to install  CIS 1.0.301 version of the chart. Also other charts like monitoring behaves correctly.

Close.
