### ISSUE TITLE
Keycloak OIDC - when a user that's not explicitly authorized and tries to login the login just stays in a blank page

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#3234]
Rancher version `2.6 master-head (06/14/2021)` _9d54b1a_

When we use the option `Restrict access to only the authorized users & groups`  and then I try login in with a restricted user (a user not in this list) and we click _login_ the Keycloak Login page the user is taken to a blank page in the dashboard.

The API returns: 

`{"type":"error","status":"401","message":"Unauthorized 401: must authenticate"}`

The Browser stays in this URL: `/dashboard/auth/verify?state=<REDACTED>`

Related epic: https://github.com/rancher/rancher/issues/30280

**Comment by richard-cox** [comment]
I've fixed the root cause of the error, however I think there's a secondary issue. Once the user has logged in to keycloak a keycloak session cookie is created linked to that user. We then determine that the user cannot access rancher and show an error message. The problem occurs when the user then wishes to try a different user. The cookie from the previous attempt still exists so keycloak doesn't prompt for user creds again, so they're stuck until the session times out or they manually remove the keycloak cookie

**Comment by izaac** [comment]
Rancher version: `2.6 master-head (06/22/2021)` _4d18400_

Original issue reported is fixed, the user is not allowed to login, and it gets redirected to the login page with an error message now.

Secondary session issue is tracked in the `rancher/rancher` issues.
https://github.com/rancher/rancher/issues/32920#issuecomment-861837448
