### ISSUE TITLE
Different Text in Header or Footer for Fixed Banners 

### ISSUE THREAD

**Issue by bdekany** [rancher/dashboard#3241]
Hi,

We should be allowed to set a different text for header and footer in Fixed Banner.

The current behavior is that the same text is shown at top and bottom of the page.

`Global Settings > Branding > Fixed Banners`
Have two different text box

Regards

**Comment by gaktive** [comment]
This was doable in Ember (Cluster Explorer) before. @vincent99 said something about an array?

**Comment by thehejik** [comment]
**Test report:**
* Texts and colours of Banners for Header and Footer can be set now in Dashboard on `rancher/rancher:master-head e546ffe`
![banner](https://user-images.githubusercontent.com/12828077/123991906-6883f900-d9cb-11eb-9e72-5911bfe3fb08.png)
* The migration from legacy/Ember to Dashboard with following JSON works - the Footer and Header are just using the same values (text, colours) then but it can be changed afterwards in Dashboard Branding Configuration pane:
```json
{
  "banner": {
    "background": "yellow",
    "color": "black",
    "text": "My Custom Banner"
  },
  "showHeader": "true",
  "showFooter": "true"
}
```
* Migration in the other direction doesn't work - for eg. if I (re)Apply the values in Dashboard (originaly entered in Ember) and go back to Ember the banners are not shown anymore because the resulting JSON changed to JSON non-compatible with Ember like:
 ```json
{
  "bannerHeader": {
    "background": "yellow",
    "color": "black",
    "text": "My Custom Banner"
  },
  "bannerFooter": {
    "background": "yellow",
    "color": "black",
    "text": "My Custom Banner"
  },
  "showHeader": "true",
  "showFooter": "true"
}
```

@westlywright please is it the migration from Dashboard back to Ember supported? If not I would just close it as user still can easily rewrite the JSON in Ember.

**Comment by westlywright** [comment]
I dont think there is any need to make the api backwards compatible since we're preventing users from going back in the future.

**Comment by thehejik** [comment]
Ok, thanks, closing.
