### ISSUE TITLE
Docs link should point to versioned docs for Rancher v2.6

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#3279]
I was looking at the Rancher UI in the docker install and saw that the docs link on this page points to https://rancher.com/docs/rancher/v2.x/en/.

![Screen Shot 2021-06-16 at 6 02 02 PM](https://user-images.githubusercontent.com/20599230/122314612-54b99c80-cecd-11eb-98cf-d1bf5cb7870d.png)

I just want to make sure the link will be https://rancher.com/docs/rancher/v2.6/en/.

**Comment by vincent99** [comment]
There are several other `2.x` 's sprinkled around (and in translations) also; these should all be updated to read from a common constant so they can be updated all at once easily.

**Comment by nwmac** [comment]
Note there is a prop 'docsBase' that is available when localising strings - its set to https://rancher.com/docs/rancher/v2.6/en currently.

The string for the docs link is in config/footer.js - it should be moved to a i18n string and use docsBase. The options method in footer will need to have t passed into it in order to be able to access the i18n strings

**Comment by catherineluse** [comment]
The docsBase variable could introduce errors if the page is relocated in a different docs version. We could potentially add redirects, but that would mean that the docs team would have to remember that if they move a page, they need to maintain a redirect for the old location of the page for all future docs versions of that page.

For the main landing page, docsBase can be used because we know the equivalent of https://rancher.com/docs/rancher/v2.6/en will be there going forward.

But for something like the instructions for how to migrate from V1 monitoring to v2 monitoring, I doubt docsBase should be used because that page isn't guaranteed to be in docs for Rancher v2.7.

**Comment by vincent99** [comment]
I added the docsBase a few weeks after this issue was created because every single link was independently hardcoded to 2.x and going to be wrong, but this one in config/footer was missed.  The vast majority of links to docs should go to whatever the corresponding docs version is (`2.6` for now) so they should use `docsBase` so they can all be changed in one place when needed.

If there's a good reason to point a particular one to a different version that can be special cased...  But in your example: if v1 to v2 migration is still a concern in 2.7 (for us to link to it in the UI) then I would say it _should_ have a page in the 2.7 docs, not that the UI should point that particular link to 2.6 docs.

**Comment by catherineluse** [comment]
Some links go to sections partway down the page, so they won't work right when the section title changes. Since the docs always change, I think the only way to keep the links from breaking would be to either do an automated scan for 202s and 404s before major releases or have the docs team review the links.

**Comment by ronhorton** [comment]
pass - docs links to https://rancher.com/docs/rancher/v2.6/en in v2.6-1a5785604ed0b65e12c23d3739627d42b23ac1a0-head
