### ISSUE TITLE
Port/iFrame from Ember: Istio v1

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#3297]
Istio v1 was initially noted as Leave from Ember but in light of recent changes, we'll need to incorporate that functionality into Dashboard

Ember location: <cluster> → Tools → Istio	Leave	
Vue location: ||| → <cluster> → Cluster Tools / V1 → Istio (Legacy)

**Comment by nwmac** [comment]
Legacy Istio can be enabled/disabled via Cluster Tools in the same way v1 Monitoring can be.
 
The istio functionality is available within the 'Legacy' Side nav for a cluster.

Select a cluster -> Legacy -> Project -> (select project) -> Istio

**Comment by kravciak** [comment]
Legacy monitoring can be enabled from cluster -> Legacy -> Project -> (select project) -> Monitoring -> Enable

It would be cleaner to have the same iFrame for Istio - in cluster -> Legacy -> Project -> (select project) -> Istio -> Enable

Currently there is only link to Cluster tools page. I am reopening, but since it's working fine otherwise feel free to close it.

![Screenshot from 2021-07-02 12-54-55](https://user-images.githubusercontent.com/538604/124268752-36dd7000-db3a-11eb-8470-8212bc148daa.png)

Tested on: master-head (c1151f6)

**Comment by nwmac** [comment]
Thanks for the feedback @Martin-Weiss - I'm going to leave as is for now.
