### ISSUE TITLE
Port/iFrame from Ember: Pipeline

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#3300]
In light of recent UI consolidation, we need to ensure that pages from Ember aren't lost when accessing them via Vue.

Ember location: <cluster> → <project> → Tools → Pipeline
Vue location: Use Cluster Manager

**Comment by nwmac** [comment]
The legacy pipelines functionality is available within the 'Legacy' Side nav for a cluster.

Select a cluster -> Legacy -> Project -> (select project) -> Pipelines

This page has two tabs - one to view pipelines and one to configure them

**Comment by kravciak** [comment]
When I select Project/Namespace then I am redirected to Apps but `left menu collapses`.
I have to navigate again Cluster -> Legacy -> Project -> Pipelines to display them.

This makes it quite cumbersome to access pipelines. Reopening.

**Comment by kravciak** [comment]
The issue with navigation is not fixed in master-head (e83ac8c), but it seems unrelated to pipelines.
I will open separate issue for left menu navigation, closing this one.

Verified by:
 - enabled example repository https://github.com/rancher/pipeline-example-go.git
 - run rancher/pipeline-example-go pipeline (passed fine)
 - enabled github repository authentication
 - in repository configuration I can see custom repositories from github ^
 -
