### ISSUE TITLE
RKE2 Template provisioning issues -- unable to provision cluster for ec2, vsphere, custom clusters

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3304]
master-head(4d18400) 
**Note:** some of these might not be strictly UI issues. If that is the case, please let me know and I can create a separate issue for them. parent issue: https://github.com/rancher/dashboard/issues/2972

Issue: unable to provision clusters using the following providers with RKE2 templates:
amazonEC2, vsphere, azure, custom

**AmazonEC2**:
* add a valid RKE2 template
* (you can create a secret for your selected provider by going to cluster management -> create -> ec2 and saving the secret. not necessary to create a cluster after creating the secret)
* go to create a cluster with said template, and enter valid ec2 settings
* chart install will fail with the following error:
* `Error: YAML parse error on qa-registry-template/templates/nodeconfig-aws.yaml: error converting YAML to JSON: yaml: line 24: could not find expected ':'`
* was unable to find a workaround for this issue

**Vsphere**: 
* add a valid RKE2 template
* (you can create a secret for your selected provider by going to cluster management -> create -> vsphere and saving the secret. not necessary to create a cluster after creating the secret)
* go to create a cluster with said template, and enter valid vsphere settings
* chart install will fail with the following error:
* `failed to create resource: VmwarevsphereConfig.rke-machine-config.cattle.io "test" is invalid: [memorySize: Invalid value: "integer": memorySize in body must be of type string: "integer", sshPort: Invalid value: "integer": sshPort in body must be of type string: "integer", diskSize: Invalid value: "integer": diskSize in body must be of type string: "integer", network: Invalid value: "string": network in body must be of type array: "string"]`
* was able to work around this issue by updating the `type` in questions.yaml to `string` where necessary, in combination with updating values through rancher to force them to be strings... i.e. `memorySize=4096Mib`.  It seems that the UI is interpreting `2048` as type `"Integer"` instead of as a string.

**Custom**: 
* add a valid RKE2 template
* go to create a cluster with said template, and enter valid custom settings
* chart install succeeds 
* cluster provisioning fails with the following error:
* `Invalid machinePool [<name_entered_for_nodepool>] missing name or valid config` 
  * nodepool name is required when using an RKE2 template, but I don't think this is a field for custom clusters. 
  * removing the `nodepool` section from the yaml when creating via RKE2 template appears to be a valid workaround for this issue
![Screen Shot 2021-06-21 at 2 36 47 PM](https://user-images.githubusercontent.com/16691014/122831028-20aff400-d29e-11eb-8003-0f423c7db220.png)

**Azure**: 
* add a valid RKE2 template
* create a valid secret for azure (you can create a secret for your selected provider by going to cluster management -> create -> azure and saving the secret. not necessary to create a cluster after creating the secret)
* go to create a cluster with said template, and enter valid settings -- **There are no unique questions for azure**
* chart install succeeds 
* cluster stays in `pending` state on stage `Creating server (AzureMachine) in infrastructure provider`  It appears that the request is missing some required values, such as Azure Location, resource group, etc.

![Screen Shot 2021-06-21 at 2 36 04 PM](https://user-images.githubusercontent.com/16691014/122830973-07a74300-d29e-11eb-8a9a-96fe3af97807.png)
 
compared to an azure cluster provisioned without a template: 
![Screen Shot 2021-06-21 at 3 10 13 PM](https://user-images.githubusercontent.com/16691014/122834101-d9783200-d2a2-11eb-87a3-a7c35b3c4822.png)

**Comment by vincent99** [comment]
Yes these are all basically things wrong with the chart..  The UI is deploying it exactly the same as any other, and you know it's possible to create the underlying resources since the UI does and probably your own automation.

Amazon: This is a straight up syntax error in the YAML that gets generated after templating is processed

vSphere: All the values on a machine config need to be strings because that's how they're declared in all docker-machine drivers.   So anything like that asking for an integer is a mistake.

Custom: There shouldn't be any pools for custom

Azure: Sounds like it's not asking for all the fields that are actually required?

**Comment by slickwarren** [comment]
@vincent99 ok thank you for confirming.  I'll go through the charts and update each of these

**Comment by vincent99** [comment]
If you're updating the charts I'm adding support for question `type: secret` (or `configmap`, `pvc`, or `storageclass`) which will offer a choice of `<that-type>` s defined in the namespace, so that should work reasonably well for cloud credential.   Those 4 types were defined in older 2.x docs, but we can now do it generically so it actually supports `type: reference[any-type-name]` for any type you want (where type-names are exactly as you'd see it in the URL bar when listing that type, e.g. `provisioning.cattle.io.cluster`).

**Comment by slickwarren** [comment]
tested on 2.6.0-rc1
- all node provisioners are working fine now after fixing syntax issues. Some smaller issues have been found, will file separately

**Comment by slickwarren** [comment]
https://github.com/rancher/dashboard/issues/3689
was unable to test vsphere, but all others were tested and working properly.
