### ISSUE TITLE
No API errors shown when attempting to create projects in a cluster.

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#3342]
Rancher master-head commit 4d18400

**Addressing 4 enhancement in this ticket**

1. Create an rke2 node driver 1 worker ,1cp, 1 etcd cluster from explorer.
2. Create standard users - user1, user2, user3, user4, user5
3. Create a project P1
4. Add user1 as project owner in P1, user2 as project member in P1 and user3 as read-only

#### Enhancement1: 
1. Login as user1 and create a project in the cluster 
2. Only the create button says 'Error' but no error message is displayed on the UI.
3. When project owners or project members create a project in the cluster, an error should be displayed to the users.
reference from ember UI:
```projects.management.cattle.io is forbidden: User "u-7g8s9" cannot create resource "projects" in API group "management.cattle.io" in the namespace "c-m-593a381b"```

**Comment by anupama2501** [comment]
Verified on master-head [`01665d0`](url)

1. Created two users u1, u2 and added to project P1 as project member and `read-only` permissions in a downstream clusetr.
2. Verified if logged in as u1/u2, no create option is given to the users.
3. Verified for `cluster Driver`, when tried to add a cluster driver, following error is displayed
`kontainerdrivers.management.cattle.io is forbidden: User "u-ltdcv" cannot create resource "kontainerdrivers" in API group "management.cattle.io" at the cluster scope`

**Comment by anupama2501** [comment]
Reopening this ticket:

For a user as a `project owner` permissions, `Create` project option is provided. If we click on create, button says `Error` but no message is displayed to the user.

`Expected Result`:

An error message should be displayed to the user, when the user has no permissions to create a project.


`Screenshot reference`
<img width="400" alt="Screen Shot 2021-07-27 at 4 25 29 PM" src="https://user-images.githubusercontent.com/38144301/127240131-57176ead-282d-47fa-9281-24c4d667862d.png">

**Comment by richard-cox** [comment]
I think the real issue is the button shouldn't show if the user cannot create a project (#3609). In whatever case though this is a good bug to fix

**Comment by igomez06** [comment]
Verified on v2.6-head - 4b6af95

**Steps taken to see the issue is fixed:**

* Created an RKE2 Digital Ocean cluser with 1 worker ,1cp, 1 etcd from explorer.
* Created standard users - user1, user2, user3, user4, user5
* Create a project P1
* Added user1 as project owner in P1, user2 as project member in P1 and user3 as read-only
* Logged in as user1 and attempted to create a project in the cluster
* Create Button says _**Error**_
* Error message is displayed: _**projects.management.cattle.io is forbidden: User "u-b95gj" cannot create resource "projects" in API group "management.cattle.io" in the namespace "c-m-0a31f210"**_
