### ISSUE TITLE
Dashboard UI have inconsistent option title and labels on buttons for node-label and node-taint for node driver

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/dashboard#3354]
On master-head commit id: 7a2fc74

Steps to reproduce:

- Cluster-management->Create->Amazon EC2->Show Advanced
- Node label has **Kubernetes Node Labels** and taints have **Taints** and label on the button has **Add label** for node-labels and **Add** for node-taints

Expected:
Consistent labels and taints

![image](https://user-images.githubusercontent.com/56045581/123756443-c4d30580-d871-11eb-84e5-41365568fee6.png)

**Comment by nwmac** [comment]
'Kubernetes Node Labels' is used to be clear that this is for the k8s nodes rather than the node it is provisionned on.

@neillsom Can you look at this for the 'Add' buttons - I think we should use 'Add Tag', 'Add Label' and 'Add Taint'

should just be some new translations and wiring them in - changes need to be made in MachinePool.vue

**Comment by sowmyav27** [comment]
**On master-head commit id: `f33188d`**
<img width="221" alt="Screen Shot 2021-07-19 at 9 30 43 PM" src="https://user-images.githubusercontent.com/26032343/126262250-0aee4338-e22c-4068-aec7-87539af55dce.png">
