### ISSUE TITLE
[V2 Provisioning] Registration tab not selected by default during cluster creation

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#3396]
When you create a custom RKE2 cluster, the registration tab is not selected by default, once you created the cluster. Instead the empty machine pool tab is shown.

![Bildschirmfoto 2021-06-30 um 12 01 32](https://user-images.githubusercontent.com/243056/124615369-7d520800-de75-11eb-8cca-3ea7d5ac85dd.png)

The registration tab should be selected to guide users through the next steps of creating a custom cluster.

**Comment by davidnuzik** [comment]
Validation Failed:
master-head `24ab082`

1. Create a custom rke2 cluster
![image](https://user-images.githubusercontent.com/45179589/126012566-f919e4fa-1d93-4656-b0e6-fc1a3eb66217.png)
![image](https://user-images.githubusercontent.com/45179589/126013976-9019395a-a5d3-4192-b41f-7b61f85615a6.png)
2. I'll see a Loading... notice for quite a while. Perhaps 10-20 seconds.
![image](https://user-images.githubusercontent.com/45179589/126014083-f30b30d6-925f-47ce-927b-aa86a0c01f85.png)
3. I am taken to the Machine Pools tab, not the Registration tab. A registration tab does not seem to exist:
![image](https://user-images.githubusercontent.com/45179589/126014105-b10e0636-4cee-42dd-af33-15108f5f40c8.png)

Additional Details:
I observe nothing interesting in the web browser console.
If I go back to the Clusters page:
![image](https://user-images.githubusercontent.com/45179589/126014186-6b1d9b8e-3614-46dd-ac8e-fe82188b2091.png)
And THEN click on the cluster, then I will be taken to the Registration tab (perhaps this is the default, rather than from the change in https://github.com/rancher/dashboard/pull/3397 -- not sure):
![image](https://user-images.githubusercontent.com/45179589/126014206-ea0299ea-5164-4327-9a48-0f791c6d7b58.png)

Finally, if I create ANOTHER (second) custom rke2 cluster, then The loading screen is extremely quicker and I will then see the Registration tab. As such, it's possible this only happens the first time -- the first time you won't ever be taken to the Registration tab. Nor does a registration tab seem to exist. It's quite interesting that this seems to work the second time.

All testing was done on clear browser cache (incognito browser window) In FireFox on modern amd64 Linux.

**Comment by gaktive** [comment]
@neillsom can you take a look into this? Some of this tabbing logic should be better now in release-2.6 branch

**Comment by bashofmann** [comment]
I just tested `v2.6-6c14c339a699af2c88d1c5ea075f8eedce07f55b-linux-amd64` and when creating a custom cluster, there is no long loading screen anymore and the registration tab is directly visible.

**Comment by bashofmann** [comment]
Maybe I was just lucky. Today I could reproduce the behaviour @davidnuzik described again on v2.6.0-rc1
.

**Comment by richard-cox** [comment]
There may well be a race condition, we should wait for the mgmt cluster before leaving the create cluster page in `saveOverride`...however we navigate away as part of the default `save`. Have added a fix for it in a branch for another issue. Could be entirely unrelated though, would expect errors if we haven't got something required

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.
 
**Validation Steps:**

Rancher version: v2.6-head 4b6af95d7 8/9/21 8:46 am Pacific
Rancher cluster type: single-node docker
Docker version: 19.03
 
Downstream cluster type: rke2 custom cluster
Downstream K8s version: v1.21.3-rc4+rke2r2
 
Validation steps:

1. Create a custom RKE2 cluster
2. Notice, you are now taken to the registration tab without any issues (the problem appears to be resolved).

![image](https://user-images.githubusercontent.com/45179589/128736017-7a5cbdd6-ca92-4884-bf1d-a08d9913a055.png)
