### ISSUE TITLE
Fail Whale error page rewrites the current URL in the browser

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#3421]
When an error occurs, a nice error page is shown:

![Bildschirmfoto 2021-06-30 um 12 06 33](https://user-images.githubusercontent.com/243056/124923962-40b01900-dffb-11eb-81bc-27934f85c27e.png)

Unfortunately, this also rewrites the URL in the browser to `/dashboard/fail-whale`. This is bad practice because it influences the user's browser history and makes it impossible for a user to just refresh the current page and see if the error may have gone away (for example a crashed cluster agent started again).

The dashboard should show a nice error message, but the URL should not be rewritten.

**Comment by rak-phillip** [comment]
There are a few things that we might be able to try in order to resolve this one. The simplest path forward from my perspective seems like adding a button to take the user back to their previous route instead of setting the expectation to reload the page. 

I've also been reviewing vue router`s [pathMatch](https://router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route) prop as an alternative, but it looks like this only applies to catch-all routes, which `fail-whale` is not...

Finally, I noticed that we're usually committing and error to our store before redirecting to `fail-whale`. I'm wondering if we can't make use of a getter in our layouts (default, home...) to render the `fail-whale` component in place of our regular content.

Is there a preferred path that we would like to take? Can I be overlooking an alternative approach?

@nwmac @richard-cox @vincent99

**Comment by davidnuzik** [comment]
**My checks PASSED**
This took several attempts to find a scenario where I can cause the fail wail error to occur.
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `1a57856` pulled 9/17/21 ~9:30am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.4+rke2r2
 
**Validation steps:**

1. Try to navigate to this invalid URL: /dashboard/c/local/explorer/apps.deployment/create#storage
2. A fail-wail error is seen in the UI
3. The URL is re-written but this is expected today as per the PR. However there is a new addition - a "Reload" button.
4. Click this reload button, it does indeed appear to attempt to reload.
