### ISSUE TITLE
[provisioning v2] A standard user cannot create a cluster

### ISSUE THREAD

**Issue by dramich** [rancher/dashboard#3430]
I see two issues currently:

1. The ui attempts a GET call to the local cluster when a user doesn't have any clusters which causes a 403 since a standard user does not have this permission. 
2. Once past the GET request issue by granting the standard user GET on the local cluster, clicking create ends up at a blank screen with numerous errors in the console but no issues in the network tab for requests.

**Comment by gaktive** [comment]
Relates to work started here: https://github.com/rancher/dashboard/pull/3418

**Comment by richard-cox** [comment]
1. #3418 Should fix this, however I'm discussing with Vince if this is the correct solution. It's definitively the low bar one. Nancy is looking into similar issues around the dashboard where restricted-admins fail to reach certain screens (due to failing to fetch the local cluster).
2. After testing create cluster with #3418 the only errors I see are two related to errors fetching the provision cluster type (which I think Dan is looking in to.

As an aside I'm create a bucket issue for problems related to permissions - #3416

**Comment by richard-cox** [comment]
Could not reproduce. This will have been tested a lot by QA over the last two years
