### ISSUE TITLE
Harvester Integration - Harvester List Page

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#3466]
New Global Navbar link for Harvester and a page to list Harvester host clusters and functionality to import them
 - Harvester host clusters are a k8s cluster with a provider of "Harvester" 
  - Ability to click on link of harvester cluster and open Harvester UI

**Comment by guangbochen** [comment]
@deniseschannon the Harvester UI team will work on this feature.

**Comment by guangbochen** [comment]
And just to clarify the design, from the `Hamburger menu >> Virtualization Management >> Harvester Listing Page ---click one to go to the single cluster view-->> single Harvester cluster view `. cc @yasker 
![image](https://user-images.githubusercontent.com/4569037/125726271-17db7a32-f9f3-4117-9762-ad401f53df6b.png)
![image](https://user-images.githubusercontent.com/4569037/125726260-c3456b84-876b-480f-b968-300fc33e7364.png)

**Comment by guangbochen** [comment]
additionally, @deniseschannon can u please help to ask about the design of `Import Existing Harvester Cluster`, or it will just be similar to the `Import the external k8s cluster`, thanks
![image](https://user-images.githubusercontent.com/4569037/125726614-3dd2b191-eaf2-4d36-bc6b-11c1747efbe5.png)

**Comment by guangbochen** [comment]
This feature is already included in the PR https://github.com/rancher/dashboard/pull/3726, u can test by replacing the `ui-dashboard-index` value with the `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`, let us know if there is any design enhancement needed, thanks

**Comment by nwmac** [comment]
@guangbochen Is your team doing this? I see in the Harvester PR on dashboard that you have a list page for Harvester clusters - I don't see the ability to click on one and open the Harvester UI.

**Comment by guangbochen** [comment]
Yep the harvester team has already include this feature in the https://github.com/rancher/dashboard/pull/3726, since this is not merged so u won't be able to test it without replacing the ui-dashboard-index  settings with the custom build UI.
I believe there is actual work left for the Rancher UI team except the PR review which is already WIP, thanks

**Comment by nwmac** [comment]
@guangbochen "I believe there is actual work left for the Rancher UI team except the PR review which is already WIP, thanks" - there is, or is NOT?

**Comment by gaktive** [comment]
Based on what was Richard has shown, this looks to be done but we'll allow @richard-cox to review.

**Comment by slickwarren** [comment]
tested on v2.6-head (45dfeb4):
I’m concerned about the design of the harvester’s virtualization management in rancher from a UX perspective. 
for cluster management, when a user selects a cluster, they are shown some metadata like machine pools, conditions, etc. about the cluster. In order to view the resources of the cluster, they must select the cluster through the hamburger menu instead.

But now for the virtualization management, the user can directly view harvester’s resources when selecting the cluster in the virtual management page.  Which is inconsistent with the behavior in cluster management.
Could someone help me understand why this is the case?

**Comment by richard-cox** [comment]
I don't think there's an issue here. Kube resources underpin everything shown in the dashboard, including the continues delivery, cluster management and now virtualisation management pages. In terms of the later two the user will manage the lifecycle of the general rancher or harvester cluster from those pages. The cluster explorer on the other hand is a view of the raw kube resources inside a specific cluster. So management views to manage the clusters, explorer view to dive into the cluster.

As per slack comment, moving this back to test

**Comment by janeczku** [comment]
Based on comments from prospects, the user expectation is:

When navigating to the virtualisation management page,  i can click on a cluster name in the list and that directly allows me to view to manage the VM resources in that cluster.

**Comment by slickwarren** [comment]
Ah, ok I think I've pin-pointed my issue with this: in short, the `explore` and `manage` buttons are swapped on the virtualization page.  
In cluster management, when the user clicks the name of the cluster, they are brought to the `manage` page (node pools, related resouces, etc.) and there is a button on the far right to explore the cluster
<img width="1792" alt="Screen Shot 2021-09-21 at 9 16 02 AM" src="https://user-images.githubusercontent.com/16691014/134208242-d8ae6782-0ee1-44ce-b33f-20da450d0976.png">


however, in virtualization management, these are swapped.  There is a `manage` button on the far right, and clicking the name now brings you to the equivalent of the `explore` button from the previous example.

<img width="1791" alt="Screen Shot 2021-09-21 at 9 16 10 AM" src="https://user-images.githubusercontent.com/16691014/134208229-b2f793d4-a161-42c8-9a55-ff73bd670591.png">

Can we make this more consistent between the two management panes?

**Comment by yasker** [comment]
I also feel a little weird that in the virtualization management page, click the `name` brings users to the VM management instead of resources. I remember it was the same as explorer a few days back, e.g. click the `name` bring to the resource page, and click the `Harvester` (the button was called `Harvester` instead of `Manage` at the time) brings to the Harvester UI page. 

We still need the resource page for downloading kubeconfig etc. 

It's more depends on how Rancher UI team wants it. Personally, I would prefer the way to be consistent across different pages, but I am not the designer for this page. cc @gaktive

**Comment by yasker** [comment]
Per @deniseschannon it's better to say `Harvester Clusters` in the `Virtualization Management` page to distinguish from Kubernetes clusters which are showing on the `Cluster Management` page.

**Comment by nwmac** [comment]
I think the UX is okay - clicking on the name takes you a level down where you are - in Cluster Manager, clicking shows cluster detail. In VM, clicking drills down to the harvester UI for that cluster.

**Comment by yasker** [comment]
@n313893254 @WuJun2016 can you help to tweak the title of the cluster list inside virtualization management per https://github.com/rancher/dashboard/issues/3466#issuecomment-924467964 cc @guangbochen

**Comment by gaktive** [comment]
@yasker it looks like the appropriate changes are in. If there's nothing else to do, shall we pass this to QA?

**Comment by slickwarren** [comment]
on v2.6-head (06e19b0):
* virtualization management page now shows title as `harvester clusters` -- pass
* `create` button on the virtman page also shows title as `harvester clusters: create` -- pass
  * warning is not on harvester create page -- pass
* `explore` and `manage` button/links are now working and match behavior on `cluster management` page -- pass
*
