### ISSUE TITLE
Redacted/hidden `sensitive` information in `Secrets` is inconsistent. Some sensitive info is revealed when a user has `hide sensitive info` enabled

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3474]
on master-head (8073489):

Repro:
* on a cluster, go to the `secrets` page, and select a random secret
  * observe each of the different tabs (details, config, yaml)

Issue:
  * each tab shows by default different 'sensitive' info, when the `sensitive` (eye icon) button is not selected

<img width="1557" alt="Screen Shot 2021-07-14 at 10 57 38 AM" src="https://user-images.githubusercontent.com/16691014/125670384-be22c8e4-0337-401b-bd04-b4f8623529f3.png">
<img width="1437" alt="Screen Shot 2021-07-14 at 10 57 24 AM" src="https://user-images.githubusercontent.com/16691014/125670389-f6eed064-51ba-4b17-ae62-0f722dca68b3.png">
<img width="524" alt="Screen Shot 2021-07-14 at 10 57 06 AM" src="https://user-images.githubusercontent.com/16691014/125670392-f2a2da89-787e-4c30-a654-bc2f6b0acb30.png">

Suggested fix:
* hide all values of a secret on each page
  * fix the `details` page to hide `ca-cert` values
  * add the hide/show feature to the yaml view page if this is possible
  * not sure if this is what rancher would want, but sensitive data like this may never want to be revealed (similar to what Jenkins has for any sort of value when viewing/editing a `credential`) through the UI.

**Comment by nwmac** [comment]
This behaviour is as designed - we detect that is is a certificate, so on the detail view we only conceal the data that are sensitive.

On the Config view, we conceal everything - this is a generic view.

**Comment by slickwarren** [comment]
@nwmac my main concern would be that, even `data` is revealed through the yaml view.  in ember, we base64 encode any data when viewed through the UI (even on edit, user can only see the b64 encoded data).  
The other concern is just from an optics point of view as a customer. i.e. if the user visits one of these pages, then the others, it is not obvious why information is revealed with the same setting (hide sensitive info) applied on each page.

**Comment by vincent99** [comment]
Again this is all working as intended.

The YAML view/editor shows the YAML that is present.  We are not going to arbitrarily disable showing/editing YAML for the Secrets type, or build in something to parse the document, detect data segments and redact them.

The data is base64-encoded because that's how it's actually stored and needs to be sent, because the values can contain binary data, not to pretend that it's unreadable in that form. (You can use `stringData` to send un-encoded ASCII data, but that gets converted on save anyway).  This is the same in Ember and Vue, that's just what the YAML is.
  
The toggle for hiding sensitive data is to prevent casual shoulder-surfing while viewing resources, largely in the before-times when people were in offices with shoulders to surf.  It is not meant to prevent you from seeing the original value if they're _trying_ to see it, nor to not let you read what you're editing.  The mechanism in Ember to see the actual data was not very good because it was always on whether you want it or not, and undiscoverable to find out it even existed; this is what we're doing now.

It hides data that is sensitive.  It does not hide things that are known not to be.  Certificates are data that literally HAS to be given to the other side to be useful.  The public/username portion of cloud credentials and basic auth, etc.

**Comment by slickwarren** [comment]
ok, thanks for clarifying Vincent.
