### ISSUE TITLE
Not able to open Edit Yaml of Namespace under a cluster's Projects/Namespace

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3500]
**On master-head commit id: `f33188d`**

- Go to Cluster --> Projects/Namespace --> 'Edit YAML' a namespace
- Page is stuck in loading
- Error in console

```
TypeError: Cannot read property 'doneOverride' of null
    at f.r (index.vue?7c0a:1)
    at f.t._render (vue.runtime.esm.js:3548)
    at f.r (vue.runtime.esm.js:4066)
    at _n.get (vue.runtime.esm.js:4479)
    at _n.run (vue.runtime.esm.js:4554)
    at gn (vue.runtime.esm.js:4310)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at ie (vue.runtime.esm.js:1906)
```

**Comment by nwmac** [comment]
@sowmyav27 I can't reproduce this - are you doing this as an non-admin?

**Comment by richard-cox** [comment]
@nwmac I just hit this, cluster needs to be non-local. Issue is caused by a 403 when trying to fetch the namespace

**Comment by sowmyav27** [comment]
Reopening because of https://github.com/rancher/dashboard/issues/3500#issuecomment-882455995

**Comment by mantis-toboggan-md** [comment]
I wasn't able to reproduce this, downstream cluster (k3s on digital ocean) or otherwise. I tried with admin, restricted admin, and standard users with cluster owner and member roles, and wasn't able to create a situation in which the active user had 'Edit as YAML' as an option on a namespace they couldn't fetch... @richard-cox do you have any more details on how you reproduced this? The issue appears to be more specific than just any namespace in a downstream cluster.

**Comment by richard-cox** [comment]
My local cluster is a tad old (Jul 14, 2021). Are you on a newer version? If so perhaps there was a backend issue that's been fixed and this should go back to test.
To confirm, the `Edit as YAML` button is always visible however when clicking on it then the 403 to `k8s/clusters/c-m-c37649bb/api/v1/namespaces/<name>` happens

**Comment by mantis-toboggan-md** [comment]
I am using a shiny-new rancher install so maybe it is a recent backend fix. I'm going to move this back to test, then.

**Comment by sowmyav27** [comment]
**On master-head commit id: `9e0d1b2`**

- Able to do an Edit Yaml of namespace of a downstream cluster with no errors.
