### ISSUE TITLE
Single Cluster: Improve presentation of home page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3510]
Separated out of issue rancher/dashboard#2795

Can we change the format of these links and Provider and Created details?

 ![image](https://user-images.githubusercontent.com/1955897/126288098-e192d6c1-99de-4706-873f-51c2d11cfd8b.png)

**Comment by catherineluse** [comment]
I'm closing this issue as outdated, since the dashboard overview page has gone through a lot of changes since this issue was opened.
<img width="1479" alt="Screenshot 2022-11-05 at 2 24 37 PM" src="https://user-images.githubusercontent.com/20599230/200141908-eacbcb57-b931-4a20-94b1-eb4d9d026281.png">
