### ISSUE TITLE
`All Namespaces` doesn't select any data (i.e. workloads is empty by default) -- inconsistently reproducible

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3523]
on master-head (cfbd0d3):
Repro Steps (inconsistent):
* navigate to a downstream cluster
* note that `all namespaces` is selected by default in the namespace field
in this case, no workloads were populating
<img width="1178" alt="Screen Shot 2021-07-20 at 8 23 05 PM" src="https://user-images.githubusercontent.com/16691014/126426626-6a5b1c05-4f72-4c79-a429-ef9e819774d0.png">

Workaround Steps:
* select a namespace from the dropdown (i.e. `default`)
* de-select the namespace
you should now see all namespaces correctly populating workloads

Notes for the developer:
* at the time, this setup was shared and another person was able to repro upon visiting the downstream cluster. However, after clearing the cache and attempting a repro (after doing the workaround from above), neither of us were able to get back to a bad state. 
* this was seen on a downstream cluster, with GKE as the local cluster

**Comment by vincent99** [comment]
The list of namespaces to show is in a preference, so this is probably somehow related to timing and/or multiple people updating it.  If you get into the situation again, knowing what the value is before it's lost (by changing to `default`) would be useful.

**Comment by gaktive** [comment]
@slickwarren were you able to reproduce this since you first saw it?

**Comment by sowmyav27** [comment]
Reopening to validate the original issue

**Comment by Auston-Ivison-Suse** [comment]
**Setup for Reproduction**
Rancher Version: 2.6-head (e322f8f)
Cluster info: RKE1 k8s: v1.21.6, single node all roles

**Steps for Reproduction**

1. Right after provisioning a cluster go to the deployments. 
2. Go to workload --> Deployments
3. Witness the bug. 

**Notes**
The initial mentioned workaround no longer works, it instead reverts to "Only User Namespaces" instead of all namespaces. Seems this is issue wasn't fixed and I mistakenly moved it to Done. 

**Gif of Bug**

![2021-11-22_10-41-32 (1).gif](https://zube.io/files/rancher/0bfb8bd6d0c607be4651b28e5446f989-2021-11-22_10-41-32-1.gif)

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Validation**
- Rancher version: v2.6-head(4375161)
- Freshly provisioned Rke1 Cluster

**Steps For Validation**
1. From a freshly provisioned
2. go to Workload --> Deployments
3. Notice you land on Deployments page with the "Only User Namespaces" selected in the namespace selector.
4. Press x in the namespace selector and see it change to "All Namespaces" as intended. 

**Note**
As mentioned in the original issue the intended default in the namespace selector should be "All Namespace" but instead it seems from a freshly provisioned rke1 cluster it instead defaults to "Only User Namespace."
