### ISSUE TITLE
Theme changes from light to dark if we create an rke1 cluster in the vue UI right after the rancher is up 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3530]
master-head b6bcfad

1. Create a rancher server and set user password and server URL
2. From cluster management page, create an rke1 cluster 
3. Refresh the page, theme changes from light mode to dark mode

This happens sometimes when we try right after the server is up. If we change the setting in preferences from dark to auto, the issue is not seen.

**Comment by gaktive** [comment]
The "sometimes" sounds a bit hard to reproduce. We can have @neillsom to try this out, perhaps with a page that is embedded from Ember since that sounds like where we need to look. If we can't repro, then we may need a more reliable way from QA to show this behaviour.

**Comment by lvuch** [comment]
I tried this and cannot reproduce. Logged in with light on, create rke1 cluster, stays in light

**Comment by anupama2501** [comment]
Hi @lvuch
I'm seeing this on a fresh master-head installation as soon as the server is up, if we try to create an rke1 cluster and then refresh the page the theme is changed from light to dark

https://user-images.githubusercontent.com/38144301/127546389-76f00b49-c0af-441d-ba3d-34cf6bafb74f.mov

**Comment by sowmyav27** [comment]
See this on the latest master too `37561eb`

**Comment by lvuch** [comment]
I've tried this several times and can't reproduce the issue. Could it be a cache issue?

**Comment by rak-phillip** [comment]
@anupama2501 A PR is raised for the fix. Because this bug was "sometimes" happening, I thought it would be a good idea to cover the steps I was using to reproduce the issue in dev:

1. Clear all cache and cookies
2. Start a new container for rancher dashboard
3. After initial setup and login, navigate to preferences and set your theme to the opposite of what was automatically picked for you (if the dark theme was automatically picked for you, set the theme to light and vice versa)
4. Exit rancher dashboard and stop container
5. Start new rancher dashboard container
6. After initial setup and login, verify that your theme is the explicit value you set in step 3
7. Navigate to Cluster Management => Create => RKE1 => Amazon EC2

**Comment by kravciak** [comment]
Works fine on 2.6-head (4b6af95). To test I followed instructions in https://github.com/rancher/dashboard/issues/3530#issuecomment-894576956.
Theme setting was remembered through rancher redeployment and consistent (no black-white mix anymore)
