### ISSUE TITLE
Not able to add members to default project in a cluster 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3550]
master-head 01665d0

1. Create an rke2 node driver cluster 1 node all roles
2. From Project/namespaces --> edit the `Default` project and add members
3. The save button is disabled for `local` and `Default` projects. 
Can be added from ember UI

**Comment by deniseschannon** [comment]
I attempted to add project members through the Vue UI to the Default and System project. I can "Save" it, but when I re-look at the Project, there are no members showing up.

Note #1: I can see the list of Project Owners and Members in Ember.
Note #2: The default admin who is a project owner is not showing up on the project member list.

**Comment by igomez06** [comment]
Verified on v2.6-head - ba95a58

**Steps taken to see the issue is fixed:**
   * I created a Digital Ocean RKE2 cluster with one node all roles.
   * I created two Project Member users.
   * I went to Project/Namespaces I edited the Default project and add those two aforementioned users, and was able to successfully save the project.
   * I repeated this with the System project as well, and was able to successfully save the project.
