### ISSUE TITLE
UI Validation on Cluster Names

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#3585]
Due to having multiple cluster types and different provisioning frameworks, currently, clusters in the new framework cannot be named `local` or `c-XXXXX`. 

We have an issue for a proper fix for the backend. https://github.com/rancher/rancher/issues/33694

But we should also add in UI validation to prevent clusters to be created with either `local` or `c-XXXXX`.

**Comment by igomez06** [comment]
Verified on v2.6-head - 4b6af95

**Steps taken to see the issue is fixed:**

* I attempted to create an RKE2 cluster: (Custom, Digital Ocean, Amazon EC2,etc) with cluster names of local, and variations of c-xxxxx (ex, c-abcde, c-aaaaa, etc.)
* The UI prevented me from created a cluster with any of the aforementioned names. Siting this error: _**Cluster name cannot be 'local' or take the form 'c-xxxxx'**_
