### ISSUE TITLE
UI error after user password reset

### ISSUE THREAD

**Issue by dveni** [rancher/dashboard#3612]
See on `rancher/rancher:master-head 3499046`

After creating a user with the must reset password option, I log in with that user and after changing the password I get the error you can see in the screenshot. However, you can navigate to the <rancherURL>/dashboard and you are already logged in with that user. You can also log out and log in again with the new password, so it's actually changed in the backend. 

![image](https://user-images.githubusercontent.com/28764301/128016722-21916548-00e1-43ce-9b6e-3c193dcc2458.png)

**Comment by igomez06** [comment]
Verified on v2.6-head - 4b6af95

**Steps taken to see the issue is fixed:**

* From admin account, created a standard user with _**Ask user to change their password on next login **_ option.
* Logged in with the new user, and changed password as directed
* Successfully logged in with NO error messages.
