### ISSUE TITLE
Download KubeConfig fails to download when MCM feature flag is disabled

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3625]
**Rancher Server Setup**
- Rancher version: master-head
- Installation option (Docker install/Helm Chart): Docker install

**Information about the Cluster**
- Kubernetes version: v1.20.7+k3s1
- Cluster Type (Local/Downstream): Local

**Describe the bug**
Download KubeConfig fails to download when MCM is disabled

**To Reproduce**
- Deploy a single node docker install of rancher.
```
docker run -d --privileged --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher:master-head --features=multi-cluster-management=false
```
- Go to the cluster explorer of the local cluster
- Click on Download kubeconfig icon top right of the page
- Respoonse: `404 page not found`**

**Comment by deniseschannon** [comment]
Today in explorer dashboard, generateKubeconfig is called from `/v3/clusters`. Since if user run MCM=false v3 api will be disabled, then the action will be broken.(related issue https://github.com/rancher/rancher/issues/33687). https://github.com/rancher/rancher/pull/33811 adds the ability to expose `generateKubeconfig` from v1 api and UI needs to be able to pick it up.

**Comment by catastrophe-brandon** [comment]
It looks like the back-end was updated in #3571. Has the front-end code been updated to match?

**Comment by catastrophe-brandon** [comment]
As of `10588ab` I'm still seeing a 404 in the dev console. The front-end is still trying to invoke the v3 API, which doesn't exist.

**Comment by catastrophe-brandon** [comment]
Appears to be working in v2.6-head `v2.6-8784750074bceb84615b4b4a26d5d5e62683121c-head` and master-head `master-ce917fbb50db169343dff470b8370322da0150d1-head`.
