### ISSUE TITLE
Fleet controller logs do not show up on dashboard

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#3668]
**Rancher Server Setup**
- Rancher version: `rancher/rancher:v2.6-head` (`e3316c9de7f089c5eef25bf58ff700a0198527c3`)
- Installation option (Docker install/Helm Chart): Docker install
- Proxy/Cert Details: no certs

**Information about the Cluster**
- Kubernetes version: v1.21.3+k3s1
- Cluster Type (Local/Downstream): Local

**Describe the bug**

Fleet controller logs are only visible on Cluster Manager but not visible on Cluster Dashboard unless they are downloaded

**To Reproduce**
 

- Spin up a Rancher cluster
- Provision a downstream cluster
- View the logs of the fleet-controller Deployment in the local cluster
- Try to download the logs or view the same logs on Cluster Explorer

**Result**

Logs are downloadable or viewable on Cluster Explorer but not on Cluster Dashboard

**Expected Result**

Logs should be viewable on Cluster Dashboard

**Screenshots**

![Screen Shot 2021-08-04 at 6 42 26 PM](https://user-images.githubusercontent.com/13127443/128277917-ee0f9094-68d2-46ae-b906-d0a722190cd2.png)

![Screen Shot 2021-08-04 at 6 42 49 PM](https://user-images.githubusercontent.com/13127443/128277925-5343a548-b1ba-4412-b9be-1b37505d2beb.png)

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by aiyengar2** [comment]
They also do not show up if you try to access the logs on the Pod instead of the Deployment

**Comment by aalves08** [comment]
This feature seems to be working fine. By default, the logs filter (cog on the bottom) is set to look at the logs for the last 30 minutes, but we change that to the last 1000 lines, we get the logs for the deployment as expected. Can you confirm that @aiyengar2 ?

![Screenshot 2022-02-18 at 16.33.18.png](https://zube.io/files/rancher/4574bd305c1779a4d5ab2369103c704b-screenshot-2022-02-18-at-16-33-18.png)
![Screenshot 2022-02-18 at 16.33.27.png](https://zube.io/files/rancher/b4a3035a5311cdee7661b7aac7c9e0ba-screenshot-2022-02-18-at-16-33-27.png)

I know that we aiming to revise that footer bar for a future version so that the options available to the user are clearer.

Thanks

**Comment by aalves08** [comment]
@gaktive @nwmac 
Will move forward this issue to testing. Thank you

**Comment by deniseschannon** [comment]
[QA Manager] Since this was filed by a dev and no UI work was done, we've sent it over to dev-validate.

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.

**Comment by eliyamlevy** [comment]
Validated that I was able to view the logs from the Cluster Dashboard. Although I'd like to add that if there weren't any logs from the previous 30 minutes no logs would show. Since I believe the default setting is to only show the most recent 30 min it could look like no logs are available. After changing that I could view all the log outputs. 

![Screen Shot 2022-03-22 at 3.30.15 PM.png](https://zube.io/files/rancher/a6981df2441bfaaeab0caf9b32a7bf69-screen-shot-2022-03-22-at-3-30-15-pm.png)
![Screen Shot 2022-03-22 at 3.04.54 PM.png](https://zube.io/files/rancher/486c9a975c1857bcb53429f29dbd4641-screen-shot-2022-03-22-at-3-04-54-pm.png)
