### ISSUE TITLE
Randomly Darkmode is turned on.

### ISSUE THREAD

**Issue by phillipsj** [rancher/dashboard#3675]
**Rancher Server Setup**
- Rancher version: 2.6-head
- Installation option (Docker install/Helm Chart): Docker

**Describe the bug**

Fresh installs of Rancher have recently been activating the dark mode. It is hard to reproduce, but I was finally able to grab a screen shot of it.

**Screenshots**

![image](https://user-images.githubusercontent.com/1568133/128348982-fc7e58eb-f5e9-4c59-a8b7-cd0402bf6448.png)

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by richard-cox** [comment]
This is/highly likely the root cause of #3530. @lvuch these need tackling together

**Comment by igomez06** [comment]
Verified on v2.6-head - c47122a

**Steps taken to see the issue is fixed:**
* Created an RKE1 cluster right after rancher is up.
* Created an RKE2 cluster.
* Created multiple standard users.
* Logged in and logged out.
* Created a project.
* As a result the theme did NOT change, and has been in light mode.
