### ISSUE TITLE
Session timeout while looking at iframed ember pages needs to log vue out

### ISSUE THREAD

**Issue by vincent99** [rancher/dashboard#3704]
1. Set the `auth-user-session-ttl-minutes` setting to 1 minute to make this easy.
2. Log out, then back in. (the TTL is saved on each token at create time so your current session is still good for 16hrs)
3. Go to the Cluster Management product
4. Wait 1 minute
5. Click on RKE Templates or Node Templates (any page that's an ember iframe)
6. You end up looking at the Ember login screen on the right half of the page and regular Vue nav on the left.
(7. Then the Ember login redirects you to Vue login inside the iframe, but not really relevant).

![image](https://user-images.githubusercontent.com/753917/128568739-9c68b840-9c7f-45ea-921e-b5eaeb0ee6df.png)

If Ember is iframed and receives a 401, it needs to send a signal up to the parent Vue window to tell it to bring you to the login screen via the vue logged out actions, instead of redirecting to the ember login route and staying in a frame.

**Comment by igomez06** [comment]
Verified on v2.6-head - 4b6af95

**Steps taken to see the issue is fixed:**

* Set the _**auth-user-session-ttl-minutes**_ setting to 1 minute
* Went to Cluster Management
* Waited 1 minuted
* Clicked RKE Templates
* Session timeout, and was sent to the login screen. Just the Ember login screen, Vue nav was NOT to the left. I was successfully logged out to the correct screen.
