### ISSUE TITLE
when provisioning a cluster, Cloud Provider should only display currently selected node driver 

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3709]
on 2.6.0-rc1:

Issue:
Cloud Provider should only show the option(s) available for the current node driver. Currently it is displaying all options

(screenshot of digital ocean node driver during `create)
<img width="1425" alt="Screen Shot 2021-08-06 at 5 50 22 PM" src="https://user-images.githubusercontent.com/16691014/128585132-e4238ae7-7e26-4a81-b45b-a1f76478af1e.png">

**Comment by richard-cox** [comment]
Fixing this will resolve release blocker #3468. @vincent99 where's the gotcha here, does the field just need removing and `agentConfig['cloud-provider-name']` set to the query-parm `type`? It looks like the field is populated given the kube version, given we now up front select the type does that kube version list need filtering by those that have the provider type from header?

**Comment by richard-cox** [comment]
@vincent99 Was there a PR associated with this?

**Comment by slickwarren** [comment]
tested on 2.6-head (72986b2):
* ec2 shows only amazon cloud provider/external -- pass
  * on create
  * on edit
* azure shows only azure cloud provider/external -- pass
  * on create
  * on edit
* non-provider cluster (i.e. Digital Ocean) displayed all options -- pass

**Reopening for the following issue**
* vsphere shows only vsphere cloud provider/external -- fail -> shows external only
* expecting `rancher-vsphere` out-of-tree to show up for vshpere

**Comment by vincent99** [comment]
vsphere wasn't showing up because of the rename from vsphere -> rancher-vsphere.

Both the driver list and the cloud-provder list are dynamic and we don't really know what to do in most cases so I don't want to just hide everything for all unknown combinations.  For example you could make your own fork of the EC2 driver and then should be able to use the AWS cloud provider.  So I only added "if the provider is known_thing_x (like amazonec2), limit the options to y (aws)", not the other way around.  If there is no particular mapping for a driver it's still going to show all the options kdm provides.

**Comment by slickwarren** [comment]
on v2.6-head (c10ef4b):
* vsphere/external only show up for vsphere provider -- pass
* non-provider clusters show all options (after clarity from Vincent's comment above) -- pass
