### ISSUE TITLE
"Paste lines for easy bulk entry" info tool tip is not relevant in the Key input field of Linode cloud credential

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3724]
**On 2.6-head commit id: `4b6af95`**

- Go to Cluster Management --> Cloud credential --> Create Linoode creds
- The info tool tip for the Key `"Paste lines .....for easy bulk entry"` is not relevant here, as this is just one key value pair.

<img width="850" alt="Screen Shot 2021-08-08 at 3 41 47 PM" src="https://user-images.githubusercontent.com/26032343/128647927-4f214e70-2fbb-4cd9-9366-a4aaf0305118.png">

**Comment by Auston-Ivison-Suse** [comment]
Note: 
Screenshots are numbered 1 and 2 for v2.6-head and v2.6.0 respectively.

I can validate this issue was fixed. 

**1.**![Screen Shot 2021-09-16 at 4.56.53 PM.png](https://zube.io/files/rancher/0797f60223d9284a513c0d9b55320e41-screen-shot-2021-09-16-at-4-56-53-pm.png)

**2.**![Screen Shot 2021-09-16 at 4.56.46 PM.png](https://zube.io/files/rancher/eface3f50d5627522336913123018d7e-screen-shot-2021-09-16-at-4-56-46-pm.png)
