### ISSUE TITLE
Some 2.5 content (text) in dark mode difficult to distinguish from background colour

### ISSUE THREAD

**Issue by David-VTUK** [rancher/dashboard#3729]
Some text presented in iframes (2.5 content), in dark mode, is difficult to distinguish from the background colur.

# Example 1 - Node Template
![nodetemplate](https://user-images.githubusercontent.com/5892615/128683887-835fac38-3b76-4a83-be2b-4a681bf758a3.gif)

# Example 2 - Node/Cluster Drivers
![nodedrivers](https://user-images.githubusercontent.com/5892615/128683927-d04d5a85-0dfe-4d58-82b0-2e68b393e76a.gif)

Related: rancher/dashboard#3713

**Comment by kravciak** [comment]
Issue is fixed in v2.6-head (25d39aa)
![Screenshot from 2021-08-12 10-43-39](https://user-images.githubusercontent.com/538604/129167146-b4c1e3ed-c7b3-4b1f-8e98-0f19d205c6c2.png)
![Screenshot from 2021-08-12 10-44-39](https://user-images.githubusercontent.com/538604/129167149-fdb5cba0-cf9a-4599-8e5a-c1e5d6c7568d.png)


But overall black theme could use redesign, for example:
 - random mix of grey/white/black text (Clusters -> Create -> DO RKE1)
![Screenshot from 2021-08-12 12-12-46](https://user-images.githubusercontent.com/538604/129180558-8a1f7d8f-233d-470f-b623-50fb3bb5ebb5.png)
 
 - some inputs have no border, it's hard to distinguish them from labels (Cluster Management -> Drivers)
![Screenshot from 2021-08-12 12-11-03](https://user-images.githubusercontent.com/538604/129180325-f3010c5e-311a-45be-8608-e5b54516a642.png)
