### ISSUE TITLE
rke1 node driver/custom clusters go into edit cluster mode when we click on view config in cluster management

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3773]
rancher version v2.6.0-rc2

1. Create an rke1 node driver/custom cluster 
2. From cluster management --> click on the cluster created above --> click on config --> all the options are editable with a `save` option enabled.

** Expected Result: **
View config of the cluster should have only details displayed and no `save` option  be provided

**Comment by richard-cox** [comment]
@nwmac This is part 1 from #3698 that I previously moved out due to not quite understanding. Do we need to address in the 2.6 time frame?

**Comment by catherineluse** [comment]
I'm closing this issue as not applicable because there is no longer a "View Config" option in cluster manager. We only have "Edit Config."
<img width="1243" alt="Screenshot 2022-11-05 at 4 35 48 PM" src="https://user-images.githubusercontent.com/20599230/200147018-3d18e068-5a53-4256-8660-679a60dfdca3.png">
