### ISSUE TITLE
As user with Manage Users permission I can delete Default admin

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#3784]
This removes the only Admin from cluster.
As User I am not able to increase my own permissions, so I am cut from rancher.

As Admin:
- Create user with `User-Base` Global Permissions
- Add `Manage Users` built-in role to the user

As User:
- Users & Authentication -> Users -> Default Admin -> Delete

Result: I deleted the only admin from rancher setup.

Tested on: v2.6-head (9d2e086)

**Comment by nwmac** [comment]
The API allows this to be done, so we don't prevent it in the UI.

We could look to add a warning if this is possible.

**Comment by catherineluse** [comment]
I'm closing this as expected behavior. It is a supported use case to delete the default admin in favor of the restricted admin role. https://docs.ranchermanager.rancher.io/v2.5/how-to-guides/advanced-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions#restricted-admin
