### ISSUE TITLE
Add some minimal validation to Server URL input field

### ISSUE THREAD

**Issue by catastrophe-brandon** [rancher/dashboard#3832]
When entering a new Server URL from the Global Settings page, the field input description says `Default Explorer install url. Must be HTTPS. All nodes in your cluster must be able to reach this.` However, I was able to enter a URL with `httpq` as the protocol without any complaints. This was done in `master-c58f95221d76c6e6a32c89426b300f8afd2ab69a-head`.

<img width="593" alt="Screen Shot 2021-08-12 at 4 50 04 PM" src="https://user-images.githubusercontent.com/20647751/129274842-38289c43-82f3-47b2-b5ef-a012aa7181cd.png">

Edit: I was also able to enter `file://usr/bin/env/bash` and save. Seems like there may be no validation in place at all.

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: 
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: 
Downstream K8s version: 
 
**Validation steps:**

1. Go to Global Settings > Advanced Settings and try to change the server-url setting to a different protocol or invalid protocol. These will not work (as expected with the change).
Basically, I tested https://github.com/rancher/dashboard/pull/3871/files#diff-047bbe2c51aa332b6d394403d4f832c3663e1909794661ebba34c14f586cfb03R8 in various ways I could think of:

httpq:// (does not work as expected, get "server-url must be https." error)
http:// (does not work as expected, get "server-url must be https." error)
ftp:// (does not work as expected, get "server-url must be https." error)
HTTP:// (does not work as expected, get "server-url must be https." error)
HTTPS:// (DOES work as expected, since capital HTTPS will not hurt anything)

```
 https://
```
Does seem to work but is not expected, however this doesn't seem to hurt anything? I can add spaces before or after the URL but can still browse around just fine. Perhaps on the backend this is handled.
