### ISSUE TITLE
continuous delivery: Git repo update fails with error about message size

### ISSUE THREAD

**Issue by catastrophe-brandon** [rancher/dashboard#3833]
I added the repo rancher/dashboard to Continuous Delivery -> Git Repos. After a while, an error message appeared in the UI:

```
Time="2021-08-12T22:01:58Z" level=fatal msg="rpc error: code = ResourceExhausted desc = trying to send message larger than max (2343775 vs. 2097152)"
```

This may suggest that we need to tune the message size of the client so that we can handle a broader assortment of git repos.

<img width="917" alt="Screen Shot 2021-08-12 at 5 06 08 PM" src="https://user-images.githubusercontent.com/20647751/129276048-718f3a23-0d22-40f2-a5ad-956ef28ec5f7.png">

**Comment by catastrophe-brandon** [comment]
This was `master-c58f95221d76c6e6a32c89426b300f8afd2ab69a-head`

**Comment by catastrophe-brandon** [comment]
More diagnostic information from the pod that error'd out.

[dashboard_error.txt](https://github.com/rancher/dashboard/files/6978865/dashboard_error.txt)

**Comment by richard-cox** [comment]
The message shown comes directly from fleet's `gitrepos` resource, rather than something the UI has failed to receive. So from the UI's perspective we're showing the correct information.

![image](https://user-images.githubusercontent.com/18697775/200814742-c05b21a5-372b-49db-9488-c6c5d9ac23c8.png)

To resolve this you'll need to create an issue over at https://github.com/rancher/fleet. That being said, the `rancher/dashboard` repo isn't compatible with fleet (it depends on other resources and shouldn't be scaled via fleet)
