### ISSUE TITLE
Enabling SUSE subscription breaks window title

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3861]
After enabling the subscription the title goes to `dashboard` and ignores any custom branding setting (possibly also the default `rancher` too?).

Not sure of the correct behaviour here. I guess it should default to SUSE and still allow the branding to override? Check with Neil / Lauren.

**Comment by nwmac** [comment]
@mantis-toboggan-md Low priority - but maybe a quick fix?

**Comment by thehejik** [comment]
Tested on `rancher/rancher:v2.6-head b43e4d9`

After enabling SUSE subscription (`Get Support/Add a Subscription ID`) the web page title is now showing `Rancher` and not `dashboard` (reproduced on `rancher:v2.6.0-rc1`). Also when custom `Private Label Company Name` field on `Branding` page is set to something else than default `rancher` the custom value is used as title correctly.

Anyway when SUSE Subscription is enabled I think it should show `SUSE Rancher` instead of `Rancher` so I opened a new issue https://github.com/rancher/dashboard/issues/3982

This is fixed so closing.
