### ISSUE TITLE
Create Harvester Cloud Credential lack of "kubeconfigContent" and "annotations" in the response body

### ISSUE THREAD

**Issue by n313893254** [rancher/dashboard#3905]
**Rancher Server Setup**
- Rancher version: 44bb5b4 (v2.6.0-rc2)

**Describe the bug**

Create Harvester Cloud Credential lack of "kubeconfigContent" and "annotations" in the response body

**To Reproduce**
 
- Go to "Cluster Management"
- Go to "Cloud Credentials" and create Harvester Credentials
- Input the name and select an imported harvester cluster
- Click save

**Result**
"kubeconfigContent" and "annotations" are sent in the request body, but in the response body is empty.

**Expected Result**

"kubeconfigContent" and "annotations" in the response body

**Screenshots**

![image](https://user-images.githubusercontent.com/18737885/129202942-f05da01f-48c5-4744-a350-ddbe6eb5c792.png)

![image](https://user-images.githubusercontent.com/18737885/129203031-35594e4c-0c77-4c19-a03a-da85857642b4.png)

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested with Rancher v2.6.1-rc5 and harvester v0.3.0-rc1. Still not seeing annotations or Kubeconfigcontent in the response.
![image](https://user-images.githubusercontent.com/83787952/135363095-02451ae7-8162-4b99-9049-678a3b758fe1.png)

**Comment by guangbochen** [comment]
Confirmed with @n313893254 , this issue was out-of-date.
- the `Kubeconfigcontent` is a secret field of the `harvestercredentialConfig ` and is "write-only", so you don't get the value back for security purposes. 
- the `provisioning.cattle.io/driver: "xxx"` annotation will only be used by the backed to identify the cloud provider type and will not be persisted to the `/v3/cloudcredentials` response. (same behaviour across all of the cloud providers e.g VMware)
![image](https://user-images.githubusercontent.com/4569037/135399514-21f59b70-4c4b-4f76-877c-407ebf891831.png)
![image](https://user-images.githubusercontent.com/4569037/135399599-c9621aa8-5e0a-4f25-bae1-25d7c2858156.png)
