### ISSUE TITLE
As a cluster member attempting to add a member to the cluster results in no error message just stuck in creating

### ISSUE THREAD

**Issue by igomez06** [rancher/dashboard#3911]
**Rancher Server Setup**
Rancher version: v2.6.0-head on commit-id: 72986b2
Installation option (Docker install/Helm Chart): Helm Chart
If Helm Chart, Kubernetes Info:
Cluster Type (RKE1, RKE2, k3s, EKS, etc): RKE1
Information about the Cluster
Kubernetes version: v1.21.3-rc6+rke2r2
Cluster Type (Local/Downstream): RKE2 Digital Ocean Cluster

**Describe the bug**
With a cluster member, when attempting to add a member to the cluster, it gets stuck in the creating phase, with no error message ever returned.

This is the API response:

```
{baseType: "error", code: "Forbidden",…}
baseType: "error"
code: "Forbidden"
message: "clusterroletemplatebindings.management.cattle.io is forbidden: User \"u-jsrv7\" cannot create resource \"clusterroletemplatebindings\" in API group \"management.cattle.io\" in the namespace \"c-d4zkz\""
status: 403
type: "error"
```

**To Reproduce**

- With an Admin user created a cluster (either RKE1 or RKE2)
- Create a 2 standard users; user1 and user2
- Add that the user1 as a cluster member for the aforementioned cluster.
- Login as user1, and attempt to add user2 as a cluster member.

**Result**
- UI gets stuck in the creating state and no error message is returned.

**Expected Result**
A failure with a descriptive error message, like in the API call. OR removed `Add` option for CLuster Members.

**Comment by aaronRancher** [comment]
On Rancher `v2.6-head` `version c10ef4b`:

![Screen Shot 2021-08-18 at 4 44 03 PM](https://user-images.githubusercontent.com/57409052/129986144-693ef00e-7f21-4a46-93c1-83bca55c0323.png)

**Comment by davidnuzik** [comment]
v2.6-head `1a57856` pulled 9/17/21 ~9:30am Pacific

@igomez06 I have a question about the steps mentioned to reproduce - I cannot reproduce this. It is not possible for a cluster member to add another cluster member as they do not have rights to modify the cluster.

Was there anything else you might have done during user1 creation? suer1 is just a standard user right? (that's it?)

![image](https://user-images.githubusercontent.com/45179589/133860994-25e34b0e-81a8-4a6f-9a92-a3f568805a37.png)

No option to edit cluster (as expected) therefore not possible to add user2
![image](https://user-images.githubusercontent.com/45179589/133861017-cecdd006-4c26-4010-b392-7bf520b9ed44.png)

hmm - or maybe I am confused? How did you add another user to the cluster as a cluster member?

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required. The issue was filed by a peer and I understand the reproduction steps.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `1a57856` pulled 9/17/21 ~9:30am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2 (could also be rke1, does not matter)
Downstream K8s version: v1.21.4+rke2r2
 
**Validation steps:**

1. With an Admin user create a cluster (RKE2 in my case, 1 node with DO provider but this does not matter)
2. Create a 2 standard users; user1 and user2
3. Add that the user1 as a cluster member for the aforementioned cluster.
4. Login as user1, and attempt to add user2 as a cluster member (do this by exploring the cluster and on the left pane, go to RBAC>Cluster Members)
5. The backend will respond with a 403 error (as expected) but now the UI will keep us on the form and show an error message in the UI. Therefore this now works correctly and the issue is resolved.
 
![image](https://user-images.githubusercontent.com/45179589/133861614-9c3dd43a-8d97-4857-8ce3-e5145dd877b4.png)
![image](https://user-images.githubusercontent.com/45179589/133861632-51f283b9-d489-4b9b-adf7-4616fa95df6a.png)


 
**Additional Info:**
- You cannot as a cluster member edit the cluster to add a member, but you can see this in the UI under the cluster explorer - why? If the user is not authorized I would expect to see this hidden in the UI -- but I think this is because they might be able to add custom roles of some kind if their user had the correct rights.
