### ISSUE TITLE
Cannot distinguish between placeholder/hint and default values in input fields in light mode 

### ISSUE THREAD

**Issue by aaronyeeski** [rancher/dashboard#3925]
On Rancher `v2.6-head` `version 9d5c699`. In light mode dashboard UI.

Eg. when defining a new AKSv2 cluster in Explorer there are some input boxes which have no default value set but they look like they have it. Cluster Resource Group text is not greyed out enough. The text in `Linux Admin Username` field looks greyed out, but there is actually text in the field.
![Screen Shot 2021-08-18 at 3 43 15 PM](https://user-images.githubusercontent.com/57409052/129984550-bf6ccb4e-e18d-4799-b7b6-d5d65ad8c2ce.png)
Can we grey out placeholder text? Including `DNS Prefix` field. And make default text a normal opacity? `Linux Admin Username` field for example.
![Screen Shot 2021-08-18 at 4 23 35 PM](https://user-images.githubusercontent.com/57409052/129984584-974804bb-9f2d-4288-8a2f-a7869fe186c8.png)

Related issue:
https://github.com/rancher/dashboard/issues/3837

**Comment by davidnuzik** [comment]
**I successfully reproduced**
Note: I don't see this issue in dark mode, only in the light mode.
 
**Reproduction Environment:**

Rancher version: v2.6-9d5c699e18d174cb980e342a796ed828eeefcd18-head
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: AKS
Downstream K8s version: n/a
 
**Reproduction steps:**

1. Launch v2.6-9d5c699e18d174cb980e342a796ed828eeefcd18-head
2. Create an AKS cluster
3. I reproduced - I see the `Linux Admin Username` has text in a dark gray color. It's slightly darker than the `Cluster Resource Group` field but could indeed be mistaken for not having text filled in.

![image](https://user-images.githubusercontent.com/45179589/140099423-27c4133f-12cb-48e8-8ecc-d2ed98e676d2.png)

4. I tried with dark mode - dark mode works as expected the `Linux Admin Username` is a bright white compared to grey for the `Cluster Resource Group`
 
**Additional Info:**

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Validation Environment:**

Rancher version: v2.6-head `e322f8f` pulled at 11/22/21 10:11am Arizona time
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: AKS
Downstream K8s version: n/a
 
**Validation steps:**

1. Create an AKS cluster. Notice the fields are now darker and more apparent what is pre-fill text and what is hint text:

Here in this screenshot we can see that the Linux Admin Username with `azureuser` is black, making it very clear this is text that is pre-filled into this field for us (default text content). Notice the Cluster Resource Group field remains gray to indicate it's helper text.
![image](https://user-images.githubusercontent.com/45179589/142914251-ea083074-13fa-4c39-9d58-3b83a58f9a91.png)

Here in this screenshot we can see that the Network Policy dropdown/field is now black since it's filled in with `None`. Also, the DNS Prefix is gray to indicate it's hint text.
![image](https://user-images.githubusercontent.com/45179589/142914427-e99e30ef-68aa-4018-898e-b9d04e59bc3d.png)
