### ISSUE TITLE
gkev2 - should be able to edit "network policy"

### ISSUE THREAD

**Issue by prabalsharma** [rancher/dashboard#3941]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**

- master-618c9efe52856daff6a534097bd927b69f03f4e4-head
- Create GKE
- Select  Network Policy
- Network Policy Config (master only)
- Create --> Active
- Edit

**Result:**
UI lets users to disable / enable `Network Policy Config (master only)`, but not `Network Policy`. 
If a user disable `Network Policy Config (master only)`, without disabling `Network Policy` from GCP (Rancher UI doesn't allow it), then 
```
Googleapi: Error 400: Network policy addon cannot be removed until network policy has been disabled on the nodes., badRequest
```
Either, we make "network policy" editable or we should make "Network Policy Config (master only)" un-editable as well.

If we make "network policy" editable, then "Network Policy Config (master only)" should become editable only when user has disabled "network policy" (to avoid the error ^)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
- Installation option (single install/HA):

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`):

```
(paste the output here)
```

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `1f5852d`**

**Scenario 1**
- While creating a GKE cluster Select `Network Policy for Nodes` and `Network Policy Config (master only)` is also selected
- Deploy the cluster.
- Cluster comes up Successfully.

**Scenario 2**

- While creating a GKE cluster Select `Network Policy for Nodes` and `Network Policy Config (master only)` is also selected
- Unselect `Network Policy Config (master only)`
- Create cluster
- Cluster has an error `Waiting for API to be available:googleapi: Error 400: Network policy addon cannot be removed until network policy has been disabled on the nodes., badRequest`

The fix is working fine from UI
