### ISSUE TITLE
Mark Harvester as Tech Preview in the UI for v2.6.1

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/dashboard#4028]
For when we ship v2.6.1, we are planning to include the Tech Preview of Harvester. We will need to make a note on the UI that the Harvester integration with Rancher is in Tech Preview.

Will fill this out with more information when I get it.

**Comment by gaktive** [comment]
@Jono-SUSE-Rancher let us know if there's more info to work on this. We could replicate what was done during the RKE2 import.

**Comment by gaktive** [comment]
@Jono-SUSE-Rancher where would you like this message to appear in the UI? Would this be for both single and multi-cluster? This should be super simple to take care of but we just want to make sure we put the blurb in the right place (likely under Virtualization Management)

**Comment by richard-cox** [comment]
I've added the following to the Virtualization Management Clusters list
![image](https://user-images.githubusercontent.com/18697775/133636612-3f6bbfa0-f06f-4b8e-b87c-6ad263cd4e3f.png)

**Comment by slickwarren** [comment]
I think we should also put a similar note on the page shown to the user after creating an `import` cluster. The one that has the kubectl registration command to run on the cluster to import. Something like `Harvester clusters will be added to the **virtualization management** page, a Tech Preview feature` Otherwise, it might be difficult to find the imported harvester cluster(s) if not used to the new UI. 

<img width="1059" alt="Screen Shot 2021-09-20 at 2 30 42 PM" src="https://user-images.githubusercontent.com/16691014/134078627-50417bdd-998a-47ac-bbec-0ab3682b4551.png">

**Comment by richard-cox** [comment]
I've now covered the issue of no tech preview warning in the cluster management section in https://github.com/rancher/dashboard/issues/4244. That will require either additional work covered there or non-at all

**Comment by slickwarren** [comment]
on v2.6-head (223ec88):
* virtualization management is marked as `tech preview` in a dismissible notification at the top of its page -- pass

**Comment by slickwarren** [comment]
related to https://github.com/rancher/dashboard/issues/4249
