### ISSUE TITLE
Nodepool role suggestions misaligned in Ember Iframe

### ISSUE THREAD

**Issue by David-VTUK** [rancher/dashboard#4034]
In `v2.6.0-rc7`, provisioning an IaaS-based RKE1 cluster (vSphere, EC2, etc) displays the suggestion for node placement and count incorrectly:

In `2.6.0-rc7`:

![image](https://user-images.githubusercontent.com/5892615/130928051-29a8d461-ee64-45a7-8b3e-be58d1781f13.png)

in `2.5.9`:
![image](https://user-images.githubusercontent.com/5892615/130928195-0d056af2-3bb6-4165-97a6-a41682c3a5c9.png)

**Comment by davidnuzik** [comment]
**My checks PASSED**

**Reproduction Environment:**
Rancher version: v2.6.0
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: RKE1 DigitalOcean
Downstream K8s version: n/a - just launched create rke1 cluster form to check the issue

 
**Reproduction Steps:**
![image](https://user-images.githubusercontent.com/45179589/132413507-8395ecc9-7e87-4a74-8c4c-32c67ba2cdb3.png)

-----
 
**Validation Environment:**

Rancher version: v2.6-head `1718f1455` pulled at 9/7/21 12:04 pm Pacific
Rancher cluster type: single-node docker
Docker version: 20.10
 
Downstream cluster type: RKE1 DigitalOcean
Downstream K8s version: n/a - just launched create rke1 cluster form to check the issue
 
**Validation steps:**

1. Confirmed fixed in latest v2.6-head
![image](https://user-images.githubusercontent.com/45179589/132413562-d025a528-0a95-4f9b-b3cf-44d4902a5ae3.png)
