### ISSUE TITLE
Switch to Simplified Chinese, unable to create backup in Cluster Explorer

### ISSUE THREAD

**Issue by doremi8** [rancher/dashboard#4102]
**Rancher Server Setup**
- Rancher version: 2.5.9
- Installation option (Docker install/Helm Chart): helm

**Describe the bug**
1. Switch to Simplified Chinese
2. Failed to create a backup file in the Cluster Explorer

**Screenshots**

![002-1](https://user-images.githubusercontent.com/18179678/131837151-0d3e1f98-3274-4074-b195-1dc546b5766c.png)
![002-2](https://user-images.githubusercontent.com/18179678/131837150-8b5e564c-8afb-4aa6-8b8c-ec0193d2505e.png)
![image](https://user-images.githubusercontent.com/19684717/131838150-0de84651-fc0d-4212-84b3-a803ff3d763c.png)

If switch to English Can successfully create a backup

**Comment by nwmac** [comment]
I'm guessing this is due to a missing string - but should be checked. If so, use the en-us string for now and we can get that updated. The code should not error if a string is missing, so worth seeing if there is a simple fix for that.

**Comment by catherineluse** [comment]
The problem was that the Chinese translation string was incorrect. The translation string was `backupRestoreOperator.encryption`. The English version of that is just the word "Encryption" but the Chinese translation file had an error message with a variable in it. Because the string wasn't supposed to have a variable at all, it broke Rancher.

The solution is to replace the Chinese translation with the equivalent of "Encryption." @jiaqiluo does this change look right to you? https://github.com/rancher/dashboard/pull/4140/files

**Comment by jiaqiluo** [comment]
@catherineluse Thank you for providing the fix, it looks good to me.

**Comment by anupama2501** [comment]
verified on v2.6-head 1a57856

- Installed backup `v2.0.1-rc1` and changed the language to Chinese
- created a backup and backup was stored in S3
