### ISSUE TITLE
registry authentication -> created secret is not saving/being sent in request when using `configure advanced containerd mirroring and registry authentication options`

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4137]
**Rancher Server Setup**
- Rancher version:v2.6.0-rc9
- Installation option (Docker install/Helm Chart):helm
   - If Helm Chart, Kubernetes Info:v1.21.4
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):rke1
         Node Setup:HA
         Version:1.3.0-rc19
- Proxy/Cert Details:letsencrypt certs

**Information about the Cluster**
- Kubernetes version:any
- Cluster Type (Local/Downstream):downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):any

**Describe the bug**

when user tries to  use the registry option  `configure advanced containerd mirroring and registry authentication options` and create a secret, the secret is created but not sent in the request for creating the cluster. This sets the secret to `null`, therefore the registry isn't configured properly and the cluster is unable to come to active state

**To Reproduce**
 
* bring up a registry 
* configure the cluster to use a registry and select `configure advanced containerd mirroring and registry authentication options` 
  * add all valid options for this (add a registry authentication, create a secret, registry name, etc.)

**Result**
the request does not send the secret when creating the cluster

**Expected Result**

this should have the same behavior as when the user selects `pull images for images from a private registry` (this is the case if the user uses the same flow from the reproduce section, but selects a previously created secret)

**Screenshots**

**Additional context**

selecting a previously created secret _does_ send the request properly. 
parent ticket: https://github.com/rancher/rancher/issues/34224

**Comment by slickwarren** [comment]
on rancher v2.6-head (4375161):
I am still seeing the original issue:
* bring up a registry
* configure the cluster to use a registry and select configure advanced containerd mirroring and registry authentication options
* add all valid options for this (add a registry authentication, create a secret, registry name, etc.)

Result
* the request does not send the secret when creating the cluster

**Comment by catherineluse** [comment]
I think it is okay for the secret to be null if you set up a mirror so that `registry1.com` redirects to `registry2.com` and then create credentials for `registry1.com`. Because when you set up a mirror, registry1.com would never be used because you are actually pulling from registry2.com and would need registry2.com's credentials.

If you create a mirror to redirect from `registry1.com` to `registry2.com`, then create credentials for `registry2.com`, the secret for registry2.com is created and associated with the registry1.com endpoint. So while it is a little bit odd, I think it is still the expected behavior.

I think it might help to clarify this in the info tip for the registry credentials and say "If you add a mirror for the registry, the credentials for the mirror will be used for the mirrored registry" or something to that effect.

**Comment by slickwarren** [comment]
on rancher v2.6-head (3dbea4c):
This issue is no longer occurring:
* bring up a registry
* configure the cluster to use a registry and select configure advanced containerd mirroring and registry authentication options
* add all valid options for this (add a registry authentication, create a secret, registry name, etc.)

Result
* the request for creating the secret is sent; secret is applied to the cluster
