### ISSUE TITLE
Overview UI issues

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#414]
- [x] Overview menu should be on top
- [x] Overview menu item is always highlighted
![image](https://user-images.githubusercontent.com/11514927/77466522-a3aa7c00-6dc7-11ea-8eb6-e9c8448a3ad6.png)

- [x] Fix alignment of top bar info
![image](https://user-images.githubusercontent.com/11514927/77465592-1fa3c480-6dc6-11ea-936b-a52e91daefed.png)

- [x] Remove Type from Event's table.  The type will always be event :)
![image](https://user-images.githubusercontent.com/11514927/77465783-714c4f00-6dc6-11ea-8822-1821bcc6b4f6.png)

- [x] Event's Last Seen column title should be date
- [x] Event table should be sorted by date by default.  Last event should always be on top.

![image](https://user-images.githubusercontent.com/11514927/77465946-b53f5400-6dc6-11ea-9b5b-5ad9f88a0a6f.png)

**Comment by vincent99** [comment]
- [ ] Provider: Doesn't have nice versions of the standard providers (shows `Rancherkubernetesengine`)
- [ ] Created: Needs an "ago" suffix (add an option to LiveDate for one)

- Usage/reserved:
  - [ ] Space is a bit tight here so only show the unit once: `1.51 of 4.03G Reserved` (`addSuffix=false`)
  - [ ] All the values in a section should be in the same units, i.e. not `10K of 4G Reserved`, `50M of 4G Used`.  Set `minExponent` and `maxExponent` on all to the `exponentNeeded()` of the capacity (since that's the biggest value).
  - [ ] Memory values are always in units of powers of 2, `increment` should be 1024.
  - [ ] The ProgressBars are always showing full unless the value is 0 (mismatch expecting 0-1 vs 0-100%?)
  - [ ] The data disappears sometimes and starts showing all zeros until next refresh.. If you already had data and get none, keep what's already shown
  - [ ] These are mostly not the right info.  ±error handling and getting the data, they should be:
```
${cluster.status.requested.memory} of ${cluster.status.allocatable.memory} Reserved
${ sum of node metric usages } of ${cluster.status.capacity.memory } Used
```

- Events:
  - [ ] Type column is useless, it's always Event
  - [ ] "Name" is also not useful, except as a link to view as yaml.  Show regular action menu on the right instead?
  - [ ] Object ("Node") is not useful without also showing which one it is (involvedObject.name).  Should also link to it.
  - [ ] Use LiveDate formatter for the last seen (there is a "First seen" and a "Last seen", so I don't necessarily mind it being labeled explicitly vs "Date")

**Comment by tfiduccia** [comment]
Lauren, Wes, Vincent and I discussed:
1.  Add node count to info box at top.
2.  Change node section to say "Unhealthy Nodes"
3.  Only show node not in Active state in node section, if no nodes say "All nodes Active"
4.  Change OPA section and add "Violations" to end of title
5.  Only show OPA constraints that have violations, if no violations say "No violations"

**Comment by tfiduccia** [comment]
relating to Vincents comments:
VUE:
The info from Rancher Cluster page should match in our Overview page.  Here is info from both:
![image](https://user-images.githubusercontent.com/11514927/77590543-2e17dc00-6eab-11ea-8d72-ed89e00eb7d1.png)
RANCHER:
![image](https://user-images.githubusercontent.com/11514927/77590558-3a9c3480-6eab-11ea-857c-c8077bf0b6e4.png)

**Comment by vincent99** [comment]
@westlywright For "overview" being highlighted all the time, why don't you just move it to a overview.vue so that it's a different route than the main cluster index, and have cluster index redirect.  That's easier than trying to solve whether or not the active-link should be highlighted or not for this special case.

**Comment by tfiduccia** [comment]
Fixed
