### ISSUE TITLE
[2.6] New project names are downcased

### ISSUE THREAD

**Issue by ineus** [rancher/dashboard#4148]
**Rancher Server Setup**
- Rancher version: 2.6.0

**Describe the bug**
I have a number of projects created in previous versions of Rancher 2. Most of them are two-words long, like `MyProject`.
In 2.6 I can no longer create such project names. It allows me to enter such a name, but neither uses the exact name, nor reports a validation error. Instead it silently downcases the name, converting it to `myproject`, which is definitely not something I expect.

**Expected Result**
Either it allows me to use the name `MyProject`, or it shows a validation error. No silent/implicit conversion happens without notifying the user.

**Comment by vincent99** [comment]
For most types the name is the k8s `metadata.name` and the rules are very restricted for those (lowercase a-z, 0-9 and hyphen basically).  So common transforms (lowercasing and space->hyphen) are done automatically because that's the only reasonable thing you'd do anyway.

This particular type is a Rancher one where the k8s name is generated (`p-xxxxx`) and the displayed name is a separate field that can be anything.  So it doesn't need to go through that transform and should be disabled.

**Comment by sowmyav27** [comment]
**Reproduced the issue on 2.6.0**
<img width="760" alt="Screen Shot 2021-09-17 at 4 17 51 PM" src="https://user-images.githubusercontent.com/26032343/133862935-46c512fb-6fa0-4498-93dc-910f540c64b8.png">

**On 2.6-head commit id: `1a57856`**

- Create a cluster RKE1 and create a project `TestProject-2`
- Project `TestProject-2` is created.

<img width="1078" alt="Screen Shot 2021-09-17 at 4 17 04 PM" src="https://user-images.githubusercontent.com/26032343/133862918-29f6aa3c-350f-46fd-8c9b-446f5b713078.png">
