### ISSUE TITLE
Local cluster visible in Cluster Explorer when hide-local-cluster set to true

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4193]
Spotted in 2.5.8.

Issue description:
When the `hide-local-cluster` setting is set to true, the local cluster will not appear in the Cluster Manager UI, however it is appearing in the Cluster Explorer.

Business impact:
Tenants, who are restricted admins, should not be able to modify the local cluster and it's better if they don't see it at all.

Repro steps:

1. run `kubectl patch settings.management.cattle.io hide-local-cluster --type merge -p '{"value":"true"}'`

2. Go to the Cluster Explorer and click the drop down in the top right corner to select the local cluster.

Actual behavior:
User can see local cluster in Cluster Explorer. User cannot see local cluster in Cluster Manager.

Expected behavior:
User should not be able to see local cluster in Cluster Explorer or Cluster Manager.

**Comment by nwmac** [comment]
@gaktive Has anyone validated this in 2.6.x ? Or is this an ask for a 2.5.x fix?

In 2.6.0 the cluster choose in the top-right is no longer present.

**Comment by gaktive** [comment]
Pinged @SheilaghM on the 2.5.x aspect. 
@sowmyav27 was this tested during 2.6.0?

**Comment by markusewalker** [comment]
Verified this has been fixed in v2.6-head https://github.com/rancher/rancher/commit/6c12bee2d0bee16a2854df5471aaa0cdee5b9bf1.

**Verification Steps**
1. Downloaded `kubeconfig` file and applied to local client machine (performed testing using local cluster's kubectl shell as well).
2. Ran command `kubectl patch settings.management.cattle.io hide-local-cluster --type merge -p '{"value":"true"}'`.
3. Refreshed the page and verified the local cluster is no longer appearing in the home page, cluster management and cluster explorer:

_**Home Page**_

![image](https://user-images.githubusercontent.com/52591819/164059816-024420d4-d439-4be5-9d43-9ae50f0d47bd.png)

_**Cluster Explorer**_

![image](https://user-images.githubusercontent.com/52591819/164059876-a3f92627-47ec-4a2c-8e75-a28b1b42aac5.png)

_**Cluster Management**_

![image](https://user-images.githubusercontent.com/52591819/164059934-89562558-6ed5-46c5-a990-972bfbdabfd1.png)

4. Ran command `kubectl patch settings.management.cattle.io hide-local-cluster --type merge -p '{"value":"false"}'`.
5. Refreshed the page and verified the local cluster once more appears in the home page, cluster management and cluster explorer:

_**Home Page**_

![image](https://user-images.githubusercontent.com/52591819/164060236-0e6807bf-5c9b-4d15-88d3-13bb03a54139.png)

_**Cluster Explorer**_

![image](https://user-images.githubusercontent.com/52591819/164060309-cab488b9-f304-45d2-8551-05ce79704807.png)

_**Cluster Management**_

![image](https://user-images.githubusercontent.com/52591819/164060358-2f9cee73-282a-4a77-a26a-b2752d6a3bda.png)

6. Created user accounts for roles: restricted administrator, standard user, user base. With the value set to false, logged into each account and verified none of these accounts can see the local cluster. This is expected behavior.
