### ISSUE TITLE
[Bug] Reading agent environment vars from file does not work

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#4196]
Rancher 2.6.1-RC1

1. Given the following txt file, named "proxy-vars.txt":
```
HTTP_PROXY=http://USERNAME:PASSWORD@10.0.1.1:8080/
HTTPS_PROXY=https://USERNAME:PASSWORD@10.0.0.1:8080/
NO_PROXY=master.hostname.example.com,10.1.0.0/16,172.30.0.0/16
```
2. Navigate to Cluster Manager -> Create RKE2 Cluster (any provider)
3. Scroll to Agent Environment Vars and select "Read from file"
4. Select the txt file

Result:

The content of the txt file is not correctly parsed into key/value pairs:

<img width="1330" alt="Screenshot 2021-09-17 at 15 44 21" src="https://user-images.githubusercontent.com/3813921/133792943-173119ce-f12d-4b2b-a4c7-182b49cf5726.png">

**Comment by richard-cox** [comment]
@Sean-McQ Is there a PR related to this that needs to be reviewed?

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Validation Environment:**

Rancher version: v2.6-head `e322f8f` pulled at 11/22/21 10:11am Arizona time
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

1. Create any RKE2/K3S cluster.
2. On the form, go to the Cluster Configuration section > Agent Environment Vars
3. Create a text file locally on disk "proxy-vars.txt" with the following contents in the file:
```
HTTP_PROXY=http://USERNAME:PASSWORD@10.0.1.1:8080/
HTTPS_PROXY=https://USERNAME:PASSWORD@10.0.0.1:8080/
NO_PROXY=master.hostname.example.com,10.1.0.0/16,172.30.0.0/16
```
4. Click the "Read from file" button and upload the "proxy-vars.txt" file when prompted.
5. Notice, this now works correctly. I no longer experience the issue as reproduced earlier here https://github.com/rancher/dashboard/issues/4196#issuecomment-949766160
The file is parsed properly and we now have three entries each with proper key=value pairs. There is one extra entry but this seems to be benign.
![image](https://user-images.githubusercontent.com/45179589/142908105-a2d91dcc-084a-46b6-ab4a-cc2ba9c03224.png)

And, when I submit the form to create the cluster, the POST to provisioning.cattle.io.clusters looks normal, except a benign additional entry is sent. I created a separate bug for that here:  https://github.com/rancher/dashboard/issues/4619
![image](https://user-images.githubusercontent.com/45179589/142908344-d68a3015-f680-44f2-ad6a-122d530e44b9.png)

This appears to be because the UI is creating an additional entry when reading in the text file.
 
**Additional Info:**
