### ISSUE TITLE
UI - Add Workload - UI allows user to submit unvalidated text in Name and get large error on submit

### ISSUE THREAD

**Issue by jmcsagdc** [rancher/dashboard#4235]
**Rancher Server Setup**

 - Rancher version: ef760ce ( v2.6-ef760ce7606af9ef589cc1dc89253acc27609b5b-head )
 - Installation option (Docker install/Helm Chart): Docker in DO
 - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
 - Proxy/Cert Details: self-signed

**Information about the Cluster**

 - Kubernetes version: v1.21.5-rancher1-1
 - Cluster Type (Local/Downstream): Downstream
 - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): EC2

**Describe the bug**

When adding a Workload, the user can add unvalidated text in the Name field and get a huge (5 lines) error containing regex back in the UI on submit.

**To Reproduce**

1. In a browser, go to a running 2.6 Rancher
2. Log in if you haven't already
3. Go to Hamburger > Home and select an existing Cluster
4. In the left side menu, click Workload
5. Click Create on the right side of page
5. Page reloads to Deployment: Create page; click Deployment button in body of page
5. Page reloads to Deployment: Create page with options to specify; add Name "one " (this is the word "one" with a space after it
8. Use Container Image: nginx:latest
9. Leave all other stuff as defaults.
9. Click the Create button on bottom of page

**Result**

The page reloads loads with what looks like an RFC spec containing a description of allowable name formats (see screenshot) and a regex.

**Expected Result**

I would expect either:
 - the page ghosts the Create button at the bottom until the content is validated,
 - or the content of the bad field should be displayed to the user with a simple message like "Only alphanumeric characters are allowed in the Name field".  In my opinion, having 5 lines of fairly low-level text like this may be more confusing:

Here is the most illuminating part of the actual error displayed: "Deployment.apps "one " is invalid: [metadata.name: Invalid value: "one ": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character[remaining removed]"

![regex-in-error](https://user-images.githubusercontent.com/15971368/134076804-bb4889fc-3ee7-41c1-9c30-451ece69d19f.png)

**Comment by MSpencer87** [comment]
_Reopened_ on `2.6.7-rc1`

While the added indicator is successfully triggered upon the addition of invalid charcaters or spaces, the behvaior can be improved so that the user cannot still trigger the error message unncessisarily by selecting the Create button. My suggestion is the that Name field mimic the behavior of the Container Image field, which removes a trailing space, to prevent the user from triggering the error message and keep the form's behaviors consistent.

The GIF is showing that the Cluster Image field removes a trailing space while the Name field allows them to aggregate.
![TrailingSpaceRemoved](https://user-images.githubusercontent.com/6477538/178618543-43fa9ce5-3f0e-4082-9266-1f7cff4bf96b.gif)



**Steps To Reproduce**

1) Bring up HA Rancher on 2.6.5
2) Select the local or downstream cluster
3) From the Main Menu, select Workload->Jobs and select Create
4) Enter "one " (_this is the word "one" with a space after it_) into the Name field (No Validation seen on Name field)
5) Enter "nginx:latest" inot the Container Image field
6) Select the Create button to trigger the following error:
`Job.batch "one " is invalid: [metadata.name: Invalid value: "one ": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "one ": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), spec.template.labels: Invalid value: "one ": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]`

**Steps for Validation**
1) Bring up HA Rancher on 2.6.7-rc1
2) Select the local or downstream cluster
3) From the Main Menu, select Workload->Jobs and select Create
4) Enter "one " (_this is the word "one" with a space after it_) into the Name field (Field validation indicator is present with error message on hover, user can still select Create)
5) Enter "nginx:latest" inot the Container Image field
6) Select the Create button to trigger the following error:
`Job.batch "one " is invalid: [metadata.name: Invalid value: "one ": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "one ": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?'), spec.template.labels: Invalid value: "one ": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]`

Field validation indicator properly displays error message pertaining to use of Space:
![Screen Shot 2022-07-12 at 3 20 41 PM](https://user-images.githubusercontent.com/6477538/178618589-cb3374fd-fc32-4f40-962d-9e947cdcd475.png)


User is still able to trigger Error message with field validation indicator present:
![Screen Shot 2022-07-12 at 3 57 02 PM](https://user-images.githubusercontent.com/6477538/178618649-259862a1-f2aa-45e9-b7f0-702520734125.png)
