### ISSUE TITLE
Add Validation to form fields going forward

### ISSUE THREAD

**Issue by davidnuzik** [rancher/dashboard#4238]
**Summary:**

There are many fields in the Vue UI that we do not validate. I propose we programmatically try to validate fields as we implement/design new areas when/where reasonable.

-----

**Environment:**
Rancher version: v2.6-head `ba43472` pulled at 9/21/21 10:43am
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a

**Details:**
- Various fields today don't validate input of the fields. The field may be wanting for just a number or alphanumeric charatcters but not actually validate. The field/form will allow the user thus to submit and cause issues which can break things.
- I propose going forward we try to validate most fields when reasonable. That is to say I suggest using best judgement and only validating fields when we are 100% certain what types of data should be passed.

**Specific Examples:**
It would require extensive work to try to manually identify all the areas we don't do validation. I'm sure if I had time I could find many more than are listed below.

Today we don't validate (as of 9/21/21) the following fields.

apps.Deployment > Security Context > Filesystem Group
![image](https://user-images.githubusercontent.com/45179589/134243666-0170ee51-34db-46bd-952e-c87d4a094eea.png)
![image](https://user-images.githubusercontent.com/45179589/134243894-ef69937e-6376-4de0-bc83-c0f635c1273d.png)

- I should not be able to enter spaces
- This should only take integers (1-30 I think? not 100% sure)
- Note: the form will submit but no securityContext gets passed in the POST

apps.Deployment > Security Context > Add/Drop Capabilities drop downs
![image](https://user-images.githubusercontent.com/45179589/134244246-c8d3ce85-193d-45be-a475-2ee75c007607.png)
- Dropdowns let you enter text - is this something we could prevent? if text does not match entries/options then remove it when user clicks off the field? Not sure if this one is easy or a reasonable ask.

**Comment by gaktive** [comment]
@Sean-McQ once you wrap up work here, to help QA with testing, can you highlight certain areas or pages that should be focused on? The feeling is that this change is wide in scope so narrowing down where to look will help (hopefully) so that they don't have to look everywhere.

**Comment by nwmac** [comment]
@gaktive Why is this a release blocker? I don't think this will go in for 2.6.3 dues to its impact on the code.

**Comment by gaktive** [comment]
@nwmac this was something I wanted to ensure was on QA's radar, hence the label. If it's still in progress, then pushing this out is fine, especially based on code impact.

**Comment by brandonsuse** [comment]
@AndrewHoffmanQA  This ticket should be fairly easy to knock out. You basically just need to make sure they are validating inputs into the fields specified in this ticket. Let me know if you need assistance with this one though. CC: @ronhorton

**Comment by AndrewHoffmanQA** [comment]
examples provided have been tested

testing result:

**Field 1**
Deployment > Security Context > Filesystem Group
-I should not be able to enter spaces-- **passed**
-This should only take integers (1-30 I think? not 100% sure)-- **failed**
          - there is no cap on the integer limit.
          - users can type the letter 'e' -- potentially related to the lack of integer cap, which allows users to enter numbers so large that when auto formatted, include 'e' (attached pic)

![image.png](https://zube.io/files/rancher/b00aeed9a4c303af47f3dd4282adf412-image.png)

**Field 2**
requirements are pretty open to interpretation. in 2.6.7-rc1 this is the behavior I witnessed.
- user can type in the 'add capabilities' 
- when the user types a string in the dropdown field that does contain any of the selectable options, those options are displayed
- when the user types a string in the dropdown field that doesnt reflect any of the selectable options, all options are hidden
![image.png](https://zube.io/files/rancher/e6e830be259e43cbefce3950c4a2896d-image.png)

![image.png](https://zube.io/files/rancher/9c81326c58df1a3b7a5a4d3256e08ec7-image.png)

**Comment by AndrewHoffmanQA** [comment]
per discussion with @Sean-McQ , the scope of this ticket and its testing will be limited to the validation of these fields and the restrictions described in the spreadsheet. 

![image](https://user-images.githubusercontent.com/89030218/179025490-a6cc2bb1-aeca-4e3a-8315-a27ecd0a5b74.png)


link to cronjob hyperlink- https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html#CronExpressions

**Comment by Sean-McQ** [comment]
Container Image is marked as required by default but only with the red '*' in the field. The designed behavior for the "required" validator is that it only triggers if the user focuses on the field and then blurs their focus on it. The tab notification of an error is designed to only show if the tab is not currently active so that also acts as designed.

Replica should probably provide feedback to only allow integers but I don't think it breaks anything if you submit a decimal. I can put in a small PR to add that in in the near future but for now it makes sense to satisfy the strict requirements of the ticket as written so we can ensure it's merged in for the upcoming release.

**Comment by sowmyav27** [comment]
Reopening so the latest fixes can be tested.

**Comment by AndrewHoffmanQA** [comment]
@Sean-McQ passing this work item back. 

this bug is still persisting "'node port- target port'-users can add letters and special characters" I was able to create a NodePort with a string applied to the target port field. (see screenshots) , the rest of the scope of the ticket passes

I tested this on an HA server
rancher v2.6.7-rc5
k8- v1.24.2+rke2r1

screenshot 1
![image.png](https://zube.io/files/rancher/beb1f7b4faf62abeb7b3b631a785a054-image.png)

screenshot 2

![image.png](https://zube.io/files/rancher/c6bc375cd743cb91b7aede042921b690-image.png)
