### ISSUE TITLE
Users are able to import harvester clusters via the Cluster Management section

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4244]
### Distinct Problems
This pattern has brought up a number of UX/Bugs

Bugs
- Clusters imported via the Cluster Management section are not correctly filtered out in the Cluster Management list view (https://github.com/rancher/dashboard/issues/3467#issuecomment-924169979)
  - Caused by a missing `cluster.harvesterhci.io` label which is only applied during the Virtualization Management import process

UX Issues
- Users can import their cluster via Cluster Management however, when working, it's filtered out from the list view (user cannot see newly created cluster) (https://github.com/rancher/dashboard/issues/3467#issuecomment-924049150)
- In cluster management users are not warned that the harvester feature is in tech preview (https://github.com/rancher/dashboard/issues/4028#issuecomment-923332912)

### Other considerations
- Currently users can only _create_ a harvester cluster using the harvester driver from the Cluster Management section
- In all worlds we can never stop the user from going to Cluster Management section, creating a generic cluster to import to and running the `apply` commands to their harvester cluster

Ignore Proposed Solutions (based on incorrect assumption on create/import harvester features)
----------------------------------------
### Proposed 2.6.1 (Harvester Beta) Solution
Docs/Guidance is updated such that
- Users are directed to the Virtualization Management page to import their Harvester Cluster. Importing via the Cluster Management will not be supported
- Users are directed to the Cluster Management page when creating their Harvester Cluster, and told via docs to switch to Virtualization Management page once complete 

### Proposed post 2.6.1 Solutions 
We think both import and create should only happen in a single location. So either...

1. Import and Create are only allowed in the Virtualization Management Section
   - Create flow would need to be created/enabled in this section
   - This supports where we'd like to go for other types of 'cluster instance (epinio, etc)
      - pattern allows for a fully customisable create/import/register 'instance' process for other secondary cluster types
2. Import and Create are only allowed in the Cluster Management Section
   - The import flow would need to be removed from Virtualization Management, so the list page purely becomes a way to dive into a cluster
   - There should be a specific 'tech preview' warning for both create and import (this could be optionally shown on the clusters list?)
   - There should be a customer 'import' option for harvester which would allow the `cluster.harvesterhci.io` label to be applied
   - The Cluster Management cluster list would need to support showing different types of cluster (kube, harvester, epinio, etc)
     - Could be done with a list filter component 
     - Needs to be sensitive of feature flags

**Comment by janeczku** [comment]
> We think both import and create should only happen in a single location.

I agree that importing a Harvester cluster with the goal of enabling VM management should only happen in a single location, either Cluster Management section or Virtualisation Management section.
If we decide to have the import in the VM section, then while we can't prevent a user from importing the Harvester cluster as "generic Kubernetes cluster" in the Cluster Manager, we would simply treat such imported cluster as any other generic cluster and not enable VM management for example.

I don't agree that import and create need to be in the same location because they refer to entirely different management functionalities:

`Import` refers to importing the the "root" Kubernetes cluster of the Harvester HCI with the goal of managing VM workloads in Rancher.

`Create` does not refer to the "root" cluster of Harvester HCI but instead refers to creating a RKE or RKE2 cluster using  Harvester as the infrastructure provider. It is not different from creating clusters on vSphere or AWS and should always happen on the Cluster Management section.

**Comment by yasker** [comment]
> ### Distinct Problems
> This pattern has brought up a number of UX/Bugs
> 
> Bugs
> 
> * Clusters imported via the Cluster Management section are not correctly filtered out in the Cluster Management list view ([Harvester Integration - Filtering Harvester clusters #3467 (comment)](https://github.com/rancher/dashboard/issues/3467#issuecomment-924169979))
>   
>   * Caused by a missing `cluster.harvesterhci.io` label which is only applied during the Virtualization Management import process
> 
> UX Issues
> 
> * Users can import their cluster via Cluster Management however, when working, it's filtered out from the list view (user cannot see newly created cluster) ([Harvester Integration - Filtering Harvester clusters #3467 (comment)](https://github.com/rancher/dashboard/issues/3467#issuecomment-924049150))
> * In cluster management users are not warned that the harvester feature is in tech preview ([Mark Harvester as Tech Preview in the UI for v2.6.1 #4028 (comment)](https://github.com/rancher/dashboard/issues/4028#issuecomment-923332912))
> 
> ### Other considerations
> * Currently users can only _create_ a harvester cluster using the harvester driver from the Cluster Management section

We need to clarify some terminologies first. User cannot `create a Harvester cluster` in Rancher, just as you cannot `create a VMWare ESXi cluster`. In the Cluster Management (CM), `Create` means create a Kubernetes cluster (RKE1/RKE2) using Harvester as the cloud provider.  Harvester cluster cannot be `created` since users need to setup the Harvester cluster separately from the Rancher by installing ISOs into the baremetal nodes.

> * In all worlds we can never stop the user from going to Cluster Management section, creating a generic cluster to import to and running the `apply` commands to their harvester cluster

Yes, this is something we don't really have control over. So ideally we should be able to identify the imported cluster as Harvester or not, rather than just adding labels for the cluster imported from the `Virtualization Management` page.
> 
> ### Proposed 2.6.1 (Harvester Beta) Solution
> Docs/Guidance is updated such that
> 
> * Users are directed to the Virtualization Management page to import their Harvester Cluster. Importing via the Cluster Management will not be supported
> * Users are directed to the Cluster Management page when creating their Harvester Cluster, and told via docs to switch to Virtualization Management page once complete

I think two words are confused here. User will need to go to CM page for `creating` RKE1/RKE2 based Kubernetes cluster. If they `import` a Harvester cluster, they will need to access it via the VM page.
> 
> ### Proposed post 2.6.1 Solutions
> We think both import and create should only happen in a single location. So either...
> 
> 1. Import and Create are only allowed in the Virtualization Management Section
>    
>    * Create flow would need to be created/enabled in this section
>    * This supports where we'd like to go for other types of 'cluster instance (epinio, etc)
>      
>      * pattern allows for a fully customisable create/import/register 'instance' process for other secondary cluster types
> 2. Import and Create are only allowed in the Cluster Management Section
>    
>    * The import flow would need to be removed from Virtualization Management, so the list page purely becomes a way to dive into a cluster
>    * There should be a specific 'tech preview' warning for both create and import (this could be optionally shown on the clusters list?)
>    * There should be a customer 'import' option for harvester which would allow the `cluster.harvesterhci.io` label to be applied
>    * The Cluster Management cluster list would need to support showing different types of cluster (kube, harvester, epinio, etc)
>      
>      * Could be done with a list filter component
>      * Needs to be sensitive of feature flags

I would think `import` a Harvester cluster should work in both places (VM and CM, because we don't have a way to restrict user from do it in the CM ATM), and `create` a Kubernetes cluster using Harvester cloud provider will only be available in the CM to make is consistent.

I think we need a call to clarify all the details.

**Comment by yasker** [comment]
> > We think both import and create should only happen in a single location.
> 
> I agree that importing a Harvester cluster with the goal of enabling VM management should only happen in a single location, either Cluster Management section or Virtualisation Management section.
> If we decide to have the import in the VM section, then while we can't prevent a user from importing the Harvester cluster as "generic Kubernetes cluster" in the Cluster Manager, we would simply treat such imported cluster as any other generic cluster and not enable VM management or other Harvester specific features.

I don't think it's a good idea to treat it as a generic cluster if user imported it in Cluster Management. What if user want to use it as a Harvester cluster? Also, we don't want to recognize Harvester cluster as a Kubernetes cluster in Rancher per our previous discussion. 

I'd rather to have some mechanism to allow the Harvester cluster even imported from CM can be recognized as a Harvester cluster.
> 
> I don't agree that import and create need to be in the same location because they refer to entirely different management goals and objects:
> 
> `Import` refers to importing the "root" Kubernetes cluster of the Harvester HCI with the goal of managing VM workloads in that root cluster.
> 
> `Create` does not refer to the "root" cluster of Harvester HCI but instead refers to creating RKE or RKE2 clusters running on Harvester as the infrastructure provider with the goal of managing Kubernetes workloads. It is not different from creating clusters on any other IaaS provider such as vSphere or AWS and should therefore always happen on the Cluster Management section.
> 
> In that sense import and create could definitely live in different sections.

**Comment by nwmac** [comment]
Okay - so I think I understand this now.

(VMMgmt = Virtualisation Mgmt, CMgmt - Cluster Mgmt)

From VMMgmt, importing will import a Harvester cluster. This is all good and works well.

From CMgmt, creating a cluster using the Harvester Node driver, creates a k8s cluster on Harvester infrastructure - this will appear as a k8s cluster - all good.

From CMgmt, using the "import existing" cluster feature will import a k8s cluster. If you run the commands on the harvester cluster, it will get imported as a k8s cluster. This makes sense, as Harvester is a k8s cluster. There is no easy way to prevent this - I suggest for 2.6.1, we add a banner to the CMgmt cluster import that is shown when the Harvester feature flag is enabled, that makes the user aware that if they are importing a Harvester cluster, they probably want to do that from VMMgmt.

**Comment by richard-cox** [comment]
Example of banner is in https://github.com/rancher/dashboard/pull/4269 (only shows in create mode, if the harvester feature flag is enabled and if the user has not previously dismissed it)

**Comment by yasker** [comment]
@nwmac I do have concerns over the following part
> From CMgmt, using the "import existing" cluster feature will import a k8s cluster. If you run the commands on the harvester cluster, it will get imported as a k8s cluster. This makes sense, as Harvester is a k8s cluster. There is no easy way to prevent this - I suggest for 2.6.1, we add a banner to the CMgmt cluster import that is shown when the Harvester feature flag is enabled, that makes the user aware that if they are importing a Harvester cluster, they probably want to do that from VMMgmt.

As I mentioned, we will face problems if the user wants to use it as a Harvester cluster.
Also previously agreed we think we shouldn’t expose a Harvester cluster as a k8s cluster in Rancher at all since it opens door to the user to use the Harvester cluster as a k8s cluster, which is against our designated usage of Harvester.
We probably don’t have time to address it in v2.6.1, though I think we have to recognize the Cluster Mgmt imported Harvester cluster in the GA/2.6.2 release.

**Comment by nwmac** [comment]
Agreed - I don't think there's an easy way to prevent the import - but if we focus on 2.6.1, if there anything we need to do beyond what we have?

**Comment by yasker** [comment]
@nwmac I think a banner is enough for v2.6.1. Do you think we can repurpose this issue to track `make sure Harvester cluster imported from Cluster Management is recognized in Virtualization Management page`? Or we should create another issue to track it for v2.6.2.

**Comment by vincent99** [comment]
The UI can't solve that problem; it _is_ a k8s cluster and it is unknown what's in it until after it is registered. (And you can install harvester into a cluster after it's already been registered.)

There should be a controller or something maintaining this label based on what _actually_ exists in the cluster after the agent is running.  Not UI trying to steer the user to guess which of two slightly different versions of the same page they should use with banners.

**Comment by yasker** [comment]
@vincent99 I see, thanks. @richard-cox where is the label used to identify a Harvester cluster? I suppose it's a label on a certain CR. I can create an issue to address it in Rancher backend instead of the UI adding the label from the Virtualization Management page.

**Comment by richard-cox** [comment]
This is the label mentioned in the bug at the top, `cluster.harvesterhci.io`. From what i can tell it's the only difference in `import cluster` between Virtualization Management and Cluster Management and it's what the frontend uses to determine if a cluster is a harvester one.

I'd recommend keeping this issue as is for QA to test the banner change and create a separate one for the `rancher/rancher` work.

**Comment by deniseschannon** [comment]
I haven't read this entire thread thoroughly, but @yasker we should talk with PM on expected behavior as I think as an end user, if I imported a Harvester cluster through cluster manager, I would expect it to show up in cluster Manager (not Virtualization management) as that it where I am.


I also commented on the backend issue, but we shoul dhave a meeting to discuss as this was never the intent or plan to have it automatically move from one UI management screen to another. 

https://github.com/rancher/rancher/issues/34880#issuecomment-926209763

**Comment by richard-cox** [comment]
Note for QA
- As of https://github.com/rancher/dashboard/pull/4269 there's now a warning in Cluster Management / Import Cluster to use the Virtualisation Management import instead. That should address the problems listed in this issue's description in the 2.6.1 time frame
- There are further discussions in https://github.com/rancher/rancher/issues/34880 on where and how a harvester cluster can be imported for post 2.6.1

**Comment by slickwarren** [comment]
on v2.6-head(0dd1ce6)
* warning is shown on `cluster management` -> `import` cluster page, with a link to `virtualization management` -- pass
* based on the linked issue above, I think this issue is good to close with the current behavior for 2.6.1
