### ISSUE TITLE
Editing a Global Role as an admin via YAML fails

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4265]
- This is `blocked` (...)
- We should investigate other places where this might apply and hide the edit yaml feature given (i think) PUT permissions

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6-head Commit ID f487c88`

The original issue was logged as `editing a global role as an admin via YAML fails.` This was corrected by Remove Edit as Yaml button for blocked-PUT resource methods #4481

`Original issue is negated by removing the `Edit YAML` function and creating a `View YAML` option. There is no longer a `save` button so the user cannot click `save` - which was the use case that triggered the error. 

1. Click on Hamburger
2. click on `users & authentication`
3. click on `roles`
4. click the three dots next to an active role and select `View yaml`
 **No longer a SAVE button since the user can only view*
<img width="987" alt="Screen Shot 2021-11-17 at 5 01 42 PM" src="https://user-images.githubusercontent.com/89212856/142289596-54d93446-c3b4-4267-a214-271de4d93092.png">
*
