### ISSUE TITLE
2.6-head | Can't add a port type clusterIP to a deployment created in the old UI

### ISSUE THREAD

**Issue by sgapanovich** [rancher/dashboard#4280]
**Rancher Server Setup**
- Rancher version: v2.6-ba4347297ef8984f629650979a1b3a470592f4da-head
- Installation option (Docker install/Helm Chart): Docker Install
- Proxy/Cert Details:n/a

**Information about the Cluster**
- Kubernetes version: v1.21.5
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Provisioned RKE cluster in EC2

**Describe the bug**

Can't add a port type clusterIP to a deployment created in the old UI

**To Reproduce**
 

- Navigate to the old UI
- Go to workloads
- Click "Deploy" (type: deployment, "Scalable deployment of")
- Add a port (type: clusterIP)
- Click "Launch" 
NOTE: at this point you have a deployment created and a service created 

![new](https://user-images.githubusercontent.com/40282141/134260071-e4579c21-6b33-4588-95dc-c2b09725574d.png)

- Navigate to the new UI
- Select your cluster
- Go to Workloads 
- Go to Deployments 
- Select "Edit Config" next to your deployment 
- Add a port
type: clusterIP

![add port](https://user-images.githubusercontent.com/40282141/134257868-3c0f269b-9cbb-491c-a3b8-f51c1b69cce6.png)
- Open Devtools so you can see what request payload the UI sends 
- Click "Save"
NOTE: UI sends both ports

<img width="690" alt="request payload" src="https://user-images.githubusercontent.com/40282141/134257884-916dc08e-fc99-422f-b887-336bb378b5dc.png">

**Result**
The newly passed port is not added to the service 

![not added](https://user-images.githubusercontent.com/40282141/134258078-e5824e05-a727-4044-8f09-8c86bcee20ee.png)

**Expected Result**

It is expected that the clusterIP will have another port added 
There is a workaround if you
- Go to workloads again
- Go to Deployments 
- Click "Edit Config" next to your deployment 
You will notice that the dropdown was reset to “Do not create a service”
 
![was not added](https://user-images.githubusercontent.com/40282141/134258341-edbd9147-9ad6-4960-9e8c-3003009a6026.png)

- Select "Cluster IP"
- Click "Save"
NOTE: the UI sends exactly the same request payload like it did the first time but this time the service is created 

![added](https://user-images.githubusercontent.com/40282141/134258460-e465c959-2c3a-4ede-8d64-759ce9aeb5b2.png)

Had no ability to test/reproduce it if somebody upgrades from 2.5 to 2.6

**Comment by mantis-toboggan-md** [comment]
@brendarearden it looks like you've tested with 2.6.1-rc1 it should be working on 2.6.1-rc2; HOWEVER, the new UI doesn't leverage those annotation at all (didn't even know they were a thing when I added this to the dashboard 9 mo ago tbh). I'm unsure if I need to start adding them for workloads made/edited in the new UI; as far as I can tell that alone isn't enough to make services with workloads.

When you add workload ports in the old UI the workload POST contains info about those services and the backend creates them. When you add workload ports in the new UI, the workload POST is just the kubernetes workload config -- it has spec.template.spec.containers[].ports[] but they don't explicitly define associated services -- then separate POST requests create the services. "service <name> already exists" bug was happening because the new UI wasn't detecting the services created the old way, and was trying to make new ones with the same name instead of editing (POST instead of PUT as you already found).

It sounds like workload.TemplateSpec.Annotations['field.cattle.io/ports'] (this appears in spec.template.metadata.annotations in dashboard/steve) is being used by the backend to make services but merely adding that label when creating a workload through steve is insufficient: I made a deployment in the old UI with a nodeport defined, this created ClusterIP and Nodeport services. If I clone that workload in the new UI, and ensure the annotation has the right workload name in it, then intentionally bypass the new UI's form of service creation, the service's aren't automatically created by the backend.

**Comment by gaktive** [comment]
At least there's a workaround for 2.6.1 users. Should release note the workaround for people upgrading until we can sort this out in an upcoming release.

**Comment by mantis-toboggan-md** [comment]
This is ties into to a backend issue https://github.com/rancher/rancher/issues/34981

**Comment by catherineluse** [comment]
I'm closing this issue as stale due to its age, lack of activity, and the fact that the workaround exists. If this fix is still needed, we can reopen the ticket.
