### ISSUE TITLE
"Pause Orchestration" button is missing

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4331]
This is an important debugging tool used widely in one specific environment. It remembers the scale of the workload and one doesn't have to remember what it was set to while debugging.

The prior UI had this function within the Workload view, in between the Redeploy and Download YAML buttons.

**Comment by ronhorton** [comment]
**PASS** Verified fixed in `2.6-head Commit ID 78b25c3`

1. verified that the pause orchestration button was NOT in 2.6.2
![Screen Shot 2021-11-15 at 11.11.26 AM.png](https://zube.io/files/rancher/ebc312674206d4ae1212449efd5b34f7-screen-shot-2021-11-15-at-11-11-26-am.png)
2. created rke2 ec2 cluster in 2.6-head 
3. created a deployment nginx:latest
4. clicked the 3 dots to the right of the new deployment
5. verified `pause orchestration` option is present
6. clicked `pause orchestration`
7. test-deployment changed from `active` to `paused`
8. clicked the 3 dots to the right of the new deployment
9. clicked `resume orchestration` option
10. test-deployment changed status from `paused` to `active`

![Screen Shot 2021-11-15 at 11.12.22 AM.png](https://zube.io/files/rancher/bdc74f419ef6c2fdbdc21c5364fd9866-screen-shot-2021-11-15-at-11-12-22-am.png)
