### ISSUE TITLE
rancher-logging: Namespaces flows can't reference global ClusterOutputs

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#4415]
**Setup**
- Rancher version: 2.6.1
- Browser type & version: Chrome

**Describe the bug**
When you create a namespaces Flow, the UI does not allow you to pick global ClusterOutputs from the `cattle-logging-system` namespace. With rancher-logging all global ClusterOutputs must be in the `cattle-logging-system` namespace though.

**To Reproduce**
* Install rancher-logging
* Create a ClusterOutput in the `cattle-logging-system` namespace
* Create a Flow in the `default` namespace and try to pick the created ClusterOutput as a output

**Result**
The UI does not show the ClusterOutput in the drop down.

**Expected Result**
The UI should show the ClusterOutput in the drop down.

**Comment by gaktive** [comment]
Similar questions popping up in https://github.com/rancher/dashboard/issues/5878, which points to a fix in part in https://github.com/rancher/dashboard/pull/5870/files for 2.6.5.

There may be more backend work required around permissions and namespaces. Not sure what happened with the milestone here since this was intended to be addressed for 2.6.3.

**Comment by izaac** [comment]
Reproduced on Rancher `v2.6.2`

I can't select the cluster output on different namespace, the ClusterOutput is not listed

Validated this is now working on `v2.6.5-rc9`

I am able to select the cluster output in a flow that's created in a different namespace
![Screen Shot 2022-05-10 at 3 35 30 PM](https://user-images.githubusercontent.com/27659/167732831-35f421b6-dcae-46a0-bce0-7bd76d4976a9.png)
