### ISSUE TITLE
Improve top-level menu items behavior and appearance

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4424]
**Setup**
- Rancher version: 2.6.1
- Browser type & version: Chrome, latest

**Detailed Description**
Following up on https://github.com/rancher/dashboard/issues/4358, it would be great to improve behavior/visuals for top-level menu items that are clickable and have content associated with them (e.g. "Cluster") vs. the ones that don't (e.g "RBAC").
Currently, by just looking at the UI there is no way to tell which top-level menu items fall in the first or the second category. Also, with top-level item with content selected, there is nothing on the UI that indicates that this item is actually selected. Compare how it looks like with "Cluster" selected vs. "Nodes" selected:
"Cluster":
![image](https://user-images.githubusercontent.com/85187633/137938930-098866e0-5719-40f5-b9e9-f94bbf3f8bc9.png)

"Nodes":
![image](https://user-images.githubusercontent.com/85187633/137939088-f2572bf6-8493-435a-bf38-9fe113eb7c22.png)

**Context**

Improvements in this area will make it more intuitive to use Rancher UI.

**Comment by catherineluse** [comment]
Should this be in v2.6.6 since it ties into https://github.com/rancher/dashboard/issues/4431?

**Comment by edenhernandez-suse** [comment]
This issue is a bit outdated.

> It would be great to improve behavior/visuals for top-level menu items that are clickable and have content associated with them (e.g. "Cluster") vs. the ones that don't (e.g "RBAC")

This was fixed at some point. Menu items without children don't show a chevron anymore.

> Also, with top-level item with content selected, there is nothing on the UI that indicates that this item is actually selected.

This is also fixed: those items are now highlighted.

![image](https://user-images.githubusercontent.com/120640736/212062526-bc47b66d-ba12-4cbf-8e73-b259d84b85d5.png)

However, there is a bug with the `Cluster` section. It doesn't get the `active` CSS class and, therefore, it's not highlighted. 

There is also some weird CSS in the children list items:

![image](https://user-images.githubusercontent.com/120640736/212063163-a020281b-e256-4961-bf3f-83548767849e.png)

![image](https://user-images.githubusercontent.com/120640736/212063064-3b6b1a38-c494-426a-8653-8f77f3a49e43.png)

That margin is wrong (and deleting it doesn't change anything).

**Comment by kwwii** [comment]
Closing this as everything works as expected now except the selected background color of top level menu items. Created a new bug for that issue here https://github.com/rancher/dashboard/issues/7937
