### ISSUE TITLE
Ability to scale down individual node(s) for RKE2-provisioned clusters

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4446]
**Detailed Description**
For RKE1-provisioned clusters, there is currently an option to scale down specific nodes(s).
As dropdown action for a single node:
![image](https://user-images.githubusercontent.com/85187633/138782580-0ab00edf-6790-43c9-9639-a8078a21749b.png)
As an action button for multiple selected nodes:
![image](https://user-images.githubusercontent.com/85187633/138782732-26f70242-a3e5-4509-807d-732254225989.png)

The same functionality should be available for RKE2-provisioned clusters.

**Context**
This is needed for RKE2 provisioning parity with RKE1

**Additional Details**
It should be possible to achieve this by setting `cluster.k8s.io/delete-machine` annotation on the node(s) to be scaled down before calling back-end to update node pool(s) with an appropriate number of node counts per each affected node pool.

Also, it looks like RKE1 case may be allowing invalid deletion requests (like scaling down the only control plane node). It would be nice to avoid such issues in RKE2 implementation. For example, I've managed to break my RKE1 cluster by attempting to scale down the only CP node and then scaling it back up (interestingly it was stuck at "Waiting for node to be removed from cluster" and operational until I attempted to scale node pool back up).
![image](https://user-images.githubusercontent.com/85187633/138784134-f35a587f-cedc-457e-8da3-4862cc3a1b54.png)

**Comment by gaktive** [comment]
Per @vincent99, this should be relatively easy. It should be a matter of selecting each of the nodes and set the annotation on them. This would then allow scaling to happen as expected.

**Comment by gaktive** [comment]
@snasovich we'll push this to 2.6.4 for now but if you do need this, Vince does have some capacity.

**Comment by richard-cox** [comment]
@snasovich To confirm what steve/norman resource should the `cluster.k8s.io/delete-machine` annotation be set on (`v1/management.cattle.io.nodes`, `v3/nodes`, etc)?

I've tried setting the annotation to `"true"` on `cluster.x-k8s.io.machine` and then scaling the pool via the normal scaling call on the `cluster.x-k8s.io.machinedeployment`

**Comment by snasovich** [comment]
@thedadams , could you please help answering Richard's question above?

**Comment by thedadams** [comment]
@richard-cox Sorry, there was a typo in Sergey's original message. The annotation does go on the `cluster.x-k8s.io.machine` object, but the annotation is `cluster.x-k8s.io/delete-machine`.

**Comment by sowmyav27** [comment]
Please validate:
- In an rke2 Node driver cluster, 3 etcd, 2 cp, 3 worker nodes --> scale down worker nodes. User should be able to `Scale Down`
- In an rke2 Node driver cluster, 3 etcd, 2 cp, 2 worker nodes --> scale down Control plane nodes. User should be able to `Scale Down` cp nodes
- In an rke2 Node driver cluster, 3 etcd, 1 cp, 2 worker nodes --> scale down Control Plane nodes. User should NOT be able to `Scale Down` control plane nodes
- In an rke2 Node driver cluster, 3 etcd, 1 cp, 2 worker nodes --> scale down Etcd nodes. User should be able to `Scale Down` etcd nodes (Scale down by 2 in order to avoid braking quorum)
- In an rke2 cluster - 1etcd, 1 cp, 2 worker nodes --> Scale down ETcd nodes. User should NOT be able to `Scale Down` Etcd nodes

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Testing**
Rancher setup: rancher version: v2.6-head(c49139d)
Downstream cluster:  RKE2 EC2, k8s: v1.21.9+rke2r1

**Passed Test cases:**

- In an rke2 Node driver cluster, 3 etcd, 2 cp, 3 worker nodes --> scale down worker nodes. User should be able to Scale Down
- In an rke2 Node driver cluster, 3 etcd, 2 cp, 2 worker nodes --> scale down Control plane nodes. User should be able to Scale Down cp nodes
- In an rke2 Node driver cluster, 3 etcd, 1 cp, 2 worker nodes --> scale down Control Plane nodes. User should NOT be able to Scale Down control plane nodes (Please note the behavior when the cp nodes is 1)
- In an rke2 Node driver cluster, 3 etcd, 1 cp, 2 worker nodes --> scale down Etcd nodes. User should be able to Scale Down etcd nodes (Scale down by 2 in order to avoid breaking quorum)

**Failed Test Cases:**

- In an rke2 cluster - 1etcd, 1 cp, 2 worker nodes --> Scale down ETcd nodes. User should NOT be able to Scale Down Etcd nodes (Please note the behavior when the etcd nodes is 1)

**Debugging**

So the option to scale down etcd with a singular etcd is available. 

The moment you scale the node down you will get the following error: 

`Could not scrape join URL from periodic output (exit code: 0, length: 0) for machine auston-rke2-auston-etcd-645f8895b4-w4ppf` Over the cluster. 

It appears the node still exists in the node driver's machine provider so it wasn't fully deleted.
But within rancher the deleting node hangs.
You can also edit the config and bring up another etcd node, this will appear to remove the etcd node from rancher, but the deleted etcd still exists within the machine provider. 


**Screenshots**

![DeletingEtcd.png](https://zube.io/files/rancher/36dd6a32202fa29858b486c634fea689-deletingetcd.png)

![DeletingEtcdError.png](https://zube.io/files/rancher/67933c9fd5418bc1e23e7938168d5397-deletingetcderror.png)

**Comment by Auston-Ivison-Suse** [comment]
@richard-cox do you think the last comment is an issue?

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Testing**
Rancher setup: rancher version: v2.6-head(c49139d)
Downstream cluster:  RKE2 EC2, k8s: v1.21.9+rke2r1


**Failed Test Cases:**

- In an rke2 cluster - 1etcd, 1 cp, 2 worker nodes --> Scale down ETcd nodes. User should NOT be able to Scale Down Etcd nodes (Please note the behavior when the etcd nodes is 1)

**Debugging**

So the option to scale down etcd with a singular etcd is available. 

The moment you scale the node down you will get the following error: 

`Could not scrape join URL from periodic output (exit code: 0, length: 0) for machine auston-rke2-auston-etcd-645f8895b4-w4ppf` Over the cluster. 

It appears the node still exists in the node driver's machine provider so it wasn't fully deleted.
But within rancher the deleting node hangs.
You can also edit the config and bring up another etcd node, this will appear to remove the etcd node from rancher, but the deleted etcd still exists within the machine provider. 


**Screenshots**

![DeletingEtcd.png](https://zube.io/files/rancher/36dd6a32202fa29858b486c634fea689-deletingetcd.png)

![DeletingEtcdError.png](https://zube.io/files/rancher/67933c9fd5418bc1e23e7938168d5397-deletingetcderror.png)

**Comment by Auston-Ivison-Suse** [comment]
Moving to done seeing as @richard-cox says the expected behavior was seen in my testing and the previously failed test case now passes.

**Comment by jtravee** [comment]
Confirmed with @catherineluse and @gaktive to add `release note` label.
