### ISSUE TITLE
Continuous Delivery GitRepo edit is not allowed

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#4499]
**Setup**
- Rancher version: 2.6.0
- Browser type & version: Chrome 89.0

**Describe the bug**
Editing GitRepo configuration in Continuous Delivery fails.

**To Reproduce**
Rancher GUI -> Main Menu -> Continuous Delivery -> GitRepo -> Create -> OK
Edit any setting in the GitRepo configuration -> Fails

**Result**
Fails.

**Expected Result**
Change saved.

**Screenshots**
![image](https://user-images.githubusercontent.com/86831399/140064970-fa0380f5-70b2-4759-b063-88ad0e431e90.png)

**Additional context**

**Detailed Description**

**Context**

**Comment by nwmac** [comment]
This may have been fixed by a fix for a similar issue elsewhere - validate fist.

**Comment by peteingithub** [comment]
@nwmac 
Seems to be working with 2.6.3-rc2.

**Comment by jmcsagdc** [comment]
Reproduced error in 2.6.2
Verified fixed in 2.6.3-rc3

1. Deploy a downstream cluster from Rancher
2. Go to Continuous Delivery
3. Click Create
4. Add a name
5. Add a repo. I used one of our test ones that creates a few resources `https://github.com/sgapanovich/fleet-examples.git`
6. Use Master for branch
7. Our repo has a path... `/single-cluster/helm`
8. Click save and let it deploy
9. After deploying, click its ellipsis menu and Edit Config
10. Change branch to `hello`

EXPECTED:
Resource allotments change after a successful save. In 2.6.3-rc3, this is true (see screenshot)

The original repro in 2.6.2 you get an error and it seems the config is not saved. (see screenshot)

![2021-11-30_15-38-26](https://user-images.githubusercontent.com/15971368/144149138-cfcc8cd6-5664-4a40-a298-c084b9c2d22b.jpg)
