### ISSUE TITLE
Branding Config: Text color shown as white when not configured

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4501]
Top Menu -> Global Settings -> Branding

Bug:

If the text color is not selected, it shows white in the color box but the color of the text would be black. Text box color should match the color of the text.`

i.e. The default text color is black (light mode) and white (dark mode) (see css vars) - we're always showing white when this has not been configured, rather than picking up the color from the theme css var.

![image](https://user-images.githubusercontent.com/1955897/140068578-752672df-fc6e-43da-821a-65313a2372fa.png)

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6-head Commit ID cd3c9d7`

1. In light mode (white background), go to global settings > branding
2. select 'show banner in Header, show banner in footer, and show consent banner on login screen'
3. in light mode, the text color is set to black
4. switch to dark mode
5. repeat step 2
6. in dark mode, the text color is set to white
7. switch to auto
8. repeat step 2
9. in auto, light mode is on due to 12:00 pm, and text color is set to black

![Screen Shot 2022-01-10 at 12.08.54 PM.png](https://zube.io/files/rancher/e21f71620fded8bca14a8dd2db37f16e-screen-shot-2022-01-10-at-12-08-54-pm.png)


![Screen Shot 2022-01-10 at 12.10.27 PM.png](https://zube.io/files/rancher/9bd400576e8c8473f77cdeb9d2043203-screen-shot-2022-01-10-at-12-10-27-pm.png)
