### ISSUE TITLE
Users with access to a cluster should be able to use the cloud credential on the cluster

### ISSUE THREAD

**Issue by thedadams** [rancher/dashboard#4529]
**Describe the bug**

After a lengthy discussion, it has been determine that if a user has access to a cluster then that user should be able to use the cloud credential associated to that cluster.

Currently for KEv2 clusters, if an admin creates a cluster and assigns a standard user as an owner, that cluster owner will not be able to edit the cluster from the UI because the cloud credential dropdown may not have an cloud credentials in it. A cluster owner should always have the ability to edit a cluster with the cloud credential that is currently on the cluster or change it to one they have direct access to.

**To Reproduce**

1. As an admin, create an EKS/GKE/AKS cluster
2. Create a standard user
3. Assign the standard user as cluster owner.
4. Log in as the standard user and try to edit the cluster.

**Result**
The user will not be able to proceed unless they specify a different cloud credential.

**Expected Result**

The user should be able to continue with the cloud credential currently on the cluster or change it to one they own.

**Comment by gaktive** [comment]
Bumping out of 2.6.3 based on backend: https://github.com/rancher/rancher/issues/35413

**Comment by gaktive** [comment]
Backend did complete after all. Maybe we can still get this in for 2.6.3 if it's quick.

**Comment by vincent99** [comment]
Either the API change doesn't work or there was more than one problem with it.  Editing EKS for example isn't failing because the UI can't list the cloud cred (though it does display it empty on the edit screen, which isn't great).

The current value of `eksConfig.amazonCredentialSecret` is preserved and sent back to the API, but on `PUT /v3/clusters/foo` the server returns 404 `{"baseType":"error","code":"NotFound","message":"error accessing cloud credential","status":404,"type":"error"}`.

**Comment by thedadams** [comment]
There was an oversight in the change in the backend: the check for access to the old cloud credential was removed when a user is trying to change the cloud credential, but Rancher shouldn't check for access to the cloud credential passed in the PUT request unless the cloud credential is being changed.

I will discuss this with @snasovich to see if we can still get this in v2.6.3. It's not a difficult change on the backend.

**Comment by thedadams** [comment]
Update here:

When the cloud credential doesn't change, the UI doesn't send any cloud credential with the PUT request. In this case, the request will succeed.

However, when making a PUT request via the API and passing the cloud credential ID, then the error Vince is seeing appears. The backend change is very straightforward and I will push to get it in to v2.6.3.

**Comment by snasovich** [comment]
Relevant backend change: https://github.com/rancher/rancher/pull/35675
However per https://github.com/rancher/dashboard/issues/4529#issuecomment-981823616 it looks like this is not blocking actual flow as UI doesn't seem to send cloud credential in PUT request in this case.

So to recap, the ask here is to have UI display currently set cloud credential in the dropdown rather than having it empty - similar to how RKE2 does it, e.g.:
https://user-images.githubusercontent.com/4569037/133878526-8cdcb9db-9b50-44b7-85dd-ea1de966e974.png

**Comment by brudnak** [comment]
# My checks PASSED
 
## Reproduction Environment

Reproduced in: [https://github.com/rancher/rancher/issues/35413](https://github.com/rancher/rancher/issues/35413)

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-03ed782ae89950ae664b9cfef899723cf5e60b4a-head |
| Rancher cluster type    | Docker                                             |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2            |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | EKS                                                |
| Downstream K8s version  | 1.21                                               |
| Browser type            | Google Chrome                                      |
| Browser version         | 96.0.4664.55 (Official Build) (x86_64)             |

## Validation steps

1. As an admin, create a EKS cluster
2. Create a standard user
3. Assign the standard user as a cluster owner of the EKS cluster
4. Logout as admin and login as the standard user
5. Edit the cluster and see if the cloud credential is available

#### RESULTS

The cloud credential appears, and the standard user with owner status is able to edit the cluster.
  
## Additional Info

Also verified this is working with AKS, and GKE.
