### ISSUE TITLE
Pass clusterID when using meta proxy with provisioned RKE2/K3S clusters

### ISSUE THREAD

**Issue by thedadams** [rancher/dashboard#4544]
It was decided that a cluster owner should be able to use the meta proxy when editing a cluster they own regardless of whether they have access to the cloud credential on that cluster. In order for this to happen (and to make it consistent with the way KEv2 handles this situation), the UI should pass a `clusterID=c-m-xxxxx` (where the `c-m-xxxxx` is the ID for the management cluster associated to this cluster) in the `X-API-CattleAuth-Header`. That way the backend can validate that the user has access to the cloud credential OR is the owner of a cluster associated to the cloud credential.

**Comment by vincent99** [comment]
I thought this was going to be done on the API-side by looking up the user making the request and seeing if they have appropriate access to any clusters that uses the requested credentialId;  I _could_ add clusterID=foo to the header as you've asked, but:

  - That has to be individually done in the UI for every machine-config provider making a request to /meta/proxy, which is going to be error-prone.
  - People who write 3rd party drivers will forget and edit will just unexpectedly not work right.
  - There's other kinds that aren't directly the proxy and don't use that header, but still need support, like the special azure/google/vmware endpoints.
  - It's sort of implying that 
  - You still have to verify the that there actually exists a CRTB for the requested user+cluster with an appropriate permission and that that cluster uses the credentialId... so an extra step of "...for any clusterId" seems like just one more lookup and loop?

**Comment by thedadams** [comment]
Ultimately, the decision boils down to performance. It would be very straightforward to list all clusters and check whether the user has access to a cluster and that cluster has the appropriate cloud credential associated to it. But if a Rancher setup has many clusters, then this will be slow and will need to be repeated for every request made through the proxy.

The Azure and Google proxies already work this way. And the meta-proxy works this way for EKS clusters. My PR updates the meta-proxy to work this way for provisioning v2 clusters. I need to update the vmware and oci proxies to work this way.

As far as third-party drivers: a user cannot create a cluster unless they have access to the cloud credential and multi-user editing currently doesn't work unless a user has access to the cloud credential. So this wouldn't break any third-party drivers and a driver could be updated to support this use case.

**Comment by vincent99** [comment]
I meant when someone works on a driver, all the create flow and them doing their own edits (with the same user) work without adding a clusterId.  So that developer (& their QA) will have little reason to know that editing by a different person marked as an owner requires sending additional info to the proxy.  They will forget to test it, and then it won't work when someone actually needs it.  We have in fact done this ourselves frequently during this whole chain of issues.

It also sort of implies more validation is occurring than it really is, which I don't love.. the proxy calls aren't being scoped or restricted in any way to things related to that clusterId.   It's acting like a 2FA token you have to provide, but the 2nd factor isn't really a separate factor at all because it's plainly visible to anyone who knows the 1st.

So yes I agree it's an optimization to make the validation faster on the server-side, but not one I think we should force the client to provide.  I don't think it's necessary now, but if you wanted to this could certainly be optimized in other ways on the backend.  Like keeping a cache of the [user, credentialId] -> cluster that authorizes it (and updating it on RBAC changes, or just verifying the cached answer you got back is still true with a single lookup instead of trying to do perfect caching & invalidation).

**Comment by thedadams** [comment]
Closing this in favor of the suggested approach.
