### ISSUE TITLE
Project/namespace quota not working 

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#4597]
**Setup**
- Rancher version: 2.6.3-rc1 (3 node k3s KVM setup, 2 node k3s downstream cluster v1.21.5)
- Browser type & version: Chrome 89.0.4389.90 (Official Build)

**Describe the bug**
Namespace quota for CPU Reservation is not followed. 

**To Reproduce**
Create a project.

Set quota.
![image](https://user-images.githubusercontent.com/86831399/142631008-cdf20afd-edee-406a-bdcf-fdd0327b4d21.png)

Create a namespace. Quota configuration is displayed correctly.
![image](https://user-images.githubusercontent.com/86831399/142631147-e6b6017c-e7f2-40b2-97bb-34be53064713.png)

Create a deployment.
![image](https://user-images.githubusercontent.com/86831399/142631391-fa3f7477-9802-473c-ba48-2f3e60da4516.png)

**Result**
The deployment is created without quota setting to be obeyed.

**Expected Result**
Error about the quota limit.

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by mantis-toboggan-md** [comment]
It looks like the workload does error out eventually, but there's no validation prior to creating the workload, we'll have to decide if we want to warn or prevent this from the UI side

![Screen Shot 2021-11-19 at 7.02.32 AM.png](https://zube.io/files/rancher/5db212dddee52199bf0c2e8320d8227f-screen-shot-2021-11-19-at-7-02-32-am.png)

**Comment by gaktive** [comment]
The backend does have a better validator in the web hook that we can use (different than the mutating web hook).

**Comment by peteingithub** [comment]
@mantis-toboggan-md @gaktive 
Has the code changed in the 2.6.3 rcs? My experience is the quotas worked with 2.6.0-2.6.2.

**Comment by richard-cox** [comment]
It looks like..
- the project has the correct **defaults** set `spec.containerDefaultResourceLimit(limitsCpu|requestsCpu)`,
- the namespace has the correct **max's** set `annotations['field.cattle.io/containerDefaultResourceLimit]` `{\"limitsCpu\":\"200m\",\"requestsCpu\":\"300m\"}"`
- the app.deployment has the correct **container specific max** set (in post) `spec.template.spec.containers[].resources` `requests: {cpu: "500m"}`

So I think either
1) We set inputs to have max values relative to the namespace available
1) We do visual validation up front  (just like we show in Namespace when the project has max's set) 
    ![image](https://user-images.githubusercontent.com/18697775/150353212-313a17eb-4155-49c4-a3ee-94da8f75cf5b.png)
2) We request the backend returns an error when invalid values are supplied (don't think this exists in Steve world?), or make use of some kind of validation hook as mentioned by Gary (@gaktive Not quite sure what that means?)

**Comment by gaktive** [comment]
@vincent99 do you recall how the web hook validator mentioned earlier worked?

**Comment by nwmac** [comment]
@codyrancher Can you take a look?

**Comment by samjustus** [comment]
@maxsokolovsky can you take a look at this? did we address this already?

**Comment by maxsokolovsky** [comment]
@peteingithub, what are the values for the resource quota itself on the project? I'm not seeing them on the screenshots. I see container default resource limits, but that's something else. These limits are the default container limits applied, if none are specified. But this is relevant for non-blank quotas. From the docs:
```When setting resource quotas, if you set anything related to CPU or Memory (i.e. limits or reservations) on a project / namespace, all containers will require a respective CPU or Memory field set during creation.```
But you don't seem to have any resource quota limits.

If you did not set any limits (in the Resource Quotas tab), then this behavior makes sense - you don't have limits in the project's namespaces, so a namespace and a deployment in it can have any resource amounts.

**Comment by peteingithub** [comment]
@maxsokolovsky 
I'm quite positive the screenshots I added would be the only ones I set (have not been working with Rancher in months).

I guess I misunderstood this. I had the feeling, that the default limits would be the ones the system sets for you unless there were other values already set, hence filling the blanc, overriding non-blanc.

Thanks for clarifying!

**Comment by seanwcom** [comment]
Ok, sorry I haven't chimed in sooner... I have a case where this **is not** working as expected (on Rancher v2.6.3).

**Project created with the following:**
  - Resource Quotas
    - Project Limits
      - CPU Limit: 4000
      - CPU Reservation: 4000
      - Memory Limit: 4096
      - Memory Reservation: 4096
    - Namespace Default Limits
      - CPU Limit: 1000
      - CPU Reservation: 1000
      - Memory Limit: 1024
      - Memory Reservation: 1024
  - Container Default Resource Limits
    - CPU Limit: 500
    - CPU Reservation: 250
    - Memory Limit: 256
    - Memory Reservation: 128

**One Namespace Created in Project with the following:**
  - Resource Quotas
    - CPU Limit: 1000
    - CPU Reservation: 1000
    - Memory Limit: 1024
    - Memory Reservation: 1024
  - Container Default Resource Limits
    - CPU Limit: 500
    - CPU Reservation: 250
    - Memory Limit: 256
    - Memory Reservation: 128

**One Deployment created with the following to override container defaults:**
  - Resource Limits and Reservations
    - CPU Limit: 10000
    - CPU Reservation: 5000
    - Memory Limit: 16384
    - Memory Reservation: 8192

That deployment **SHOULD** immediately fail since all of its defined resources exceed every limit set correct? As a test, the exact same setup in Rancher 2.5.12 fails immediately with the typical quota exceeded message.

Am I missing something about how this should work now? Thanks!

**Screenshots:**

**Project:**
![image](https://user-images.githubusercontent.com/128131/164298095-fa7267a2-9b91-4766-80df-b15b88b4a00e.png)
![image](https://user-images.githubusercontent.com/128131/164298144-e57ed2e0-25df-4009-8a08-4dddb83ccd61.png)

**Namespace:**
![image](https://user-images.githubusercontent.com/128131/164298241-e14e435d-90e4-49f3-bbf8-1150ece4cb57.png)
![image](https://user-images.githubusercontent.com/128131/164298280-8bee384f-1ed7-49af-bd58-35649d1ea8df.png)

**Deployment:**
![image](https://user-images.githubusercontent.com/128131/164298648-b3b4fa82-16ec-45d8-aeda-96ce8ece2cd9.png)

**Deployment YAML:**
![image](https://user-images.githubusercontent.com/128131/164298725-c144e179-0b3f-4f20-b9e8-5109d5c8dddd.png)

**Deployment Running:**
![image](https://user-images.githubusercontent.com/128131/164298590-2bc55768-f9d2-49e0-b171-67ef14cacd1c.png)

**Comment by maxsokolovsky** [comment]
@seanwcom, I just tried your scenario in `v2.6.4` and could not reproduce. Kubernetes did not let me create that deployment, since the container resource failed to meet the quota limits (in this case, the namespace default limits).

**Comment by seanwcom** [comment]
Oh, great! I'll try to get my lab updated this week, but glad to hear its working there. Thanks for the update.

**Comment by seanwcom** [comment]
A coworker just tested this on `v2.6.4` and also had the expected error message, so this looks great to me. Thanks all!
