### ISSUE TITLE
Show all container images in Workload view

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4626]
![image](https://user-images.githubusercontent.com/18697775/143001038-af1529b1-becc-4de5-85dc-fcf86e105714.png)

- The images column in workloads lists only shows the first one, subsequent images are hidden behind a `+<x>` . 
- To see these images the user has to drill down into the workload and then specific pod

Suggestion - Show list of images on mouse over of `+<x>`. This won't then consume space in the list

**Comment by nwmac** [comment]
Add a tooltip to the `+X more` with all of the images in that workload.

**Comment by aalves08** [comment]
![Screenshot 2022-01-21 at 17.48.02.png](https://zube.io/files/rancher/e8b1dfc9ef2eaedc9dc18bd9b8f01205-screenshot-2022-01-21-at-17-48-02.png)

@nwmac how does it look?

Since the logic is attached to the formatter and all "image" table cols use that same formatter, it will automatically apply to all "image" table cols.

**Comment by brandonsuse** [comment]
@AndrewHoffmanQA Just ensure that the images column no longer hides the listed images behind the "+ x more" label. Thanks

**Comment by AndrewHoffmanQA** [comment]
image names now populate when the user hovers their mouse over +<x> more. setting this product enhancement ticket to 'done'

![image.png](https://zube.io/files/rancher/8f275363cd54f9fedcd208a420182fc8-image.png)
