### ISSUE TITLE
"helm3-library" partner chart error while upgrading

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/dashboard#4628]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Describe the bug:**
While testing this [issue](https://github.com/rancher/rancher/issues/35353), `Alcide` chart upgrade from "Edit/upgrade" option under Apps & Marketplace(installed apps) showing all the charts under drop-down.(Check screenshot below).

**Rancher Installation option (Docker install/Helm Chart):** Docker

**Steps to reproduce:**

1) Deploy rancher v2.6.2 and enable legacy feature.(from side-panel -> Global Settings -> Feature Flags -> enable legacy)
2) Create 1.21.6 downstream k8s cluster.
3) Deploy `alcide` partner chart from helm3 catalog (Under Multi-cluster Apps section) on downstream cluster.
4) Upgrade rancher to v2.6.3-rc1.
5) Goto Apps & Marketplace -> installed apps -> alcide -> "Edit/Upgrade" option
6) Drop down contains all the charts from the catalogs (attached ss)
![ss2](https://user-images.githubusercontent.com/36376154/143000213-8458c22c-b245-4edf-9ee6-450950ae50ec.png)

**Comment by catherineluse** [comment]
Closing this PR because it's a stopgap measure, whereas this issue is tracking the work of solving the same problem in a better way and it's also in v2.6.3.  https://github.com/rancher/rancher/issues/35680. When that work is done, I believe no UI work would be needed to address this issue.

**Comment by catherineluse** [comment]
This issue seems addressed by https://github.com/rancher/rancher/pull/35711 and I believe no additional UI work is necessary to fix it. I did the same steps in `v2.6-head` and I didn't see all of the charts being displayed in the upgrade form. What I did see was:

For openebs app deployed in Rancher v2.6.2, it showed under Apps & Marketplace > Installed Apps and the normal upgrade page was shown:
<img width="1419" alt="Screen Shot 2021-12-08 at 4 49 59 PM" src="https://user-images.githubusercontent.com/20599230/145309589-575d832f-7157-4a25-8e34-710df3ea20b0.png">

For a multi-cluster app mariadb deployed in Rancher v2.6.2, it showed under Apps & Marketplace > Installed Apps and we are redirected to the multi-cluster app section, where you can successfully upgrade the app:
<img width="1412" alt="Screen Shot 2021-12-08 at 4 49 47 PM" src="https://user-images.githubusercontent.com/20599230/145309605-9ccdb887-1053-4eb8-86a7-83a7e47a3f22.png">

For the multi-cluster app alcide-advisor deployed in Rancher v2.6.2, it wasn't under Apps & Marketplace > Installed Apps, but it still showed under the legacy Multi-cluster Apps section and could be successfully upgraded from there.

I'm not sure why some multi-cluster apps are shown under Installed Apps and some aren't, but the upgrade forms aren't breaking anymore.

**Comment by rishabhmsra** [comment]
**Verified on rancher v2.6-head (e62e1ae)**
**Rancher Installation option (Docker install/Helm Chart):** Docker

**Validation steps:**

1. Deployed rancher v2.6.2 and enabled legacy feature.(from side-panel -> Global Settings -> Feature Flags -> enable legacy)
2. Created a 1.21.6 downstream k8s cluster.
3. Deployed alcide partner chart from helm3 catalog (Under Multi-cluster Apps section) on a downstream cluster.
4. Upgraded rancher to v2.6-head (e62e1ae).
5. Goto Apps & Marketplace -> installed apps -> alcide -> "Edit/Upgrade" option.
6. Alcide chart is present under "Apps and marketplace" and can be successfully redirected multicluster app section where it can be updated:
![alcide](https://user-images.githubusercontent.com/36376154/145817200-0d226f5f-02fe-4e9a-835a-137aae905619.png)

**Result :**
- Working as expected
