### ISSUE TITLE
Dashboard generates too many requests when listing resources

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#4637]
There is a "tidal wave of requests" UI sends to backend in certain cases as per https://github.com/rancher/rancher/issues/30718#issuecomment-934087414

This issue is for tracking specifically this fix.

**Comment by snasovich** [comment]
This has been fixed in UI as per the following PR: https://github.com/rancher/dashboard/pull/4264 and made it into 2.6.1 first.
@sgapanovich @sowmyav27 , was this ever validated on 2.6.1 ? There was a lot of confusion around what exactly was done in connection with addressing original https://github.com/rancher/rancher/issues/30718 issue. This one is specifically about the prevention of all redundant requests UI sends to API in case linked in issue description.

I'm setting milestone as 2.6.3 for visibility, feel free to change it to 2.6.1 if that makes sense.

**Comment by vincent99** [comment]
I think someone else besides me verified it at the time but it's very obvious if you have more than a few ingress resources.  

- Load the ingress list without having first been to the Workloads list
- In 2.5 each and every row of ingress triggers simultaneous requests to each of the ~7 workload types.
- In 2.6 you'll see just one set instead of one per row (and it won't take forever).

**Comment by vincent99** [comment]
No, the logging is normal.

**Comment by sgapanovich** [comment]
updating the milestone to `2.6.1` and closing the issue
