### ISSUE TITLE
Imported AKS cluster does not show any workload level metrics

### ISSUE THREAD

**Issue by jls-tschanzc** [rancher/dashboard#4658]
**What kind of request is this (question/bug/enhancement/feature request):**

bug

**Steps to reproduce (least amount of steps as possible):**

1. Import an AKS Cluster
2. Enable Monitoring (0.0.7 or 0.1.0)
3. Wait a while
4. Go to Project -> Namespace -> Workload (Or browse to any workload/pod metrics in Grafana)
5. Open the "Workload Metrics"

**Result:**

It always states "Not enough data for graph". In Grafana it only shows requests/limits and no CPU/Memory data.

**Other details that may be helpful:**

It has already been this way on Rancher 2.3.5 / Monitoring 0.0.7 and remained the same after upgrading to Rancher 2.4.4 / Monitoring 0.1.0.

It does show cluster level metrics.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.4
- Installation option (single install/HA): HA

**Cluster information**

- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): AKS Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Cloud, 1.9 vCPU / 4.5 GB
- Kubernetes version (use `kubectl version`): v1.15.10

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:25Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"059c666b8d0cce7219d2958e6ecc3198072de9bc", GitTreeState:"clean", BuildDate:"2020-04-03T15:17:29Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

gz#12942

**Comment by catherineluse** [comment]
@gaktive I realized that this issue is for the deprecated monitoring V1. Therefore I suggest closing it because we are no longer updating the V1 apps. In addition to that, the UI is moving away from injecting certain values into Helm charts because it could potentially introduce a version incompatibility issue between the Helm chart version and the Rancher version.

I think it would be better to address this issue through documentation in these places:

- Rancher documentation for imported AKS clusters
- Rancher documentation for the monitoring application
- The monitoring Helm chart README

**Comment by gaktive** [comment]
Closing as won't fix. For docs people who see this, we should document as @catherineluse suggests.

**Comment by catherineluse** [comment]
I have opened a docs ticket to track the work of figuring out if a similar requirement needs to be documented for Monitoring V2. https://github.com/rancher/rancher-docs/issues/377
