### ISSUE TITLE
Cluster Name link on Mgmt Clusters page throws an error Cannot read properties of null (reading 'doneOverride')

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#4667]
**Setup**
- Rancher version: `2.6-head Commit ID 4375161`
- Browser type & version: `Chrome` v. 96.0.4664.45 (Official Build) (x86_64)

**Describe the bug**
 On a downstream cluster, Cannot read properties of null (reading 'doneOverride') - error prevents Mgmt Cluster page from loading. This is not reproducible on the local cluster.

**To Reproduce**
1. Create a downstream cluster
2. Go to `hamburger menu > Cluster Management`
3. Click `Explore` for downstream Cluster
4. Click `More resources > Rancher > Mgmnt Clusters`
5. click name-link for downstream cluster

**Result**
Error thrown in console: `vue.runtime.esm.js:1888 TypeError: Cannot read properties of null (reading 'doneOverride')
    at f.r (index.vue?ed4d:1)
    at f.t._render (vue.runtime.esm.js:3548)
    at f.r (vue.runtime.esm.js:4066)
    at _n.get (vue.runtime.esm.js:4479)
    at _n.run (vue.runtime.esm.js:4554)
    at gn (vue.runtime.esm.js:4310)
    at Array.<anonymous> (vue.runtime.esm.js:1980)
    at ie (vue.runtime.esm.js:1906)`

Loading screen displayed
**Expected Result**
Yaml for selected cluster displayed

**Screenshots**

**Additional context**
Works when following the same navigation path for local cluster

**Detailed Description**

**Context**

**Comment by rak-phillip** [comment]
1 should be the correct count when exploring a downstream cluster in this case, as the backend is providing us with the counts and list of Mgmt Clusters.

This issue was caused by the fact that we were listing too many options when exploring a downstream cluster. We were exclusively using the `Management` type to lookup Mgmt Clusters regardless of where we were at (Cluster Management vs. Explore); selecting one of these Mgmt Clusters originally failed because they didn't exist in the downstream cluster's context.

@ronhorton @vincent99

**Comment by ronhorton** [comment]
**PASS** Verified in `2.6-head Commit ID 77392a6`
1. click cluster management
2. click explore
3. click more resources > rancher > mgmt clusters

`No error, and correct number of mgmt clusters (1) is shown`
