### ISSUE TITLE
Fleet request: more real time visibility

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4680]
A request came for more real time feedback to appear in the UI for Fleet, potentially in a DAG style as ArgoCD uses; of what the state of the GitRepo, its bundles, and child resources are in, would be highly beneficial. 

For example, it was reported that they could see all resources under a GitRepo enter a wait state rather than just some, before seeing a single error message under the conditions tab if something is wrong. 

Internal reference: SURE-4650

**Comment by nwmac** [comment]
Look at visualizing a Git Repository - we should show a directed graph with the GitRepo -> Bundles -> Resources

We can then show the state of each item on the nodes in the graph and use color to re-enforce this.

**Comment by ronhorton** [comment]
@aalves08 is this testable by QA? if so, please provide a testing template. (how to repro, what to test, definition of fixed) The related card is closed as 'done'

**Comment by aalves08** [comment]
Hi @ronhorton . Really sorry for not updating the issue properly... 🙏 

This is a new feature released for Fleet on which the user can go to the details of a git repo on Fleet and get a graphical representation of the bundle deployments that came from that git repo (check button Graph on top right of the screenshot)

![Screenshot 2022-06-09 at 10.15.15.png](https://zube.io/files/rancher/7cf7381a34627c9e2ac9ed33474276e2-screenshot-2022-06-09-at-10-15-15.png)

Graph representation here:
![Screenshot 2022-06-09 at 10.19.58.png](https://zube.io/files/rancher/6af8fba5bb4e49d02e4a8809899ba730-screenshot-2022-06-09-at-10-19-58.png)

(this one doesn't have any **Bundle Deployments** associated because I don't have any clusters assigned to it).

Another example here of what to expect, with 4 **Bundle Deployments** per **Bundle** (take this one with a grain of salt since it's an older iteration):

![Screenshot 2022-04-26 at 10.17.35.png](https://zube.io/files/rancher/a18fc7ddeeefcfefcdecdb79d362f351-screenshot-2022-04-26-at-10-17-35.png)

It should present itself in a 3-tier level of nodes, with the central node representing the **Git Repo**, the intermediate level representing **Bundles**, and the outermost level representing **Bundle Deployments**.
Status are represented by colours and by clicking on a node you can view some details on the right-hand side area.

For this, you need create a git repo on Fleet (check example config):
![Screenshot 2022-06-09 at 10.24.20.png](https://zube.io/files/rancher/2572e151e541ff188b22a1422a1d8c32-screenshot-2022-06-09-at-10-24-20.png)

then assign some clusters to the same namespace and you should get the graph view with a bunch of 
**Bundle Deployments** (one per each cluster, if the cluster has only one machine).

**Comment by AndrewHoffmanQA** [comment]
this ticket passes. the graph page consistently generates graphs. was able to see bundles/bundle deployments.
