### ISSUE TITLE
Use currentVersion parameter on template requests for apps.

### ISSUE THREAD

**Issue by rmweir** [rancher/dashboard#4700]
**Detailed Description**

A query parameter, "currentVersion", can now be passed to inform the templates API in norman what the current version is so it can include it in versionLinks regardless of current compatibility with that version. This parameter should be used for app overview page and app detail page so the UI know if the app can be edited.

**Context**

Without this if a user was on a version of an app then upgrade rancher or kubernetes, their setup may become incompatible with the version of their app(s). The templates API will not include the version in the chart templates' versionLinks field and the UI will block edits for that version.

**Backend Issue:**
https://github.com/rancher/rancher/issues/35680

**Comment by catherineluse** [comment]
When this is done, it should also fix these issues along with it:

- https://github.com/rancher/dashboard/issues/4627
- https://github.com/rancher/dashboard/issues/4628

**Comment by catherineluse** [comment]
Closing this issue as not needed because after these changes https://github.com/rancher/rancher/pull/35711, the following four errors are no longer seen in `v2.6-head`:

- https://github.com/rancher/dashboard/issues/4627
- https://github.com/rancher/dashboard/issues/4645
- https://github.com/rancher/dashboard/issues/4628
- https://github.com/rancher/dashboard/issues/4708
