### ISSUE TITLE
Dark mode is not applied on log in page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4710]
**Describe the bug**
Dark mode is not correctly applied to the log in page after previously setting to dark mode. I'm sure this previously worked.

From memory I think dark mode is primarily determined by per user settings which are only picked up on log in. However I thought these were also tied to something locally on the client... which would be picked up pre-log in.

**To Reproduce**
1. Log in
2. Set to dark mode
3. Log out (log in page is in dark mode)
4. Refresh (log in page is in light mode)

**Result**
Log in page is in light mode

**Expected Result**
Log in page is in dark mode

**Comment by vincent99** [comment]
The login screen uses the `R_THEME` cookie and appears to work correctly when it's set.  And the exact steps you said do set the cookie.

But if you don't already have the cookie, and don't literally do step 2 and click Dark (maybe because it already appears selected), then just logging in isn't causing it to be set.

Then it isn't present on the reload in 4, and the default is `auto`, which looks at the browser/os preferred color scheme (indirectly, via `R_PCS` cookie, for SSR support), and presumably your Mac is set to light (or auto + it's daytime).

I don't think this ever actually worked right until you clicked and changed the preference, since that's the only place that sets the cookie.  But once set it's there for a year.

So after prefs are loaded, the cookie should be written to match the user's preference.  Probably at the end of [store/prefs.js get()](https://github.com/rancher/dashboard/blob/master/store/prefs.js#L124) when `definition.asCookie` is true, so it's updated any time someone tries to read it.  And pulling out/reusing [this block](https://github.com/rancher/dashboard/blob/master/store/prefs.js#L252-L257) to write it.

**Comment by richard-cox** [comment]
I'd just started to debug this but hadn't got passed where it was set. In my env even toggling the dark mode setting failed to apply it on a fresh load. I'm on chromium on linux though, maybe that's coming in to play. At the least the default OS dark mode is never normally picked up. Will to continue to investigate

**Comment by richard-cox** [comment]
Mystery deepens. My `R_THEME` value was set to light, even after changing in `/prefs`... though whilst logged in https://github.com/rancher/dashboard/blob/master/store/prefs.js#L170 gave the 'correct' output of `Get Theme dark light` (behaviour continued over refresh). I cleared cookies.. and it now everything works correctly (i can change the theme to light/dark and it's immediately set to `R_THEME`). Maybe I had another window open somewhere that was battling the setting.

Whilst looking in to this though found another issue, refreshing on the `/prefs` page redirects to ember. Will open a separate issue.
