### ISSUE TITLE
rke2/k3s chart values do not update when switching versions

### ISSUE THREAD

**Issue by rancher-max** [rancher/dashboard#4714]
**Setup**
- Rancher version: v2.6.3-rc4
- Browser type & version: Firefox 94.0.2

**Describe the bug**

Chart values do not update when changing kubernetes version for rke2 and k3s.

**To Reproduce**

1. Point to my custom KDM, which has different values for the calico charts for rke2 in v1.22 and v1.21: https://raw.githubusercontent.com/rancher-max/kontainer-driver-metadata/rke2-chart-versions/data/data.json
2. Navigate to the create cluster page for rke2
3. Change Kubernetes Version to use v1.21.7+rke2r2
4. Go to "Edit as YAML"

**Result**
Notice `spec.rkeConfig.chartValues` are not updated. I would expect `spec.rkeConfig.chartValues.rke2-calico` to be using v1.17.6 for tigeraOperator. Basically what is happening is that none of the values are being updated according to the KDM values. 

Even if I do not point to any custom KDM and just change the Kubernetes Version in the form to use a k3s version, I still have these rke2-calico config params. I shouldn't have these at all because k3s does not use calico. 

**Expected Result**

Changing kubernetes version in the form on the UI should also update any chart values to be use those associated with that version.

**Screenshots**

Initial Values:
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/55997940/144937535-230effdf-56dc-408c-a635-1841d6d50049.png">
<img width="578" alt="image" src="https://user-images.githubusercontent.com/55997940/144937591-85f5e5c9-25bc-4589-b4a1-2856d0b1bf47.png">

After Changing:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/55997940/144937671-fd002195-226c-472a-8357-a62a509d0f5c.png">
<img width="672" alt="image" src="https://user-images.githubusercontent.com/55997940/144937651-02f661c1-8a7c-4a84-b25b-40cdd052a6e2.png">

**Additional context**

**Detailed Description**

**Context**

**Comment by anupama2501** [comment]
- seeing this issue on v2.6.3-rc4 HA. Not able to upgrade any chart as a standard user.
- When we try to upgrade, no requests are sent to the backend  and the screen won't load:

<img width="462" alt="Screen Shot 2021-12-07 at 8 13 55 AM" src="https://user-images.githubusercontent.com/38144301/145065578-87bb7ae1-70d2-4ee5-9cb8-2a2a128bdba4.png">

**Comment by janeczku** [comment]
The same issue exists when changing CNI provider instead of Kubernetes version: The addon-config content should be updated to match the CNI provider but it isn't.

**Comment by ronhorton** [comment]
This issue is also preventing provisioning of RKE2 cluster with k8s version v1.21.7+rke2r2 (which is the min version available in 2.6.3-rc4 drop down when creating the cluster)
<img width="980" alt="Screen Shot 2021-12-09 at 1 00 25 PM" src="https://user-images.githubusercontent.com/89212856/145450757-d7e2b0c6-d793-433f-9796-7870f6acdea8.png">

**Comment by slickwarren** [comment]
tested on rancher v2.6-head (e62e1ae):
* rke2 1.22.4+rke2r2 single node deployment -> working fine
**Reopening for the following issue:**
* rke2 1.21.7+rke2r2 single node deployment -> **still broken** (workaround: before clicking the button to create the cluster, edit as yaml and remove the entire chartValues section [down until the etcd block] which will deploy successfully).

**Comment by richard-cox** [comment]
I think there's multiple issues in this thread. The core issue of `chartValues` not updating has been fixed (updates on changes to `Kubernetes Version`, `Container Network` or `Cloud Provider`). I don't think those are related to rke2 1.21 failing to provision, that probably needs another issue in `rancher/rancher` (containing a copy of the `chartValues` section and also any helpful logs)

**Comment by richard-cox** [comment]
There's a fair amount of cluster provisioning cases that should be tested for this issue - see https://github.com/rancher/dashboard/pull/4772#issuecomment-994795874

**Comment by davidnuzik** [comment]
**I successfully reproduced the problem**
 
**Reproduction Environment:**

Rancher version: v2.6.3-rc4
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2
Downstream K8s version: (vDefault and switch in dropdown)
 
**Reproduction steps:**

1. Point to Max' custom KDM, which has different values for the calico charts for rke2 in v1.22 and v1.21: `https://raw.githubusercontent.com/rancher-max/kontainer-driver-metadata/rke2-chart-versions/data/data.json`
2. Navigate to the create cluster page for rke2
3. Change Kubernetes Version to use v1.21.7+rke2r2
4. Go to "Edit as YAML"

**Result**
Notice `spec.rkeConfig.chartValues` are not updated. 
![image](https://user-images.githubusercontent.com/45179589/146274301-aa0b1492-c902-41a3-ae67-ea2aac776121.png)

Note, I also changed CNI and the result was the same.

**Comment by davidnuzik** [comment]
v2.6-head `bbde38e` 12/15/2021

Something isn't quite right. Either that or I'm misunderstanding the change. I still expected to see chartValues in the cluster YAML. I have reproduced this one two separate setups each with latest v2.6-head:
 
![image](https://user-images.githubusercontent.com/45179589/146278850-90fed000-d410-4e12-acb2-42dbac3e4159.png)

@richard-cox I'm going to re-open -- could you follow up and move back to QA Working if this is a non-issue (and explain) or investigate?

**Comment by vincent99** [comment]
What's stored/sent is the diff from the chart's original values, which is nothing if you haven't customized it.  Before we always saved the whole thing, which wasn't necessary (because Helm starts from that anyway) and made it hard to tell what the user intended to customize on edit/future upgrade.

**Comment by richard-cox** [comment]
It doesn't look like this change is in the latest RC (`v2.6.3-rc6` which uses dashboard tag `v2.6.3-rc5`). In `2.6-head`, as per Vince's comment and the PR comment (I'm kicking myself for not including it in the Notes to QA section), we now don't populate chartValues with default content. You'll be able to see the change in default config though by the Add-on Config tab though.

**Comment by davidnuzik** [comment]
**My checks PASSED**
As described [here](https://github.com/rancher/dashboard/pull/4772#issuecomment-994795874), I tested each area as mentioned and also ran our validation tests on each downstream cluster. I also smoke tested on my own accord checking that cluster provisioning v2 works as expected.
HOWEVER, I did NOT specifically test vSphere and Harvester as @anupama2501 and @slickwarren will check these areas each, respectively.
 
**Reproduction Steps:**

Already covered in my prior comment [here](https://github.com/rancher/dashboard/issues/4714#issuecomment-995284153).

-----
 
**Validation Environment:**

Rancher version: v2.6-head `39cecf0` 12/16/2021 pulled ~9:00AM Arizona time
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2 and K3S
Downstream K8s version: Various
 
**Validation steps:**

1. Create an RKE2 and K3S cluster each with k8s 1.22. Create additional ones each with 1.21. Notice, due to the changes chartValues are no longer shown in the cluster YAML. This is expected.
![image](https://user-images.githubusercontent.com/45179589/146411867-2d9882d0-21bf-42c0-bfb6-66144550bd84.png)
2. For each of these clusters, during creation switch in the UI from either 1.21 and 1.22 in the dropdown until pick the version will actually deploy with. This is to ensure the UI is working correctly whether or not we switch kubernetes versions prior to submitting the cluster creation form. All my clusters both RKE2 and K3S and versions 1.21 and 1.22 provision without any issues when single-node clusters and multi-node clusters only worked for RKE2 - for those I used a 3-pool configuration like etcd - 3, controlplane - 2, worker - 3. (Default options otherwise used during cluster provisioning). All validation tests run on RKE2 multi-node clusters only.
3. On each cluster, checked chart versions - they appear to be what they should be set to when compared to KDM. Executed validation tests on each of these downstream multi-node RKE2 clusters. Ensured that validation tests contained no unexpected failures.
4. Smoke tested on my own accord. I created additional single-node and multi-node clusters for RKE2 and manually tested addons in the UI (this is an additional change in this issue) to ensure these work as expected. I didn't identify any problems with cluster provisioning or with addons during my testing with RKE2. However, my testing was not 100% extensive.
 
**Additional Info:**
Note, during my runs of validation tests on RKE2 clusters I did encounter some failures but manually tested where necessary and saw things work correctly.
Note, to validate that addon settings actually worked, I navigated to calico settings (where I applied my addons) and ensured the config looked correct. I saw my settings (overrides) in FelixConfiguration.metadata.annotations.projectcalico.org/metadata
![image](https://user-images.githubusercontent.com/45179589/146446629-57a634ab-f35d-4ef0-9681-fde36ef87485.png)

Note, I had some issues with my multi-node k3s clusters. As these are still experimental I didn't run validation tests against them as I couldn't get a multi-node k3s cluster to come up correctly. I still did some basic checks with single node k3s clusters. The focus was primarily on RKE2 downstream clusters.

Lists of setups I checked during my testing:
- Create an RKE2 DO Kube version 1.21 instance with no custom addon config
- Create an RKE2 DO Kube version 1.21 instance with custom config
  - Use `felixConfiguration.genericXDPEnabled: true`
- Create an RKE2 DO Kube version 1.22 instance with no custom addon config
- Create an RKE2 DO Kube version 1.22 instance with custom config
  - Use `felixConfiguration.wireguardEnabled: true`
- Create an RKE2 AWS Cluster, any kube version, with custom addon config
_(Except I tested primarily with aws ec2 node driver, and one smoke test with DO node driver)_

**Comment by slickwarren** [comment]
finished validation on v2.6-head 39cecf0 for harvester:
k8s 1.21.7
* Create an RKE2 DO Kube version 1.21 instance with no custom addon config
* Create an RKE2 DO Kube version 1.21 instance with custom config
  * Use felixConfiguration.genericXDPEnabled: true
* after deployment, check that the additional config has applied (apps & marketplace -> calico -> view values.yaml) -- pass
* run automation checks -- pass

**Comment by anupama2501** [comment]
finished validation on v2.6-head 39cecf0 for vsphere:
k8s 1.21.7+rke2

Create an RKE2 vsphere Kube version 1.21 instance with no custom addon config
Create an RKE2 vsphere Kube version 1.21 instance with custom config
Use felixConfiguration.genericXDPEnabled: true
after deployment, check that the additional config has applied (apps & marketplace -> calico -> view values.yaml) -- pass
run automation checks -- pass
Upgraded both the clusters to 1.22.4+rke2, validation tests - PASS
