### ISSUE TITLE
Login to the rancher server requires 2 attempts to successfully login

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#4716]
**Setup**
- Rancher version: `2.6-head Commit ID 4375161` **Docker Install & HA**
- Browser type & version: `Chrome` Version 96.0.4664.45 (Official Build) (x86_64)

**Describe the bug**
In 2.6-head, I have to attempt login 2 times, with the `second being a successful login`. The first login looks like it is going to login, but the page refreshes, shows the loading circle, but user is returned to login page. No error is shown, and user is not logged in. Second attempt, same user & password, user logs in successfully.

**To Reproduce**
1. Login to Rancher Docker install as admin user 
2. Log out via the Avatar > Log Out menu item in the upper right corner of the app
3. fill in admin and password
4. click `Login with Local User`
5. Page refreshes and wipes out username / password (looks like it's logging in)
6. Enter same login info
7. Click `Login with Local User`
8. Login successful

**Result**
It requires two login attempts to successfully login
**Expected Result**
With correct login information, user should be logged in on first attempt. 

**Additional context**
- I've replicated this in chrome and in chrome incognito. Also confirmed that other users on QA team have seen this behavior. 
- Network tabs show a call made to logout `https://rancher-server/v3/tokens?action=logout` after the first login attempt (after setting password)
- Logs in rancher server after this `2021/12/01 15:21:27 [ERROR] Unknown error: Post "https://127.0.0.1:6443/apis/management.cattle.io/v3/namespaces/user-s29gz/preferences?timeout=15m0s": context canceled`

**Comment by nwmac** [comment]
I validated the same with 2.6-head docker install.

If I run a frontend locally and point to the same backend it is fine. Once I login with the local frontend, I can go back to the 2.6-head UI and I also no longer see the problem. Clearing cookies does not cause the problem to come back

Looking at the network tab, after the first login, we make several API requests, the first being:

/v3/users?me=true

This request and a few others after, all return 200 with a set of headers . The /v3/users?me=true returns a content-length header with a length, but the response is empty.

Instead of logging in again, once you're bounced back to the login page, modify the URL in the browser and remove the path - hit return to load this URL and it will load correctly - so it looks like the login is working, but for some reason the API calls made directly after login return empty responses and I assume we bounce back to the login page.

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Environment:**

Rancher version: v2.6.3-rc3
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Reproduction steps:**

1. Login to Rancher Docker install as admin user 
2. Log out via the Avatar > Log Out menu item in the upper right corner of the app
3. We are routed back to the login screen - fill in admin and password
4. Click `Login with Local User` to submit the form
5. Page refreshes and wipes out username / password (looks like it's logging in)
6. Enter same login info
7. Click `Login with Local User`
8. Login successful

I successfully reproduced, here is step five:
![image](https://user-images.githubusercontent.com/45179589/145275035-f1f3a1fc-0f85-4a03-9b78-e8ffa0490822.png)


-----
 
**Validation Environment:**

Rancher version: v2.6-head `b7d78a8` 12:55PM AZ time 12/8/2021
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

1. Login to Rancher Docker install as admin user 
2. Log out via the Avatar > Log Out menu item in the upper right corner of the app
3. We are routed back to the login screen - fill in admin and password
4. Click `Login with Local User` to submit the form
5. We now successfully get brought to the home page, rather than the login page again.
