### ISSUE TITLE
Not getting publicEndpoints in Workload yaml

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#481]
Steps:
1.  Create a workload
2.  Edit/View the YAML

Results:  the YAML is missing the publicEndpoint section and we need that to be able to have the Endpoint link on the list page.

**Comment by deniseschannon** [comment]
Is this related to when you create a workload with a port? Should we still be adding publicEndpoint annotation when creating it? Is this actually part of the post or something that Rancher ECM was adding?
```
    field.cattle.io/publicEndpoints: '[{"addresses":["18.216.138.97"],"port":30236,"protocol":"TCP","serviceName":"default:deniseembertest-nodeport","allNodes":true}]'
````

**Comment by deniseschannon** [comment]
This is something in that needs to be added into Steve.

**Comment by vincent99** [comment]
The annotation is added by Norman when created through the API and doesn't work/shouldn't be shown in dashboard (which is why I removed the column a while ago).

The info is correlating workloads -> services -> endpoints and will be inefficient for dashboard to figure out so it should be added by Steve as a rearionship entry or similar.

**Comment by tfiduccia** [comment]
Closing in favor of #1728.  The current way workloads work is that the port section is "just a suggestion" and doesn't really create a open port.  So Darren & Vincent agreed to get a service created and pull the port from the service.
