### ISSUE TITLE
Rollback revision list is not sorted

### ISSUE THREAD

**Issue by w1ck3dg0ph3r** [rancher/dashboard#4824]
**Setup**
- Rancher version: 2.6.3
- Browser type & version: Firefox 95.0.1

**Describe the bug**
Rollback To Revision drop down list items are not sorted by revision number or age (i.e. appears to be in random order).

**To Reproduce**
- Go to deployments page
- Select deployment that had seen multiple revisions
- Click on rollback in the dotted context menu
- Expand the drop-down list of revisions

**Result**
Revisions appear to be in random order

**Expected Result**
Revisions are sorted by revision number

**Screenshots**
![image](https://user-images.githubusercontent.com/10450851/147446220-c52dc639-1e06-4906-aa2e-1201024f4ed9.png)

**Comment by rak-phillip** [comment]
This was merged a while back, but it slipped through the cracks because I had the wrong issue mentioned in the PR. All that is fixed now.

**Comment by w1ck3dg0ph3r** [comment]
Looks good, thanks! Should I close the issue now or wait for v2.6.4?

**Comment by sgapanovich** [comment]
### Test Environment: ###
Rancher version: v2.6-head bc8260d
Rancher cluster type: single-node docker install
Docker version: 20.10

Downstream cluster type: ec2 node driver

----------

### Testing: ###
1. create a deployment 
2. set a new image in the deployment (so a new revision is created) 
3. do the step 2 a few more times 
4. on 2.6.3: revisions are not sorted 
![2 6 3](https://user-images.githubusercontent.com/40282141/151482349-93775d41-2af9-4dff-b73c-83417463d652.jpg)


 on 2.6-head: revisions are sorted 
![sorted](https://user-images.githubusercontent.com/40282141/151482358-3105e345-8507-4bde-b8bd-1c11b95f2707.jpg)



5. update the deployment to use some images used before so some revisions are removed
on 2.6-head: revisions are still sorted
![rollll](https://user-images.githubusercontent.com/40282141/151482396-96c2bd17-f104-4c66-9d1f-16304b404256.jpg)

was not able to do perform a rollback in a downstream cluster because of the issue https://github.com/rancher/dashboard/issues/4664#issuecomment-1023865839
