### ISSUE TITLE
q param in url not work when parse url in 

### ISSUE THREAD

**Issue by lishoujun** [rancher/dashboard#4847]
**Setup**
- Rancher version: 2.6.3
- Browser type & version:  Microsoft Edge | 96.0.1054.62

**Describe the bug**
param q in url like this not work
dashboard/c/c-m-xxxxxx/explorer/apps.deployment?q=push

**To Reproduce**
open workloads page
filte workloads use 'push'
copy the url and open it in new tab

**Result**
in the new tab the workloads not filted

**Expected Result**
in the new tab the workloads filted

**Screenshots**
![image](https://user-images.githubusercontent.com/8399413/147809975-d8c92bfa-4870-43c4-a46a-d50d096661bf.png)

**Comment by lishoujun** [comment]
@gaktive   
Hi  sorry to bother you.  
Is there any progress on this issue.  
Thanks

**Comment by gaktive** [comment]
We need to look backwards here to see what's going on since the q parameter had some problems as it would break on subsequent loads when there are multiple tables on a page.

We had removed it sometime ago but we may have to relook at this if this helps with a filtered page. Need to look a bit for the 2.7 time frame.

**Comment by lishoujun** [comment]
Thanks very much~

**Comment by catherineluse** [comment]
Closing as duplicate of https://github.com/rancher/dashboard/issues/6848
