### ISSUE TITLE
Incorrectly parsing Prometheus 'Duration' in Prometheus Rule Group

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4851]
A Prometheus Rule's Group `interval` / `Override Group Interval` works with a Prometheus 'Duration' which can contain a number of different time units (days, months, seconds, etc). In the UI we always use seconds, if the user edits as yaml as any other unit then we continue to assume they're seconds. 

See https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#rule_group for docs on rule group and interval

This is the same issue as raised in https://github.com/rancher/rancher/issues/35331, except there it applied to a different property. This issue would be resolved by applying the same fix as there to this other property (see https://github.com/rancher/dashboard/pull/4839)

**Comment by ronhorton** [comment]
**PASS** Verified fixed in `2.6-head Commit ID e7f03fd`

1. Provisioned downstream cluster
2. Installed monitoring
3. Created prometheus rule
4. Added Alert - Wait to fire for `10 Seconds`
5. Edited yaml for prometheus rule
6. Changed Wait to fire from 10 seconds to 10m
7. Saved
8. Checked Config in UI
9. `Minutes were correctly converted to seconds - ie, 10m = 600s`
<img width="614" alt="Screen Shot 2022-01-27 at 4 14 48 PM" src="https://user-images.githubusercontent.com/89212856/151446478-9ddf8dea-77f3-42cb-aa37-d78453eeeb4d.png">
<img width="910" alt="Screen Shot 2022-01-27 at 4 15 04 PM" src="https://user-images.githubusercontent.com/89212856/151446504-36c8d01c-d234-4e7f-847f-7bb75117a3d1.png">
