### ISSUE TITLE
[v2.6.3] Cannot use "Edit Config" on vSphere Clusters

### ISSUE THREAD

**Issue by frank-at-suse** [rancher/dashboard#4901]
**Setup**
- Rancher version: 2.6.3
- Browser type & version: Edge Version 97.0.1072.55 (Official build) (x86_64)

**Describe the bug**
"Edit Config" page hangs and does not load for vSphere clusters when using kebab menu in "Cluster Management" 

**To Reproduce**
Click on "Cluster Management" from Rancher default homepage, select a vSphere cluster from the "Clusters" list, click kebab menu to the left of the cluster name and select "Edit Config"

**Result**
Page transitions to "Edit Config" screen then immediately displays "Loading..." and the cluster cannot be edited (screenshot below).

**Expected Result**
Clicking on "Edit Cluster" would allow me to edit the cluster

**Screenshots**

From Dev Console: 

```
vue.runtime.esm.js:1888 
        
    TypeError: Cannot read properties of undefined (reading 'forEach')
    at f.get (computed.js:31:17)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.evaluate (vue.runtime.esm.js:4584:21)
    at f.cfgparam (vue.runtime.esm.js:4836:17)
    at f.r (vmwarevsphere.vue?3b47:1:9537)
    at f.t._render (vue.runtime.esm.js:3548:22)
    at f.r (vue.runtime.esm.js:4066:21)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.run (vue.runtime.esm.js:4554:22)
    at gn (vue.runtime.esm.js:4310:13)
```
Screenshot:

![CleanShot 2022-01-11 at 17 48 51@2x](https://user-images.githubusercontent.com/88675306/149033880-1f9f0e37-5da4-4c78-8abb-1be171a0e153.png)

**Additional context**
This only happens with vSphere clusters - with a cluster created from any other provider, "Edit Config" works as expected

**Comment by nwmac** [comment]
@codyrancher Can you take a look when you have capacity. Thanks.

**Comment by samkulkarni20** [comment]
@vivek-infracloud @rishabhmsra can you test this issue?

**Comment by vivek-infracloud** [comment]
**Tested this issue on rancher v2.6-head and v2.6.3.**
(Screenshot attached with the issue is of RKE2 cluster edit config, hence, I validated this issue on RKE2 and RKE1 as well.

**On rancher v2.6-head**

- Created a rancher server v2.6-head on vSphere.
- **RKE2** cluster creation with vSphere node driver fails with following error. (also fails with DigitalOcean node driver with same error)
`Failed to reconcile MachineSet: failed to retrieve RKEBootstrapTemplate external object "fleet-default"/"edit-config-testing-bootstrap-template": [rkebootstraptemplates.rke.cattle.io](http://rkebootstraptemplates.rke.cattle.io/) "edit-config-testing-bootstrap-template" not found`

- **RKE1** cluster creation with vSphere node driver is successful.
- Edit Config options allows updating the cluster.
- Hence, issue is not active for RKE1 cluster on v2.6-head rancher.


**On rancher v2.6.3**
- Created a rancher server v2.6-head on vSphere.
- RKE2 cluster creation with vSphere node driver is successful.
- Edit Config option allows updating the cluster.
- Hence, the issue is not active for RKE2 cluster on v2.6.3 rancher version.

@ronhorton Let me know if there is need of more testing.

**Comment by vivek-infracloud** [comment]
### Validated on rancher v2.6-head and v.2.6.3 with RKE2 and RKE1 clusters. Issue is not active.

After few failed attempts, RKE2 cluster provisioning was successful on rancher version 2.6-head.

`Edit Config` option allows updating the cluster.
Hence the issue is not active on v2.6-head and also on v2.6.3.

**Comment by ceesios** [comment]
please reopen this issue. I am also having this problem when creating the cluster with terraform.
I have not been able to reproduce the issue when manually creating the cluster through the webui.

below are the values that I captured with fiddler when terraform creates the cluster.

```{
  "links": null,
  "actions": null,
  "kind": "VmwarevsphereConfig",
  "apiVersion": "rke-machine-config.cattle.io/v1",
  "metadata": {
    "generateName": "nc-cluster002-master-",
    "namespace": "fleet-default",
    "creationTimestamp": null
  },
  "boot2dockerUrl": "https://releases.rancher.com/os/latest/rancheros-vmware.iso",
  "cloneFrom": "ubuntu20.04_v1.10",
  "cpuCount": "2",
  "creationType": "template",
  "datacenter": "datacenter",
  "datastore": "datastore",
  "diskSize": "20480",
  "folder": "folder",
  "memorySize": "4096",
  "network": [
    "network"
  ],
  "sshPassword": "tcuser",
  "sshPort": "22",
  "sshUser": "docker",
  "sshUserGroup": "staff",
  "vcenter": "1.2.3.4",
  "vcenterPort": "443"
}
```

and

```
{
  "links": null,
  "actions": null,
  "kind": "Cluster",
  "apiVersion": "provisioning.cattle.io/v1",
  "metadata": {
    "name": "cluster002",
    "namespace": "fleet-default",
    "creationTimestamp": null
  },
  "spec": {
    "cloudCredentialSecretName": "cattle-global-data:cc-k7zgp",
    "kubernetesVersion": "v1.21.9+rke2r1",
    "rkeConfig": {
      "upgradeStrategy": {
        "controlPlaneConcurrency": "10%",
        "controlPlaneDrainOptions": {
          "IgnoreErrors": false,
          "timeout": 0
        },
        "workerConcurrency": "10%",
        "workerDrainOptions": {
          "IgnoreErrors": false,
          "timeout": 0
        }
      },
      "chartValues": {
        "rke2-calico": {}
      },
      "machineGlobalConfig": {
        "cni": "calico",
        "disable-kube-proxy": false,
        "etcd-expose-metrics": false,
        "profile": null
      },
      "etcd": {
        "snapshotScheduleCron": "0 */5 * * *",
        "snapshotRetention": 5
      },
      "machinePools": [
        {
          "etcdRole": true,
          "controlPlaneRole": true,
          "workerRole": true,
          "machineConfigRef": {
            "kind": "VmwarevsphereConfig",
            "name": "nc-cluster002-master-kfgp5"
          },
          "name": "masters",
          "quantity": 3
        }
      ]
    },
    "localClusterAuthEndpoint": {},
    "enableNetworkPolicy": false
  },
  "status": {
    "observedGeneration": 0
  }
}
```

**Comment by codyrancher** [comment]
@ceesios the issues in this repo are specific to the UI. Can you please open a new ticket with the backend  here https://github.com/rancher/rancher

**Comment by ceesios** [comment]
@codyrancher are you sure? The issue is that the UI keeps loading. I would be happy to create a new issue however it seems to me that the issue must be resolved in the UI. The json is just to reproduce the issue.
