### ISSUE TITLE
Add configuration UI for Cluster Badges

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#4934]
Cluster badges have been added by PR - https://github.com/rancher/dashboard/pull/4933.

This issue is to add UI to allow the cluster badge for a cluster to be configured via the UI.

1. Add a link in the space next to 'Install Monitoring' -
<img width="1182" alt="Screenshot 2022-01-18 at 14 38 30" src="https://user-images.githubusercontent.com/1955897/149958180-9d8424d9-bcf6-4fcb-bc59-4db2fceff805.png">

This should say 'Add Cluster Badge' when no badge is configured, or 'Edit Cluster Badge' when it is set.

When clicking this link, a modal dialog should be displayed.

2. Modal Dialog

The modal dialog should allow the user to configure the badge for a cluster. It should contain:

A Checkbox 'Show a badge for this cluster

A preview of how the badge looks - icon, name, badge - same as shown in the header bar

The rest of the fields in the form will only be enabled when this is checked. A user can thus remove the badge when set, by unchecking this and clicked 'Apply'.

An input box for the text to show in the badge (limit 32 chars)

A color selector for the badge color. We might also want to show a few standard colors that the user can choose from (red, orange, green, blue ...)

A checkbox to allow the badge to be used for the icon.

Two buttons, Cancel, Apply - clicked apply will add the labels required to the cluster management object and save it, close the dialog.

**Comment by davidnuzik** [comment]
**My checks PASSED**
 
**Reproduction Steps:**

Not required. Is an enhancement.

-----
 
**Validation Environment:**

Rancher version: v2.6 `1d2b746` 3/3/2022
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

1. Explore the local cluster, notice the new "Add Cluster Badge" option.
2. Click the button
![image](https://user-images.githubusercontent.com/45179589/156664386-86096a64-a216-46fd-a6ea-4a8f92efa887.png)
3. A modal is shown, as expected.
![image](https://user-images.githubusercontent.com/45179589/156664435-24c013f8-2273-4643-a841-58a1ad7fe6d7.png)
4. Check off "Show badge for this cluster", a preview is shown to the right. Enter text in the "Custom description" field including unicode/emoji. This works correctly. Click apply to apply the badge.
![image](https://user-images.githubusercontent.com/45179589/156664644-19404a75-2719-4abf-9533-fde1b0e76387.png)
The browser sends a PUT request to `v3/clusters/local`. The request includes annotations on the cluster `ui.rancher/badge-color` and `ui.rancher/badge-text`. The PUT request and response content look normal. The UI immediately updates and shows the badge just like it did int he preview:
 
![image](https://user-images.githubusercontent.com/45179589/156664948-d042f637-d239-4e5b-b797-bccd925b53cd.png)
The link now reads "Edit Cluster Badge", as expected.

5. Click on "Edit Cluster Badge" and modify by overriding the icon with some custom text like pictured below:
![image](https://user-images.githubusercontent.com/45179589/156665105-b1bad4a2-58bc-4ccd-a5ef-a764e9e3d15c.png)
6. Click Apply and the PUT request and response appear normal. Another annotation is added: `ui.rancher/badge-icon-text` which contains the contents "DN" just like sent. The UI immediately updates and shows this content. The field limits this to two characters max including spaces and unicode (like emoji)
![image](https://user-images.githubusercontent.com/45179589/156665284-66cf867b-5458-4e02-b741-c06527fd4cb9.png)

7. Edit the badge again, now uncheck "Show badge for this cluster" this works as expected. The UI immediately updates and no longer shows the badge. The PUT request again looks normal. UI annotations are not included in the request body and response body.
![image](https://user-images.githubusercontent.com/45179589/156665417-870a6e09-b311-4429-a642-37c628f4333f.png)

8. Additional Tests and information:
- Custom Description is limited to 32 chars. If use full 32 chars sometimes the content is cut off by Vue:
![image](https://user-images.githubusercontent.com/45179589/156665616-7cc72420-ed38-4bf2-807d-5cd7e57936e5.png)
This also happens once submitted - the UI shows this cut off:
![image](https://user-images.githubusercontent.com/45179589/156665679-2131a23c-4340-453a-b419-6572c35bad31.png)
**I filed a bug for this, but I personally consider this a low priority matter... See Additional Info section below.**
- The Customize Cluster Icon is supposed to limit to two chars but with some unicode/emoji it only allows one - probably because of how some codes work and their length:
![image](https://user-images.githubusercontent.com/45179589/156665886-b2bafd81-18ff-436d-bbc8-f234521474e1.png)
- Tried various colors and custom colors -- all seem to work correctly.
If I try to enter invalid hex the UI will show it in the field but won't post it, it just uses the last value picked by cursor. This makes sense to me. (Looks like this is controlled by the browser?)


**Additional Info:**
Here is the bug I created for the issue where the custom description can get cut off by Vue:
https://github.com/rancher/dashboard/issues/5293
