### ISSUE TITLE
Update no git repo landing page.

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#4952]

**Comment by Jono-SUSE-Rancher** [comment]
Hey @Shavindra - Can you do me a favor and put a few details in this ticket on what specifically should be validated by the QA team? I am hesitant to assign this a QA resource because I don't really know what they can validate. I realize there are some updates going to the git repo landing page....but what are they? :)

**Comment by Shavindra** [comment]
@Jono-SUSE-Rancher Designs are still being finalised. I've added this ticket as a placeholder for now. Once designs are finalised I will update the ticket. 

CC: @nwmac

**Comment by nwmac** [comment]
![image](https://user-images.githubusercontent.com/1955897/152501379-c0ea6584-fcaf-4055-be2f-8c8414d736bf.png)

**Comment by davidnuzik** [comment]
I don't see this change on v2.6-head pulled today - commit `8c785a1`

![image](https://user-images.githubusercontent.com/45179589/155430803-19a15702-810c-4adb-898a-4860f9da4d7e.png)

**Comment by davidnuzik** [comment]
Also the issue should have a description.
