### ISSUE TITLE
Cluster Manager and Cluster Dashboard show different age for same cluster

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4966]
Internal reference: SURE-3800

Issue description:
The Cluster Dashboard and Cluster Manager are not showing the same age for the cluster. For example, Cluster Dashboard shows cluster was created 561 days ago, whilst Cluster Manager shows the same cluster as 56 days old. 

Business impact:

Confusion as to when the cluster was created.

Troubleshooting steps:

Checked that environment was upgraded from Rancher v2.5.9 to 2.6.1 56 days ago, so likely something with the upgrade reset the cluster age for the cluster management.

Repro steps:

- Install Rancher v2.5.x.
- Deploy a downstream cluster
- Wait a few days
- Upgrade to Rancher v2.6.x
- Wait a few more days
- Check the downstream cluster in cluster management and cluster dashboard

Actual behavior:

Age of cluster does not match between cluster management and cluster dashboard after rancher upgrade.

Expected behavior:

Age of cluster should match

**Comment by aalves08** [comment]
@richard-cox this looks like a BE issue to me:

- `AGE` header defined here: https://github.com/aalves08/dashboard/blob/master/shell/config/product/manager.js#L137-L168 uses `LiveDate` formatter
- `LiveDate` formatter doesn't change any values coming from the BE... Only does the math to compute to the date from "now" https://github.com/aalves08/dashboard/blob/master/shell/components/formatter/LiveDate.vue

**Comment by richard-cox** [comment]
@aalves08 The cluster resources will differ a lot between old (norman cluster) and new (home page mgmt clusters vs cluster management provisioning clusters) ui's. We need to tie down which resources show as different. From that we should get a better understanding of the scenario where the date could differ a lot. We'll then probably need to discuss with BE

**Comment by aalves08** [comment]
@gaktive had some help from BE (slack thread [here](https://suse.slack.com/archives/C02CX064EBX/p1652881540619519)):

> There is a new object ([clusters.provisioning.cattle.io](http://clusters.provisioning.cattle.io/)) in 2.6 that wasn't in 2.5. The Cluster Management page displays this new object. Since that object was created when they updated to 2.6, that would explain the age.

Since the 56 days count is exactly the count from the day the client upgraded, I believe this might just be the root cause for the issue. If you check SURE-3800, the Cluster Management is exactly where the 56 days are displayed.

On the FE side we don't modify the data (age) from my investigation. (check [here](https://github.com/rancher/dashboard/issues/4966#issuecomment-1126237612))

Not sure what should be the next steps here @gaktive . Will wait for further indications.

FYI: @richard-cox

**Comment by richard-cox** [comment]
This one needs discussing with the team. When the steve mgmt cluster / norman cluster 's radically differs from the steve provisioning cluster we could
- show a custom age component covering both times (create x, upgrade y)?
- just show the original resource age and ignore the prov cluster's ago?

**Comment by markusewalker** [comment]
@aalves08 could you please provide a test template for this issue? I noted that in the issue description that several days are needed before upgrading? We're hoping to get further context so that I can properly validate this issue better and if, by chance, days are not needed, I can test this issue sooner.

Thanks in advance!

**Comment by aalves08** [comment]
Hi @markusewalker . I was able to "mock" this for development purposes by hacking the code, then working on the fix... Unfortunately I don't see any other way via the UI that doesn't involve waiting a  couple of days after installing Rancher v2.5.x (so that you can check the Age column with something like 2 days)

Some time can be "shaven" because you don't need to wait a few days after upgrading to 2.6.X (you can already check the outcome).

Also SURE-3800 provides more context into this, be sure to check that.

**Comment by markusewalker** [comment]
Verified on `v2.6-head` https://github.com/rancher/rancher/commit/c8d01c681cdaf9ed8f4d5e0f86c18681848d0734.

**ENVIRONMENT DETAILS**
- Rancher - Docker Install
- Rancher version
     - Verified version: `v2.5.14` -> `v2.6-head` https://github.com/rancher/rancher/commit/c8d01c681cdaf9ed8f4d5e0f86c18681848d0734

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher `v2.6.5` and navigate to the UI in a browser.
2. Created a standard user and logged into Rancher as that standard user.
3. Created a downstream RKE2 node driver cluster.
4. Once it successfully provisioned, waited for 7 hours before returning to the cluster.
5. After the time has elapsed, upgraded Rancher to `v2.6-head` https://github.com/rancher/rancher/commit/c8d01c681cdaf9ed8f4d5e0f86c18681848d0734.
6. In the UI, navigated to Cluster Manager and noted the time of the cluster:
![image](https://user-images.githubusercontent.com/52591819/173465537-3b1ebb60-d246-4d6c-9270-9658c450036f.png)
7. Navigated to Cluster Dashboard and noted the time matches what I saw above:
![image](https://user-images.githubusercontent.com/52591819/173465525-90f1e6f5-d47e-4504-b86b-7169a3762274.png)
