### ISSUE TITLE
Cluster Tools requires the same OS indicators as the Charts page

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/dashboard#4983]
~~OS filtering was added to the Charts page in https://github.com/rancher/dashboard/pull/4639 but not to Cluster Tools. This causes a confusing user experience as there are three Windows-compatible charts listed under the Charts page in a Windows cluster while all of the Rancher charts are listed under Cluster Tools in the same cluster.~~

Updates per Teams  cross-team meeting:
Rather than filtering charts there will strictly be visual indicators of OS compatibility. The Cluster Tools page should have the same indicators as the Apps and Marketplace pages: rancher/dashboard#5137 **Unless the legacy feature flag is enabled**, in which case the banner will not be shown as it does not apply to v1 tools.

**Comment by phillipsj** [comment]
Initial testing with Rancher 2.6-head (1d2b746) produced the following results.

![image](https://user-images.githubusercontent.com/1568133/156246824-0154daf0-930e-48d8-93fd-57f2410d901a.png)

**Comment by phillipsj** [comment]
## Rancher Version: 
2.6-head b26b920

## Steps to reproduce

1. Deploy Rancher
2. Create a custom RKE2 cluster with RKE2 1.22.7
3. Register a linux controlplane, linux worker, and one windows node.
4. Once registered navigate to the cluster in the cluster explorer
5. Open cluster tools

## Outcome

Cluster tools isn't displaying any labels on the cards related to the deploys-on OS annotation.

![image](https://user-images.githubusercontent.com/1568133/157324147-97f822d5-df65-419a-9c6b-b660930bc852.png)

The Apps and Marketplace is displaying correctly.
![image](https://user-images.githubusercontent.com/1568133/157324209-7ecd3985-ea11-4a14-bcf0-012177126679.png)

**Comment by PennyScissors** [comment]
Checks based on QA's test plan: **FAIL** (see below)
Rancher v2.6.4-rc11


PASS - Apps & MarketPlace: Only monitoring v2 and Logging v2 charts should have labels Deploys on Windows
![image](https://user-images.githubusercontent.com/8951271/159813285-127fda3a-c1ef-4128-a274-cb2c3e98cd15.png)

PASS - Apps & MarketPlace: All partner charts to have Linux only label
![image](https://user-images.githubusercontent.com/8951271/159813334-c05f1aeb-2905-4987-bc94-fbe8d3b741a3.png)

PASS - Cluster Tools: Only monitoring v2 and Logging v2 charts should have labels Deploys on Windows
![image](https://user-images.githubusercontent.com/8951271/159813356-9fb6b5ce-340c-44d7-96c7-9c6997763ef1.png)

PASS - There should be an icon to show that other charts versions (older ones) do not deploy on Windows in the charts install page.

hover on older rancher-logging version
![image](https://user-images.githubusercontent.com/8951271/159813861-b8d9c08c-a943-45cd-be5a-35d8f65ff654.png)

message on older version's chart page
![image](https://user-images.githubusercontent.com/8951271/159813931-1d2687a6-9b2b-4cf7-afc7-c20620c6be5c.png)

**Comment by mantis-toboggan-md** [comment]
I've borrowed Steven's setup and was unable to repro this - looking at the `userpreference` object it seems the visibility of that banner was toggled off so the TypeDescription component is behaving as expected. Probably an accidental click or another person with access to that account clicking it off. 
I'll file a separate issue for a later release regarding a) how easy it is to misclick that banner (it's very close to other buttons) and b) how type descriptions can't be toggled back on through the UI at all.

**Comment by PennyScissors** [comment]
**PASS** - Message "All charts have at least one version that is installable on clusters with Linux and Windows nodes
unless otherwise indicated." Should be displayed in Apps & MarketPlace → Charts page and the charts install page.

Note: I could only reproduce by intentionally pressing the `x` to close the banner which then made it disappear from all places, so I'll blame accidental misclick on my part for this one. Thanks for checking on this @mantis-toboggan-md !

Banner in Apps & Marketplace:

![image](https://user-images.githubusercontent.com/8951271/160174830-2d9c165d-9ba0-407f-8b9f-bd176a212a36.png)


Banner in chart's page:

![image](https://user-images.githubusercontent.com/8951271/160175136-c2525cf7-98c4-4ac5-adbf-6aedc3d0bf41.png)


Banner in chart's install page
![image](https://user-images.githubusercontent.com/8951271/160175413-d21f432a-87cc-43aa-afab-108fa8ab01c7.png)
