### ISSUE TITLE
The `Apps > Repositories` list should display the name given to the cluster repo

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#5039]
**Setup**
- Rancher version: v2.6-head
- Browser type & version: Any

**Describe the bug**
The `Apps > Repositories` list should display the name given to the cluster repo rather that displaying "custom" names for particular repo names assigned

**To Reproduce**
- Go to `Apps > Repositories`
- hit `Create`
- create a new git repo with the following information:
*name*: rancher-charts
*Target*: git repository
*git repo url*: https://git.rancher.io/charts
*git branch*: dev-v2.6

- hit `Create` again
- create a new git repo with the following information:
*name*: some-repo
*Target*: git repository
*git repo url*: https://git.rancher.io/charts
*git branch*: dev-v2.6

check the difference in names on the list view

**Result**
Will create a new repo, which will display a label of "Rancher" on the list view
<img width="1684" alt="Screenshot 2022-02-03 at 16 43 49" src="https://user-images.githubusercontent.com/97888974/152389305-97a468c9-7df7-4425-83d5-8f240bd685bd.png">

*details*
<img width="1684" alt="Screenshot 2022-02-03 at 16 44 01" src="https://user-images.githubusercontent.com/97888974/152390298-e7c0a73e-adae-4d5f-ace0-52a730262c87.png">

**Expected Result**
Should display the name `rancher-charts` rather than a "custom" name `Rancher`

**Additional context**
Imo, we should maintain consistency. If a differentiating aspect is needed, some icons could appear next to name on the list view.

**Comment by vincent99** [comment]
These are special cased becausee we wanted the install screen to offer Rancher vs Partner even though that's not really the name of the repos (and they can't have capital letters in the name).  If you put in your own regular entree you get the name you entered.

**Comment by richard-cox** [comment]
Gonna close this one as not planned. The conversion from `rancher-charts ` to `Rancher` (whatever vendor is) and `rancher-partner-charts` to `Partners` was intentional for readability reasons. 

Thought about editing the translations to be `Rancher (rancher-charts)` but that's just messy.

For code see [nameDisplay](https://github.com/rancher/dashboard/blob/master/shell/models/catalog.cattle.io.clusterrepo.js#L116) and the [translations](https://github.com/rancher/dashboard/blob/master/shell/assets/translations/en-us.yaml#L991).
