### ISSUE TITLE
Not obvious how to view previous container logs

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5075]
To view the previous logs for a container logs you have to use an option via the cog icon - this is not intuitive.

UX to look at a better way to do this.

![image](https://user-images.githubusercontent.com/1955897/153008941-84b66a80-a6a3-4995-ab7a-668d8326f7fa.png)

**Comment by lvuch** [comment]
wip https://xd.adobe.com/view/e8fa8bee-01e8-4035-9145-79a6482669f0-bda9/

**Comment by lvuch** [comment]
link updated: https://xd.adobe.com/view/e8fa8bee-01e8-4035-9145-79a6482669f0-bda9/

**Comment by nwmac** [comment]
We'll get feedback on the change made in 2.6.4 and re-open if needed

**Comment by stefanhoth** [comment]
Thank you for mentioning it here and improving on it. I needed this ticket to notice the small checkbox underneath the logs.

Would it be worth considering adding another entry to the "View Logs" actions? 
Logs->
- Current
- Previous

At least this would make it intentional as you're usually looking for the one or the other, not both, right?
