### ISSUE TITLE
Projects/Namespace view does not respect filter

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5088]
When on the Projects/Namespaces view, selecting a project or namespace in the filter in the header does not filter what is seen.

The filter is really designed to filter the set of resources seen when they are namespaced resources.

We should consider the UX here.

**Comment by gaktive** [comment]
Internal reference: SURE-4094

**Comment by catherineluse** [comment]
Should it say at the bottom of the list "not showing {count} filtered namespaces"?

**Comment by catherineluse** [comment]
Jameson McGhee pointed out that there is a discrepancy in the "Not in a Project" namespaces list in the tables vs. the top nav dropdown menu. He provided this screenshot:

![image](https://user-images.githubusercontent.com/20599230/179089939-670e65cc-c0d9-4316-ac7a-858855f7d1b0.png)


The projects/namespaces list view has code in it that intentionally filters out namespaces that are marked with an "isObscure" flag: 

https://github.com/rancher/dashboard/blob/master/shell/pages/c/_cluster/_product/projectsnamespaces.vue#L164

@mantis-toboggan-md Do you know if it was intentional to hide obscure namespaces in the table but the top nav? Should those namespaces also be filtered out of the top nav?

**Comment by mantis-toboggan-md** [comment]
I doubt that was intentional @catherineluse though I don't know for sure. I don't think we need to be filtering the table behind the scenes at all when we already have a namespace filter that hides system namespaces by default. The table is filtering out everything that starts with one of:  `[ 'c-',  'p-',  'user-', 'local', ]` while the ns filter appears to be using more complex logic that wouldn't lead to someone inadvertently hiding their own namespace: 
```
  get isSystem() {
    if ( this.metadata?.annotations?.[SYSTEM_NAMESPACE] === 'true' ) {
      return true;
    }

    if ( SYSTEM_NAMESPACES.includes(this.metadata.name) ) {
      return true;
    }

    if ( this.metadata.name.endsWith('-system') ) {
      return true;
    }

    if ( this.project ) {
      return this.project.isSystem;
    }

    return false;
  }
```

**Comment by jameson-mcghee** [comment]
I am setting this ticket to Reopened until the changes that @catherineluse mentioned have been implemented.

cc @sowmyav27

**Comment by jameson-mcghee** [comment]
This appears to be functioning as designed in v2.6-head. Therefore I am closing this ticket.

![image.png](https://zube.io/files/rancher/4cc0eb8ff0b91a565ef0e041eb3274ea-image.png)

**Comment by richard-cox** [comment]
Internal reference: SURE-5066
