### ISSUE TITLE
Standard user with restrictive role granting access to Flows cannot see Flows

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5138]
*Issue description:*
The ability to view Flows in the Cluster Explorer Logging view, requires permissions not just on the `flows.logging.banzaicloud.io` resource but also (unexpectedly) on the `clusteroutputs.logging.banzaicloud.io`

*Business impact:*
Cannot grant user ability to view Flow resources without also enabling them access to ClusterOutput resources

*Troubleshooting steps:*
N/A

*Repro steps:*

- Provision a Rancher instance with a single node downstream custom cluster (I used github.com/superseb/tf-do-rancher2)
- Install the logging chart
- In the Logging UI create a simple test syslog output and a simple test flow to this output
- Create a custom Cluster role than inherits from Cluster Member and grants all verbs on `flows.logging.banzaicloud.io` and `outputs.logging.banzaicloud.io`
- Create a test user and grant the user the custom cluster role on the custom cluster
- Login as the test user and navigate to Logging view of the Cluster Explorer UI, note output and flow are shown on the overview page, and output is visible on Outputs page, but Flows page is empty
- As admin user add all verbs on `clusteroutputs.logging.banzaicloud.io` to custom cluster role
- As the test user observe flows are now visible in the Flows page of the Logging view

*Workaround:*
None

*Actual behavior:*
A user requires only grant on flows.logging.banzaicloud.io resource to view flows

*Expected behavior:*
A user also requires grant on clusteroutputs.logging.banzaicloud.io resource to view flows

Files, logs, traces:
N/A

Additional notes:
Internal reference: SURE-3521

**Comment by superseb** [comment]
Discussed with @catherineluse that this is a dashboard issue.

**Comment by catherineluse** [comment]
Yes, Seb is right - I believe this is a dashboard issue after all. I'm pretty sure the root cause of this issue has nothing to do with logging - it's actually this more general issue with the role creation form. That form is getting fixed and enhanced in v2.6.4 though. Those changes should fix this issue as well. https://github.com/rancher/dashboard/issues/4315

**Comment by catherineluse** [comment]
# QA template

### Root cause

When creating a role in the role creation form (in any scope, global, cluster or project/namespace), if you selected Flows from the resource dropdown, and created the role, the resulting role did not include any API group. Without the API group, the role was not sufficient to give the user permission to see Flows. In the case of Flows, `logging.banzaicloud.io` should be filled in.

The Flows form also had issues where it tried to list ClusterOutputs even if you don't have permission to see them. I added something to check if you have permission to see ClusterOutputs before it tries to load them, so it no longer panics.
 
### What was fixed, or what changes have occurred

In v2.6-head, when you select a resource from the resource dropdown, its API group is automatically populated in the form. 

The exception is for resources in the core Kubernetes API, such as ConfigMaps, in which the API group is supposed to be an empty string.
 
### Areas or cases that should be tested

To test that the permissions issue is fixed,
1. Install the logging application on any cluster and create a couple of Flows.
2. Go to Users & Authentication > Roles > Cluster > Create Cluster Role.
3. Create a cluster role where the rule grants access for all verbs for the Flow and Output resources. (You need an Output to use Flows properly, but you should not need a ClusterOutput.) When flow is selected, `logging.banzaicloud.io` should be filled in.
4. Create a standard user.
5. In cluster manager, go to the cluster where logging is installed, click Edit Config and assign the role to the standard user.
6. Log in as the standard user.
7. Go to Cluster Explorer > Logging > Flows. Confirm that the standard user can see the Flows. Note: May need to filter by all namespaces to see the Flows.
 
### What areas could experience regressions?

Creating/editing roles, role detail pages
 
### Are the repro steps accurate/minimal?

Yes, it's mainly just making sure you can see Flows and Outputs without having access to cluster scoped stuff like ClusterFlows or ClusterOutputs.
