### ISSUE TITLE
Provide user feedback for image file upload

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#5184]
**Detailed Description**

Provide user feedback for image file upload when used within the form:

- **Weight**, user is not informed
- **Format**, we may restrict the upload, but the user is not informed
- **Proportions**, images may not be square, nor we crop them
- **Limitations**, in some cases we set `20000` in others `200000`, while server triggers EOT error

Issue: on image limitation, no feedback is provided and the image is not added

**Context**

While uploading images, we do not provide these information, nor any feedback related to server communication.

#### Navlinks

- Path: `/c/local/explorer/ui.cattle.io.navlink/create#group`
- How to reach:
  - Search for resource `navlink`
  - Create new resource
- Custom component adopted: `FileImageSelector`

![Screenshot from 2022-02-22 17-56-14](https://user-images.githubusercontent.com/5009481/155180514-2365e13d-a992-4aa4-a382-5ec5559dc068.png)

#### Global Settings> Branding > Logo

- Path: `/c/local/settings/brand`
- How to reach:
  - Open global settings
  - Navigate to Branding
  - Scroll to Logo settings
  - Enable "Use a custom logo"
  
![Screenshot from 2022-02-22 17-58-04](https://user-images.githubusercontent.com/5009481/155181248-d2024041-3f84-495c-8913-c46ced58ace0.png)

**Comment by eva-vashkevich** [comment]
Hi @cnotv , could you please clarify if what we have for Branding/logo is sufficient and we should do the same for NavLink or if we want to enhance both places.
Thank you,
Eva

**Comment by cnotv** [comment]
For the UI details you should coordinate with @kwwii 
When I created the issue, I just mentioned that were missing the parameters information. It is unknown which format, size and max weight the user has to upload, as defined in the issue.
There's also no feedbacks in the UI in case of errors.

**Comment by richard-cox** [comment]
@eva-vashkevich This has a 2.7.x milestone and is linked to a PR marked as 2.7.x. Can you confirm which version the fix was shipped with and update both milestones? We also need to consider how to get this passed QA

**Comment by eva-vashkevich** [comment]
@richard-cox this went in July, so I think it is part of 2.7. Not sure why it is not tested yet.

**Comment by richard-cox** [comment]
@eva-vashkevich it needs to have a specific version. v2.7.x is generic and won't show up in filters QA look at

**Comment by gaktive** [comment]
@richard-cox or @eva-vashkevich as we evaluate things for 2.7.next1, remind me: is this also fixed in 2.8.0 or later? This may need a forward port if so but I can't tell which branch this wound up in. If this is already in 2.8.0, then I'd lean towards having that fixed there and not worry about this ticket and maybe just update the milestone.

(This tells me I need to look over the other 2.7.x tickets but I'll deal with what I know about elsewhere.)

**Comment by richard-cox** [comment]
@gaktive The change was merged to master in July sometime in the 2.7.x releases. So it should appear in release-2.8.0 and the go forward master branch. 

The issue was that the milestone in both gh issue and pr had an incorrect milestones (2.7.x) so did not go through QA. So this issue just needs that part to complete the process.

**Comment by izaac** [comment]
Unit test coverage looks good I don't feel inclined to have any E2E on this one unless @yonasberhe23 has anything to chime in.

This Branding Image uploads is similar to other issues we reviewed in the past and it could be a good case for visual testing using cypress in the future.
