### ISSUE TITLE
Read EC2 instance types from API for RKE2 clusters

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#5190]
- When creating an Amazon EC2 RKE2 cluster the options for instance type are hardcoded
- These should come from Amazon's API directly

**Comment by catherineluse** [comment]
Vincent's PR successfully updated the list of EC2 instances for K3s/RKE2 https://github.com/rancher/dashboard/pull/5103

However, another PR also needs to be made to the Ember UI so that when you create a node template, the iFramed form will also use the updated list.

<img width="1389" alt="Screen Shot 2022-02-23 at 1 00 45 PM" src="https://user-images.githubusercontent.com/20599230/155402800-2788759c-89f4-4e6a-bade-630f9c00da97.png">

**Comment by Auston-Ivison-Suse** [comment]
**Setup For Validation**
Rancher Server: 2.6-head(ec4b26b)
Google Chrome: version: 99.0.4844.51

**Notes**

If I'm to understand, the iframe means it isn't actually coded into the rancher, so observing the change is done is enough. 

**ScreenShots**
![Screen Shot 2022-03-04 at 5.21.34 PM.png](https://zube.io/files/rancher/efcdcf25b817511eebb4bb009eaefe0c-screen-shot-2022-03-04-at-5-21-34-pm.png)

**Comment by catherineluse** [comment]
No, the list of instances in the cluster creation form is not iFramed. However the list of instances in the RKE1 node template form is iFramed.

The list in the cluster creation form is affected by this PR that was made to the dashboard. The list in the RKE1 node template form will have to be updated in a separate PR made to the Ember UI in the rancher/ui repo.
