### ISSUE TITLE
During installation workflow, add banner warning that Docker install is for testing and development only

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5256]
I have opened this issue due to conversations in Slack about how many issues could be prevented if users would use the Helm CLI install instead of the Docker install.

Kyle Rome said that in pre-sales, there are many cases where potential customers have all kinds of issues and bugs, then it turns out they are caused because they are using the Docker install.

Ryan Hunt also noticed that the Docker install creates bugs that ruin the user experience. For example, when users had Rancher installed with Docker and they upgraded to Rancher v2.6.3, they encountered a bug where it looked like all their clusters disappeared. https://github.com/rancher/rancher/issues/35955 There was a workaround, but ideally those users should never try to upgrade the Docker install of Rancher because that install is not meant for production use.

The docs already state in multiple places that the Docker install is meant only for testing and development, but there are still too many people using it. A banner would help more people understand that the Helm CLI install is the way to go.

The banner should link to docs on how to migrate Rancher to the Helm install https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/

**Comment by ajacques** [comment]
I'm guessing this is partly because of a blog post I wrote. At least, I was using the Docker single node install because it has been super easy to install and HA mode has always appeared to involve quite a bit of work, along with inertia (I was doing this since 1.6, I'll keep doing it like this to avoid breaking anything), I suspect many other small installs feel the same.

It suffers from the bootstrapping problem--how do you go from nothing to something? Sure, [this page](https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/) details how to do this. But hose new to K8s, get confused on what to go with. I know I would if I was starting from scratch, after running it for a while I could probably follow the instructions, but the Docker single node install was one command and I'm basically done. But then if I do that, the single node -> HA mode became a bit daunting (partly because I don't want to lose my cluster which I have a local and downstream installed.)

**Comment by catherineluse** [comment]
You're right that the Docker install is much simpler. We have ongoing efforts to make it simpler and easier to install Rancher on Kubernetes (see RancherD https://github.com/rancher/rancherd). Until then, we need to make it more obvious that the Docker install should not be used for anything important.

**Comment by catherineluse** [comment]
Product management would need to approve this change though, because that banner would cause a problem for someone who is using Docker in production. But it's a matter of balancing inconvenience to those users versus tackling the ongoing technical problems and bad user experience that the docker install creates.

There are other changes that should be made along with this, such as warning in the docs and release notes that upgrading the docker install is not a good idea. We could also document how to use a temporary domain name to make the helm install easier for testing purposes, among other thing. I've opened an issue in rancher/docs about it.

**Comment by KornKalle** [comment]
I think there are many docker installations out in the wild, doing their job flawlessly. 
For smaller companies it is a lot more expensive to run Rancher in HA + it was a pain setting it up prior to Rancher 2.5, the Docker install provides a very fast start, and in most cases it seems to be stable. 
I encountered enough Docker setups which are used in production by companies which either won't be able to pay for the HA infrastructure or fear the effort to migrate to HA.

**Comment by catherineluse** [comment]
Point taken about the effort to migrate. But be clear, I'm not saying the banner should come up if you have Rancher running on a single node. This issue is about installing with the Helm CLI vs. Docker. A single-node Helm CLI install is still more stable and maintainable than the Docker install, and would cost the same amount.

**Comment by catherineluse** [comment]
We could limit this banner to only the installation flow when someone is installing Rancher for the first time so that it would not disrupt anyone already using the Docker install to manage clusters.
