### ISSUE TITLE
Disable autocompletion in Rancher Cluster Editor

### ISSUE THREAD

**Issue by HoustonDad** [rancher/dashboard#5273]
**Rancher Server Setup**
- Rancher version: 2.5

**Describe the bug**
A global configured private registry setting was created via Rancher. Upon editing another cluster, the private registry username and password were being autofilled in the UI by the users browser autofill for passwords (Rancher username/password). When clicking 'edit as yaml', those auto-filled fields were being translated into the YAML configuration. 

This brought the impression that when adding that private registry, Rancher somehow automatically added those saved credentials (which turned out to be the local user credentials for the Rancher cluster), to not only the local cluster, but auto applied to every other cluster in Rancher MCM. 

It would be useful to disable auto-completion either on the form level, or just on those fields (and any other credential fields in the form) to ensure auto filling does not accidentally populate fields not expected by end users.

**To Reproduce**
1. Edit Cluster Config (Rancher UI -> Cluster -> Edit)
2. Fill out private registry info with random stuff
3. Click 'Edit as yaml'
4. Note that random stuff is present in YAML

**Result**
YAML configuration provided in editor is the state of the form provided in the UI before clicking 'edit as yaml'

**Expected Result**
YAML configuration provided in editor is the cluster state

**Additional context**
The reverse does not happen. If you 'Edit as YAML', manually add the fields in YAML format, and click 'Edit as form', the fields added in the YAML editor are *not* translated to the form.

**Comment by nayrnet** [comment]
I had a client complain that they had edited an existing template and had credentials autofilled in without their knowledge which broke things since those credentials were not valid.

Would like to see if we can come up with a reasonable solution to prevent these extentions/tools from messing with these fields to improve the user experience and reduce opportunity for these kinds of issues.

**Comment by abonillabeeche** [comment]
Can we have an update on this issue?

**Comment by kwwii** [comment]
This sounds like an issue with a given browser than a problem with Rancher UI. As Vince mentions, this might very well be a desirable thing for many users. Do we have any additional information on how many users have reported similar issues? (Changing this for a handful of users because of their choice of browser/configuration is probably not the right way to go.)

**Comment by catherineluse** [comment]
What if instead of trying to disable it, we just try to notify the user that it has happened? I figure the problem is not really that fields are auto-filled, it's that the user didn't notice. So if we can detect that a field has been autofilled, we could show some kind of warning to the user along the lines of "Some information was autofilled by your browser. Is this correct?"

I found some discussion on detecting autofills here. https://stackoverflow.com/questions/11708092/detecting-browser-autofill

**Comment by mallardduck** [comment]
After some extensive testing for a customer I've found that the likely culprit here is Chrome itself. I use a proper password manager and was not seeing the issue being reported even with auto-fill fully enabled. In my case this password manager is Bitwarden - so it may vary based on the password manager in use.

However, once I added credentials for Rancher into Chrome's built-in Password Manager the issue happened immediately. So from those findings it became clear that Bitwarden does respect the `autocomplete="off"` attribute Rancher set's on these inputs. However, Chrome itself is what is ignoring the attribute to disable auto-complete.

So as a workaround for users facing this issue, please try:

1. Setup a real password manager for your credentials,
2. Add the Rancher credentials into your new password manager, and
3. Remove the Rancher credentials stored in Chrome's Password Manager.

Note: you may be able to skip to step 3 if you already use a real PW manager.

**Comment by richard-cox** [comment]
Unfortunately taking on browser's handling of autocomplete isn't something planned at the moment
