### ISSUE TITLE
Create v2prov clusters in dedicated namespaces

### ISSUE THREAD

**Issue by Oats87** [rancher/dashboard#5295]
Today, the v2prov UI will create new clusters in the `fleet-default` namespace. This is not scalable, and new clusters should be created in a dedicated namespace for each cluster.

**Comment by snasovich** [comment]
@nwmac , heads-up as this is something we may want to do depending whether we can resolve some issues related to it.

@Oats87 to provide updates. We also need to agree what that namespace should be.

**Comment by snasovich** [comment]
@Oats87 , after discussing with @thedadams it looks like we're not ready for this due to https://github.com/rancher/rancher/issues/36132 ?

Is this correct understanding?

Even disregarding this, I think it's too late for such a drastic change to make it into 2.6.4. Changing milestone to 2.6.5 for now - let me know if you insist on it being in 2.6.4.

**Comment by gaktive** [comment]
Backend now moved to 2.6.6 so will do so here too.

**Comment by gaktive** [comment]
Backend work is now unscheduled.

**Comment by gaktive** [comment]
Duplicate of https://github.com/rancher/dashboard/issues/9730, which was solved in 2.8.0 as connected to https://github.com/rancher/rancher/issues/36132, as I understand. Closing.
