### ISSUE TITLE
Should always show 'Not in a Project' group on the Projects/Namespaces page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5322]
In order for a user to be able to create a namespace that is NOT in a project, they use the 'Create Namespace' button that is part of the 'Not in a project' group - which is only shown if there are namespaces not in a project.

We should always show the 'not in a project' group.

**Comment by nwmac** [comment]
Internal Reference: SURE-4238

@richard-cox You got time to take a quick look at this - should be fairly straight forward?

**Comment by Josh-Diamond** [comment]
@richard-cox Could you please provide a QA template for this?  Or at the very least, the versioning and reproduction steps? Thank you!

**Comment by catherineluse** [comment]
Adding the QA template at Josh's request since Richard is OOO.

This is more of a functionality change or feature than a bug fix. The Rancher version with the behavior we wanted to change was 2.6.3.

## QA Template

### Root cause

Currently in cluster explorer, the Projects/Namespaces has the "Not in a Project" group at the bottom:
<img width="1495" alt="Screen Shot 2022-03-30 at 3 40 24 PM" src="https://user-images.githubusercontent.com/20599230/160942916-538d517c-6512-4c08-8819-f44dfec46959.png">

It's nice that there's a Create Namespace button there so you can easily create a namespace that is not in a project. The problem was that when all namespaces in that group were deleted, the whole section disappeared. So a user could get the misleading impression that it was not possible to create a namespace outside the project.
 
### What was fixed, or what changes have occurred

Richard made it so that the "Not in a Project" group is always displayed even if it is empty.
 
### Areas or cases that should be tested

1. Should go to cluster explorer and click Projects/Namespaces in the side nav.
2. Delete all namespaces that are not in a project
3. Confirm that the group is still there and you can still use the Create Namespace button
 
### What areas could experience regressions?

The list view for projects/namespaces

**Comment by kwwii** [comment]
Any of the Namespace creation buttons will allow you to create a Namespace assigned to ANY or NO Projects. The different Create Namespace buttons only pre-seed the Project Name from the table row in the Project field of the creation UI.

I opened https://github.com/rancher/dashboard/issues/5558 to address the larger issue.
