### ISSUE TITLE
Cluster Overview: Incorrect Kubernetes Version 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#534]
Instead of k8s version, it's showing `Rancher RKE`

<img width="215" alt="Screen Shot 2020-04-20 at 8 55 07 PM" src="https://user-images.githubusercontent.com/11410997/79823736-48799400-8349-11ea-8d34-b2d00bf0f3fc.png">

**Comment by deniseschannon** [comment]
@westlywright For an imported cluster, how come the k8s version says "Unknown"? 

In ember, we were able to determine this.

**Comment by westlywright** [comment]
I set the display to unknown when we can't find the Kubernetes version in the normal path `spec.<configName>.kubernetesVersion` (where `configName` is dynamic based on a search through the keys on the object for a key containing `config` in it. This type of cluster may need a special case.

**Comment by izaac** [comment]
We still not show the K8s version in a local HA k8s cluster for example. What's the plan for each of the cases where we're displaying `Unknown` ?

**Comment by deniseschannon** [comment]
@izaac @westlywright I think we need to figure out why the k8s version isn't populated correctly or where else it could be obtained. 

@vincent99 do you have any ideas?

**Comment by vincent99** [comment]
I don't know the detail of where it is it should be, but it seems like the problem is you're trying to read the "desired" version from the spec (which varies with driver and such. But Norman mapping has been hiding?) instead of the actually reported version in status.  A similar problem to what we talked any last week.

We should have a new cluster API eventually and opportunity for it to re-normalize this, so just ignoring for now is also an option.

**Comment by westlywright** [comment]
@deniseschannon @izaac I put in a [fix](https://github.com/rancher/dashboard/pull/579) to pull the k8s version out of `status.version.gitVersion` as we do in Norman and Ember UI. I suspect this will prevent the `unknown` case, all the clusters I tested on showed the correct version. Like @vincent99 said we were grabbing the "desired" version off the spec.
