### ISSUE TITLE
Wrong error message when creating repo with same name in same workspace.

### ISSUE THREAD

**Issue by Shavindra** [rancher/dashboard#5345]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**
When creating a repo with same name wrong error message is displayed 

<img width="1779" alt="image" src="https://user-images.githubusercontent.com/1387263/157643187-537c3a30-8465-41a4-99e4-4c21823ff5dd.png">
**To Reproduce**

1. Navigate to continuous deliver and then click on `Add Repository`.
2. Make a note of the name that was given when creating the repository.
3. After successfully adding first repository, click the button again and give the same name as the previous repository.

**Result**

**Expected Result**
It should show the original 409 conflict error in the UI

**Comment by nwmac** [comment]
@richard-cox Shavin will talk to you about this - looks like the generic handling of the 409 conflict is also catching the POST request here which is returning 409 conflict because the resource already exists - either we don't do that retry 409 handling for POSTs or we check the code is not AlreadyExists.

**Comment by richard-cox** [comment]
The way the conflict is handled in `mixins/create-edit-view/impl.js` `save` should just return the normal API error response for the second request. Is the second request different to the first one?

The POST case covers a lot of cases and I don't think we can generically avoid conflict handling for it. I can't remember the exact response `code` for it though, maybe it should be restrict to that? Otherwise we can fall back on avoiding for status codes of `AlreadyExists` (if it doesn't clash)?

**Comment by richard-cox** [comment]
Had a chat with Neil and the conflict handling in `mixins/create-edit-view/impl.js` `save()` should only apply in `edit` mode

**Comment by izaac** [comment]
Rancher version: `v2.6.4-rc9`

A clearer error is displayed in the UI at the bottom of the new GitRepo form.
![Screen Shot 2022-03-17 at 10 54 49 AM](https://user-images.githubusercontent.com/27659/158865493-b5d2bb88-632c-4e37-bcbc-50f9bd1be402.png)
