### ISSUE TITLE
masthead changes on list, create, detail

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#538]
detail top: https://github.com/rancher/dashboard/pull/537

https://xd.adobe.com/view/6fa2a7f7-2bcf-4d5c-75de-9beb1a9b6fae-1993/screen/d37974cf-dd0a-4d3a-8983-12b0ef948dd3/detail

![nancy-masthead](https://user-images.githubusercontent.com/3013118/79921296-cb9cf780-83e6-11ea-9b7b-1d6296c03309.png)

- [x] move namespace below h1, outside of detail top
- [x] create breadcrumbs
- [x] yaml | form toggle

**Comment by deniseschannon** [comment]
Original Requirements discussed with @ibuildthecloud 

* ResourceName - More focus on the actual resource name
* Breadcrumbs shouldn't be as dominant on the page and make it clearer that it goes back to list 
* Namespace - Instead of part of DetailTop, add it as part of header (i.e. masthead) as every resource has a name and is in a namespace
* Switching beteen Yaml/Form - Ability to navigate between yaml/form for when viewing and editing a page. Note: buttons shouldn't exist if no custom form view exists.

**Comment by vincent99** [comment]
> Switching beteen Yaml/Form - Ability to navigate between yaml/form for when viewing and editing a page. Note: buttons shouldn't exist if no custom form view exists.

@tfiduccia  and I specifically removed this switch to the other editor thing and added separate "edit as..." actions to choose in advance because you're going to lose whatever you've already input when you click it.  There is not always a direct, or even necessarily 1 form:1 yaml mapping from one to the other to try and preserve what they've entered so far in the other view.

**Comment by deniseschannon** [comment]
Updating the requirement to show the buttons only during view mode of a resource to avoid having to preserve the changes during create/edit.

**Comment by ibuildthecloud** [comment]
Yeah, there should be no toggle for edit or create screens.

**Comment by vincent99** [comment]
The component shown is a button group which typically operates like a radio, one option is always selected.  So it doesn't make sense on view (the action menu already has the links to edit), or it shouldn't be a button group.

**Comment by lvuch** [comment]
> Updating the requirement to show the buttons only during view mode of a resource to avoid having to preserve the changes during create/edit.

xd file updated to reflect this

**Comment by deniseschannon** [comment]
@vincent99 why doesn't a button group make sense? one option is always selected, either yaml or form for viewing a detailed resource.

**Comment by vincent99** [comment]
Oh, you're toggling "view the detail component" and "view as yaml"?  Not links to "edit as form" and "edit as yaml"?  I guess that works, but calling the detail page with no form components on it a form is odd.

**Comment by deniseschannon** [comment]
I agree that calling a "Form" is weird for viewing a detail resource, but haven't come up with a better word yet.  YAML vs <blank>. Any ideas?

**Comment by deniseschannon** [comment]
@mantis-toboggan-md We should make sure that these changes also work for the `Namespace` resource since we're moving `Namespace` into the masthead component. Ideally for when using  `Namespace` resource, it should say `Project` with the project name.

**Comment by vincent99** [comment]
Friendly, Detail, Overview, Visual?

Only some resources are namespaced, projects are optional, and you'll have similar primary relationships to show in global resources soon.. so something like:

```vue
<div v-if="schema.namespaced">
  Namespace: <nuxt-link ...>{{namespace}}</nuxt-link>
</div>
<div v-else-if="type === 'namespace'">
  Project:
  <nuxt-link v-if="project" ...>{{project.nameDisplay}}</nuxt-link>
  <span v-else>(None)</span>
</div>
<!-- Later more special cases, like cluster points to cluster group -->
```

**Comment by deniseschannon** [comment]
Instead of `Form`, let's try `Overview` @mantis-toboggan-md

**Comment by vincent99** [comment]
![image](https://user-images.githubusercontent.com/753917/80747074-b48d9200-8ad7-11ea-86c7-b465b1edb206.png)

- Cluster is showing `id` instead of `nameDisplay`
- YAML/Overview states are backwards; Blue should be the one that you're currently on (use `ButtonGroup` component)
- I don't have any particular logic but feel like it should be Overview/YAML, not YAML/Overview.
- Created (and any other dates that go in the header, removed?) should be a `LiveDate`

**Comment by deniseschannon** [comment]
@mantis-toboggan-md Let's do a separate issue/PR to update all the DetailTops in all resources to remove the Namespace in detailTop.

As a side note, we have talked about moving Description into mastHead as well, but haven't filed an issue. 

Switching the order of Overview/YAML makes sense to me. 

I'll figure out what we want the common items to be in detailTop. I'll do a review of detailTop across all the resources to determine what the standard items should be in it.

**Comment by deniseschannon** [comment]
There are some small pixel changes I want to request, but I'll file a separate issue for them. 

Generic
- [ ] Cluster is showing id instead of nameDisplay in the breadcrumbs

<img width="218" alt="Screen Shot 2020-04-30 at 5 52 38 PM" src="https://user-images.githubusercontent.com/11410997/80772389-74e09d80-8b0b-11ea-9324-83a74c466ea5.png">

- [ ] Add in `Description` as part of masthead. Basically, only show the description under the `Namespace` section using font in a lighter color, if there is a description. Otherwise, show nothing.

<img width="347" alt="Screen Shot 2020-04-30 at 5 58 24 PM" src="https://user-images.githubusercontent.com/11410997/80772631-37304480-8b0c-11ea-84d3-c22c83a8e46b.png">

## Edit Pages
- [ ] Namespace is showing up in masthead when creating and editing resources in the form input and the yaml input. This should be hidden as it's an input option when you're editing/creating the resource. 
- [ ] From the multi-action menu, the `Edit as YAML` and `Clone as YAML` takes me to edit the form version instead of YAML.
- [ ] For `Create <ResourceType>`, can we enable so that the breadcrumbs link works for going back to the list of resources? 

<img width="300" alt="Screen Shot 2020-04-30 at 5 50 17 PM" src="https://user-images.githubusercontent.com/11410997/80772322-2a5f2100-8b0b-11ea-92c5-8f5d9fa84bf6.png">

Remove the link on the `<ResourceType>`:
- [ ] `Edit <ResourceType>: <ResourceName>` 
- [ ] `Create <ResourceType`
- [ ] `Clone from <Resourec Type>`

## Detail Pages
- [ ] YAML/Overview states are backwards; Blue should be the one that you're currently on (use ButtonGroup component)
- [ ] Reverse the order of the buttons. `Overview` first and then `YAML`. 

Let me know if you want me to track these as a separate issue, but seems to make sense as part of here since it's part of the fact that we're moving this info into masthead. 

- [ ] Remove `Namespace` from DetailTop for all resources. 
- [ ] Remove `Description` from DetailTop for all resources.

**Comment by deniseschannon** [comment]
- [ ] Can we remove the padding/spacing next to `Namespace` so that it lines up with the resource?

<img width="186" alt="Screen Shot 2020-05-04 at 2 40 41 PM" src="https://user-images.githubusercontent.com/11410997/81016462-50d7d180-8e15-11ea-93f4-135b9ed55dd7.png">
