### ISSUE TITLE
EC2 RKE2 node driver cluster's pool takes longer to load

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5384]
**On 2.6-head commit id: `f904267`**
Ui makes around 10 calls to `https://<>/meta/proxy/ec2.us-west-2.amazonaws.com/`

In 2.6.3, UI makes 5 calls to the same ^^^

This is making loading of nodepools tab quite slow in an EC2 cluster

**Comment by richard-cox** [comment]
This is working as expected.

In 2.6.3 five requests are made to fetch ec2 regions, availability zones, vpcs, subnets and security groups. 

In 2.6.4 we now also fetch instance types, however there can be quite a few of these (412 are available for the access key i was using). So the response is paginated and split over 5 requests.

Also two things that don't help debugging 
- AWS's api isn't RESTful and only includes the requested resource in the payload of the the request rather than the path,
- Paginated responses are not returned as xml like non-paginated requests and the response is not shown in dev tools

**Comment by sowmyav27** [comment]
Closing this as per https://github.com/rancher/dashboard/issues/5384#issuecomment-1068011097
