### ISSUE TITLE
Not landing in the cluster page after setting the cluster as the landing page 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#5439]
Setup

Rancher version: 2.6-head 1ae31b1
Browser type & version: Chrome

**Describe the bug**
On 2.6.2, I created a cluster and set the cluster page as the landing page. After upgrading the rancher server to 2.6-head, I'm not taken to the cluster page but land on the home page.

**To Reproduce**
1. Create a cluster[any cluster should work. I tried with rke1 node driver] in 2.6.2
2. From home >> set the cluster as the preferred landing page
3. Upgrade rancher to 2.6-head
4. Log out of the server and login

**Result**
Landing in home page instead of the set cluster page. Even if we change the cluster to local cluster, we land in the home page.

**Expected Result**
Expected to land in the cluster page and not home page.

**Screenshots**

<img width="300" alt="loginpage" src="https://user-images.githubusercontent.com/38144301/159091361-28d4323f-6628-43a1-b087-adbf702d1939.png">

**Additional context**
Could be a regression from https://github.com/rancher/dashboard/issues/5004

**Comment by richard-cox** [comment]
I've tried going from HA 2.6.3 to 2.6.4-rc9 (twice) and 2.6.4-rc10 (once). Both rc's have the 404 PR in.

The first two times i tried to log in quickly after the upgrade. On both attempts the first log incorrectly redirected to the homepage instead of the cluster home page. On the second attempt i checked the availability of the cluster in the side menu and it showed as available. On both attempts though subsequent refreshes and log in's correctly redirected the user to the cluster home page.

On the third attempt I waited until activity in the local rancher cluster died down (in the first two attempts fleet pods were still coming up) and exactly the same thing happened. 

@anupama2501 Do you have a publicly available system that was upgraded from 2.6.3 to latest that repeatedly shows a failure to be redirected to the home page? If so i'd like to take a quick look

**Comment by anupama2501** [comment]
Verified on 2.6.4-rc10. As mentioned by @richard-cox the issue is not seen on an rc version.
