### ISSUE TITLE
Cannot edit an RKE2/k3s cluster as a standard user/cluster owner

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5442]
**On 2.6-head commit id `024e6fa`**

- Deploy an RKE2 k3s node driver DO cluster as an admin
- Add user1 as a cluster owner
- Login as user1
- Edit config on the cluster
- Edit config page is not loaded.
Instead RKE1 create cluster page loads

**Comment by catherineluse** [comment]
I haven't pinpointed the root cause yet but I think it's my fault for messing with the `emberLink` https://github.com/rancher/dashboard/pull/5433/files#diff-57eee22cde55fcc07b9a14c4f7f9d24680e0968aae812a5d7c7f611e403fb475R154

I think it is incorrectly trying to import an ember page when it shouldn't. Currently it always tries to use an ember page if an emberLink exists. https://github.com/rancher/dashboard/blob/master/edit/provisioning.cattle.io.cluster/index.vue#L427

**Comment by catherineluse** [comment]
For me, when I log in as the cluster owner and try to edit an RKE2 cluster, it sends me to the cluster create page instead of the cluster edit page.
<img width="1314" alt="Screen Shot 2022-03-21 at 8 40 14 PM" src="https://user-images.githubusercontent.com/20599230/159403346-8c96e24c-1e69-4dc9-9ef2-c280a9bc5e87.png">

In that page, the `isRke2` computed property is incorrectly returning false. https://github.com/rancher/dashboard/blob/master/edit/provisioning.cattle.io.cluster/index.vue#L212

I also noticed that if you navigate away and then return to the page, the cluster edit form renders normally.

I saw on that page that the compu

**Comment by sowmyav27** [comment]
**On 2.6-head commit id `0b44573`**

- Deploy an RKE2 k3s node driver DO cluster as an admin
- Add user1 as a cluster owner
- Login as user1
- Edit config on the cluster
- Edit config page is not loaded.

**Comment by Josh-Diamond** [comment]
Ticket #5442 - Test Results

Reproduction Failure on `v2.6-024e6fa23af3678aafa85d4085c02143127bd3a1-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, create a standard user
3. As admin, provision a Digital Ocean Node driver RKE2/k3s cluster and add standard user as `Cluster-Owner`
4. Once provisioned, as standard user, `edit config` of RKE2/k3s DO cluster
5. Reproduction Failure - standard user can `edit config` on cluster

Screenshot:
<img width="1436" alt="reprod#1" src="https://user-images.githubusercontent.com/46494969/160012896-c8a032d2-92b5-4ff3-8dec-b2e87e18672c.png">


Reproduction Failure on `v2.6.3`:
1. Fresh install of rancher `v2.6-head`
2. As admin, create a standard user
3. As admin, provision a Digital Ocean Node driver RKE2/k3s cluster and add standard user as `Cluster-Owner`
4. Once provisioned, as standard user, `edit config` of RKE2/k3s DO cluster
5. Reproduction Failure - standard user can `edit config` on cluster

Scre
<img width="1438" alt="2 6 3 reprod#2" src="https://user-images.githubusercontent.com/46494969/160012916-c7095623-fc4c-4b17-81ec-e00b639a7218.png">
enshot:


Reproduction Failure on `v2.6-0b4457317840d80c17990b5e04ba326eb411fb8f-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, create a standard user
3. As admin, provision a Digital Ocean Node driver RKE2/k3s cluster and add standard user as `Cluster-Owner`
4. Once provisioned, as standard user, `edit config` of RKE2/k3s DO cluster
5. Reproduction Failure - standard user can `edit config` on cluster

Screenshot:
<img width="1436" alt="reprodFAIL#3" src="https://user-images.githubusercontent.com/46494969/160012949-bcbea18f-37ba-477c-8bf0-5fa97a942293.png">


Verified on `v2.6-85d692518525d2a1f9eb740833145b242608632e-head`:
1. Fresh install of rancher `v2.6-head`
2. As admin, create a standard user
3. As admin, provision a Digital Ocean Node driver RKE2/k3s cluster and add standard user as `Cluster-Owner`
4. Once provisioned, as standard user, `edit config` of RKE2/k3s DO cluster
5. Verified - standard user can `edit config` on cluster

Screenshot:
<img width="1432" alt="verify-screenshot" src="https://user-images.githubusercontent.com/46494969/160013076-84bf7093-8b27-4b2a-b225-ae2a365a3d4f.png">
