### ISSUE TITLE
State of Machine in Cluster Management page is seen as Active when the node is in Provisioning state

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#5443]
**On 2.6-head commit id `024e6fa`**

- Deploy an RKE1 cluster - 1 node all roles
- After the cluster has come Active, Edit cluster --> add a worker node pool
- The node will be in Provisioning state in cluster details page
- State of Machine in Cluster Management page is seen as Active when the node is in Provisioning state
<img width="1436" alt="Screen Shot 2022-03-21 at 1 42 34 AM" src="https://user-images.githubusercontent.com/26032343/159184206-b93561b3-3b8e-4b57-bb2c-bcd1ae7aac05.png">
<img width="1448" alt="Screen Shot 2022-03-21 at 1 42 19 AM" src="https://user-images.githubusercontent.com/26032343/159184210-63509a72-30f2-4c48-9368-70d1c031b674.png">

**Expected:**
One of the 2 nodes should NOT be in ready state

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `7db4fe4e`**

- Two states are seen - `Ready` and `Pending`.
- Correct number of `pending` nodes are seen
- But Incorrect number of `Ready` nodes seen.
- Reopening the issue
- one node is Active and 2 are Registering
<img width="1391" alt="Screen Shot 2022-04-27 at 12 29 29 PM" src="https://user-images.githubusercontent.com/26032343/165605343-29def5d7-5393-4192-b679-8d357810d61f.png">
<img width="1420" alt="Screen Shot 2022-04-27 at 12 29 34 PM" src="https://user-images.githubusercontent.com/26032343/165605353-85a28491-ed12-4f3c-a271-dfe42e4b9288.png">

- All 3 are Registering 
<img width="1401" alt="Screen Shot 2022-04-27 at 12 28 13 PM" src="https://user-images.githubusercontent.com/26032343/165605413-5187248a-57a8-456a-84ba-89d9e0aca15d.png">
<img width="1419" alt="Screen Shot 2022-04-27 at 12 28 21 PM" src="https://user-images.githubusercontent.com/26032343/165605424-d5e1860b-3a5b-47de-a970-12aefb817781.png">

**Comment by markusewalker** [comment]
Issue still failing in `v2.6-head` https://github.com/rancher/rancher/commit/d5e68641e8f5f2d05bfa82731e5d8148e0f45017.

**ENVIRONMENT DETAILS**
- Ubuntu 20.04: Docker Install
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/d5e68641e8f5f2d05bfa82731e5d8148e0f45017
- Browser: Chrome

**TEST RESULT**
FAIL

**REPRODUCTION STEPS**
1. Setup Rancher and create a Standard user and login to Rancher UI as that user.
2. Create an RKE1 cluster with 1 node pool that has 1 cp, 1 etcd, 1 worker.
3. Once the cluster Is created, click the cluster and edit the config to add a worker node pool of 2 machines.
4. The status of the machine shows as `Active` despite the worker nodes not being `Active` themselves:
![image](https://user-images.githubusercontent.com/52591819/165825379-bee4c779-4966-403e-a90a-9f7dcf541a62.png)
![image](https://user-images.githubusercontent.com/52591819/165825404-01523c49-b4c7-47de-bca3-9dc90d05710b.png)

There was a quick glimpse that I was able to capture where the status changes as expected as seen below:
![image](https://user-images.githubusercontent.com/52591819/165825420-bc5dda2d-e64e-4206-9717-81686b6f516c.png)

However, this proved to be a red herring as the above repro steps quickly showed the issue is still prevalent.

**Comment by richard-cox** [comment]
@markusewalker I think that's a separate issue. This one concentrates on aligning the individual nodes states with the machine states (they're actually the same resource under the hood). The issue you described is the clusters state (mgmt cluster's `metadata.state`) showing as active when there are nodes in transitional state. That's more of a backend issue and worth splitting out.

**Comment by markusewalker** [comment]
@richard-cox I see, thanks for the explanation. In that case, I'll create a separate issue and assign you and I with regards to my issue. For this issue, I'll close out.
