### ISSUE TITLE
Add endpoints (and other) metadata to workload detail views

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5463]
The detail view for a workload looks like this:

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/1955897/159499001-90e0303f-b898-469a-8a29-c852f636a576.png">

The code for this page is in `detail/workload/index.vue` - it is used for various workload typed (e.g. deployment, statefulset).

We need to show the following metadata on this detail view:

1. Endpoints
2. Ready
3. Up-to-date
4. Available

These 4 details are shown on the list page already for a workload, but should also been shown on the detail page.

These should go above the 'Pods by State' section - Suggest a simple list of name/value as per the Image and Annotations already shown on the detail view.

**Comment by catherineluse** [comment]
Related issue https://github.com/rancher/dashboard/issues/4974

**Comment by catherineluse** [comment]
After talking to Neill, Giuseppe and Kenneth, here's the takeaway about endpoints and the workload detail page. The dashboard isn't communicating much about the relationships between workloads, services and ingresses, and there are some l

At minimum -
  - Add some text that says something like "Exposing your Workload" and link to Services and Ingresses. (May make sense to do that in a separate PR because it is net new)
 
This is more work which estimate could take another week, but I think it could still fit into 2.6.5 -
  - Address https://github.com/rancher/dashboard/issues/4845 by enhancing the "Exposing Your Workload" section above by making it so that it also shows you Services and Ingresses that expose your workload.
  - If there are no existing services that expose your workload, it suggests using your workload's selectors and port information to create a Service

**Comment by igomez06** [comment]
**Setup:**
Rancher Version: v2.6.5-rc6
Kubernetes Version: RKE2 v1.22.8+rke2r1
HA Install

**Steps:**
1. Created a deployment (name: test, image: nginx) with node port service
2. New metadata now shows up in the workloads (deployment) detail view
  * Endpoints doesn't no longer shows up in the workloads list view.
