### ISSUE TITLE
RoleTemplate description not respected

### ISSUE THREAD

**Issue by evhan** [rancher/dashboard#5568]
**Setup**
- Rancher version: 2.6.3
- Browser type & version: Firefox 98.0.2

**Describe the bug**
Descriptions added to custom RoleTemplates are not respected.

This applies to both the management interface under **Users & Authentication** and when adding a user to a cluster in **RBAC > Cluster Membership** or to a project in the **Add Project Member** dialog.

**To Reproduce**
Navigate to `/dashboard/c/_/auth/roles` and create a custom cluster role, providing a description in the "Description" field.

Then, click on the role you've just created to view it and see that the read-only "Description" field is empty. Also enter edit mode for the role and see that the editable "Description" field is also empty. View the YAML representation for the role and see that the `description` field _does_ contain the description.

Also, navigate to `/dashboard/c/local/explorer/members` and click **Add** to see that the description is not used when granting a user the cluster role. Instead, the label reads "User created - no description".

Note all of the above applies to project roles too (i.e. RoleTemplates with `context: project` instead of `cluster`), I've only added description/screenshots for the cluster role case.

**Result**
The user-provided description is not used, per the above.

**Expected Result**
The user-provided description is shown when viewing/editing the role, and when assigning it to a user on a cluster or project.

**Screenshots**
![Screenshot from 2022-04-04 13-17-13](https://user-images.githubusercontent.com/96712/161458912-ea6d6346-55c2-4ab1-8341-46bfa1787168.png)
![Screenshot from 2022-04-04 13-15-59](https://user-images.githubusercontent.com/96712/161458918-a5bb64a8-b109-42cd-a535-c168984cccbc.png)
![Screenshot from 2022-04-04 13-15-40](https://user-images.githubusercontent.com/96712/161458923-e45f367d-850d-4308-bd2b-660605a953ad.png)

**Additional context**

**Detailed Description**

**Context**

We have worked around this problem by copying the descriptions from the `description` field into a `field.cattle.io/description` annotation on the RoleTemplate resources, since that seems to be where the dashboard is looking for the description.

I've reproduced this on both `master` and `v2.6.3` of the dashboard and see the same behaviour either way. I _haven't_ tested against any other versions of Rancher *server*, so if there's a fix in the `rancher` project I may have missed it.

Note this issue seems similar to rancher/dashboard#4594, but the PR for that issue doesn't seem to fix the problem with descriptions.

**Comment by nwmac** [comment]
This has been fixed - moving to QA for validation.

**Comment by dasarinaidu** [comment]
I reproduce this issue on v2.6.7

Steps to reproduce:

1. Provision rancher Docker / HA
2. Users & Authentication
3. Roles ->Cluster
4. Create a cluster role with a 'Description' 
5. Check for the Cluster role description by opening the cluster OR try to add 'Cluster Member' for a downstream cluster & check for the cluster role description

Actual:
The descriptions are not displayed, it shows empty.
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/22034884/205778502-f565ccbf-5bfd-4552-a1a9-39f437baca75.png">

**Comment by nwmac** [comment]
@dasarinaidu This is fixed in the main code branch and will be released in the next 2.7 release.

**Comment by dasarinaidu** [comment]
This issue validated on `v2.7-60ab459ac61cae96dfc3145e70e5d3afb9fdf7c8-head` - The fix is working for ClusterRole but not for the Global Role creation and I created a separate ticket to track the issue.

https://github.com/rancher/dashboard/issues/7635

**Below tests were executed as part of this ticket validations :** 

1. Rancher HA & Docker installed
2. Browsers : Chrome & Firefox
3. Modes : Light and Dark
4. Create and Edit - Cluster Role
5. Login with Admin and Standard user and Create Cluster Role

**Setup : **
Rancher version: `v2.7-60ab459ac61cae96dfc3145e70e5d3afb9fdf7c8-head`
Browser type & version: Chrome and Firefox

**Steps To Reproduce : **

1. Provision rancher (HA) and Login
2. Navigate to : Users & Authentication-> Roles -> Cluster-> Create Cluster Role
3. Provide Name and Description to the role
4. Create
5. Check for the Cluster Role by open the role and check for the description (Make sure to refresh the browser)

![image](https://user-images.githubusercontent.com/22034884/205991406-3d5291e3-0dab-4674-a5ab-4b93a9ba5bbc.png)
