### ISSUE TITLE
Spinner animation on AsyncButton is wibbly

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#5581]
**Describe the bug**
The async button contains a spinner when the async function is running. The spinner is not rotating around a central point so spins in a very wibbly wonky way

**To Reproduce**
- Nav to log in page and enter credentials
- Using Dev Tools reduce network speed (Network tab - Throttling drop down)
- Click log in button

**Result**
- Spinner in button on left of the 'Logging in..` text wibbles around a bit 

**Expected Result**
- Spinner should remain central and spin around the centre of the spin. No Wibbling.

**Comment by rak-phillip** [comment]
@richard-cox if this is similar to the issue that I experienced in Rancher Desktop, the wobble would only be present on Linux.. In that case, a quick fix might be to use svg for the icon instead of the icon classes (`<span class="icon icon-info icon-lg " />`). 

Either way, I'd be interested in the root cause of the offset that's causing the wobble if we're able to find one.

rancher-sandbox/rancher-desktop#1282

**Comment by kwwii** [comment]
The problem seems to be that the icon is in an "i" element with padding and margin. The whole element is being animated from the centre which creates a wobble effect.

**Comment by sowmyav27** [comment]
**On 2.6.4**

Reproduced the issue:

- Nav to log in page and enter credentials
- Using Dev Tools reduce network speed (Network tab - Throttling drop down)
- Click log in button
- Spinner in button on left of the 'Logging in..` text wibbles around a bit

**On 2.6.5-rc2**
No wibble in spinner in the login button
