### ISSUE TITLE
Home Page clusters table fetches counts for clusters that are not ready

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5717]
On the home page clusters list, if a cluster if not ready, we still fetch the counts for the cluster so we can show pod count - this gives an error in the console and leaves the spinner on the page:

![image](https://user-images.githubusercontent.com/1955897/165303042-e8330bb4-e329-42a1-8e40-8289cf2a6cd4.png)

**Comment by sowmyav27** [comment]
@aalves08 On 2.6-head commit id: `7db4fe4e819`

- I see multiple behaviors when i refresh the page or when i navigate between CLuster Management and Home pages.
**Issue 1**
<img width="1160" alt="Screen Shot 2022-04-27 at 12 14 08 PM" src="https://user-images.githubusercontent.com/26032343/165602551-4566d51b-712e-428d-842a-c628d737ab79.png">

- After a few attempts I was unable to reproduce ^^^ issue 1 but I see Issue 2 (below)

---
**Issue 2**
<img width="1170" alt="Screen Shot 2022-04-27 at 12 15 49 PM" src="https://user-images.githubusercontent.com/26032343/165602559-fcd35de0-0698-4baf-aaf8-1fe46d5a7787.png">

- 2 `-` are seen inPods section

**Expected:**
Only 1 `-` is seen to make it consistent with other columns

**Comment by aalves08** [comment]
@sowmyav27 I've changed the **-** symbol to match the other cols.

Just to create understanding, if the issue/PR isn't clear, the spinner should only appear if the cluster is ready (aim of the issue was to fetch the **Pods** metrics only when the cluster was ready) and should go away once it fetches the metrics for the **Pods**.

**_Caveat:_** if we are looking at the table when we are provisioning a new cluster, and the live update updates the cluster status to ready, the **-** symbol won't go away (user needs to refresh) to again fetch the pods count (because that only runs once, when the table row is rendered).

To change this behaviour would entail a lot of work on the table component and might have unexpected changes to various areas of the UI.

The main goal of this issue was to prevent the API call when the cluster isn't ready, so that the user doesn't have errors on the console/interface.

FYI: @nwmac

**Comment by markusewalker** [comment]
Verified on `v2.6-head` https://github.com/rancher/rancher/commit/d5e68641e8f5f2d05bfa82731e5d8148e0f45017.

**ENVIRONMENT DETAILS**
- Ubuntu 20.04: Docker Install
- Rancher version: `v2.6.5-rc3` and `v2.6-head` https://github.com/rancher/rancher/commit/d5e68641e8f5f2d05bfa82731e5d8148e0f45017
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and create a Standard user and login to Rancher UI as that user.
2. Create an RKE1 and RKE2 cluster (specifications do not matter).
3. Navigate back to the home page and verified that I see "-" in columns that are not ready yet in the cluster:
![image](https://user-images.githubusercontent.com/52591819/165828686-ef1670f6-2749-4dcd-b973-b9d2dd37ed1e.png)
4. Refreshed the page several times until the clusters finished and still did not see this issue.
