### ISSUE TITLE
Add `ProjectHelmCharts` to the dropdown menu in the form for creating custom roles

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5747]
Based on feedback from a recent demo of v2 Project Monitoring, we need to add `ProjectHelmCharts` to the dropdown menu in the form for creating custom roles.

**Comment by gaktive** [comment]
This can be done manually in its current form, which would need to be documented.

**Comment by xhejtman** [comment]
> Based on feedback from a recent demo of v2 Project Monitoring, we need to add `ProjectHelmCharts` to the dropdown menu in the form for creating custom roles.

Is there the demo of v2 Project Monitoring available for preview?

**Comment by catherineluse** [comment]
# QA Template
## What was fixed, or what changes have occurred
In the custom role creation form, I added ProjectHelmChart to the list of resources that you can pick from when creating a role.
 
## Areas or cases that should be tested
Just the same steps that I did when testing the PR. The steps are captured here https://github.com/rancher/dashboard/pull/6052#issue-1250578520
 
## What areas could experience regressions?
Can't think of any

**Comment by ronhorton** [comment]
**Pass** verified fixed in `2.6-head Commit ID c5746d9`

1. installed monitoring
2. installed alerting-drivers
3. installed prometheus-federator
4. navigated to hamburger menu > users & authentication > roles > project/namespaces
5. clicked create project/namespaces role

verified `helm.cattle.io` and `ProjectHelmCharts` are available as resources
![Screen Shot 2022-06-27 at 2.45.49 PM.png](https://zube.io/files/rancher/15524dc524d5bc34a3ca9185c4a16978-screen-shot-2022-06-27-at-2-45-49-pm.png)

**Comment by ronhorton** [comment]
Had already tested this when I noticed that zube reopened the ticket and put it in working. 
Verified in `2.6-head Commit ID 07ee596`

<img width="1623" alt="2022-07-18_14-41-26" src="https://user-images.githubusercontent.com/89212856/179580511-c37cbf49-806a-4c03-985a-0a6dbece7110.png">
<img width="1613" alt="2022-07-18_14-41-54" src="https://user-images.githubusercontent.com/89212856/179580538-63d67bac-0904-4547-a4be-b6448dbfe70d.png">
