### ISSUE TITLE
Dashboard requires external CSS/JavaScript from releases.rancher.com

### ISSUE THREAD

**Issue by leolb-aphp** [rancher/dashboard#575]
![rancher-new-dashboard-external-css-js](https://user-images.githubusercontent.com/61736362/80509954-5bf4b280-897a-11ea-80e1-2004167c2c4f.png)

I am thinking it would be more appropriate to include these resources in each deployment?

**Comment by vincent99** [comment]
The dashboard is experimental and they are intentionally not bundled with the Rancher release for now so that we can update it outside of the regular Rancher release cycle.

**Comment by leolb-aphp** [comment]
@vincent99 OK, then could you please add `referrerpolicy="no-referrer"` on all elements that import external resources? So it does not leak unnecessary information.

**Comment by leolb-aphp** [comment]
I'm trying to find where that is to make a PR but I can't find it.

**Comment by leolb-aphp** [comment]
So apparently because you use Nuxt.js it has to be done there, and investigating that code base seems even more adventurous. They allow you to add crossorigin, but not anything else. https://nuxtjs.org/api/configuration-build#crossorigin

**Comment by vincent99** [comment]
In 2.5 it will likely be officially supported and the dashboard code packaged with the Rancher release like normal.  I'd take a PR for it if an easy option existed in nuxt, but otherwise have no plan to address this.  

It is backed by a google cloud storage bucket which we don't have logging configured for; not that you can verify that externally, but if believing me is a problem you definitely shouldn't be running the remote code we're serving up from it...

Anyway, there's a feature flag you can use to disable the Dashboard in the meantime if you choose.

**Comment by leolb-aphp** [comment]
@vincent99 I investigated Nuxt as well but it's unfortunate that this library is so bloated that adding attributes to html generation is so complicated. I'll disable it for now.

**Comment by gittygoo** [comment]
So we run rancher via desktops that do not have internet access... the dashboard doesnt work there because of this. still any plans to fix this and bundle these with rancher? I'm on 2.4.5

**Comment by vincent99** [comment]
When it becomes a supported stable feature (likely in 2.5), yes.  Until then, no.
