### ISSUE TITLE
Handle ingress url correctly if url rewrite is applied

### ISSUE THREAD

**Issue by xhejtman** [rancher/dashboard#5768]
**Setup**
- Rancher version: 2.6.4
- Browser type & version: chrome version 101

**Describe the bug**
If one enable rewrite rules in nginx ingress, URL is rendered in ugly form like:
<img width="1167" alt="sparkaddress" src="https://user-images.githubusercontent.com/22795052/165842892-a467271f-f00b-4e1e-b164-dcd964941bde.png">

Would it be possible to make it active, either using annotation what 'presented' url should look like or just stripping that match/replace part?

**Comment by momesgin** [comment]
@nwmac @gaktive I think we can't find a solid solution to strip that match/replace part because there's no specific indicator in a URL that explicitly marks a portion of the URL as a regex pattern, we can’t cover all the possible cases, it will also require lots of testing to avoid changing things we shouldn’t.  

I’m not sure I understand this: '_...using annotation what the 'presented' URL should look like._', we can show just the host URL e.g. `https://bla.com` but it might look weird when you have multiple paths and show the same url for all of them.

**Comment by nwmac** [comment]
Having discussing with @momesgin, I think we won't do this.

We can't easily determine the non-regex part of the URL. We could add an annotation, but then if we made the target clickable, the user would see the target URL but then would open a different URL when clicked, which doesn't feel great from a security point of view.
