### ISSUE TITLE
[project monitoring v2] Unable to create route on alertmanagerconfigs page

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5819]
**Setup**
- Rancher version:`2.6-head Commit ID eb03517`
- Browser type & version: `chrome latest`

**Describe the bug**
When I attempt to add a route to an alert, I click 'edit config' and go to the route page; I can input waiting and intervals, but there is no input availbe for matching 

**To Reproduce**
rke2 cluster
1. Cluster > Monitoring > Alerting > Alertmanage configs
2. Click new alert
3. click 3 dots > edit config
4. Click route tab
5. Select New receiver > click grouping

**Result**
Grouping and Matching are not configurable - missing input fields

**Expected Result**
can fully configure a route

**Screenshots**
<img width="1620" alt="Screen Shot 2022-05-04 at 11 26 03 AM" src="https://user-images.githubusercontent.com/89212856/166716001-39278e73-2fed-4da1-98ff-5a84bdc58a8e.png">

**Comment by catherineluse** [comment]
# QA Template

## Root cause
The input fields didn't match the required YAML format of the new routes API. So the fix was to add/change the fields for grouping and matching to become compatible with the new API.
 
## What was fixed, or what changes have occurred
I updated two sections of the route form on the Route tab within the AlertmanagerConfig detail page.

 The first is the Grouping section, which should now allow you to enter a list of strings that will be used to group alerts by label:
<img width="765" alt="Screen Shot 2022-05-06 at 2 07 19 AM" src="https://user-images.githubusercontent.com/20599230/167103169-35203803-1579-422d-9438-8a9155abf853.png">

**Comment by ronhorton** [comment]
fixed `2.6-head Commit ID 628b1b9`
