### ISSUE TITLE
[project monitoring v2] editing prometheus rule throws an error when saved

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5820]
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**
Attempted to edit prometheus rule, error 'name' contains an invalid character

**To Reproduce**
1. click monitoring > alerting > advanced > prometheus rules
2. select a rule that includes a '.' and edit config
3. modify a value
4. click save

**Result**
"Name" contains an invalid character: . (the dot is included in the name of the selected prom rule)
`impl.js:182 CreateEditView mixin failed to save:  Array(1)`

**Expected Result**
rule saved

**Screenshots**
<img width="1620" alt="Screen Shot 2022-05-04 at 11 32 50 AM" src="https://user-images.githubusercontent.com/89212856/166717210-20bd7ae5-a074-4a3c-ab39-394e3b587885.png">

**Comment by gaktive** [comment]
Need to determine if the `.` is a known Grafana issue or not since we'd need to work around that.

**Comment by Sean-McQ** [comment]
The error message itself is either originating from a specific rule in the model (see code snippet from model below paragraph) so it seems like the error message _should_ be preventing the user from saving. I think @aiyengar2 had mentioned that these prometheus rules were automatically created and therefore bypassed validation rules on the backend but that would indicate that these rules shouldn't be available to edit.

```
      {
        nullable:       false,
        path:           'metadata.name',
        required:       true,
        translationKey: 'generic.name',
        type:           'dnsLabel',
      }
```

The warning message `This PrometheusRule is managed by the Helm app rancher-monitoring; changes made here will likely be overwritten the next time Helm runs.` seems to indicate that we shouldn't be letting the user perform this edit to begin with. That warning seems to be keyed off of the following code in the resourceDetail masthead:
```
managedWarning() {
      const { value } = this;
      const labels = value?.metadata?.labels || {};

      const managedBy = labels[KUBERNETES.MANAGED_BY] || '';
      const appName = labels[KUBERNETES.MANAGED_NAME] || labels[KUBERNETES.INSTANCE] || '';

      return {
        show:    this.mode === _EDIT && !!managedBy,
        type:    value?.kind || '',
        hasName: appName ? 'yes' : 'no',
        appName,
        managedBy,
      };
    },
```
I can probably bake some additional logic into the model to remove the "edit config" and "edit yaml" options from the action menu if that's the route we need to go or I can remove the customValidationRule from the model which we'd probably want to think critically about since this rule was specifically created in this pull request: https://github.com/rancher/dashboard/pull/1685 for this issue: https://github.com/rancher/dashboard/issues/811

**Comment by catherineluse** [comment]
This is odd. We've documented that users are supposed to be able to edit PrometheusRules. https://rancher.com/docs/rancher/v2.6/en/monitoring-alerting/configuration/advanced/prometheusrules/ It's the Prometheus resource that you're not supposed to touch because it's managed, not PrometheusRules.

It looks like the "managed by" label is being incorrectly added to the metadata of the PrometheusRule. I think.

**Comment by gaktive** [comment]
This runs into a grey zone whereby we should guide the users to not modify certain rule names since they're internal but they could based on what's doable via kubectl. 

Overall, this is a DNS validation rule tied to `.` but since this is a Prometheus rule. Prometheus has its own validation mechanism that we could leverage so that we can look at this down the road.

**Comment by nwmac** [comment]
@aiyengar2 How does the resource get created with a `.` in it? How is that a valid k8s resource name?

For now, we can detect an invalid name and prevent editing and show a banner at the top saying that the resource can not be edited.

**Comment by Sean-McQ** [comment]
Validator in place and working. Just need to disable entire form and provide banner when "." in the name field.
