### ISSUE TITLE
Remove experimental marker for 1.23 and 1.22 RKE2/k3s versions

### ISSUE THREAD

**Issue by timhaneunsoo** [rancher/dashboard#5858]
**Setup**
- Rancher version: v2.6.5-rc7
- Browser type & version: Chrome Build 101.0.4951.54 

**Describe the bug**

1.23 and 1.22 RKE2/k3s versions should not be marked as experimental for 2.6.5

**To Reproduce**

1. Click create cluster
2. View versions under `Cluster Configuration -> Kubernetes Version`

**Result**
1.23 and 1.22 versions for RKE2/k3s are marked as experimental

**Expected Result**

Experimental marker should be removed for 1.23 and 1.22 versions

**Screenshots**

![image](https://user-images.githubusercontent.com/97477402/167172566-5aefbd35-85e7-48d2-9e71-95b813b8a5b2.png)

**Comment by gaktive** [comment]
@timhaneunsoo do you see the same labels when looking at the command line?

**Comment by catherineluse** [comment]
For the dashboard UI, we take the default version from the backend and mark all versions later than that as experimental.

In 2.6.5 there is a change to get the default version from a new API. https://github.com/rancher/dashboard/pull/5608

If too many things are marked experimental, my first guess would be that the wrong version is default on the backend.

**Comment by gaktive** [comment]
Checking with @snasovich what the default version is on the backend based on the UI PR and if RCs are somehow querying another release channel.

**Comment by snasovich** [comment]
@timhaneunsoo , what is the exact version of Rancher it was tested on? The description states it's `v2.6.5` but it cannot be so as it's not yet released.
I'm seeing only 1.23 marked in 2.6-head that points to 2.6-dev KDM, but this may be due to how defaults are evaluated when Rancher version is not "normal" (like "v2.6.5") - default is used to determine what is experimental as any version higher than default would be considered experimental. Could you test it by setting version to 2.6.5 (it can be done via passing settings to Rancher deployment) and let is know if you see an issue?

@jiaqiluo , heads-up as you recently worked on this. Could you please look into it in parallel with Tim?

**Comment by timhaneunsoo** [comment]
I apologize, I meant to type in v2.6.5-rc7. I tested this issue again in v2.6.5-rc8 and the issue seems resolved.
![image](https://user-images.githubusercontent.com/97477402/167224621-0aa45e4c-fada-4a9e-9eda-495149017f04.png)
I'll close this issue as not reproducible.
