### ISSUE TITLE
 `Unable to fetch principal info` is seen while adding users when auth provider mode is set to restricted/required

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#5876]
Setup

Rancher version: 2.6.5-rc8
Browser type & version: Chrome

**Describe the bug**
When adding auth users to be allowed while the auth provider mode is set to `Allow members of clusters and projects, plus authorized users & groups` or `Restrict access to only the authorized users & groups`, `Unable to fetch principal info` is seen added to the list of users. Thereby preventing to save the config for the new users. Config can be saved if we remove the `Unable to fetch principal info` .

**To Reproduce**

- Enable auth provider in rancher server - I used openLDAP
- Set the mode on the UI Allow members of clusters and projects, plus authorized users & groups or Restrict access to only the authorized users & groups
- Add a few users from the auth providers

**Result**
 `Unable to fetch principal info` is seen in the list of users. As a result unable to save config

**Expected Result**
Expected no errors seen while adding users.

**Workaround**
Remove the `Unable to fetch principal info` from the list of users and save config

**Screenshots**:
<img width="200" alt="consolerros" src="https://user-images.githubusercontent.com/38144301/167468618-b37a0665-1403-4319-8e1a-b1097b2ca65a.png">

**Additional context**
Following response is seen when the user is added.
```
{"baseType":"error","code":"ServerError","message":"invalid id undefined","status":500,"type":"error"}
```

Console logs:
```
xhr.js:178 
 GET https://<redacted>/v3/principals/undefined 500 (Internal Server Error)
Principal.vue:36 Failed to fetch principal undefined undefined

```

Do not see this issue when user is added from a v3 API.
Not seen on 2.6.4 version

**Comment by catherineluse** [comment]
# QA Template

## Root cause
The UI attempts to make an async call to `/v3/principals/<principalId>`. On this page, `principalId` is undefined, so the API call was going to `/v3/principals/undefined`, which causes an error.
 
## What was fixed, or what changes have occurred

Anupama showed that in v2.6.4, there was no async call to get the principal details on this page. So it looks like the bad API call was not needed.

The API call was originally added in https://github.com/rancher/dashboard/pull/3064 to add support for the Keycloak OIDC provider, but it isn't needed in the context of this page.

The async code was not supposed to run if the principal data was already in the store, and in this case the data is already in the store. But the code executed anyway because the thing that loads info from the store (the getter in `data`) was running after the code in `fetch`.

So I made it when it checks if the principal data already exists, it looks for it in the store and finds it there. Now we have the same behavior as v2.6.4.
 
## Areas or cases that should be tested
Adding authorized users from OpenLDAP (same steps as reproducing the issue)
 
## What areas could experience regressions?
Can't think of any

**Comment by anupama2501** [comment]
Verified on v2.6-head 628b1b9

- Enabled openldap auth in rancher
- Verified adding new users does not trigger `Unable to fetch principal info`
