### ISSUE TITLE
[project monitoring v2] navigation after creating receiver should land back on alertmanagerconfigs page

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5882]
**Setup**
- Rancher version: `2.6-head Commit ID 628b1b9`
- Browser type & version: `chrome latest`

**Describe the bug**
When user creates a new receiver, the landing page after `create` is the newly created receiver. User then has to navigate to Monitoring > alerting > alertmanagerconfigs.

**To Reproduce**
1. Cluster > Monitoring > Alerting > Alertmanage configs
2. click alert
3. click add receiver
4. add unique name
5. click create

**Result**
user is looking at the newly created receiver

**Expected Result**
user lands back in the alertmanager config for which they are configuring the receiver. 

**Screenshots**

<img width="1628" alt="Screen Shot 2022-05-09 at 4 16 34 PM" src="https://user-images.githubusercontent.com/89212856/167490431-da3b18e3-7069-4f53-8c62-ad7c902deb66.png">

**Additional context**

**Detailed Description**

**Context**

**Comment by catherineluse** [comment]
# QA Template

## Root cause
Incorrect handler for `finish` event on CruResource component
 
## What was fixed, or what changes have occurred
Removed broken code from the handler for saving a receiver so it redirects to AlertmanagerConfig on save.
 
## Areas or cases that should be tested
Same as repro steps
 
## What areas could experience regressions?
Can't think of any

**Comment by ronhorton** [comment]
**Pass** verified fixed in `2.6-head Commit ID 132b182`

1. create alertmanagerconfig
2. click new config
3. click add receiver
4. configure receiver
5. on save, user lands on alertmanagerconfigs: alert details
