### ISSUE TITLE
Internationalization needs improving in 2.6

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5950]
Internal reference: SURE-4640
Reported in 2.6.4 but applies to all of 2.6.x thus far

Issue description:
It looks like there's no option in the 2.6 UI to change the UI language – it's locked on English. Rancher is used by many developers in our organization whose native language is not US English.

All the versions of Rancher up to 2.5 had internationalization, so it's surprising to me that this feature was dropped in 2.6.

It's mandatory to login with English, navigate the UI in English, and the language selection has mandarin and (None). This was not a great experience.

(https://github.com/rancher/dashboard/issues/3336 may cover this already but it's not as explicit there about language support.)

Do note that there is a language selector once logged into the dashboard (under the 3-bar menu, bottom right, next to the version). This brought up more feedback however.

Expected behavior:

- Similar experience to v2.5, able to select the language at login, or have an obvious pop-up on first login to allow selection. As it is, it's not easy to find, and requires English to login and find it.
- The full set of languages as in v2.5
- Seeing (None) as a language looks like a UI bug.

**Comment by richard-cox** [comment]
The description is a bit contradictory (stating i18n has been dropped but then mentioning the i18n process). I've updated the title to make that clear (in case it makes it's way into release notes).

Working through the expected behaviour
- Agreed, user should be able to change language on the login screen (#3336). The plumbing gets a bit weird as the language is currently a per user setting (i think, rather than stored in session storage). We should also consider setting language on the setup screen.
- The languages from 2.5 were, from my understanding, community provided. If there are specific ones required for customers they'll need to be specifically requested (Gary/Neil correct me if I'm wrong).
- `(None)` is shown if the signed in user has enabled the `Enable Developer Tools & Features` option. Previously we didn't provide the consequences of this setting, but have updated the process for 2.6.6 (https://github.com/rancher/dashboard/pull/5761)

**Comment by nwmac** [comment]
Plan for 2.7 is to add locale indicator to login screen and pull out all of the strings, ready for new locales to be added.

We won't add new locales in 2.7 though.

**Comment by nwmac** [comment]
Stale. Some changes made to address locale change
