### ISSUE TITLE
Custom Node name not found in 2.6.x

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5951]
Internal reference: SURE-4644
Reported in 2.6.3

Issue description:

There was a setting for custom node name in 2.5, but not found in 2.6. Seems like a regression bug or the feature is removed. The user no longer has the option to change the node name as per their naming convention, which is causing difficulty for operations.

Repro steps:

- Create a 2.6.x rancher 
- Try to edit the node name from the node menu.

Actual behavior:
Not able to edit the node name in the node options.

Expected behavior:
Can be able to edit the node name in 2.5.

**Comment by gaktive** [comment]
Checking if Edit as Yaml is a sufficient workaround since that does work.

**Comment by gaktive** [comment]
Edit as YAML doesn't work either as it's throwing an error.

**Comment by cnotv** [comment]
Just to try to understand, are we talking about this name?
Where is located the menu you are mentioning?

![Screenshot 2022-06-07 at 12 20 27](https://user-images.githubusercontent.com/5009481/172357280-b8cab1e5-9cb6-4363-8442-7d11ad8283dd.png)

**Comment by cnotv** [comment]
Custom node field for 2.5.x UI

<img width="1336" alt="Screenshot 2022-06-07 at 19 48 41" src="https://user-images.githubusercontent.com/5009481/172449359-67da031d-e32c-42f4-9d3e-fb09c1d1434d.png">

The custom name is something I cannot see in the YAML resource file even after changing it.

**Comment by cnotv** [comment]
Any chance to know what has been written in the YAML file?

**Comment by kwwii** [comment]
We should check with Richard and have a conversation around what exactly is needed and what the MVP could be.

**Comment by cnotv** [comment]
As @richard-cox helped me to dig further, this value is displayed in the cluster `management` and not `explorer`, under the tab `Machine Pool`, which is the name for the RKE2 rather than Node Pool from RKE1.

- Cluster management -> CLUSTER_NAME -> Management Pool
- Path: `/dashboard/c/local/manager/provisioning.cattle.io.cluster/fleet-local/local#node-pools`
![Screenshot 2022-06-22 at 15 59 41](https://user-images.githubusercontent.com/5009481/175048106-82b56635-c8ec-4b66-8f4b-9a247b4b66b0.png)

To enable the users to edit this page, we should:
- Create the resource `edit/management.cattle.io.node.js`
- Add CRU form with custom name
- Override savings with `actuallySave()` method
- Save name to the value with `value.norman.name = ` and `value.save()`

Save through Steve API is blocked as defined in the model, as the PUT request is not safe.

**Comment by cnotv** [comment]
@richard-cox There's something weird going on with the navigation, but I guess is something secondary 😅 

https://user-images.githubusercontent.com/5009481/178035375-64a8c869-0f56-4d04-b207-64f7184abcb9.mov

**Comment by cnotv** [comment]
Seems like the information we gathered have something wrong:
- `actuallySave()` is not actually saving 😅 
- `this.value` has no `norman` nor `norman.name` in it

Based on the previous finding, I guess we are mixing up something.

**Comment by nwmac** [comment]
@aalves08 Talk to myself and/or Richard first

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###
Tested this issue with the following steps:
1. Create a 2.6.x rancher
2. Try to edit the node name from the node menu.

**Result**
User is able to give a custom name to nodes, however, not through the nodes menu.
![image.png](https://zube.io/files/rancher/a441759f912a1adbe736b2065fd6c338-image.png)
When clicking on `edit config` user is brought to the following page where no option is given to give custom name. ![image.png](https://zube.io/files/rancher/4967c421c270ed9886ae3ac741faeaa2-image.png)

If the user goes to the nodes through Cluster Management, then there is an option to give custom names.
Cluster Management > Cluster > `edit config` a node under `Machine Pools`
![image.png](https://zube.io/files/rancher/67159c7ebf96b43ffd1010d5c23e8254-image.png)

@aalves08 is this the expected behavior? Will close/reopen based on response.

**Comment by aalves08** [comment]
That's the expected behaviour @timhaneunsoo . You can only apply the custom node name via `management.cattle.io.node` (Rancher Node), which is the resource that controls the custom node name (applying the changes via Norman). This is a retro-fit from a feature that was in 2.5.x and we can't apply it to `node` resource on the explorer because it's a post-2.5.x resource and we can only add it to the API that supports it, which is Norman, via the `management.cattle.io.node` resource. 🙏 💦

**Comment by aalves08** [comment]
repeated myself a bit on the previous comment, but I think it's clear enough 😄
