### ISSUE TITLE
[2.6.7] Remove RKE1 Windows provisioning due to EOL

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/dashboard#5995]
https://github.com/rancher/windows/issues/179
https://github.com/rancher/windows/issues/182

As part of the 2.6.6 release, RKE1 Windows will be EOL. We need to remove the ability to provision new RKE1 Windows clusters through the Rancher UI. 

In the UI, this will mean the removal of the Windows Support boolean during the RKE1 provisioning and any other functionality specific to Windows.

**Comment by rosskirkpat** [comment]
@gaktive  Would we be able to setup a meeting to work with a dedicated UI resource to investigate and document what we need to do for the RKE1 Windows EOL?

**Comment by codyrancher** [comment]
I created two separate PRs depending on whether we're going to remove windows support vs showing a deprecation banner.

https://github.com/rancher/ui/pull/4850
https://github.com/rancher/ui/pull/4851

**Comment by sowmyav27** [comment]
**on 2.6-head commit id: `78017e6`**

<img width="1503" alt="Screen Shot 2022-07-27 at 9 03 52 PM" src="https://user-images.githubusercontent.com/26032343/181417824-610c691d-127d-4cef-aeb4-fcbcadbaca7b.png">

**Comment by sowmyav27** [comment]
Reopnening this issue since there is a slight change we need in the message

Actual:
`Windows support is being deprecated for RKE1. We suggest migrating to RKE2/K3s.`

Expected:
`Windows support is being deprecated for RKE1. We suggest migrating to RKE2.`

**Comment by slickwarren** [comment]
Tested on v2.6.7-rc6:
The current messaging is as follows in rke1:
<img width="1007" alt="Screen Shot 2022-08-04 at 10 25 34 AM" src="https://user-images.githubusercontent.com/16691014/183154126-250d6a77-74fb-4e85-8c8c-f939a419aa14.png">

however, this message only shows up during creation of a new cluster. We should enhance the message to also show up for rke1 clusters on the provisioning page at a minimum, so that the user sees the message when trying to register the windows node in rke1.

i.e. on this page, but only for rke1 clusters. 
<img width="931" alt="Screen Shot 2022-08-04 at 10 39 36 AM" src="https://user-images.githubusercontent.com/16691014/183154935-03c46434-f6b8-4919-b243-06a4a6238155.png">

**Comment by codyrancher** [comment]
@slickwarren  We already have it in two places. Why is this new third place critical?
![image](https://user-images.githubusercontent.com/55104481/183156949-d7f8ca0a-f55c-449b-9896-ee88353bcc81.png)

**Comment by slickwarren** [comment]
That screenshot is from ember. Currently the provisioning/registration page in 2.6.7 does not have a warning ( 2nd screenshot from my previous comment)

**Comment by slickwarren** [comment]
tested on v2.6.7-rc9:
I now see the following message displayed on the `registration page` in addition to the previously tested page, when creating an rke1 custom cluster
![Screen Shot 2022-08-11 at 9 37 11 AM](https://user-images.githubusercontent.com/16691014/184186305-03ffe9b9-f988-4181-9c33-f16c6316348c.png)
