### ISSUE TITLE
Multiple issues in Fleet (Dashboard and gitRepo Graph views)

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#6007]
**Setup**
- Rancher version: 2.6-head
- Browser type & version: Any

**Describe the bug**
1) UI get's blocked when navigating to `Fleet` `Git Repo` chart view
2) UI get's blocked when navigating to `Fleet` Dashboard view, right after creation of a fleet git repo

**To Reproduce 1)**
- add an RKE2 cluster in Cluster Management
- add a git repo in fleet
**repo url:** https://github.com/rancher/fleet-examples.git
**path:** /multi-cluster
- add another repo with the same exact configuration
- Navigate to the second gitrepo created (details page)
- click Graph button (top-right)

**To Reproduce 2)**
- add an RKE2 cluster in Cluster Management
- add a git repo in fleet
**repo url:** https://github.com/rancher/fleet-examples.git
**path:** /multi-cluster
- right after creation, navigate quickly to fleet dashboard view

**Result**
1) blocked UI. Error in console
2) blocked UI. Error in console

**Expected Result**
1) See Fleet gitrepo chart being render
2) blocked UI. Error in console

**Comment by AndrewHoffmanQA** [comment]
tested on 
Rancher version: v2.6-df1b20
Browser type & version: HA helm
rke - v1.3.13-rc3


bug 1-passed with notes

bug 2- passed




bug 1 notes-
scope of the bug as written is fixed, however this error is thrown (see screenshot)
![image.png](https://zube.io/files/rancher/e1a51a65bf79770e2a2f9d2b3117f37a-image.png)


I believe this is by design, you are trying to install the same stuff onto the clusters twice.
