### ISSUE TITLE
Project Member View not rendering search results properly

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/dashboard#6028]
**Setup**
- Rancher version: v2.6-head (after v2.6.5)
- Browser type & version: Firefox 100

**Describe the bug**
Search results are not rendered properly for new project members.
The backend returns the search query results fine, but the UI renders them underneath the Add Project Member modal.
Looks like a regression.

**To Reproduce**
1. Go to a cluster's Project/Namespaces view.
1. Click Create Project to add a new project.
1. Click Add to bring up the Add Project Member modal.
1. Search for a principal.

**Result**
The search results are not visible. Only a small part is barely visible under the modal.

**Expected Result**
The search results should appear.

**Screenshots**
<img width="1034" alt="Screen Shot 2022-05-24 at 12 13 23" src="https://user-images.githubusercontent.com/17733533/170085910-0b87d055-61c3-42ad-98e9-05c9f8952758.png">

**Detailed Description**

**Context**
This is urgent, as it hinders work on Azure AD endpoint migration - it's harder to test backend code changes in the UI like this (without changing the UI version in global settings).

**Comment by timhaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head bca5ada
Rancher cluster type: HA
Docker version: 20.10
Browser: Chrome Build 101.0.4951.67 & Firefox Version 100

----------

### Testing: ###

This issue was tested with the following steps:
1. Go to a cluster's Project/Namespaces view.
2. Click Create Project to add a new project.
3. Click Add to bring up the Add Project Member modal.
4. Search for a principal

**Result**
The results list is now showing as expected

Firefox:
![image.png](https://zube.io/files/rancher/b6420329275ac4f76505cc740e4730d5-image.png)

Chrome:
![image.png](https://zube.io/files/rancher/0fdd54ab75c4c4363fc75ddc41d702d0-image.png)
