### ISSUE TITLE
Unable to create project/namespaces or add members 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#6153]
Setup

Rancher version: 2.6-head 6e7308f
Browser type & version: Chrome

**Describe the bug**
Creating namespace/projects or adding members fails with an error 
`e is not a function` 

**To Reproduce**
1. Install rancher v2.6-head
2. Create a user - local or enabled auth provider
3. Add users in Cluster >> Cluster members >> Add members any role or create a project from project/namespaces

**Result**
Error `e is not a function` pops but the user is added in the cluster. Similarly projects are created

**Expected Result**
Expected no error while creating a project or adding users.

**Screenshots**
<img width="973" alt="Projects" src="https://user-images.githubusercontent.com/38144301/173160547-b481faf7-279f-4d86-b12a-66a03c9c5e56.png">

**Additional context**
Happens in the Cluster section of the explorer - local or any downstream cluster explorer
Able to create namespaces, workloads.

**Comment by catherineluse** [comment]
Assigning myself to this one because it may have been introduced from my recent PR

**Comment by catherineluse** [comment]
# QA Template

## Root cause
The root cause is that in a PR that modified the CruResource component, I accidentally removed the data that had previously been passed when emitting the `finish` event. https://github.com/rancher/dashboard/pull/6084/files#diff-3949ec5a78c462b58bebb75bc06ccea895056a12129a9a8b8841dac3dd6b07d0R283
 
## What was fixed, or what changes have occurred
I created a PR that passes event data when emitting the `finish` event. https://github.com/rancher/dashboard/compare/fix-cruresource?expand=1#diff-3949ec5a78c462b58bebb75bc06ccea895056a12129a9a8b8841dac3dd6b07d0R283

This is which is what the CruResource component had already been doing before my PR accidentally removed it: https://github.com/rancher/dashboard/pull/6084/files#diff-3949ec5a78c462b58bebb75bc06ccea895056a12129a9a8b8841dac3dd6b07d0L384
 
## Areas or cases that should be tested
Same as the steps to reproduce the issue
 
## What areas could experience regressions?
The CruResource component is used in every form, but this PR is restoring functionality it already had previously, so I wouldn't expect a regression
 
## Are the repro steps accurate/minimal?
yes

**Comment by sowmyav27** [comment]
**On 2.6-head commit id: `a8ae635`**

- No errors seen when creating projects or adding users as cluster members.
- Able to create projects successfully.
- Able to add users as cluster members successfully.
