### ISSUE TITLE
Roles cannot be updated to inherit or grant resources

### ISSUE THREAD

**Issue by nwithers-ecr** [rancher/dashboard#6212]
**Setup**
- Rancher version: 2.6.5
- Browser type & version: firefox nightly 102.0a1 (2022-05-17) (64-bit)

**Describe the bug**

I cannot update rbac for roles through the UI.

**To Reproduce**

 Logged in as full administrator I then go to
`Users & Authentication` -> `Roles` -> `Projects/Namespaces` -> `Project Member` -> `...` -> `Edit Config` -> `Inherit From` -> `Add Resource` -> `View Secrets` -> `Save`

**Result**
It says the save was successful, but the inherited role is not listed, only `Kubernetes Edit`, and view-secrets permission is not listed in the table. Project Members assigned to that namespace are not able to view secrets.

**Expected Result**

Inheritance and GrantResources are correctly saved to roles

**Screenshots**

**Additional context**

per instructions from slack I am able to edit the `roletemplates.management.cattle.io/project-member` resource manually like so
```
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
```

**Comment by jordojordo** [comment]
Upon investigating I've noticed that the schema for `management.cattle.io.roletemplate` has multiple blocked methods (`blocked-PUT`, `blocked-PATCH`, `blocked-DELETE`) which would explain the behavior coming from the dashboard.

![roletemplates](https://user-images.githubusercontent.com/40806497/179823520-e66e4756-2313-412c-9e82-4f1f053bcd6d.png)

This leads to a question for UI, should we remove the ability to edit the config of `blocked` resources as we have done on cases similar to this (#4265)? @nwmac @richard-cox @catherineluse

**Comment by catherineluse** [comment]
It seems weird that DELETE is blocked. Is that only blocked if it is in use?

**Comment by catherineluse** [comment]
Michael Bolot said:

> Steve is configured today to reject write calls to it. Those methods signify that the user is allowed to take those actions, but not through steve (i.e. use norman).

**Comment by jordojordo** [comment]
> Those methods signify that the user is allowed to take those actions, but not through steve (i.e. use norman).

This shouldn't be an issue, however, this resource is already dispatching an action [through Norman upon save](https://github.com/rancher/dashboard/blob/c614af2173b46d171618530c7972784ca4744f6d/shell/models/management.cattle.io.roletemplate.js#L162-L166).
I attempted to manually update the resource from `/v3/roleTemplates/project-member` with the `secrets-view` within the `roleTemplateIds` property. The request was sent correctly but the new `roleTemplateId` did not save.

**Request**
![request](https://user-images.githubusercontent.com/40806497/179992889-b4122de0-0b9e-4815-8b43-24209b6ec24e.png)

**Response**
![response](https://user-images.githubusercontent.com/40806497/179992914-ce72f9d2-1778-4e74-be3b-ac168d20af16.png)

This seems to be an issue related with the backend, am I missing something here?

**Comment by jordojordo** [comment]
Update:
After further investigation it became clear that the issue was due to the Role being considered `builtin` (_i.e. Rancher specific_). In the old UI we actually prevent the user from being able to update roles that are builtin, thus we decided it would be best to transfer that functionality over to the dashboard.

The fix will remove the Edit and Delete actions from a role if it has the property `builtin: true`. This will still allow you to create your own roles and edit/delete them as necessary.

_Old UI for reference_
![oldui](https://user-images.githubusercontent.com/40806497/180081293-4daba271-7653-4674-be38-be426499823f.png)

**Comment by gaktive** [comment]
Putting this back into To Test for QA to validate.

**Comment by brudnak** [comment]
# :white_check_mark: PASSED

## Reproduction Environment

| Component                 | Version / Type                     |
| ------------------------- | ---------------------------------- |
| Rancher version           | 2.6.6                              |
| Installation option       | helm                               |
| RKE binary version used   | v1.3.11                            |
| If Helm Chart k8s cluster | v1.23.6                            |
| Cert Details              | let's encrypt                      |
| Helm version              | v2.16.8-rancher1                   |
| Downstream cluster type   | not applicable                     |
| Downstream K8s version    | not applicable                     |
| Logged in user role       | administrator                      |
| Browser type              | Opera GX                           |
| Browser version           | LVL4 (core: 89.0.4447.64) (x86_64) |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx
```

## Reproduction steps

1. Starting from the **default** Rancher dashboard, click on the `hamburger menu` icon
2. Click ==> `Users & Authentication` ==> `Roles` ==> `Projects/Namespaces` ==> `Project Member` ==> `...` ==> `Edit Config` ==> `Inherit From` ==> `Add Resource` ==> `View Secrets` ==> `Save`
3. Repeat `step #2` and see that the added resource `View Secrets` wasn't actually saved


## Additional Info

## RESULTS

#### :white_check_mark: Expected
Unable to Edit Config of a built-in role in the UI

#### :x: Actual
Appearance of being able to edit the built-in role

<hr>
  
## Validation Environment

| Component                 | Version / Type                                                                     |
| ------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version           | v2.6-2587e6a79e4778cfbe41c9e5d6e9d70e2ea0754b-head                                 |
| Rancher commit link       | https://github.com/rancher/rancher/commit/2587e6a79e4778cfbe41c9e5d6e9d70e2ea0754b |
| Installation option       | helm                                                                               |
| RKE binary version used   | v1.3.11                                                                            |
| If Helm Chart k8s cluster | v1.23.6                                                                            |
| Cert Details              | let's encrypt                                                                      |
| Helm version              | v2.16.8-rancher1                                                                   |
| Downstream cluster type   | not applicable                                                                     |
| Downstream K8s version    | not applicable                                                                     |
| Logged in user role       | administrator                                                                      |
| Browser type              | Opera GX                                                                           |
| Browser version           | LVL4 (core: 89.0.4447.64) (x86_64)                                                 |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx \
  --version 2.6.7-rc3 \
  --set rancherImageTag=v2.6-head
```

## Validation steps

1. Starting from the **default** Rancher dashboard, click on the `hamburger menu` icon
2. Click ==> `Users & Authentication` ==> `Roles` ==> `Projects/Namespaces` ==> `Project Member` ==> `...`
3. There is no option to edit, since it's a built-in role
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
Unable to Edit Config of a built-in role in the UI

#### :white_check_mark:Actual
Unable to Edit Config of a built-in role in the UI
