### ISSUE TITLE
Improve rbac user-selection filter

### ISSUE THREAD

**Issue by kwwii** [rancher/dashboard#6217]
**Setup**
- Rancher version: 2.6*
- Browser type & version: any

**Detailed Description**
The current user-selection filter only filters in the exact format of the list (Lastname, Firstname). As a user, I would like to be able to not enter a capital letter as the first letter and still see the usernames starting with that letter. As a user, I would like to be able to filter for a user starting with either their firstname OR lastname.

**Context**
The current filter is a regression from 2.5. Also, filters on other pages do not exhibit the same behavior.

**Comment by catherineluse** [comment]
This sounds like it would be an easy bug fix, since the UI would just need to make the search case-insensitive. Since it's a regression, should it be labeled as a bug instead of an enhancement? And is there any design work needed before this can be implemented, or can it be moved to the backlog?

**Comment by edenhernandez-suse** [comment]
I was checking this filter:

![image](https://user-images.githubusercontent.com/120640736/218522181-cabc7561-4f01-49a8-b515-c19b266069c1.png)

In Auth Provider, selecting an option different than "Allow any valid user", but I am not 100% sure if that's the filter this issue is all about. 

From what I could test, that one is not case-sensitive, although it has poor filtering logic. However, it looks like it gets the results from the Auth provider itself, so maybe it's not something we can solve on our end.

**Comment by edenhernandez-suse** [comment]
Part of #8233
