### ISSUE TITLE
Cluster details page shows internal ip's only for ec2 clusters

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#6371]
**Setup**
- Rancher version: `v2.6-2c2137347e42f48ea9ab8e3ded0830f78050aef0-head`
- Browser type & version: `Chrome`

**Describe the bug**
Cluster details page shows internal ip's only for ec2 clusters

**To Reproduce**
1. Fresh install of rancher `v2.6-head`
2. Deploy a downstream AWS Node driver cluster
3. From `Cluster Management`, select the cluster's name hyperlink under `Name`
4. Reproduced

**Result**
IP Addresses listed are internal 

**Expected Result**
IP Addresses listed are external OR both external/internal

**Screenshots**
<img width="1706" alt="Screen Shot 2022-07-14 at 10 28 55 AM" src="https://user-images.githubusercontent.com/46494969/179046721-09608317-c505-4004-8aab-883254c48048.png">

**Additional Context**
Linode Node driver clusters display external ip's as expected; AWS Node driver clusters do not; EC2 specific

**Comment by nwmac** [comment]
@torchiaf You'll need AWS access if you don't have it

**Comment by torchiaf** [comment]
Self-removed my assignment because Catherine is already working on it.

**Comment by catherineluse** [comment]
I closed my PR addressing this issue because I believe it unnecessary due to the fact that I can no longer reproduce the original bug in the master branch.

Here's how it looks when you have an RKE2 cluster in EC2:
<img width="869" alt="Screenshot 2022-12-01 at 4 30 37 PM" src="https://user-images.githubusercontent.com/20599230/205182261-d895339f-b12d-43e2-8579-7f3a152daac3.png">

Here's how it looks when you have an RKE1 cluster in EC2:

<img width="850" alt="Screenshot 2022-12-01 at 4 44 26 PM" src="https://user-images.githubusercontent.com/20599230/205182472-b08233aa-c519-4683-9c14-d4b510199661.png">

**Comment by catherineluse** [comment]
# QA Template
## Root cause
There are two class models for nodes:`shell/models/management.cattle.io.node.js`, which is used to represent nodes in RKE1 cluster provisioning, and `cluster.x-k8s.io.machine.js`, which is used to represent nodes in V2 cluster provisioning for RKE2/K3s. Both of these class models used an `ipaddress()` getter to represent the IP. This was inconsistent with how the IP is displayed in Cluster Explorer, because in Cluster Explorer, the table header always includes both internal and external IPs, not just one IP.
 
## What was fixed, or what changes have occurred
I have modified the class models to replace the single ipAddress getter with two separate getters for internal and external IPs. The appearance of the internal/external address column in cluster management is now supposed to be identical to the one in Cluster Explorer.
 
## Areas or cases that should be tested
RKE2 and RKE1 clusters should be provisioned in EC2 to make sure the IP is consistent across cluster management and cluster explorer.
 
## What areas could experience regressions?
RKE2 and RKE1 clusters should also be provisioned in Digital Ocean - there should be no difference for any IP address column between cluster management and cluster explorer.

**Comment by richard-cox** [comment]
@catherineluse I see the following for an RKE2 cluster on a pretty recent 2.7-head build (ignore the drained state)

![image](https://user-images.githubusercontent.com/18697775/207123035-2fb1d65d-c4ec-49e5-93dc-742877ef95f3.png)

![image](https://user-images.githubusercontent.com/18697775/207123077-5faf59f5-5139-49e9-b9c8-a10bf66339f2.png)

It could be a simple fix of this.status?.addresses --> this.status.internalNodeStatus tweaks in shell/models/management.cattle.io.node.js, but i haven't dived in to it

**Comment by Josh-Diamond** [comment]
Ticket #6371 - Test Results
---

With Docker on a single-node instance:

Verified on rancher `v2.7-ae44c398377516fcd150b8fc2a81a9fd6d4d8fb5-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Amazon EC2 RKE1 | ✅ |
| 2. | Amazon EC2 RKE2 | ✅ |

---

Scenario 1:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream AWS Node driver RKE1 cluster w/ 3 nodes - individual roles
3. Once `active`, Navigate to `Cluster Details > Machine Pools`
4. Verified - External/Internal IPs are seen as expected

---

Scenario 2:
1. Fresh install of rancher `v2.7-head`
2. Provision a downstream AWS Node driver RKE2 cluster w/ 3 nodes - individual roles
3. Once `active`, Navigate to `Cluster Details > Machine Pools`
4. Verified - External/Internal IPs are seen as expected
