### ISSUE TITLE
Creating a project as an admin results in `error updating PSPT ID` error 

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#6377]
Setup

Rancher version: 2.6-head a3a8f33
Browser type & version: Chrome

**Describe the bug**
Unable to create a project as an admin, as it results in an error `error updating PSPT ID`. If we retry creating the project, it goes through without that error.

**To Reproduce**
1. As an admin, create a downstream cluster
2. Go to projects/namespaces
3. Create a project

**Result**
Results in an error `error updating PSPT ID`
Following logs are seen in network tab:
```
baseType | "error"
-- | --
code | "Conflict"
message | "error updating PSPT ID"
status | 409
type | "error"

```

**Expected Result**
Expected the project creation to go through.

**Screenshots**
<img width="400" alt="PSPT" src="https://user-images.githubusercontent.com/38144301/179087371-a17efd96-7654-4e14-bea0-49ec277d2e18.png">

**Additional context**
This does not happen always. 
After the above error, if we retry the project creation goes through fine without any error.

**Comment by richard-cox** [comment]
Duplicate of https://github.com/rancher/dashboard/issues/6089.

There might have been a change in the backend that causes the project to be updated promptly following it's creation. That would lead to the immediate setpodsecuritypolicytemplate action to fail with the 409 conflict.

```
    const newValue = await norman.save({ replace: forceReplaceOnReq });

    await newValue.doAction('setpodsecuritypolicytemplate', { podSecurityPolicyTemplateId: this.spec.podSecurityPolicyTemplateId || null });
```

Think this issue is happened often enough to make a special case, we could catch the 409, force re-fetch of project and attempt again. Alternatively go with the whole `handleConflict` function that's used by the CreateEditView mixin to handle generic 409 errors

**Comment by anupama2501** [comment]
Verified on v2.6head b66dd0f

1. As an admin, created a downstream cluster
2. Created a project - no errors seen
