### ISSUE TITLE
Add manual refresh feature to "heavy" list views

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#6498]
Some list views for resources are quite "heavy" in terms of usage for mem and CPU, so we want to provide an option to the user (on global settings) where they can enable the ability to manual refresh a list, preventing therefore the `watch` on the resource that triggers constant UI updates and slows down rancher dashboard and is detrimental to the user experience.

**Comment by catherineluse** [comment]
Related issue https://github.com/rancher/dashboard/issues/6484

**Comment by git-ival** [comment]
@aalves08 @bmdepesa @catherineluse 
Tested all suggested cases from PR #6543. LGTM except for the case where Manual Refresh + Incremental Loading are enabled and the list view is paginated (See the middle/end of the last video below). 

Essentially, when both features are enabled and you navigate to the 2nd page and you perform a Manual Refresh then the 2nd page fails to load any entries.

Note: The issue identified above could be constrained to only occur on the final page since I only had 2 pages to work with.

No Manual Refresh + No Incremental Loading:

https://user-images.githubusercontent.com/85186645/184258881-68e169fc-61d4-4499-8254-e5942e67c22d.mp4

Manual Refresh:

https://user-images.githubusercontent.com/85186645/184259012-119b4ebf-3500-4e16-b870-f4f57786cab6.mp4

Incremental Loading:

https://user-images.githubusercontent.com/85186645/184259018-3d81f5e2-2144-401c-b7f0-3981253ccd96.mp4

Manual Refresh + Incremental Loading:

https://user-images.githubusercontent.com/85186645/184259179-098c7904-4ccd-4182-96a4-04c3f478d396.mp4

**Comment by aalves08** [comment]
@git-ival I've merged a fix for the pagination issue. 🙏

**Comment by git-ival** [comment]
@aalves08 @bmdepesa @catherineluse
Tested all suggested cases from PR https://github.com/rancher/dashboard/pull/6543 using Rancher 2.6-head. 

LGTM, however can you confirm the expected behavior when Manual Refresh and Incremental Loading are enabled when there are multiple pages on the list view @aalves08?
Observed Behavior: Post-fix when I was on the last page of a list view with multiple pages of results, I manually refreshed and it reloaded the entire list which sent me back to the first page. You can see the final video below for context.

No Manual Refresh + No Incremental Loading:

https://user-images.githubusercontent.com/85186645/184399595-7c5307a0-1640-4673-a188-2e47c72d9252.mp4

Manual Refresh:

https://user-images.githubusercontent.com/85186645/184399741-47634706-e128-4b87-bf84-67c1400bbde8.mp4

Incremental Loading:

https://user-images.githubusercontent.com/85186645/184399774-7ba3deab-0d0a-4c0a-b754-33275b67ce75.mp4

Manual Refresh + Incremental Loading:

https://user-images.githubusercontent.com/85186645/184399790-63adfcb9-3f09-45a8-ab5b-d28ccbf97b73.mp4

Behavior of Manual Refresh + Incremental Loading with Multi-Page list view:

https://user-images.githubusercontent.com/85186645/184405035-defdd6bb-68e7-415c-b2b3-7940f23a06f9.mp4
