### ISSUE TITLE
Project list does not react to changes

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#6565]
**Setup**
- Rancher version: 2.6-head

**Describe the bug**
Three bugs
- Create a project, and then create a namespace in that project. The namespace does not appear in the project's group (page refresh required)
- Create a project with a namespace in and refresh the page. Delete the project. Intermittently the project remains (with no namespace). This is similar to https://github.com/rancher/dashboard/issues/3175 (fixed by https://github.com/rancher/dashboard/pull/3275)
- Changes made to projects in a secondary window are not reflected in the original window's project list

List also suffers from https://github.com/rancher/dashboard/issues/6557

**Comment by richard-cox** [comment]
I had a quick look in to the first bug, it relates to the activeNamespaceCache cache not updating following the creation of the NS. switching this out fixes it, but isn't the right solution. On NS create/delete we probably need to force a refresh of that cache

```
      // const activeNamespaces = this.$store.getters['activeNamespaceCache']();
      const activeNamespaces = this.$store.getters['namespaces']();
```

**Comment by catherineluse** [comment]
> force a refresh of that cache

The `namespaces` getter is recalculated every time, whereas `activeNamespaceCache` is recalculated whenever we switch namespaces. While the cache can be outdated, the results should be identical. I'm thinking the simplest solution is to use the `namespaces` getter when loading the page for the first time and maybe also use that result to warm the cache.

**Comment by catherineluse** [comment]
I found out that Steve updates in the downstream and forced asynchronous updates will trigger immediate changes when you have Rancher opened in two browser. However, changes to the management cluster, such as an added or removed project, do not trigger automatic updates in downstream clusters.

I say that based on two observations, after fixing other issues with computed properties:

- With Rancher open in two browsers, the deleted project was only immediately detected in cluster explorer if both browsers were looking at the local cluster.
- The project deletion was detected if the project contained a namespace, but not if it was empty.
- When a new project was created, it would load in the second browser, usually after a short delay. But when a project was deleted, it never showed in the second browser.

On a downstream cluster, I found that when a project was deleted, the rows were reloaded, and any changes to the namespaces were reflected immediately, but the UI was not aware that the project list had changed.

To get around this, I added a watcher on the projects/namespaces list view that waits for the filtered rows to be recomputed. When that happens, it force-fetches the list of projects again. This seems to resolve the issue, so now when a project is added or removed in the first browser, the change is immediately reflected in the second browser.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.6-head 89fec60
Rancher cluster type: HA
Docker version: 20.10

----------

### Reproduction: ###
I was able to reproduce the following:
- Create a project, and then create a namespace in that project. The namespace does not appear in the project's group (page refresh required)
    - Refresh was required
- Create a project with a namespace in and refresh the page. Delete the project. Intermittently the project remains (with no namespace). This is similar to https://github.com/rancher/dashboard/issues/3175 (fixed by https://github.com/rancher/dashboard/pull/3275)
![image.png](https://zube.io/files/rancher/c0da08ec265f1dd1bb8655bdc57bfce1-image.png)
- Changes made to projects in a secondary window are not reflected in the original window's project list
    - You can see project test1 in first window but not in the second window
![image.png](https://zube.io/files/rancher/5791fca85f2ae79114ca46e69c38b81e-image.png)

### Testing: ###

Tested the following scenarios:
- Create a project, and then create a namespace in that project. The namespace does not appear in the project's group (page refresh required)
- Create a project with a namespace in and refresh the page. Delete the project. Intermittently the project remains (with no namespace). This is similar to https://github.com/rancher/dashboard/issues/3175 (fixed by https://github.com/rancher/dashboard/pull/3275)
- Changes made to projects in a secondary window are not reflected in the original window's project list

**Result**
1. The namespace appeared without having to refresh the page
![image.png](https://zube.io/files/rancher/b83c523af3f1d27c23e7c7aad548f1b1-image.png)
2. UI now asks user to also delete the namespace, if namespace is not deleted, then namespace gets moved to `Not in a Project` section.
![image.png](https://zube.io/files/rancher/784706fdfef8b56093f92665b6a97553-image.png)
![image.png](https://zube.io/files/rancher/b02aecbc23bb73ab5b7dd65f00aabd64-image.png)
3. Both windows are updating properly now
![image.png](https://zube.io/files/rancher/487d94d50ce2ebc03ec2d014b5611bec-image.png)
