### ISSUE TITLE
Add UI/API warning when removing a custom role that is in use

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6578]
Internal reference: SURE-4773
Reported in 2.6.3

Request description:
An admin had removed a project role that inadvertently orphaned access for a number of users. It was a manageable amount so they could resolve it with some corrective effort; however, the takeaway was that there might be an improvement to add a UI warning/guard rail -- some visual reference to indicate if it’s in use etc., -- or at least some documentation notes about this being a potentially destructive action.

Actual behavior:
Project role was deleted, orphaning access for users that were added as members. Some documentation around role lifecycle would also be ideal.

Expected behavior:
Visual indicator of custom roles that are being used, a warning should prevent deletion without explicit acceptance.

Workaround:
Maybe, perhaps not so easy: manually check role bindings?

**Comment by gaktive** [comment]
We'd need to grab all the role bindings ourselves, though we could cache them (especially helpful for large amounts of them) and put up an advisory stating "Looking up role bindings, please wait".

Low bar: add a banner advising the user stating "Please ensure the role binding isn't in use"

**Comment by dasarinaidu** [comment]
I have validated the issue and looks good with an observation. I reported it as a new issue(#7046) and closing this card.

**Observation:**
While removing a ROLE, the user is getting a confirmation window. On the window the Caution in RED color - the 'number' of bounded users to the roles is incorrect. It is displaying the SUM of all the users counts from all the ROLES which are associate to the each role. It would be good to have the actual number of users bounded as a total.
Ex: Role 1 has 2 users (U1, U2)
Role 2 has users (U1, U3)

The dialog window is showing as 4 users instead of 3 users as U1 is common in both roles

Note: In the attached screen the total users shows 76 which leads some confusion as this node has just 8 users all together.


**Validated below test scenarios before closing the card on **v2.6-head**:** 
1. Delete custom Project role which has a user attached
2. Delete custom Project role which does NOT have a user attached
3. Delete custom Global role which has a user attached
4. Delete custom Global role which does NOT have a user attached
5. Delete built in Project Role which has a user attached 
6. Delete custom Project role which has 2 users attached 
7. Delete built in Global Role which has a user attached 
8. Delete ALL Project Role which has a user attached and builtIn
9. Delete ALL Global Role which has a user attached and builtIn
10. Delete ALL Global Role which has a user attached and builtIn 
 (Perform the above operation with a different user LOGIN)
11. Click Cancel button from the window
12. Click Delete button from the window
13. Use the Tip to Delete the Roles(Command + Delete button)

**Example Confirmation Windows:**

<img width="395" alt="image" src="https://user-images.githubusercontent.com/22034884/193037753-87b64620-caff-42da-ae67-fb3a044b628d.png">

<img width="396" alt="image" src="https://user-images.githubusercontent.com/22034884/193037854-a4659ec3-58c5-4130-8d10-deea6d9bf137.png">

<img width="393" alt="image" src="https://user-images.githubusercontent.com/22034884/193037980-7e8f7abe-1837-498f-8f3d-3db829d9c8cc.png">
