### ISSUE TITLE
Allow to change minimum length requirement for user password

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#6633]
**Detailed Description**
Allow to change the setting for user password length requirement from default of 12.

**Context**
The password length can be defined exclusively with env var `CATTLE_PASSWORD_MIN_LENGTH` in setup time and not from the UI as other settings.

As this is a Kube resource, it can be updated using a POST request to settings.
- `management.cattle.io.setting`
- `management.cattle.io/v3`
- key: `password-min-length`

- Original merged issue: see slack
- Settings: `/v3/settings/password-min-length`

![Screenshot 2022-08-10 at 13 49 44](https://user-images.githubusercontent.com/5009481/183893984-f4e5ba88-2992-488d-b942-1441660cd2dc.png)

**Comment by richard-cox** [comment]
@cnotv Double check with the backend team that this is possible at run time, I have a feeling it can only be set when installing.

**Comment by cnotv** [comment]
@richard-cox Waiting for any answer in the private channels.

**Comment by cnotv** [comment]
Adde extra infos.

**Comment by nwmac** [comment]
@cnotv Can this be changed after install? If so, what happens when you set the min length to say 20 and users have passwords that are shorter than 20 characters?

**Comment by cnotv** [comment]
@nwmac seems like it's possible to change it after the install, based to what has been told me, not tested though.

Not sure how is the functionality for existing users, but I imagine that would be a parameter for a new request.

**Comment by nwmac** [comment]
@cnotv Do you want to go ahead and add support for configuring this setting - code is in `shell/list/management.cattle.io.setting.vue` - I think you just need to add the setting to `ALLOWED_SETTINGS` and make sure there is a localised string for the setting.

**Comment by cnotv** [comment]
Resource value as default:

```json
    {
      "id": "password-min-length",
      "type": "management.cattle.io.setting",
      "links": {
        "remove": "blocked",
        "self": "/v1/management.cattle.io.settings/password-min-length",
        "update": "/v1/management.cattle.io.settings/password-min-length",
        "view": "/apis/management.cattle.io/v3/settings/password-min-length"
      },
      "apiVersion": "management.cattle.io/v3",
      "customized": false,
      "default": "12",
      "kind": "Setting",
      "metadata": {
        "creationTimestamp": "2022-08-04T12:10:19Z",
        "fields": [
          "password-min-length",
          ""
        ],
        "generation": 1,
        "managedFields": [
          {
            "apiVersion": "management.cattle.io/v3",
            "fieldsType": "FieldsV1",
            "fieldsV1": {
              "f:customized": {},
              "f:default": {},
              "f:source": {},
              "f:value": {}
            },
            "manager": "rancher",
            "operation": "Update",
            "time": "2022-08-04T12:10:19Z"
          }
        ],
        "name": "password-min-length",
        "relationships": null,
        "resourceVersion": "511",
        "state": {
          "error": false,
          "message": "Resource is current",
          "name": "active",
          "transitioning": false
        },
        "uid": "7f570f7d-4102-4d84-a0e7-6cf24fc44c1d"
      },
      "source": "",
      "value": "12"
    },
```

**Comment by cnotv** [comment]
@nwmac If a password is e.g. length 3 and we increase/restore the value to 12, no message error is provided.

**Comment by Josh-Diamond** [comment]
Re-opening due to the following concerns:
- Current behavior allows `password-min-length` to be set to ZERO or to negative values;  This conflicts with actually setting a password, which requires at least one character.  Passwords >=1 character may be set, and used as valid credentials with a ZERO or negative `password-min-length` set. 

Suggestion:
- Restrict `password-min-length` from being set to anything >1

---

Ticket #6633 - Test Results

With Docker on a single-node instance:

Reproduced on rancher `v2.6.8`:
1. Fresh install of rancher `v2.6.8`
2. As admin, navigate to `Users & Authentication`
3. Change password to anything less than 12 characters
4. Reproduced - `Password must be at least 12 characters`

Screenshot:

`Step 4`
<img width="1452" alt="Screen Shot 2022-09-06 at 3 46 34 PM" src="https://user-images.githubusercontent.com/46494969/188755001-49602aa3-4645-4dcb-8a87-1a910be86d63.png">

---

Verified on rancher `v2.6-400e559407d14ad925caf2f56f5edd8645dbdaba-head`:

Scenario 1 - `Set pass-min-length to 0; then change password to blank field` - ❌ 
1. Fresh install of rancher `v2.6-head`
2. As admin, navigate to `Global Settings > password-min-length`
3. Change min length to `0`
4. Verified - RancherUI successfully sets pass-min-length to ZERO
5. Navigate to `Users & Authentication`, and set password to blank field
6. Veri-FAILED - RancherUI won't allow passwords >1 character to be set; `Global Settings` allow `password-min-length` to be set to `0`

---

Scenario 2 - `Set pass-min-length to 0; then change password to 1 character` - ✅ 
1. Fresh install of rancher `v2.6-head`
2. As admin, navigate to `Global Settings > password-min-length`
3. Change min length to `0`
4. Verified - RancherUI successfully sets pass-min-length to ZERO
5. Navigate to `Users & Authentication`, and set password to a single character
6. Verified - Password successfully set + valid upon login

---

Scenario 3 - `Set pass-min-length to 4; then try to change password to 3 characters; expected fail` - ✅ 
1. Fresh install of rancher `v2.6-head`
2. As admin, navigate to `Global Settings > password-min-length`
3. Change min length to `4`
4. Verified - RancherUI successfully sets pass-min-length to FOUR
5. Navigate to `Users & Authentication`, and set password to three characters
6. Verified - Password validation successfully prevents 3 character password and explains "why" w/ message

Screenshot:

`Step 6`
<img width="1451" alt="Screen Shot 2022-09-06 at 4 37 29 PM" src="https://user-images.githubusercontent.com/46494969/188758358-aacf6a86-9e1d-400f-9abd-453a76763de6.png">

---

Scenario 4 - `Set pass-min-length to 1,000,000; set password to 1,000,000 characters` - ✅ 
1. Fresh install of rancher `v2.6-head`
2. As admin, navigate to `Global Settings > password-min-length`
3. Change min length to `1,000,000`
4. Verified - RancherUI successfully sets pass-min-length to ONE MILLION
5. Navigate to `Users & Authentication`, and set password to ONE MILLION characters
6. Verified - Password successfully set + valid upon login

---

Scenario 5 - `Set pass-min-length to negative value` - ✅ - ❗  PASS NOT EXPECTED ❗ 
1. Fresh install of rancher `v2.6-head`
2. As admin, navigate to `Global Settings > password-min-length`
3. Change min length to `-2` - [type input manually]
4. Verified - RancherUI successfully sets pass-min-length to `-2`

Screenshot:

`Step 4`
<img width="1208" alt="Screen Shot 2022-09-06 at 4 47 29 PM" src="https://user-images.githubusercontent.com/46494969/188759256-fb05aede-5f09-4246-acf2-d125f731a317.png">

**Comment by cnotv** [comment]
We will have to introduce something like validation to the settings, not sure if it exists yet.
Setting back the estimation to 2.

**Comment by cnotv** [comment]
Created related issue out of this topic, as extension to this adjustment.
- https://github.com/rancher/dashboard/issues/6816

**Comment by cnotv** [comment]
@Josh-Diamond for consistency, is this option validated while installing Rancher as well is we pass something like `CATTLE_BOOTSTRAP_PASSWORD=-2`?

**Comment by Josh-Diamond** [comment]
@cnotv Yes, you may set the minimum password length to a negative value upon initial installation:

```docker
docker run -d -p 80:80 -p 443:443 --privileged -e CATTLE_PASSWORD_MIN_LENGTH=-2 rancher/rancher:v2.6-head
```

When doing so, from the UI, you'll notice a banner, `Set by Environment Variable`:

<img width="1212" alt="Screen Shot 2022-09-07 at 8 50 12 AM" src="https://user-images.githubusercontent.com/46494969/188922841-376d4dc6-dc19-4fed-86fe-1fc379c03992.png">

**Comment by Josh-Diamond** [comment]
@cnotv Is there a max password length that should be enforced?  
With my validation tests, I was able to set `min_password_length` to `1,000,000`.  
Although, not an issue, i'm curious if this is ideal/desired.  
I can't wrap my head around why someone would use triple digits even for `min_password_length`

**Comment by cnotv** [comment]
I think we should set a range but I have no parameters to define a maximum.
I guess 32 characters may be enough?

**Comment by rak-phillip** [comment]
@cnotv it looks like OWASP has some recommendations on password length. This might be a good place to start for considering any limits we might want to set. 

> Maximum password length should not be set too low, as it will prevent users from creating passphrases. A common maximum length is 64 characters due to limitations in certain hashing algorithms, as discussed in the [Password Storage Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#maximum-password-lengths). It is important to set a maximum password length to prevent [long password Denial of Service attacks](https://www.acunetix.com/vulnerabilities/web/long-password-denial-of-service/).

https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html#implement-proper-password-strength-controls

**Comment by Josh-Diamond** [comment]
Offline conversation with @macedogm has suggested:
`Yes, it's a good practice to limit the max password length....limiting in 256 is okay`

@cnotv Do you have any concerns w/ a 256 character limit? 
If not, could we try to get that implemented?

**Comment by cnotv** [comment]
It sounds good to me, thanks for taking care of it.

**Comment by cnotv** [comment]
It sounds good to me, thanks for taking care of it.

**Comment by Josh-Diamond** [comment]
@cnotv Sure thing, i will create an issue/enhancement in rancher/rancher to set a max limit for `min-password-length`

**Comment by Josh-Diamond** [comment]
Closing out issue, as validation around allowing change to minimum length requirement for user password has successfully been provided.

Further enhancements will be tracked here: [rancherlabs/rancher-security/issues/1072](https://github.com/rancherlabs/rancher-security/issues/1072)

**Comment by Josh-Diamond** [comment]
Ticket #6633 - Test Results - REOPENED
---

With Docker on a single-node instance:

Verified on rancher `v2.7-c0f6cdb9a7494cb6eae2e3b341174bd079f13073-head`:
1. Fresh install of rancher `v2.7-head`
2. Navigate to `Global Settings > password-min-length`
3. Verified - unable to set negative values, zero value, or value of 1
4. Verified - able to set value from 2-256
5. Verified - Once value is set from range 2-256, new users are prompted w/ accurate validation during new user creation
6. Verified - Unable to set value greater than 256
7. Veri-FAILED: able to set value of `2.5`; global settings accept change but it is not respected; validation during new user creation prompts 12 character min requirement;

Comments:
Although, global settings allow the use of decimals within the range of 2-256, this isn't accepted as being valid when creating a new user.  We should prevent this usecase from occurring, with further validation, if possible.

Screenshots:

`Global Settings > password-min-length`
<img width="1199" alt="Screenshot 2022-11-17 at 9 48 13 AM" src="https://user-images.githubusercontent.com/46494969/202509498-3c7884a8-2bb4-4df4-9b19-d8d83d5318bc.png">

`Create New User w/ 2 character password`
<img width="1210" alt="Screenshot 2022-11-17 at 9 48 43 AM" src="https://user-images.githubusercontent.com/46494969/202509628-69ee69fe-09f0-47db-a1af-165b5603fea9.png">

`Create New User w/ 3 character password`
<img width="900" alt="Screenshot 2022-11-17 at 10 01 08 AM" src="https://user-images.githubusercontent.com/46494969/202510051-748b78b0-7798-409e-b1ed-243a6c2b0d6c.png">

**Comment by cnotv** [comment]
@Josh-Diamond looks like Integer validation using decimals is allowed in every input field we have. What would you recommend in this case? I would rather tackle this all at once instead of this very aimed case.

**Comment by Josh-Diamond** [comment]
`set a default validation for this case, which does not allow decimals` - this sounds great!

`In the current state seems like something has been changed, as I am not able to edit the value anymore` - 😮 
well, that's unexpected 😬

**Comment by cnotv** [comment]
It seems to be solved the issue with the editing capabilities 🤷

**Comment by cnotv** [comment]
It seems like this option is now flagged as `Set by Environment Variable` and does not allow us to edit it, unless we enable it. This change seems coming from the server while in the process of QA. I am allowing now to change them in order to make it possible.

**Comment by Josh-Diamond** [comment]
Ticket #6633 - Test Results [Cont.] - RE-OPENED (again) - ❌ 

With Docker on a single-node instance:

Verifying on Rancher `v2.7-9278cf152f9b98ae3c543c0f956af2ae6ab91368-head`:
1. Fresh install of Rancher `v2.7-head`
2. Navigate to `Global Settings > password-min-length`, and `Edit Setting`
3. Verified - password must be between 2-256 characters
4. Verified - validation prevents submission of non-zero decimal values
5. Veri-FAILED:
    - `11.0` is accepted as a valid configuration via `Global Settings > password-min-length > Edit Setting`, but it isn't respected when creating a new user.  Validation defaults back to pass-min-length of `12`.
    - This usecase should be prevented, if possible.
    
Screenshots:
`Passed`
<img width="1405" alt="Screenshot 2023-01-23 at 11 45 14 AM" src="https://user-images.githubusercontent.com/46494969/214126106-2389acdb-76d4-4488-91df-c79f2a7512c2.png">

`Passed`
<img width="1405" alt="Screenshot 2023-01-23 at 11 45 30 AM" src="https://user-images.githubusercontent.com/46494969/214126124-9e4c9e9c-d376-4145-905b-76d9f0116d9e.png">

`Passed`
<img width="1407" alt="Screenshot 2023-01-23 at 11 45 47 AM" src="https://user-images.githubusercontent.com/46494969/214126143-d56c97e1-7192-4e6f-ad08-6c8654c7f21d.png">

`Questionable`
<img width="1408" alt="Screenshot 2023-01-23 at 11 46 01 AM" src="https://user-images.githubusercontent.com/46494969/214126173-4788ab59-1ed6-4dff-8184-23bfd32b4e21.png">

`Questionable`
<img width="1401" alt="Screenshot 2023-01-23 at 12 00 28 PM" src="https://user-images.githubusercontent.com/46494969/214126512-07c277b7-1bcf-4968-896b-9179a5e394e2.png">

`Failed`
<img width="1407" alt="Screenshot 2023-01-23 at 11 47 35 AM" src="https://user-images.githubusercontent.com/46494969/214126305-3531ccde-d56e-4f04-afc5-7fd56cb9b853.png">

**Comment by cnotv** [comment]
@Josh-Diamond waiting for some updates from the `rancher/rancher` repo to find out why the setting is not honored.

**Comment by Josh-Diamond** [comment]
@cnotv Are you waiting for some information or input from me?  I'm slightly confused as to how this would be related to backend.  If setting `global setting > password-min-length` to `11`, this is accepted and valid, however setting this value to `11.0` through dashboard is accepted but invalid and is not truly honored.  

I believe the change I'm requesting would be from dashboard side to remove or prevent the use of `.` in this input field. 

Am I off base here?  Should this prevention be implemented server-side? Is that what you are suggesting? And to let the dashboard just display the validation error coming from the server?

**Comment by cnotv** [comment]
The decimal with `.0` has been fixed with a newer PR.

The value is not honored still. If you try to set requirement min password to 20, then you update a password with length 3, it will accept. Previously this worked.

I've been asking to the BE information about this but the only answer I received is that the value is honored, while it's not.

**Comment by Josh-Diamond** [comment]
Ticket #6633 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-3c1e7dbaafe9c38629898273974b97ec6e8fd4da-head`:
1. Fresh install of rancher `v2.7-head`
2. Navigate to `global settings > password-min-length`, and set to `11.0`
3. Verified - validation prevents the use of `.`; as expected
4. Sanity checked using negative values, values outside the range of 2-256, and values including `e`; all failed to be accepted as valid; as expected
