### ISSUE TITLE
Allow user to configure side nav auto-collapse

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6658]
This issue is related to a larger issue https://github.com/rancher/dashboard/issues/4431 which still in design triage, but after discussion with Kenneth and based on feedback from customers (https://github.com/rancher/dashboard/issues/4431#issuecomment-1064318705) it sounds like we definitely want to do at least this small piece of it.

**Comment by catherineluse** [comment]
Related to SURE-3658

**Comment by catherineluse** [comment]
Moving this issue back to design backlog because it sounds like my PR may not be ideal? Neil said this needs to be discussed with Kenneth.

**Comment by bashofmann** [comment]
I also have a prospect who liked the current behaviour to be changed. The auto-collapse can be quite annoying if you need to switch back and fort between e.g. deployments, services and PVCs in order to debug or manage all the resources from a workload.

I can also understand that other users like the auto-collapsing. Maybe it'd be worth to make this a user specific setting?

**Comment by catherineluse** [comment]
I got some feedback on my PR that removed the auto-collapse that said it shouldn't be merged because some users would prefer the auto-collapse. https://github.com/rancher/dashboard/pull/6657 So I've changed the scope of the issue to allow the user to configure this in their preferences.

**Comment by kwwii** [comment]
We are planning on implementing a smaller icon bar to the left which expands into the full menu. This should solve the problems for those who don't like the menu always taking up space but also allow a user to quickly navigate.
