### ISSUE TITLE
Spacing between inputs

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#669]
I've noticed the spacing between inputs is different across multiple pages.

Is there a standard amount of whitespace to expect between inputs? If so, how much @lvuch?

**Comment by lvuch** [comment]
In my mocks I use 16px. Looking at our grid, it sets the margin between columns as 1.75%. Can you attach some examples so I can investigate? I'll also add the grid into storybook so there is a visual reference.

**Comment by deniseschannon** [comment]
# Secrets 

`NameNSDescription` Component and `KeyValue` Component put the inputs at different spacing

<img width="1215" alt="Screen Shot 2020-05-22 at 9 28 10 PM" src="https://user-images.githubusercontent.com/11410997/82721596-5e91b180-9c73-11ea-9dad-862a042914b6.png">

# Service

`NameNSDescription` Component versus whatever is used for port rules

<img width="1210" alt="Screen Shot 2020-05-22 at 9 30 22 PM" src="https://user-images.githubusercontent.com/11410997/82721612-81bc6100-9c73-11ea-9ab0-9b97bd48c1d8.png">

**Comment by deniseschannon** [comment]
- [ ] Update KeyValue from using a table to a grid
- [ ] Review port rules with @mantis-toboggan-md to update from table to grid

**Comment by deniseschannon** [comment]
- [ ] Spacing between `Create` and `Cancel` on the create pages seems to be very close. Can you take a look at adjusting it? 

![Screen Shot 2020-06-10 at 11.54.50 PM.png](https://zube.io/files/rancher/e130f58819fc49e34094724799f1f1b0-screen-shot-2020-06-10-at-11-54-50-pm.png)

**Comment by lvuch** [comment]
I'm moving the table/component issues into a new issue for a dev to review: https://github.com/rancher/dashboard/issues/849

**Comment by sowmyav27** [comment]
**Validated on master-head - commit id: 16616de9c**

- The spacing between the components mentioned above in the issue is still the same. Is this how we want it to be ?
<img width="1443" alt="Screen Shot 2020-07-17 at 6 10 11 PM" src="https://user-images.githubusercontent.com/26032343/87841260-fae1ca00-c858-11ea-9b83-f2e7e437e899.png">

- There is no spacing between namespace and name
<img width="945" alt="Screen Shot 2020-07-17 at 6 10 51 PM" src="https://user-images.githubusercontent.com/26032343/87841268-0cc36d00-c859-11ea-8332-c810764b73ac.png">

- Do we want `Cancel` and `Create` OR `Create` and `Cancel` (this is how it is in Amber UI)

**Comment by lvuch** [comment]
> * [ ]  Update KeyValue from using a table to a grid
> * [ ]  Review port rules (workload/ports component) with @mantis-toboggan-md to update from table to grid

this needs reviewed by a developer

**Comment by lvuch** [comment]
> **Validated on master-head - commit id: 16616de9c**
> 
> * The spacing between the components mentioned above in the issue is still the same. Is this how we want it to be ?
> 
> <img alt="Screen Shot 2020-07-17 at 6 10 11 PM" width="1443" src="https://user-images.githubusercontent.com/26032343/87841260-fae1ca00-c858-11ea-9b83-f2e7e437e899.png">
> 
> * There is no spacing between namespace and name
> 
> <img alt="Screen Shot 2020-07-17 at 6 10 51 PM" width="945" src="https://user-images.githubusercontent.com/26032343/87841268-0cc36d00-c859-11ea-8332-c810764b73ac.png">
> 
> * Do we want `Cancel` and `Create` OR `Create` and `Cancel` (this is how it is in Amber UI)

- namespace+name is a dropdown input combo so that is good to go. 
- `cancel` `create` is the correct order.
- @mantis-toboggan-md, could you look at the key value component as well as any other component that has that add row feature and convert from table to grid to make the spacing consistent. If there is a reason to keep them in tables let me know and we can figure something else out or just adjust the styling.

**Comment by izaac** [comment]
Rancher version: `master-head (08/13/2020)`  _d19f179c4_

Navigating across all resource Create forms and using both dark and light themes. 

- Spacing between inputs looks more consistent across the dashboard pages.
- The forms are responsive of different display sizes
- namespace+name component dropdown is expected to be "joined" from user point of view.
- Button order `Cancel` left and `Create` to the right.

Hit a known issue and a new one for headless service in the process but not blockers.

#921
#1028
