### ISSUE TITLE
Can't create resource when using 'Create Namespace' if there is an error first time

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6743]
Fo to a resource, like secrets and click create and choose 'custom'.

Choose 'Create a new Namespace' in the namespace dropdown and enter a new namespace name.

Enter a name for the resource and for the type choose the service-acount-token option.

Click 'Create'.

You'll get an error - because for the secret type we chose, there are required key/values that we did not provide.

Change the secret type to 'Opaque'.

Click Create.

Form errors:  Could not create the new namespace. namespaces "dsfsdf" already exists

Looks like we create the new namespace, but then if we get an error from the backend because of bad data, you can't correct this and try again, because we try to create the namespace a second time and we already created it.

**Comment by catherineluse** [comment]
# QA Template
## Root cause
The UI did not check to see if a namespace already existed before creating it. So upon the second attempt to create the same namespace, it threw an error.
 
## What was fixed, or what changes have occurred
This PR https://github.com/rancher/dashboard/pull/6853 changes the logic for namespace creation in the resource creation form so that if the namespace already exists, it does not attempt to create the namespace.
 
## Areas or cases that should be tested

To test this PR, I did the same steps as in the above issue description:

- Created a namespace `test1`.
- In the secret creation form, created a Custom secret and selected the service account token as the secret type.
- In the namespace dropdown, I selected Create a new namespace and entered `test1`.
- Attempted to create the secret multiple times.
- Confirmed that the error message was about the secret lacking required fields, not that the namespace already exists. The error was as expected: `Secret "test6" is invalid: metadata.annotations[kubernetes.io/service-account.name]: Required value`

I also tested the positive test case in which the secret is created successfully on the second attempt:

- In the secret creation form, created a Custom secret and selected the service account token as the secret type.
- In the namespace dropdown, I selected Create a new namespace and entered `test1`. (Although at this point, that namespace already exists)
- Entered a name for the secret
- Created a valid token for a valid service account (Note: If the secret is invalid, the backend won't throw errors. In order to see it show up successfully, the secret must use a valid service account token.) There was already a service account named `default` in the test namespace that I used, so I created the token by running `kubectl create token -n test1 default` to create a token for the service account called `default`. (Another note: Kubectl 1.24 is required to create the token)
- In the secret form, in the data tab, added a key-value pair `token`: and pasted the new token.
- In the secrets form, in the labels and annotations tab, added the key-value pair `kubernetes.io/service-account.name`: `default` to link the token to the service account named `default`.
- Confirmed that the token was successfully created in the `test1` namespace

I also tried the positive test case where a new namespace is successfully created at the same time as the service account token secret is successfully created.

 
## What areas could experience regressions?
This change affects all resource creation forms where you can select a namespace or create a new namespace for the resource (dozens of forms). However I would expect the behavior to be the same for all of them - if there is a backend error preventing the resource from being created, you should be able to retry it without seeing the error about how the namespace already exists.
 
## Are the repro steps accurate/minimal?
Yes

**Comment by anupama2501** [comment]
Upgrade verified from v2.6.8 >> v2.6-head 48b6bc6

- Installed rancher server on v2.6.8
- Created an rke2 and an rke1 clusters node drivers 1 worker, 1 etcd, 1 cp roles.
- In the secret creation form, created a Custom secret and selected the service account token as the secret type.
- In the namespace dropdown, selected create a new namespace and entered anu-ns1.
- Attempted to create the secret multiple times.
- It returned the error:
```
Could not create the new namespace. namespaces "anu-ns1" already exists
```
- Upgraded rancher server to v2.6-head
- Repeated the same steps as above and noticed the error for `Could not create the new namespace. namespaces "anu-ns1" already exists` is not seen anymore
- Created a workload by selecting the `create namespace` in the dropdown option. 
- Provided an invalid workload name as WK-1 --> failed but the namespace was already created. 
- Retried by changing the container name to an invalid name --> failed --> changed the container name and workload names to a valid name --> verified no namespace error seen.


Fresh checks:
-  Install rancher on v2.6-head 
- Created an rke2 and an rke1 clusters node drivers 1 worker, 1 etcd, 1 cp roles.
- Created a workload by selecting the `create namespace` in the dropdown option. 
- Provided an invalid workload name as WK-1 --> failed but the namespace was already created. 
- Retried by changing the container name to an invalid name --> failed --> changed the container name and workload names to a valid name --> verified no namespace error seen.
- Verified by creating a config map, selecting the create namespace option and verified the namespace was created and the config map was created.
