### ISSUE TITLE
Web worker leaks memory

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6901]
The `comlink` package leaks memory - should just use postMessage.

**Comment by git-ival** [comment]
@nwmac Do we know if this effects all lists? Can you give some examples on which lists this issue can be observed?

**Comment by Sean-McQ** [comment]
Removing Comlink is an incremental improvement towards fixing memory growth in Rancher Dashboard. While the memory growth effect is most pronounced when large lists are loaded, you'll likely notice it to a lesser effect whenever the user is in the cluster explorer (with regards to Comlink specific memory growth although the specific effect may be negligible compared to other memory growth). Comlink was an especially important part of the puzzle though as we'll be moving more work into the worker thread and off the ui thread in future changes to further address memory growth in the UI.

For the most accurate test, you'll want to make sure you're also going to want to make sure you're running a production build of the branch, do NOT have chrome's dev tools up, and do NOT have the vue dev tools extension enabled in the browser. Larger clusters are better because the referenced webworker processes messages for cluster counts and cluster schemas and larger clusters tend to generate more messages for those resources over the websocket.

I'm not sure there's a very deterministic test to be run here for this specific issue since you'll still see some memory growth and the amount will be variable based on websocket traffic over a protracted period of time. I suppose you could run multiple tests across machines to generate a control group's average memory growth on a known cluster using the previous release and then run the same test across multiple machines using the fixed version and compare the average memory growth over time between groups to come up with a percentage difference.

Given that we know we've got more work in this area from different angles, I'm not sure the juice would be worth the squeeze there given the setup and time spent in-test.

**Comment by git-ival** [comment]
Compared 2.7.0-rc3 vs 2.6.8. Overall, the memory usage increase after loading large lists seems reduced on 2.7.0-rc3 vs 2.6.8. Memory usage appears to grow more quickly on 2.6.8. However, 2.6.8 seems to "clean up" its memory usage better or more aggressively than 2.7.0-rc3. 

As Sean mentioned, given the various performance changes recently and since we know there is much more to work on in terms of the UI's performance, its hard to tell if this is a direct improvement on the memory leaks. Overall this seems like a promising step. Closing for now, as other issues around performance will likely be opened for more specific areas.

https://user-images.githubusercontent.com/85186645/195736288-1e0ea55a-e10c-4b29-9164-baa509ebf86a.mp4


https://user-images.githubusercontent.com/85186645/195736300-8994949e-2492-4c6a-b950-b41aadae6c0b.mp4
