### ISSUE TITLE
We don't use cluster level registry for deploying Rancher helm charts

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6910]
The majority of Rancher charts support the helm value `global.cattle.systemDefaultRegistry
` (also note that our code also allows for global.systemDefaultRegistry` - this can be used to change the registry that images are pulled from when installing a chart. This allows us to support air-gapped installed.

There is a global setting `setting-default-registry` that the user can change through the UI.

Today, we will pass the value specified by this global setting to the `global.cattle.systemDefaultRegistry` helm chart value, if not already set by the user (e.g. by editing the values as yaml) - see `shell/pages/c/_cluster/apps/charts/install.vue`.

When a user provisions a new cluster, they can specify a custom registry - this is used to pull the images when provisioning, but is also stored on the cluster object - this is referred to as the `cluster level registry`. 

The change required here is to allow the user to choose which registry to use when installing a Rancher chart.

As I see it:
- For the Helm chart install, if the chart has either the `global.cattle.systemDefaultRegistry` or `global.systemDefaultRegistry` values (note the default is empty, so we need to check for presence of the keys), then we should provide new UI in the install experience to allow the user to specify the registry.
- I suggest adding a new block of UI to the first step of the install process (Metadata) - note, it could fit in the next step as a new tab, but not all charts have values, so some just display a yaml editor for second step, so the only common place is the first step.
- Edited plan: After speaking with Kenneth on Oct 4, the plan is no longer to add radio buttons allowing the user to select a registry because most users installing apps should not need to worry about the default registries, as that is more in the domain of admins. The new plan is to have a single checkbox that allows the user to input a custom registry, with a tooltip that explains what the default is if they do not select a custom one.

The cluster-level registry is available on the cluster object in `spec.rkeConfig.machineSelectorConfig.system-default-registry`.

Old notes below:

As the registry passed to feature helm charts is done in the UI, we need to expose what is the registry that will populate the "system-default-registry" for the helm chart deployments and allow the ability to update/change it from the UI. Presently, we default to grabbing charts from the default Rancher repo but we would need the ability to toggle to another repo. 

This would require coordination with the backend (Team 2).

**Comment by nwmac** [comment]
For the local cluster, go to 'Cluster Tools', select Monitoring and Install, click Next. 

Go to Edit Yaml and look down and you'll see this section:

```
global:
  cattle:
    systemDefaultRegistry: ''
```

This currently does NOT have its value wired into the global default.

We should add UI to the `General` that allows the user to see/change which registry will be used to fetch Rancher images when deploying the chart. We should only show this if the chart has the value above that can be set.

We probably want 3 possibilities:

- Global default Rancher system container registry
- Cluster default Rancher system container registry (if this is set and is different to the global setting)
- Custom (user can enter a URL in a text box)

**Comment by nwmac** [comment]
It looks like we do the right thing here - see `apps/charts/install.vue` in `addGlobalValuesTo`

**Comment by nwmac** [comment]
I think the issue here is that the cluster level registry could be different to the global level registry.

**Comment by catherineluse** [comment]
> (3) Use Custom Container Registry for Rancher system images - with an input box to allow the user to enter a URL

I have some questions -

- Don't we need to expose inputs for credentials too?
- Cluster explorer already has a form for creating private registries (or to be more pedantic, a secret of type registry). Do we want to reuse the existing private registry creation form?
- And do we want the user to be able to select an existing secret of type registry that is already created in the cluster?

<img width="1461" alt="Screen Shot 2022-09-21 at 10 10 40 PM" src="https://user-images.githubusercontent.com/20599230/191663871-447ec69f-fc70-4469-b331-aec4c5ea843f.png">

**Comment by nwmac** [comment]
@catherineluse Yeah - (2) does support credentials - I don't know if there is a standard way to pass this onto the Helm chart for Rancher charts?

I think to start with, we keep (3) simple and don't add support for credentials. We can add username and password later - as above, we could only use the credentials if there was a standard property equivalent to `global.cattle.systemDefaultRegistry` that let the image pull secret be specified.

**Comment by catherineluse** [comment]
> I don't know if there is a standard way to pass this onto the Helm chart for Rancher charts?

@gaktive If the answer to this question is no, it could require backend work

**Comment by gaktive** [comment]
@nwmac from Catherine's comment below, does Team 2 have an issue tied to helm chart updates?

**Comment by nwmac** [comment]
As discussed, we can skip for now and ignore cluster-level registries that have auth config.

**Comment by catherineluse** [comment]
Found out a bit more info:

- The cluster level private registry is only available for Rancher provisioned clusters. It doesn't exist for hosted or imported clusters.
- If a cluster level private registry has credentials, the credentials will already be available and usable on the clusters as soon as they are provisioned. So only the private registry URL would be needed for helm chart installs on rancher provisioned clusters, regardless of whether the registry has credentials or not.

**Comment by catherineluse** [comment]
# QA Template
## Root cause
This isn't really a bug fix, but more like a behavior change. Previously, when a user installed a Rancher Helm chart, the images would be pulled from the default global private registry, which is set in the global settings. (By default, that global setting for the default registry is blank, in which case the container runtime uses docker.io to pull the images.) The desired behavior was that if a cluster scoped private registry was configured for a cluster, images would be pulled from that registry by default instead of the one in the global settings.
 
## What was fixed, or what changes have occurred
There are two main changes:

1. The default source for pulling images for Rancher Helm charts has been changed from the global scoped one to the cluster scoped one, if a cluster scoped one exists. The global one is now used as a fallback instead of the default.
2. A new section has been added to the wizard workflow for installing Helm charts. It now allows the user to select which registry is used to pull the images for the chart.
 
## Areas or cases that should be tested

- When installing Helm charts, the cluster registry should be selected by default for pulling the images.
- When a cluster scoped registry is not available, the global scoped registry is used.
- When installing Helm charts, users can enter a custom registry to use when pulling images for that specific chart.
 
## What areas could experience regressions?
A misconfigured private registry could cause Helm charts to fail to install. Rancher and non-Rancher Helm charts should be able to be installed successfully.
 
## Are the repro steps accurate/minimal?
N/A - not really a bug.

**Comment by catherineluse** [comment]
> The cluster-level registry is available on the cluster object

Project owners/members may not have access to the cluster object. If such a user is logged in, the Rancher UI will be unable to take the registry URL from the cluster object and inject it into the chart values.yaml.

For those users with limited permissions, I believe the only way they could get the cluster registry entered into the Helm chart app is by manually entering it as the "custom" option.

Based on discussing the Helm install workflow with Kenneth yesterday, it sounds like the Rancher UI should silently determine whether to use the global or cluster registry without informing the user, on the reasoning that the registry would be set up by admins and therefore the exact cluster registry URL or global registry URL is probably something that most app users would not want or care to know about. If we reduce the radio options to a single checkbox that allows the user to enter a custom registry or not, then standard users going with the default option could still use the cluster registry, even though we would not be able to display that to them as a UI option due to their restricted permissions.

**Comment by catherineluse** [comment]
Before this can be fully tested we need Team 2 to confirm the YAML format for configuring the cluster scoped registry https://github.com/rancher/dashboard/issues/7127

**Comment by richard-cox** [comment]
I've updated the draft PR and tweaked things around a bit

I've flipped the logic of the registry input field. It now always shows the user what setting will be applied (helpful just for their info, determining system vs cluster register, upgrade scenario, etc)

Additionally
- Show the registry controls if
  - the required values exist in the chart (we don't need to set them if the chart isn't rancher based)
- Show a value for the registry input field if
  - there is an an existing values (aka upgrade of an app that was installed using a custom or cluster registry)
  - there is a cluster or system registry
- Apply the value in the registry input field if
  - it differs from the global registry (the system registry is basically a blank entry)
