### ISSUE TITLE
UX Clarity on which registry takes precedence

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6917]
When multiple registries are set, Global level registry or cluster level registry, it's not clear to the end user of when/which registry is used when provisioning clusters or deploying Feature helm charts. 

Not sure if we need to make any changes, but setting/understanding expectations would be good. We may have to look at the layout to figure out highlight defaults.

**Comment by catherineluse** [comment]
Does this apply to both RKE1 and RKE2?

**Comment by catherineluse** [comment]
For context, here are screenshots of the current form.

Using the global registry:

<img width="1218" alt="Screen Shot 2022-09-23 at 4 56 18 PM" src="https://user-images.githubusercontent.com/20599230/192070695-34409d9f-ad1b-408f-8f16-026d9fb25b11.png">

Setting a cluster level registry:

<img width="1197" alt="Screen Shot 2022-09-23 at 4 57 29 PM" src="https://user-images.githubusercontent.com/20599230/192070744-9f65fa19-f022-401a-82d0-c4700b67be4c.png">

Setting up mirrors:

<img width="1208" alt="Screen Shot 2022-09-23 at 5 07 41 PM" src="https://user-images.githubusercontent.com/20599230/192071231-b97b9849-ba05-487a-a82e-640eb41c58f4.png">


My suggestion would be to have some more in-app documentation available from that tab. Maybe there could be a button that shows these docs when clicked:

# Rancher Image Registry

This registry is used for pulling the following images:

- Images for installing and upgrading the Kubernetes cluster
- Images for installing and upgrading the official Rancher Helm chart apps

## Order of Precedence

Multiple registries can be configured so that the attempt to pull images from the first registry fails, one or more mirrors will be used.

1. If a cluster scoped registry is configured in the cluster YAML, pull images from that registry. If that doesn't work, check for mirrors for that registry, and try the mirror's endpoints one by one until one works.
2. If no cluster scoped registry is configured, pull images from the global scoped registry, which is configurable from the global settings. If mirrors are configured for that registry, try the mirror's endpoints one by one until one works.



Then the radio buttons should also use "global scoped registry" and "cluster scoped registry" to match the terminology in the docs. We should also coordinate with the docs team to make sure the message is consistent.

**Comment by nwmac** [comment]
Revisit in 2.7.1 - changes to radio-button text should be sufficient for 2.7.0
