### ISSUE TITLE
UX Clarity about how to use the advanced private registry setup for RKE2 clusters, esp. around how mirrors work

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6919]
Location in the UI:

- RKE2/k3s provisioning - Private Registries section - 3rd option

**Comment by gaktive** [comment]
Same page as a bug: https://github.com/rancher/dashboard/issues/6921

**Comment by gaktive** [comment]
Need to look into how mirrors with containerd in conjunction with this.

**Comment by nwmac** [comment]
This is on the cluster creation page on the `Registries` tab, e.g.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/1955897/191308544-3afafeef-36a3-4ca5-9111-83bfe7e8bcea.png">

**Comment by catherineluse** [comment]
This seems similar to https://github.com/rancher/dashboard/issues/6917 - See my comment for a suggestion on how to resolve this https://github.com/rancher/dashboard/issues/6917#issuecomment-1256816372

**Comment by nwmac** [comment]
Move the toolip on hover on 'Mirrors' to be a text under the title:

![image.png](https://zube.io/files/rancher/d72c9c650dcb593df92ef00f4df39171-image.png)

**Comment by gaktive** [comment]
Need to check with @kwwii on the design.

**Comment by kwwii** [comment]
Could we change the name of the tab to "Registry" and then use this text:

Registry
 O Use global container image registry settings
 O Use a private container image registry
 O Use a private registry with advanced authentication and containerd mirroring

**Comment by kwwii** [comment]
Could we use "Authentication" and "Add Authentication" to simplify things? We don't mention Registry anywhere else within this page so I am not sure why we use it here.

**Comment by catherineluse** [comment]
Update per discussion w/ Kenneth on Oct 20 - The UX will be consistent with the checkbox in the Helm chart install page that allows a cluster scoped registry to be enabled, except that the options for mirrors and auth will also be exposed.

**Comment by catherineluse** [comment]
Here are the latest screenshots: 


If the checkbox is selected, the basic registry config options are displayed. If "Show Advanced" is clicked, the mirroring and advanced auth options are displayed. I have also added more UI text and docs links to help tamp down on the confusion.


Default view: 

<img width="1146" alt="Screenshot 2022-11-19 at 5 33 45 PM" src="https://user-images.githubusercontent.com/20599230/202877063-f7793dae-cf94-4cf6-b265-f53d06a94b76.png">

If cluster registry is enabled:
<img width="1144" alt="Screenshot 2022-11-19 at 5 34 41 PM" src="https://user-images.githubusercontent.com/20599230/202877076-95501447-1aca-48f7-afc9-a95214964a25.png">

If advanced options are expanded (docs link changes to K3s docs if a K3s version is selected):

<img width="874" alt="Screenshot 2022-11-19 at 5 42 39 PM" src="https://user-images.githubusercontent.com/20599230/202877398-9f2677da-b712-4f64-855f-50bd86aa4d1d.png">

**Comment by catherineluse** [comment]
# QA Template
## What was fixed, or what changes have occurred
No YAML config options have been added or removed from the form. The only thing that changed is the way the choices are presented to the user. Instead of a three-way choice, it's now a two-way choice, where you either have a cluster scoped registry or you don't. If you do have a cluster scoped registry and click advanced options, you can see options for configuring TLS and mirrors.
 
## Areas or cases that should be tested

- If a cluster does not already have a cluster scoped registry configured, the checkbox to enable the cluster scoped registry should be unchecked
- If a cluster does have a cluster scoped registry, then you go to edit config for the cluster, then you should see the registry values already filled in. If there are advanced values filled in, the advanced section should already be expanded by default so that the user doesn't have to click into the advanced options to confirm that those values were saved
- You can delete the private registry values and the form can still be saved properly
- If a cluster scoped registry domain is configured, it should show up in `spec.rkeConfig.machineSelectorConfig[0].config` in the cluster yaml
- If a registry username/password is configured, the secret should show up in `spec.registries.configs[registry domain name].authConfigSecretName` in the cluster yaml
- In the section for configuring the mirrors, the docs link goes to K3s docs when a K3s version is selected and RKE2 docs when a RKE2 version is selected
 
## What areas could experience regressions?
- Registry config options - no functionality should be lost regarding what is possible to configure in the form

**Comment by Josh-Diamond** [comment]
Ticket #6919 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on rancher `v2.7-ea6b86c79434dfc020c61227528f51ceaf4339b6-head`:
1. Fresh install of rancher `v2.7-head`
2. Begin to provision a downstream RKE2/K3s cluster - [ANY] - (I used RKE2/K3s Custom)
3. Navigate to `Cluster Configuration > Registries`
4. Verified - `Enable cluster scoped container registry for Rancher system container images` is unselected by default
5. Select `Enable cluster scoped container registry for Rancher system container images`, and configure a private registry
6. Once `Active`, `Edit Config` and observe registry data persists
7. Verified - registry data fields populated w/ data from initial configuration
8. Remove private registry configurations, and hit `Save`
9. Verified - cluster successfully saves
10. `Edit Config` once more, and confirm registry data was removed
11. Verified - registry data previously configured has been successfully removed/overwritten
12. `Edit Config` of cluster and configure an authenticated private registry
13. `View YAML` of cluster and observe `spec.rkeConfig.machineSelectorConfig[0].config`
14. Verified - `spec.rkeConfig.machineSelectorConfig[0].config` points to cluster level registry for `system-default-registry` field
15. `View YAML` of cluster and observe `spec.registries.configs[registry domain name].authConfigSecretName`
16. Verified - `spec.registries.configs[registry domain name].authConfigSecretName` points to registry secret name
17. Navigate to `Cluster Configuration > Registries > Show Advanced > Mirrors`
18. Verified - Points to RKE2 documentation if cluster's k8s version is rke2
19. Verified - Points to K3s documentation if cluster's k8s version is k3s
