### ISSUE TITLE
In ADFS, when adding an unknown Group in the Groups Page on Rancher using the text box it will create a User

### ISSUE THREAD

**Issue by leflambeur** [rancher/dashboard#6932]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
With an ADFS installation try to add a group under the Group Memberships page

If you use a random string say test-dom\iamagroup to search for the group but then hit submit it will add the group you typed but as a User rather than reject it (and we can see it is indexing which groups are available so I am more surprised it didn't outright reject the creation if the group doesn't exist).

I am getting a screenshot for an example

**Result:**
It seems you can add random users to Rancher by misusing this functionality, expected behaviour should be that you can type in groups by name but if one doesn't exist it will reject it

Related:

https://github.com/rancher/rancher/issues/28785

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

gz#12110

**Comment by gaktive** [comment]
Internal reference: SURE-3143
Reported in 2.6.8 & 2.6.6

Backend looked into reproducing the original issue and @KevinJoiner determined that this appears to be a UI bug that does not have a security impact:

> When text is entered instead of using the dropdown selection, a new GlobalRoleTemplateBinding is created with the following structure.

```
        {
            "type": "globalRoleBinding",
            "globalRoleId": "admin",
            "groupPrincipalId": "authprovider_user://custom@email.com"
        }
```

> This binding will never resolve to anything since a user principal domain is being set for the groupPrincipalID.

This is a behaviour that has happened in both Ember & Vue. 

![Screenshot from 2021-07-09 11-12-09](https://user-images.githubusercontent.com/11466788/191134043-84359a52-c252-4e90-ac44-24d07212ca70.png)
![Screenshot from 2021-07-09 11-03-50](https://user-images.githubusercontent.com/11466788/191134057-725f42b4-e828-4993-8489-2f34f4e99b1f.png)

**Comment by gaktive** [comment]
This may be resolved via other work. @richard-cox to confirm.

**Comment by richard-cox** [comment]
This has been resolved via https://github.com/rancher/dashboard/pull/7386 (https://github.com/rancher/dashboard/issues/3182). As there's a lot more detail and history here suggest QA take a look to validate

**Comment by brudnak** [comment]
Already tested via https://github.com/rancher/dashboard/issues/3182

**Comment by sowmyav27** [comment]
Reopening for specific validations

**Comment by brudnak** [comment]
# 🚧 Reopened

## Reproduction Environment


| Component                        | Version / Type                           |
| -------------------------------- | ---------------------------------------- |
| Rancher version                  | v2.7.0                                   |
| Installation option              | Helm (high availability)                 |
| If Helm Chart k8s cluster        | v1.24.7+k3s1                             |
| Cert Details                     | Let's Encrypt / `traefik`                |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2     |
| Helm version                     | v2.16.8-rancher2                         |
| Downstream cluster type          | not applicable                           |
| Downstream K8s version           | not applicable                           |
| Authentication providers enabled | Shibboleth                               |
| Logged in user role              | Administrator                            |
| Browser type                     | Google Chrome                            |
| Browser version                  | 108.0.5359.124 (Official Build) (x86_64) |

<details>
    <summary>🚨 Additional Reproduction Setup Details: Click to Expand</summary>

>K3s install command for node one. Replace values in <>

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=SECRET --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```

>K3s install command for node two. Replace values in <>. Main difference here is the --token

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=<TOKEN_FROM_NODE_ONE> --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```


</details>


## Reproduction steps

1. Login to Rancher as an admin
2. Enable Shibboleth (SAML) authentication provider
3. Once these two steps are completed, do the following
   1. Starting from the **default** Rancher homepage `/dashboard/home`
   2. Click `hamburger menu` >>> `Users & Authentication` >>> `Groups` >>> `Assign Global Roles` >>> click the `Select Member` dropdown
   3. A valid group is displayed
   4. Instead of selecting the group type a random user/group name into the field such as `thisreallydoesntexist-dadfish75`
   5. For `Global Permission` select `Administrator` and click >>> `Save`
4. The save is successful without error
5. Now use `kubectl` to check the global role bindings with:


```shell
kubectl get globalrolebindings -A
```

6. Look for the name of the most recently created role binding and run:

```shell
kubectl describe globalrolebinding grb-cm27t 
```

7. Observe the field: `Group Principal Name:  shibboleth_user://thisreallydoesntexist-dadfish75`

## Additional Info

## RESULTS

#### ✅ Expected

For the UI not to allow the creation of these group global roles with a group that doesn't exist and seem to create a user and role binding from the name that was entered

#### ❌ Actual

The UI allows for this behavior to create a group global role with a username that doesn't exist and it creates a global role binding with the name searched for

<hr>

## Validation Environment


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version                  | v2.7-d657043de1dc2110562d9035b6c1c6dc9d9232ed-head                                 |
| Rancher commit link              | https://github.com/rancher/rancher/commit/d657043de1dc2110562d9035b6c1c6dc9d9232ed |
| Installation option              | Helm (high availability)                                                           |
| If Helm Chart k8s cluster        | v1.24.7+k3s1                                                                       |
| Cert Details                     | Let's Encrypt / `traefik`                                                          |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.10.2                                               |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | not applicable                                                                     |
| Downstream K8s version           | not applicable                                                                     |
| Authentication providers enabled | Shibboleth                                                                         |
| Logged in user role              | Administrator                                                                      |
| Browser type                     | Google Chrome                                                                      |
| Browser version                  | 108.0.5359.124 (Official Build) (x86_64)                                           |


<details>
    <summary>🚨 Additional Reproduction Setup Details: Click to Expand</summary>

>K3s install command for node one. Replace values in <>

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=SECRET --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```

>K3s install command for node two. Replace values in <>. Main difference here is the --token

```shell
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=<K3S_VERSION> sh -s - server --token=<TOKEN_FROM_NODE_ONE> --datastore-endpoint=<DB_ENDPOINT> --tls-san <TLD> --node-external-ip <IP>
```


</details>

## Validation steps

1. Login to Rancher as an admin
2. Enable Shibboleth (SAML) authentication provider
3. Once these two steps are completed, do the following
   1. Starting from the **default** Rancher homepage `/dashboard/home`
   2. Click `hamburger menu` >>> `Users & Authentication` >>> `Groups` >>> `Assign Global Roles` >>> click the `Select Member` dropdown
   3. A valid group is displayed
   4. Instead of selecting the group type a random user/group name into the field such as `thisreallydoesntexist-dadfish42`
   5. For `Global Permission` select `Administrator` and click >>> `Save`
4. The save is successful without error
5. Now use `kubectl` to check the global role bindings with:


```shell
kubectl get globalrolebindings -A
```

6. Look for the name of the most recently created role binding and run:

```shell
kubectl describe globalrolebinding grb-m2kbz    
```

7. Observe the field: `Group Principal Name:  shibboleth_user://thisreallydoesntexist-dadfish42`

## Additional Info

## RESULTS

#### ✅ Expected

For the UI not to allow the creation of these group global roles with a group that doesn't exist and seem to create a user and role binding from the name that was entered

#### ❌ Actual

The UI allows for this behavior to create a group global role with a username that doesn't exist and it creates a global role binding with the name searched for


#### Screenshots

<img width="1792" alt="2022-12-30_00-32-58" src="https://user-images.githubusercontent.com/40877149/210052031-eaea313c-343c-499b-bbea-113f46bea180.png">

**Comment by richard-cox** [comment]
The fix (https://github.com/rancher/dashboard/pull/7386) is targetted for 2.7.2 and is in 2.7-head and I couldn't reproduce the bug there. @brudnak Your comment references 2.7.0, can you confirm you're seeing that behaviour in `2.7-head`?

**Comment by brudnak** [comment]
> The fix (#7386) is targetted for 2.7.2 and is in 2.7-head. I couldn't reproduce with that version. @brudnak Your comment references 2.7.0, can you confirm you're seeing that behaviour in `2.7-head`?

Hi @richard-cox - I reproduced to confirm behavior with 2.7.0, but also if you check the second section I was still seeing this on 2.7-head `v2.7-d657043de1dc2110562d9035b6c1c6dc9d9232ed-head` https://github.com/rancher/rancher/commit/d657043de1dc2110562d9035b6c1c6dc9d9232ed

The screenshot of still seeing this issue have `d657043` in the bottom left corner in the UI.

Was not seeing this with GitHub auth, which I saw GitHub auth mentioned in a linked issue: https://github.com/rancher/dashboard/issues/3182. Was seeing this while using Shibboleth.

**Comment by richard-cox** [comment]
Strange, we don't differentiate between auth providers at that point. In the browser's dev tool's network tab can you check what the response is for `/v3/principals?action=search` after you enter the bad text?

**Comment by brudnak** [comment]
@richard-cox sure thing - the response after entering the bad text is a `200` `POST` to `/v3/principals?action=search`, see screenshot below

<img width="2720" alt="2023-01-03_11-34-33" src="https://user-images.githubusercontent.com/40877149/210422339-b4a00f18-4523-434d-b7d5-4c0c76bd904b.png">

**Comment by richard-cox** [comment]
@brudnak Brilliant, thanks.

Looks like the BE is returning a group given the value the user has searched for. There could be a reason for this (the BE is unable to search for all groups, so trusts user input) or it's a bug. From the comments above @KevinJoiner might be able to provide in put?

@KevinJoiner The UI now ensures only groups returned from the search (`/v3/principals?action=search`) can be selected. It seems when the user enters a junk group name some providers like Github will ignore it, whilst others like Shibboleth will return it as a valid group. From a UI side there's not much we can do, should this be a new issue over at `rancher/rancher` or shall this one move over?

**Comment by KevinJoiner** [comment]
I took a quick look at some of the code, and it looks like the behavior you are seeing was intentionally done for SAML and OIDC providers. I am unsure why this is the case, and I will need to do more research. 

@richard-cox  do you know what other places the UI uses the search action for principles? I am guessing adding the user's search input to the returned list was originally for the UI, but I am unsure if Rancher still uses this functionality.

If somewhere else needs this functionality, we will need to come up with a fix to make both scenarios happy, and we should leave this issue open.

If Rancher does not require this functionality elsewhere, then we should be able to leave your changes as is and create a separate rancher/rancher issue for the backend to stop sending the user's input in the returned list.

**Comment by KevinJoiner** [comment]
So, I found more info on what we are seeing in our docs.  https://ranchermanager.docs.rancher.com/v2.6/pages-for-subheaders/configure-shibboleth-saml#saml-provider-caveats This implies what we are seeing is expected behavior. 
**_We may need to include OIDC in this section._**

@brudnak Based on our docs, this is expected behavior, so I don't think we can consider it a separate bug. Thus we can probably close this issue unless there is something else you want to test.

> I know there's scaling issues to consider (some enterprise customers will have many many users / groups), i'm not sure how performant ad-hoc searches for both are.

Each provider defines their own search implementation. But many perform two separate searches for users and groups and then concatenate the results.

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

#### Not required.

<hr>

## Validation Environment


| Component                        | Version / Type                                     |
| -------------------------------- | -------------------------------------------------- |
| Rancher version                  | v2.7-1dd2af2d214b159c2c8ffcfc5838b6caece381cd-head |
| Installation option              | Helm (high availability)                           |
| RKE binary version used          | v1.4.0                                             |
| If Helm Chart k8s cluster        | v1.24.6                                            |
| Cert Details                     | Let's Encrypt / `nginx`                            |
| Docker version                   | 20.10.7, build f0df350                             |
| Helm version                     | v2.16.8-rancher2                                   |
| Downstream cluster type          | not applicable                                     |
| Downstream K8s version           | not applicable                                     |
| Authentication providers enabled | GitHub OAuth                                       |
| Logged in user role              | admin, standard user                               |
| Browser type                     | Edge                                               |
| Browser version                  | 110.0.1587.41                                      |


## Validation steps

1. Login to Rancher as an admin
2. Enable GitHub (OAuth) authentication provider
3. Once these two steps are completed, do the following
   1. Starting from the **default** Rancher homepage `/dashboard/home`
   2. Click `hamburger menu` >>> `Users & Authentication` >>> `Groups` >>> `Assign Global Roles` >>> click the `Select Member` dropdown
   3. A valid group is displayed
   4. Instead of selecting the group type a random user/group name into the field such as `thisreallydoesntexist-dadfish75`
4. Unable to create assign a group that doesn't actually exist

## Additional Info

## RESULTS

#### ✅ Expected

Unable to assign a group that doesn't exist

#### ✅ Actual

Unable to assign a group that doesn't exist
