### ISSUE TITLE
Remove v1 Multi-cluster Apps from the UI

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6970]
Remove v1 Multi-cluster Apps from the UI

Note: The menu entry in the top-level menu should be renamed as 'Global Configuration'

**Comment by ronhorton** [comment]
@nwmac the menu entry is 'global settings,' rather than what you specified 'global configuration' i don't see a change documented anywhere, so double checking with you
<img width="263" alt="2022-10-13_17-03-10" src="https://user-images.githubusercontent.com/89212856/195710272-e4adc9b1-56bc-4815-96cc-23793250b614.png">

**Comment by nwmac** [comment]
@ronhorton Sorry, may not have been clear enough.

Enable the Legacy feature flag from 'Global Settings', you should now see:

![image](https://user-images.githubusercontent.com/1955897/195851481-7011f156-c4b5-46a0-98d4-1395885b4dd3.png)

This used to say "Multi-cluster Apps", but we've now removed the apps, hence the rename.

**Comment by ronhorton** [comment]
**Pass** verified in `2.7-head commit id 7cbd5a4`

1. hamburger > global settings > feature flags
2. click 3 dots to the right of 'legacy'
3. select 'activate'
4. hamburger
result: `legacy apps > global configuration present`
