### ISSUE TITLE
Forward port [2.7.0] - Workload storage mount point for volumes should be on containers

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7034]
For 2.6.9, we had https://github.com/rancher/dashboard/issues/6800 to fix a problem with workloads:

>Need to remove the mount points config from the the pod.
Need to add a storage tab to the container to configure volume mounts - this should allow multiple - same fields as are
currently in the UI above - but you will need a drop-down to allow the user to choose the volume to mount.

Describe the bug
REF: https://github.com/rancher/dashboard/pull/6632#issuecomment-1235287918
REF: https://github.com/rancher/dashboard/pull/6632#issuecomment-1233479509

To Reproduce
Navigate to Cluster Explorer > Cluster > Workload > Deployment
On the Pod tab there is a sub tab called Storage.
Mount point should be on the container

Expected Result
Should have mount volume path on the container

----

We have to do the same in 2.7.0. 
For QA, the PR is https://github.com/rancher/dashboard/pull/6986

**Comment by nwmac** [comment]
@Shavindra I think this can go to test???

**Comment by richard-cox** [comment]
https://github.com/rancher/dashboard/pull/6886 is the 2.6.9 PR
https://github.com/rancher/dashboard/pull/7041 is the 2.7.0 PR

Moving to test

**Comment by nickwsuse** [comment]
`Verified on v2.7.0-rc7`

The Mount Point field is present on the Storage section of the Container tab rather than the Storage section of the Pod tab. Adding new and editing existing workloads is working as expected still as well.

Container Tab:
![image](https://user-images.githubusercontent.com/107147272/198142910-6b0dad01-01c4-4b76-b58c-2f034966c1ca.png)

Pod Tab:
![image](https://user-images.githubusercontent.com/107147272/198143211-e3ed2605-c3db-4c77-a151-f4d2a0d951b9.png)
