### ISSUE TITLE
Issue with input in Role apiGroups

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7084]
Internal reference: SURE-5158
Reported in 2.6.5 & 2.6.7

Issue description:
Minor issue -- role creation through UI with double quotes `""` in input section of API Groups textbox resulted in a bad role with invalid API groups `'""'`.

Troubleshooting steps:
After creation of role, edit the the specific role and check the apiGroups section

```
rules:

apiGroups:
  - '""'
  resources:
  - configmaps
  verbs:
  - create
```

Repro steps:

Try to create a role through Rancher >> Cluster Explorer >> RBAC >> Roles >> Create
In create window, enter mandatory fields and put `""` in API Groups textbox for core API groups and click create

Workaround:
Use blank value in API Groups textbox or edit the role and remove the singlequotes `''`

Actual behavior:

- Mandatory Asterix `*` sign on API Groups (Asterix is not there in cluster role creation)
- Double quotes are accepted as literal value and enclosed with a single quote `'""'`

Expected behavior:

- Shouldn't have the mandatory Asterix `*` sign on API Groups, OR
- Accept double quotes `""` as an input value

**Comment by nwmac** [comment]
We should detect '' or "" in the groups text box and replace it with the empty string before saving.

**Comment by catherineluse** [comment]
To clarify, the API group must be empty if the resource is under "Core K8s API, Cluster Scoped." For all other resources, the API group is required because the resource does not exist at the root scope.
<img width="436" alt="Screenshot 2022-11-19 at 3 41 05 PM" src="https://user-images.githubusercontent.com/20599230/202874343-e906083a-42f5-411b-b479-f059fff237da.png">

I think we should just remove the asterisk because the form is expected to autofill that value if it is required anyway. Nobody should have to fill it in by hand unless it's a resource that is not in the dropdown.

**Comment by sowmyav27** [comment]
On 2.6.9

- Create a ROle with ApiGroup - `""`
<img width="774" alt="Screen Shot 2022-12-27 at 9 00 53 AM" src="https://user-images.githubusercontent.com/26032343/209698410-fecbabe7-2a44-46b6-8f1a-d04276c26156.png">

- Edit Yaml

```
rules:
- apiGroups:
  - '""'
  resources:
  - configmaps
  verbs:
  - create
```

On 2.7-head commit id: `28a84c7`

- Create a ROle with ApiGroup - `""`
<img width="781" alt="Screen Shot 2022-12-27 at 9 00 46 AM" src="https://user-images.githubusercontent.com/26032343/209698416-e59f3c10-2a57-45e4-95bc-2b3d6d21e0c5.png">

- Edit Yaml
```
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - create
```

- APIGroups are not marked mandatory
<img width="773" alt="Screen Shot 2022-12-27 at 9 02 38 AM" src="https://user-images.githubusercontent.com/26032343/209698477-f4dc9a8d-4070-4556-83e7-8f1e8f0e428a.png">
