### ISSUE TITLE
[RFE] Rancher Azure Node Driver, add option to set Availability zone - RKE2/K3s

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7180]
Internal reference: SURE-3319
Reported in 2.5.9

A user would like to be able to deploy nodes templates with an availability zone on Azure. Currently, the node templates handle only the Availability set.

Request description:
Add Availability zone to Rancher Azure Node Driver.

Actual behavior:
Rancher node driver does not support Azure Availability zones

Expected behavior:
Rancher node driver support for Azure Availability zones

Additional notes:
Rancher Azure node driver and docker node driver support availability set but not availability zones.

While availability sets are used to protect applications from hardware failures within an Azure data center, Availability zones, protect applications from complete Azure data center failures.

Docker Machine driver support option --azure-availability-set but has no option for availability zones. https://docs.docker.com/machine/drivers/

See also "Availability zones" description at: https://cloudacademy.com/course/getting-started-with-azure-virtual-machines-988/availability-sets-and-availability-zones/

Possible connection with rancher/dashboard#7164 or in Zube, rancher/dashboard#7164

**Comment by gaktive** [comment]
More info from @HarrisonWAffel, both in context to proposed overall work and then Dashboard specific work:

> After looking into this issue a bit I believe the following changes will be necessary to support this new feature. All story point estimates represent one day of development work (including developer testing), but does not include time for code review or QA verification. 

### Rancher-machine (2-3pts)

- A new CLI argument, titled --azure-availability-zone 

Azure zones are denoted by integers, and there are a minimum of three zones per region. Each virtual machine can only be assigned to a single zone. As such, only a single integer should be passed to this flag.
Availability Sets cannot be used in conjunction with Availability Zones. The presence of --azure-availability-zone should cause rancher-machine to skip the configuration/creation of an Availability Set. If both are provided, an error should be thrown. 

- A new CLI argument, titled --azure-use-public-ip-standard-sku 

[Only Standard Public IP SKU's allow for the specification of Availability Zones.](https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/public-ip-addresses#sku) Currently, rancher-machine only creates Public IP's with the Basic SKU. This flag must be passed in order for rancher-machine to use the Standard SKU so that Availability Zones work.
The Public IP Address must also be static, dynamic Public IP Addresses are not compatible with Availability Zones.
Standard Public IP Addresses are zone-redundant. By default they are deployed to all Availability Zones, so the value provided to the --azure-availability-zone flag should not be specified when creating the Pubic IP Address. 

- The Availability Zone would be applied to the [virtual machine resource only](https://github.com/rancher/machine/blob/dcf6a815d4d8075d6c90cd83952d5e2c1887bb95/drivers/azure/azureutil/azureutil.go#L613), other's are[ zone redundant by default|https://learn.microsoft.com/en-us/azure/availability-zones/az-region#highly-available-services]. 

- Some refactoring of the Azure driver needs to be done so that invalid configurations of Availability Zones are detected before making requests to Azure.

### RKE
No changes are needed for RKE, as the Azure cloud provider does not support specifying Availability Zones. 

### Rancher

As long as the new rancher-machine flags are named -azure-availability-zone and -azure-use-public-ip-standard-sku then no changes are needed in Rancher

### Dashboard (2-3 pts, section needs confirmation from UI team)

- RKE1 

A new option should be added under the 'Network' section of the Azure node template, which should allow a user to specify if they want to use a Basic Public IP SKU or a Standard Public IP SKU.
A new option should be added under the 'Placement' section of the Azure node template, which should allow a user to specify the Availability Zone they want the VM to be deployed to

- RKE2 
A new option should be provided when configuring node pools which allows the user to specify an Availability Zone for each node pool
A new option should be provided when configuring node pools which allows the user to specify if they want to use a Basic Public IP Address SKU or a Standard Public IP Address SKU 

- We may want to put additional text or help messages indicating when a user has created an invalid configuration, since it's not very obvious. 

### Terraform-provider-rancher2 (2-3 pts)

Schema's and structures need to be updated in several places to support these two new flags 
In the [machine config schema](https://github.com/rancher/terraform-provider-rancher2/blob/2e34b77d951abecb356d0ee02431a5cc2b1e6f6c/rancher2/schema_machine_config_v2_azure.go) and [structure ](https://github.com/rancher/terraform-provider-rancher2/blob/2e34b77d951abecb356d0ee02431a5cc2b1e6f6c/rancher2/structure_machine_config_v2_azure.go#L17)
In the [node template](https://github.com/rancher/terraform-provider-rancher2/blob/2e34b77d951abecb356d0ee02431a5cc2b1e6f6c/rancher2/schema_node_template_azure.go) schema and structure
Simple flatteners and expanders need to be written
[One for the machine config](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_machine_config_v2_azure.go)
[One for the node template](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_node_template_azure.go)
 

### High level Notes / Limitations:

Managed Disks must be used when deploying an instance to an Availability Zone. 

[Not all VM's are supported in all availability zones](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/create-cli-availability-zone#check-vm-sku-availability), I'm unsure if we want to perform some sort of validation when choosing a VM in a particular Availability Zone. 

Each VM can only be assigned to a single Availability Zone, to use all three zones 3 VM's must be created.

VM's using Availability Zones must use a Standard Public IP Address SKU, and the IP address must be static. 

Availability Zones and Availability Sets cannot be used together

There are at minimum three Availability Zones per region.

**Comment by catherineluse** [comment]
@HarrisonWAffel I have a question about this part:

> As long as the new rancher-machine flags are named -azure-availability-zone and -azure-use-public-ip-standard-sku then no changes are needed in Rancher

Why doesn't it need a change in Rancher? If the UI sends the `azureAvailabilityZone` and `azureUsePublicIpStandardSku` to the azure config options, can you confirm that the user be able to verify that the changes were saved after editing those values? Because when I made a PR to add tags for the Azure node driver, I saw that although the values were sent in the network request, the values were never sent back to the UI https://github.com/rancher/dashboard/pull/7296, although the existing values are needed for the edit form. I assumed that was because the backend part wasn't done yet.

**Comment by HarrisonWAffel** [comment]
@catherineluse I don't believe there is a backend dependency for storing those values in the node template / machine config. I can't find a particular type or structure that would need to be updated to support the `tags` field. I do see that a `tags` field is already present in the Azure node template and machine template when I test in my local environment on 2.7-head, i'm not sure if that is interfering with the expected behavior? 

Is this occurring for both RKE1 and RKE2? If it helps we can do a screen share and go over the behavior, it was my understanding that the UI handles the creation and management of the node templates and machine templates.

**Comment by gaktive** [comment]
Upon discussion with @catherineluse, there are two concerns to tackle here:
- different regions have different options available when it comes to VM sizes that need to be filterable (accelerated networking: true/false, availability zones, managed disks, etc.) so we need the backend to contain more details so we can map VM sizes when we get one result back
- the UI can't directly handle secrets for Azure so we can't get the detailed VM list from the Azure API

@catherineluse will chat with @HarrisonWAffel and @snasovich now that 2.7.0 is out to figure out a strategy (@gaktive to eavesdrop and take notes as needed).

**Comment by gaktive** [comment]
Backend complete, so they're awaiting UI before handing to QA: https://github.com/rancher/rancher/issues/39458 though they will await for all related Azure AD tickets to be completed before testing begins.

**Comment by catherineluse** [comment]
I'm going to split this issues into two parts, one for RKE2/K3s and one for RKE1. This is just so that QA can go ahead and test the former changes separately.

I'll change the title of this issue to be just about RKE2/K3s, and open a new issue for RKE1.

# QA Template

## What was fixed, or what changes have occurred

 - Added an Availability Zone option for Azure nodes

## Areas or cases that should be tested

- You can have an Availability Set or Availability Zone, but not both
- The Availability Zone dropdown menu may or may not have any options, depending on the selected region. For example, if you select `westus` as the location, the Availability Zone dropdown should be disabled and you should see a warning because that region doesn't support AZs. If you select `westus2` as the location, the Availability Zone dropdown should have 1, 2 and 3 as options.

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 8062f1e
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1, rke2, k3s

----------

### Testing: ###
For RKE2 and K3s, the configuration is available under the `Machine Pools` section and can be correctly set.
![image.png](https://zube.io/files/rancher/d31b48173f94687e01a53e992b1626be-image.png)

When the location does not have availability zones, Rancher notifies the user and blocks out the configuration.
![image.png](https://zube.io/files/rancher/492807fb010d427b20bf5fd883fddde0-image.png)
