### ISSUE TITLE
Rancher Icons: Tooltip icon is unreadable at small sizes

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#7186]
**Setup**
- Rancher version: 2.6.9
- Browser type & version: Chrome Version 105.0.5195.125 (Official Build) (64-bit)

**Describe the bug**
At normal text size it is impossible (for me) to detect that the icon has a lower-case `i` inside a circle. It could be a semicolon, an upside-down exclamation mark, or just some dirt on the screen:

<img width="124" alt="Screen Shot 2022-10-11 at 6 39 43 PM" src="https://user-images.githubusercontent.com/78947/195229302-a4694627-cad6-401c-a159-b38e56e7e00d.png">

Enlarging the image shows that at the very least there needs to be more separation between the letter itself and the tittle (the diacritic dot on top):

<img width="487" alt="Screen Shot 2022-10-11 at 6 40 28 PM" src="https://user-images.githubusercontent.com/78947/195229301-bbdbcabc-1e82-40cb-9f6b-39467abf2b10.png">

**Additional context**

Originally raised in rancher-sandbox/rancher-desktop#3135

**Comment by jandubois** [comment]
I'm wondering if an inverted `i` in a filled circle doesn't work better at smaller sizes because it doesn't require the extra margin between the letter and the outer circle. That would then (maybe) allow us to use a serif font, so it really looks like a letter and not like a switch or upside-down `!`.

Something like this:

![images-2](https://user-images.githubusercontent.com/78947/197914636-8bc9cc17-1560-4afd-9d63-baf62f0bfbeb.png)

This would also fit design-wise with our intended use of an inverted `?` in a filled circle as a "help button" to link to help pages: https://github.com/rancher-sandbox/rancher-desktop/discussions/3273

Personally, I find this this style of the `i` attractive (please ignore the outer circle), as it reminds me of "visitor info" road signage (Google image search does **not** seem to confirm this theory though):

![1024px-Infobox_info_icon svg](https://user-images.githubusercontent.com/78947/197914067-7f6466f5-52cb-461d-9122-cbccb0663852.png)
