### ISSUE TITLE
Specify port along with FQDN for Authorized Endpoint

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7235]
This harkens back to https://github.com/rancher/dashboard/issues/4827 though at the time, it was closed as "working as expected" since the nature of FQDN precludes specifying a port for an authorized endpoint.

*Steps to reproduce (least amount of steps as possible):*

1. Provision a Rancher v2.4.5 instance with a single node custom cluster
2. Click Edit Cluster, enable Authorized Endpoint and attempt to enter a FQDN with a port specification, e.g. `kube.example.com:6443`
3. Click 'Save'

*Result:*

UI returns `"FQDN" contains an invalid character: :` error.

*Other details that may be helpful:*

Attempting to edit the cluster via the /v3 API, updating the localClusterAuthEndpoint to contain the FQDN with port is successful, and is reflected in the cluster kubeconfig, so this appears to be a UI validation issue only.

From a design perspective, we have to decide between 1) allowing a port number in the FQDN and splitting it out upon submitting to the API 2) enforce having another field to specify port or 3) something else.

**Comment by nwmac** [comment]
This is on RKE1 cluster creation under 'Authorized Endpoint:

![image](https://user-images.githubusercontent.com/1955897/196891084-fe8e016a-5030-42ea-b7df-2bead0e820a1.png)

Currently this is an FQDN - we prevent this from accepting a port:

![image](https://user-images.githubusercontent.com/1955897/196891304-79bd9e94-2d8b-4c70-9bbb-5a686a1c0135.png)

When specifying a FQDN, this ends up in the yaml in `spec.localClusterAuthEndpoint.fqdn`

**Comment by nwmac** [comment]
Confirmed by back-end that we can support a port:

It turns out that  <CLUSTER_NAME>-kube.example.com:6443 is a valid name, so in Rancher the fqdn can contains ports

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head ea6b86c
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1

----------

### Testing: ###
Tested this issue with the following steps:
1. Provision single node custom cluster and rke1 cluster
2. Click Edit Cluster
3. Enable authorized endpoint
4. Enter a FQDN with a port specification `example.com:12345`
5. Click save

**Result**
I saw that even when just creating the cluster this bug was reproducible so I also tested this configuration while creating the cluster. Now the user is able to add ports to the FQDN in the authorized endpoint configuration section for both custom cluster and rke1 cluster

![image.png](https://zube.io/files/rancher/94e4f12577f933a78822675503f41783-image.png)
