### ISSUE TITLE
Allow Extensions to easily provide Machine Config UI

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7256]
This is a placeholder issue to be fleshed out.

**Is your feature request related to a problem? Please describe.**
- RKE2 provisioning requires config for machines which is per provider
- We have `machine-config`'s for this for a range of providers at the moment
- We need to make it easy for Extensions to supply their own machine-config components

**Describe the solution you'd like**
- This should easily be achievable with the current pattern to support generic handling of create/edit, detail, etc components

**Describe alternatives you've considered**
- The alternative is for third parties to provide (and support) code in the `rancher/dashboard` repo

**Additional context**
- This can be used by Elemental
- We have had requests from a few external interested parties for this feature

**Comment by catherineluse** [comment]
I'm not aware of a reason why this wouldn't work for Elemental, but a while ago I researched why we don't provide a separate machine config UI for RKE2/K3s. As I remember based on talking to Team 2 it sounds like the biggest reason was that if you edit a machine config, the whole cluster could reprovision, which could lead to unexpected downtime of services. The other reason is that due to the way that CAPI resources depend on each other, if you deleted a cluster using a machine config, the machine config would be deleted along with it, even if it was in use by something else. So that's why we don't already have separate K3s/RKE2 machine config UIs. Basically the equivalent of node templates for RKE2 is years away.

**Comment by richard-cox** [comment]
This is for the existing machine config components in `/shell/machine-config` that show when creating clusters, rather than a separate edit machine config experience

**Comment by richard-cox** [comment]
This will be resolved as part of https://github.com/rancher/dashboard/pull/7207
