### ISSUE TITLE
/login (legacy) URI should redirect to dashboard

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7293]
Internal reference: SURE-5433
Reported in 2.6.x though applies to every release in 2.6.x and higher

Issue description:
Some admins would prefer if `/login` would take users to the dashboard UI, since a lot of people have the `/login` URI bookmarked, and so they're not even aware that the new UI exists, since they always use the bookmark to get to Rancher.

Business impact:

Users are persisting using the legacy UI which is becoming broken in places (stopped show containers inside a pod, not showing labels, ‘edit as YAML’ went missing).

Repro steps:

- Access https://<rancher>/login
- Login

Expected results: 
Redirected to modern UI

Actual results: 
Legacy UI is presented

Workaround: 
Ensure users update URL, add redirect to ingress annotations

**Comment by jameson-mcghee** [comment]
This issue is no longer reproducing on `v2.6.9` or `v2.7.0`, therefore I am closing this ticket.

**`v2.6.9`:**
![image](https://user-images.githubusercontent.com/13294321/211092438-f252fbbb-6c5c-4e50-bd88-7bf694bf3c3e.png)
![image](https://user-images.githubusercontent.com/13294321/211092819-134d8f2e-9860-41ea-b3a4-b9088bf2ec4d.png)

**`v2.7.0`:**
![image](https://user-images.githubusercontent.com/13294321/211092846-499ce343-dbe9-4652-8aef-7c70b2014139.png)
![image](https://user-images.githubusercontent.com/13294321/211092858-7cac3df8-ee5d-437b-a731-315d8b26a615.png)

**Comment by skaven81** [comment]
I don't know that I understand how this was fixed -- the screenshots showing that the "issue is no longer reproducing" is showing the problem.  When a user accesses `/login` on v2.6.9, with this "fix", they still get the legacy UI with the skyline in the background instead of being directed to the modern login page and dashboard.  Further, it appears that once the AzureAD Graph API update is completed, logging in at all using the legacy `/login` UI doesn't even work.

I would absolutely NOT call this "fixed"
