### ISSUE TITLE
[Forward port for 2.6.next1] Correct Ember UI login flow for migrated Azure AD auth

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#7330]
This related to rancher/dashboard#6316 . The migration to the microsoft graph api exposed an issue with the Ember UI login flow, fixed in 2.5 here: https://github.com/rancher/ui/pull/4875

This fix was never forwardported to 2.6 under the assumption that users would all be using the dashboard auth flow in 2.6; however, some users have bookmarked their rancher login url in 2.5, `<rancher url>/login`, and continued to use this after upgrading to 2.6.

I think for 2.7 onwards we need to consider redirecting `/login` to `/dashboard/auth/login` so we don't need to support the ember ui login flow: given all the external auth provider options, this is a fair bit of old UI for us to maintain going forward.

**Comment by anupama2501** [comment]
@mantis-toboggan-md 

- Installed rancher on 2.5.15 
- Enbled azure ad with old end points.  
- Upgraded to rancher 2.6-head `993608f436`
- In the cluster management page of the ember UI once I login from <rancherURL>/login, I do not see the banner and button to update the old azure endpoints to the new ones. 

Since we want to support <rancherURL>/login, we would want to display the banner/button if users have the old endpoints configured for azureAD or we can have a way that redirects users to the dashboard UI endpoint update page where they can update the endpoints.

**Comment by anupama2501** [comment]
@mantis-toboggan-md 
I tried validating on v2.6-head 993608f upgraded from v2.5.15

I see the update endpoint button in the ember UI but when I click on the update button it lands in a `Page Not found` 

The get call we make from the ember UI is `https://<rancherURL>/dashboard/auth` where as anywhere from dashboard if we try the call that is made is `https://<rancherURL>/dashboard/c/_/auth/config/azuread`


Re opening the ticket based on the above observation.

**Comment by mantis-toboggan-md** [comment]
Link location fix here: https://github.com/rancher/ui/pull/4963

**Comment by anupama2501** [comment]
Verified on v2.6-head `993608f `

1. Created rancher server on v2.5.15
2. Enabled Azure AD auth 
3. From <rancher URL>/login >> Was able to sign in to the rancher server 
4. Verified when using old endpoints, we show a warning to update the Azure AD endpoints `Azure AD Authentication is using the Azure Graph API, which will be deprecated at the end of 2022. Update it here.`
5. Once we click on update button we will be redirected to the dashboard page to update the endpoints.
6. Endpoints are updated successfully.
