### ISSUE TITLE
components should use grid versus table

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#742]
Components like `<KeyValue>` and `<ArrayList>` should utilize the grid instead of being built it tables. This will avoid inconsistent spacing and positioning.

**Comment by sadiapoddar** [comment]
Verified on master-head, 5da52c0

This change is transparent to the UI users. This change internal to the components. 
Verified through "Developer Tools" that the current implementation is using grid instead of table style. 
The configMap component is effected by this change. 

Thru developer tools verified the current implementation is using grid display type.

master-head,

<img width="309" alt="Screen Shot 2020-12-30 at 4 48 53 PM" src="https://user-images.githubusercontent.com/72409237/103388625-e91a7900-4abe-11eb-9cd7-42c563cb0390.png">

In 2.5.3 the display style was flex. 

<img width="213" alt="Screen Shot 2020-12-30 at 4 50 05 PM" src="https://user-images.githubusercontent.com/72409237/103388653-254dd980-4abf-11eb-8ee6-cb70dd30a3c5.png">
