### ISSUE TITLE
Correct icon sizes after updated library

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#7496]
# Description

Some icons have been changed in size after the update of `rancher/icons`.

## Context

Since update to `rancher/icons#v2.0.8`, some icons have been changed in size due custom values in the CSS.
E.g. 
- close icon ([Banner](https://rancher.github.io/storybook/?path=/docs/components-banner--primary), BannerGraphic, NamespaceFilter), 
- chevron down ([Select](https://rancher.github.io/storybook/?path=/docs/components-form-select--select))
- info and alert ([LabeledInput](https://rancher.github.io/storybook/?path=/docs/components-form-input--labeled-input))
- checkmark (`/c/local/settings/management.cattle.io.feature`)
- plus (Tab)

List of the icons can be found in [this commit](https://github.com/rancher/icons/commit/e3ca53a36c60cabd69d53ecc86e9f4be6e6a8cbf)1.

Please ensure components quality also through the [styleguide](https://rancher.github.io/storybook).

**Comment by jameson-mcghee** [comment]
I have verified on `v2.7-head` (Commit ID: 28a84c7) a selection of the design changes outlined in the ticket. Due to that fact, I am closing this ticket as Done.

**[svg/actions.svg](https://github.com/rancher/icons/commit/e3ca53a36c60cabd69d53ecc86e9f4be6e6a8cbf):**
![image](https://user-images.githubusercontent.com/13294321/209864623-0456daaa-64bd-495a-b27e-5166a4240378.png)

**[Banner](https://rancher.github.io/storybook/?path=/docs/components-banner--primary):**
![image](https://user-images.githubusercontent.com/13294321/209864779-b3335b54-749d-41ee-8a57-34139c8ce1b3.png)

**[Unit Input Control (with suffix)](https://github.com/rancher/dashboard/pull/7557#pullrequestreview-1195626385):**
![image](https://user-images.githubusercontent.com/13294321/209864887-47cd436f-7efa-4f26-9f78-fc4eedc95e81.png)
