### ISSUE TITLE
Pod not visible in "Workload" overview page on Rancher 2.6.x UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7506]
Internal reference: SURE-5573
Reported in 2.6.8

*Issue description:*
A single pod which does not belong to a stateful set, deployment etc, are not shown in the Workload page on Rancher UI. However, this is working fine on Rancher 2.5.x, which is the user's preferred behaviour.

The user relies on the 'Workload' page to find the pods which are not a part of any deployment/daemonset and after migrating to Rancher 2.6, but they are unable to do so.

*Repro steps:*
 * Create a simple pod which is not a part of any deployment/ds/statefulset
 * Check pod is running fine
 * Login to Rancher UI -> Go to Cluster -> 'Workload' 
 * Result : On the 'workload' page, the single pod will not be available i.e, [https://rancherURL/dashboard/c/c-<id>/explorer/workload|https://TLDM/dashboard/c/c-m-9nzhsvvd/explorer/workload] , However, the pod will be available on 'Workload' -> Pod i.e, 
 * [https://rancherURL/dashboard/c/c-<id>/explorer/pod|https://TLDM/dashboard/c/c-m-9nzhsvvd/explorer/workload]

*Actual behavior:*
Pod is not available on the 'workload' page i.e 
 * [https://rancherURL/dashboard/c/c-<id>/explorer/workload|https://TLDM/dashboard/c/c-m-9nzhsvvd/explorer/workload]

*Expected behavior:*

Pod should be available on the 'workload' page i.e 
 * [https://rancherURL/dashboard/c/c-<id>/explorer/workload|https://TLDM/dashboard/c/c-m-9nzhsvvd/explorer/workload]

**Comment by richard-cox** [comment]
@steffeneichler Can you provide more info regarding the overview? In the old UI we didn't show one and only had an icon to denote workload type (the new UI has the a sortable and filterable type column)

![image](https://user-images.githubusercontent.com/18697775/218471839-354c25fc-fe6c-49f0-a277-9ea3c98ede71.png)

**Comment by steffeneichler** [comment]
@richard-cox Yes correct. Your second post with the [two screenshots](https://github.com/rancher/dashboard/issues/7506#issuecomment-1428013321) is showing my problem. The overview should show also orphaned pods.

**Comment by richard-cox** [comment]
@steffeneichler Can you expand on what you mean by `an overview on all elements (CronJobs, DeamonSets, Deployments, ..., Pods`? This is the view from our head branch that hasn't visually changed since 2.6. Note, the list in view shows all  workloads (minus pods)

![image](https://user-images.githubusercontent.com/18697775/218677155-b2cc9bc8-ea9e-4764-b89b-738cf0c12588.png)

**Comment by steffeneichler** [comment]
@richard-cox As you described in this comment https://github.com/rancher/dashboard/issues/7506#issuecomment-1428013321 in the old UI single Pods were shown if you opened the **Workloads** menu/tab.
After we migrated to new UI many of our users were confused that this is no longer the same behavior here. Man thought that the pods are not there.
In old UI the **Workloads** menu was an overview for all Cronjobs, Deamonsets, Statefulsets, Deployments, ... and also for pods (which are not part of Cronjobs, Deamonsets, Statefulsets, Deployments, ...).
To reduce confusion of our users, this should be also the behavior in new UI.

I hope you understand what I mean. Otherwise you could also contact me via rancher internal support system and we could schedule a short call.

**Comment by richard-cox** [comment]
Thanks for the update @steffeneichler , i think there was some confusion with requirements.

Yesterday I created a PR to show Pods in the Workload list that don't belong to a workload. Pods that belong to a workload will continue to not be shown in the Workload list. This should match how it used to work and from your description I think that should cover the request.

**Comment by steffeneichler** [comment]
@richard-cox sounds great. thank you.

**Comment by gaktive** [comment]
Engineering will write an automated test to help QA out in #8802
