### ISSUE TITLE
Kubernetes shown by default in target service

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#757]
What kind of request is this:
Bug

Steps to reproduce (least amount of steps as possible):
Create an ingress.
Choose a `Target Service`

Result:
The kubernetes target service is included by default.
![Screen Shot 2020-06-11 at 9 58 42 AM](https://user-images.githubusercontent.com/57409052/84422260-9be1c300-abd1-11ea-8ece-1b0c3d93de5a.png)
As this service is not used in ingress in the old UI, should we list it in the target service dropdown?

Environment information:

Rancher version:
master-head b6a3dc962
Installation option (single install/HA): Single install
Cluster type: DO

**Comment by codyrancher** [comment]
We don't want to actually filter out the kubernetes service. It's not something that rancher does. Vincent mentioned that we may be mixing up the workloads target.

There was an issue with the serviceTargets however. We needed to be filtering the services based on the current resource's namespace instead of all of the selected resources https://github.com/rancher/dashboard/pull/796#issuecomment-650461024.

So I've gone ahead and fixed that issue instead.

**Comment by aaronRancher** [comment]
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version b4067a3cb`
Target service shows services only available in selected namespace.

All namespaces:
![Screen Shot 2020-07-01 at 5 06 46 PM](https://user-images.githubusercontent.com/57409052/86302399-71c26600-bbbd-11ea-91e4-64f058b1cc3c.png)
Specified namespace:
![Screen Shot 2020-07-01 at 5 06 37 PM](https://user-images.githubusercontent.com/57409052/86302407-76871a00-bbbd-11ea-9b55-743b8558c7e6.png)
