### ISSUE TITLE
Add support for Pod Security Admission - Cluster RKE1

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#7575]
# Description

Implement point 8 of the issue https://github.com/rancher/dashboard/issues/7119 for the cluster RKE1.

Quoting:
> Cluster Creation RKE1 and RKE2
When creating an RKE1 or RKE2 cluster, the user will be able to select an existing Admission Configuration that will provided the default PSS configuration for the cluster.

https://user-images.githubusercontent.com/1955897/203307615-cb9fbea3-fa46-4513-9e24-8076714349b4.png

**Comment by gaktive** [comment]
This section is an Ember change:

"Cluster Creation RKE1 and RKE2
When creating an RKE1 or RKE2 cluster, the user will be able to select an existing Admission Configuration that will provided the default PSS configuration for the cluster."

https://user-images.githubusercontent.com/1955897/203307615-cb9fbea3-fa46-4513-9e24-8076714349b4.png

**Comment by gaktive** [comment]
Before anyone grabs this, sync with @cnotv to see what state things are since it's possible some other work blocks this.

**Comment by mantis-toboggan-md** [comment]
Additional details taken from [here]:(https://github.com/rancher/dashboard/issues/7176#issuecomment-1284718619)
>## RKE - Create New Cluster 
>If the k8s version is >= 1.25:
- Disable / remove the existing option `Pod Security Policy Support` with an annotation like "removed in k8 1.25+" 
- Add a new option `Pod Security Admission`,  its choices contain all `PodSecurityAdmissionConfiguration` defined in Rancher.  Selected value to be used  for the field `default_pod_security_admission_configuration_template_id` in the YAML representation of the cluster:
>```
>apiVersion: management.cattle.io/v3
>kind: Cluster
>spec:
>  default_pod_security_admission_configuration_template_id: <value>
>```
>
>
>## RKE  - Upgrade/Edit Existing Cluster  
If the cluster is upgraded from <=1.24  to >=1.25. On k8s 1.25+ selection in the version dropdown:
- If `Pod Security Policy Support` is enabled, UI will show a error message like "Pod Security Policy is removed since 1.25, please disable it and consider migrating to the Built-In Pod Security Admission Controller" and do not allow upgrade
- if `Pod Security Policy Support` is disabled, but objects of the kind PodSecurityPolicy are detected in the cluster, UI will show a warning message like "There are PodSecurityPolicy resources in the cluster and they will be unreachable after upgrading, please clean them up before upgrading" 
- Disable / remove`Pod Security Policy Support` field
- Show the new option `Pod Security Admission` the same way as described in the RKE - Create New Cluster section 
>
>If the cluster k8s version is already >= 1.25, UI behaves the same as described in the create new cluster >= 1.25 section.
>
>## RKE - Upgrade/Edit Imported cluster 
No changes are needed because UI does not support upgrading the k8s version of the imported RKE cluster or setting PSP/PSA.

**Comment by gaktive** [comment]
Related banner PR for RKE2: https://github.com/rancher/dashboard/pull/7821 but @nwmac needs to review what's in place already in case refinements are needed.

**Comment by markusewalker** [comment]
Upon testing the internal test cases and consulting with @jiaqiluo , there are a few issues here that need to be addressed:

1. When editing RKE1's cluster YAML, I am unable to see `spec.defaultPodSecurityAdmissionConfigurationTemplateName`. I should not be expected to manually enter this parameter and give a defined PSACT value.
2. When provisioning a RKE1 cluster with the default PSACT of `privileged`, I expect to see `spec.defaultPodSecurityAdmissionConfigurationTemplateName: privileged` in the YAML. However, I do not see this at all.
3. When provisioning a RKE1 cluster with PSACT value `restricted`, I expect to see `spec.defaultPodSecurityAdmissionConfigurationTemplateName: restricted` in the YAML. However, I instead see `spec.kubeApi.podSecurityConfiguration: restricted`. 

@gaktive @mantis-toboggan-md reopening this issue in light of the above issues noted.

**Comment by nwmac** [comment]
@markusewalker Regarding (2) - I don't believe the is a default, so I don't think this is valid - not specifying a value should result in no configuration getting added, which should result in k8s doing its default behaviour. The user can delete the PSA config template named `privileged`, so cluster creation would then fail, if we used that name as a default - the assumpuion would be that a config template with that name exists.

Point (1) might be a backend issue @mantis-toboggan-md

**Comment by markusewalker** [comment]
@nwmac thanks for your explanation! To clarify default, I mean that the value `privileged` was the pre-selected value in the dropdown when I expand the `Advanced` section (I did not create any additional PSACTs at the time of my initial testing). 

I did a bit more testing on point two. I performed the following workflow:
1. Created new PSACT named `baseline` and set enforce, warning and audit all to `baseline`.
2. Navigated to Cluster Management > Create.
3. Underneath the `Advanced` section, validated that `baseline` is the new pre-selected option in the drop-down:
![image](https://user-images.githubusercontent.com/52591819/214371463-69b82ddc-a9ee-4a4a-9e39-dba66af6dfad.png)
4. Provisioned the RKE1 cluster and I do not see `spec.defaultPodSsecurityAdmissionConfigurationTemplateName`.
5. Edited the cluster and updated the PSACT to be `privileged` -> I know am seeing point 3.

So it seems that the pre-selected value is not being registered when you provision the cluster.

**Comment by mantis-toboggan-md** [comment]
@markusewalker when I set `spec.defaultPodSsecurityAdmissionConfigurationTemplateName` manually via the 'edit yaml' option, the value isn't saved: chcking the network tab, I see it set properly in the request but it is missing from the response. `spec.podSecurityConfiguration` otoh is persisted. I found this value in the rke psa PR [here](https://github.com/rancher/rke/pull/3085) but @jiaqiluo could you confirm what key the UI should be using the set a default PSA config for rke1?

**Comment by jiaqiluo** [comment]
hi @mantis-toboggan-md , For RKE1 (and RKE2, actually) , `spec.defaultPodSsecurityAdmissionConfigurationTemplateName` is the right field to set.
As to why the value is missing from the response, it should not happen and sounds like a bug. I am going to investigate it.

**Comment by markusewalker** [comment]
To clarify, we are seeing the following different set of issues:

- The `default_pod_security_admission_configuration_template_name` is missing from the cluster's YAML in the UI.
- Currently, if you provision a RKE1 cluster with the pre-selected PSACT value in the dropdown, that value does not appear in the cluster's YAML.
- Currently, if you provision a RKE1 cluster and you choose a PSACT value other than the pre-selected value in the dropdown, the value is persisted in `spec.services.kubeApi.podSecurityConfiguration` instead of `spec.defaultPodSecurityAdmissionConfigurationTemplateName`

The second and third point are relevant to this issue, but the first point is a backend issue. @jiaqiluo as to not confusion, I will create a backend issue for the first point and assign you and I to that ticket.

Once that is resolved, we should be able to come back to this UI issue and address the second and third points.

**Comment by markusewalker** [comment]
Validated the test cases associated to this issue in the internal test plan. The prior issues addressed in my earlier [comment](https://github.com/rancher/dashboard/issues/7575#issuecomment-1402326532) have been addressed as well.

Any advanced workflows that are more specific issues that are found will be logged in separate issues. Closing this issue.
