### ISSUE TITLE
Manual Refresh Performance Option should affect secondary resources as well

### ISSUE THREAD

**Issue by Sean-McQ** [rancher/dashboard#7580]
**Is your feature request related to a problem? Please describe.**
When the "manual refresh" option is turned on in performance options, it should affect resources that are over the specified resource count threshold, this effectively reduces the websocket overhead for the web-application. However when a resource has a secondary relationship, such as Deployments > Pods, the pods in question don't use the "manual refresh" option and are subscribed as normal which often defeats the point of the option itself as in that case "pods" will almost always be a larger number of resources than "deployments"

**Describe the solution you'd like**
If either the resource or the secondary resource are over the manual refresh threshold, the manual refresh option should be triggered.

**Comment by git-ival** [comment]
Hi @Sean-McQ @aalves08, is this currently available on the latest 2.7.2-rc1?

**Comment by aalves08** [comment]
@git-ival this is not in `2.7.2-rc1`. That release was made on Jan 3rd, this PR was merged on Jan 12th.

**Comment by git-ival** [comment]
@aalves08 I tested on the latest 2.7-head image (which I believe should utlize the latest dashboard master branch) but I could use some clarification on when and where exactly the Manual Refresh button should appear. 

Given the scenario where you have a one-to-many Deployments (Primary Resource) -> Pods (Secondary Resource) relationship where the # of Pods is over the Manual Refresh limit, I expect the Manual Refresh button to appear on the Deployments (Primary Resource) list view, but that doesn't seem to be the case. Am I correct in my understanding?

Below are some recordings of the test run.

Primary AND Secondary resources are over Manual Refresh limit:

https://user-images.githubusercontent.com/85186645/216121047-7e5cd06f-c419-4ead-a48d-badf1b9ba2f1.mp4

Secondary resources are over the Manual Refresh limit:

https://user-images.githubusercontent.com/85186645/216121453-40c284cf-0be8-4ca8-bae3-49abdb25b164.mp4

**Comment by aalves08** [comment]
@git-ival There are a few concepts that aren't clarified enough and that's my fault. Let me explain:

- What we refer as `primary resource` is the resource which you want to see it's list view. Ex: List view for Deployments, Deployments is the `primary resource`.
- `Secondary resources` are kube resources that are needed to be fetched in order to display a list view for a given resource. Ex: to see the List view for Deployments you will need Pods in order to populate some data. You can check the API calls being made when you are over the threshold limit for manual refresh on the Network tab in the browser.
- The manual refresh limit is only applied to the `primary resource` count. In your examples, If you want to see the list view for the Deployments AND it's count is over 50 items, then the manual refresh button will appear. You can have 1000 Pods to be loaded in order to populate the data for the Deployments and that doesn't interfere with the threshold. what matters is the `primary resource` count.
- The big optimisation here is that before we were subscribing to those secondary resources instead of fetching them when we hit manual refresh, like we were doing with the primary resource. It was a waste of memory and computer resources. You can check all the API calls now being made on the Network tab of the browser.
- One added bonus is the incremental loading. If we are over that threshold as well, then the secondary resources are fetched incrementally as well (multiple API calls) in order to speed up the data display.

Hope this clarifies all the concepts surrounding this issue. Let me know if you have any more questions 🙏

**Comment by git-ival** [comment]
Got it, that makes sense. LGTM then, tested on 2.7.2-rc1 Rancher chart with the latest 2.7-head image!


https://user-images.githubusercontent.com/85186645/216466552-d9e212b8-631a-4d76-a69b-f9195c8bdae4.mp4
