### ISSUE TITLE
[2.6.x backport]: Resource watch re-subscription causes API load / leader election

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7707]
We have a solution for the resource watch in 2.7.x that we need to backport to 2.6.x.

2.7.x work: https://github.com/rancher/dashboard/issues/5997

Internal reference: SURE-5317

**Comment by richard-cox** [comment]
`CATTLE_WATCH_TIMEOUT_SECONDS` was brought in via https://github.com/rancher/steve/pull/49 which i think is in 2.6.x world (@cmurphy will be able to advise). From what i remember it should only affect one of the three sockets we use

1. Norman - `v3/subscribe` - No
2. Steve (Management) - `v1/subscribe` - No
3. Steve (Cluster) -  `k8s/clusters/<cluster id>/v1/subscribe` - Yes

From the screenshot of the network tab the full path isn't shown (to enable check the `Use large requests rows` option), but it does seem 2 remain up and one will die every 29.9 mins. CATTLE_WATCH_TIMEOUT_SECONDS doesn't seem to have been applied BUT it does look like the underlying closure is happening alright

**Comment by git-ival** [comment]
LGTM! Retested today with all the environment variables set on initial deployment and it looks like that forced the watch timeout correctly. I misunderstood the expected behavior and assumed that every 5 minutes all the watches would be stopped -and- the websocket would be closed + a new one would be opened. But it seems that the websocket is meant to remain open until a refresh is triggered, and the resources will be watched until reaching the `CATTLE_WATCH_TIMEOUT_SECONDS`.

Resource watches stopping with `CATTLE_WATCH_TIMEOUT_SECONDS` = 300:
![image](https://user-images.githubusercontent.com/85186645/218019895-b9b3f63c-9f90-4de3-8446-4cdb0aad0e38.png)
