### ISSUE TITLE
Confirmation Warning when creating a v1.23-v1.24 RKE1/2 Cluster with PSPs enabled

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7791]
Users running Kubernetes v1.23 - v1.24 should have a banner asking them to migrate to PSA/PSSs in the same places as we're doing for v1.25 with the phasing out of PSPs but it's more of a case of guidance before they upgrade.

An investigation is needed into the impact of maintaining PSPs in a cluster that no longer supports them. Preliminary findings show issues with orphaned PSP resources. It should be evaluated whether users are prevented from upgrading to 1.25 altogether with Rancher Launched Kubernetes and Distributions until PSPs are completely disabled in those clusters. 

(RKE1 upgrades to 1.25 will not be allowed if PSP is enabled, back-end will throw error; 
for RKE2, the upgrades are prevented when non-default RKE2 PSP is used -- by default RKE2 has PSP enabled and applies "allow all" default PSP)

**Comment by gaktive** [comment]
This will relate to another request: UI Banners Warning Users on v1.23-v1.24 with PSPs enabled they need to migrate to PSA/PSSs in Cluster Edit and PSP Configuration Pages. 

Checking if that's being tracked anywhere already; failing that, it's another ticket.

**Comment by kwwii** [comment]
If I understand correctly, this is about showing the following alerts:

- An informational alert when a user CREATES any version of cluster that PSPs no longer exist in >=1.25 
- A warning alert on EXISTING clusters <1.25 _with PSPs enabled_ that the user needs to migrate to PSA/PSSs
- An error alert when a user UPGRADES <1.25 clusters _with PSPs enabled_ to 1.25

**Comment by gaktive** [comment]
Previously titled as a Confirmation Warning Modal.

**Comment by gaktive** [comment]
There's work already merged that already has some wording around what we tell users about PSPs and 1.25.

Issue: https://github.com/rancher/dashboard/issues/7553
PR: https://github.com/rancher/dashboard/pull/7821

**Comment by gaktive** [comment]
@cnotv is the primary engineer working on the PSA/PSS work so if help on wording and behaviour is needed, he can assist.

**Comment by edenhernandez-suse** [comment]
In the planning I mentioned something but we didn't really discuss it, I'd like to let it here written so at least we can consider it as an option.

A warning message without any context or guidance to the user is unlikely to provide a good UX. Sure DevOps engineers will know how to proceed, but we want developers and other kinds of professionals to also use Rancher. It might not be 100% clear to them what to do if they just read "PSP is going to be deprecated".

I don't have an answer yet, maybe guiding the user here is a bit overkilling, but I guess we could at least provide a doc link or similar, e.g. [this post about the PSP deprecation](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/) on the Kubernetes' blog.

I'm talking here with little context about the whole thing, so I might be completely wrong; just wanted to mention this as a general rule, not only warning users but also providing context, solutions and/or guidance.

**Comment by slickwarren** [comment]
tested on v2.7-head (3c1e7db):
* rke2 new 1.24.x or below cluster - PASS
<img width="466" alt="Screen Shot 2023-02-07 at 11 11 48 AM" src="https://user-images.githubusercontent.com/16691014/217342714-99a8cbe6-c644-42a9-8664-1518ca1f5bcd.png">
* rke2 new 1.25.x cluster - PASS **however there is a space missing in podSecurity Admission banner**
<img width="722" alt="Screen Shot 2023-02-07 at 11 14 00 AM" src="https://user-images.githubusercontent.com/16691014/217342924-e1ee3925-d95a-4914-9c93-2fb03c0ea22a.png">
* rke2 upgrade from 1.24.x to 1.25 with PSP enabled - PASS
<img width="757" alt="Screen Shot 2023-02-07 at 11 12 27 AM" src="https://user-images.githubusercontent.com/16691014/217342991-86c30773-183a-4b5b-be74-08edb1932e88.png">
* rke2 upgrade from 1.24.x to 1.25 without any PSP - Currently unable to test (PSP defaults to `RKE Default` in UI) - **FAIL** (can file a separate ticket if this is not expected behavior, please provide feedback/comment for this)


* RKE1 - seems to not have been changed, looking at the linked PRs. Though this ticket title has rke1/2 mentioned. Will there be an update to the banners there as well? Currently there is only a generic banner in the `advanced options` section, that does not change based on the current k8s version, nor if PSP is enabled/disabled. (please provide feedback/comment for this)
<img width="812" alt="Screen Shot 2023-02-07 at 11 18 42 AM" src="https://user-images.githubusercontent.com/16691014/217343872-8468be48-049e-4de7-a54c-8eb364c418b5.png">

**Comment by cnotv** [comment]
@slickwarren Please create a separated issue for RKE1.

For the RKE2, displaying `RKE Default` means no picked PSP from the UI, therefore there is nothing to test.

**Comment by slickwarren** [comment]
ok thanks for the update, linked the RKE1 ticket above and confirmed with the team for PSP messaging. Closing this issue
