### ISSUE TITLE
Banner is broken

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7920]
Banner on cluster creation screen is broken - not being rendered as HTML and the spacing is wrong.

This may be affecting other Banner as well.

Please trace how this bug got in, so we can understand how this bug got in!

![image](https://user-images.githubusercontent.com/1955897/212377989-31000f09-0b65-4e97-9d98-2dc7da2f95ac.png)

**Comment by richard-cox** [comment]
This was spotted by @cnotv , i said a fix in his incoming PR would be enough. If it's split out, it's a simple fix (the args for the translation are broken and skip out the options object, so should end in something like `{} , true)`). Not sure on the spacing part though

**Comment by cnotv** [comment]
@nwmac the padding may be related to cross styling and the way we style components.
In Storybook it seems to be fine: https://rancher.github.io/storybook/?path=/story/components-banner--closable
Please let's not mix up issues of different types, because if there's an issue with a specific page, it should not be fixed in a feature. The HTML part is related to what I'm working on, so it's ok.

**Comment by cnotv** [comment]
I see no issues with the padding:
<img width="958" alt="Screenshot 2023-01-19 at 08 33 41" src="https://user-images.githubusercontent.com/5009481/213381986-c1972702-606b-49c2-bc71-0e6ede8cf8ee.png">
