### ISSUE TITLE
Logging `Cluster Outputs` and `Outputs` create forms do not have sticky footer

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#7978]
**Setup**
- Rancher version: 2.7-head
- Browser type & version:

**Describe the bug**

**To Reproduce**
- install logging cluster tool
- navigate to either of the two resources
- click create
- the footer isn't stuck to the bottom 

Could be related to https://github.com/rancher/dashboard/issues/7975

**Screenshots**
![image](https://user-images.githubusercontent.com/18697775/213657291-f61c735c-3711-493f-bf51-580037e54e40.png)

![image](https://user-images.githubusercontent.com/18697775/213657361-421c8c01-8fce-4048-9afe-9791cd84b7e5.png)

**Comment by ronhorton** [comment]
**Pass** Verified fixed in rancher `v2.7-head commit ID 897aafe`
1. Created rancher HA
2. created downstream cluster
3. clicked cluster > Apps
4. installed rancher-logging:102.0.1+up3.17.10
5. clicked cluster > logging > Cluster Flows - `buttons in footer are sticky - page scrolls in frame above buttons`
