### ISSUE TITLE
PSP Removal: Update what's new document to mention PSP issues with installed Helm Charts

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#8050]
Need to update the what's new document and add a note to draw users' attention to the removal of PSPs in k8s 1.25+ and the need to check/update Helm applications.

**Comment by gaktive** [comment]
I had hoped we'd removed What's New and point to the docs/release notes but we should add this change in if we still have it.

**Comment by gaktive** [comment]
Putting in some 2.7.1 default content to account for that version.

@nwmac let me know what we need to cover, or what you'd like me to say and I get that in for your review. PR: #8239 -- I don't know if we need Product involved this time around, or input from other engineering teams since we could always point to docs & release notes for material that lands after code freeze.

**Comment by ronhorton** [comment]
PSP verbiage added & committed
