### ISSUE TITLE
AKS: Add taints, labels & maxSurge to nodes

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8073]
Internal references: SURE-5535, SURE-5536

Request description:
Feature request to allow taints, maxSurge and labels to be added for individual nodes in rancher UI. Various public clouds have these options, so we'll begin with doing this for AKS.

Actual behavior:
- Taints can only be added to node pools instead of each node themselves.
- UI has no interface for labels or maxSurge.

Expected behavior:
- Options in Rancher UI for adding these options on each node individually.

Workaround:
- none for taints
- labels & maxSurge can be added via CLI

Additional notes:
- Upstream feature request https://github.com/rancher/rancher/issues/40214 (merged)
- Code improvement was submitted https://github.com/rancher/aks-operator/pull/82 (merged)

**Comment by richard-cox** [comment]
Taints and labels can be applied via the Cluster Explorer Node views (not sure about maxSurge). So after the cluster has been created.

On the off chance, is this enough to satisfy the original requirement?

**Comment by gaktive** [comment]
@nwmac does UI have automation in this issue or will QA have to test this? Or should we open up a ticket to add automation?

**Comment by nwmac** [comment]
@gaktive QS will need to test. It’s ember and one of the features for Q2.

**Comment by Josh-Diamond** [comment]
@nwmac Hey Neil 👋.. I'm in the process of drafting up a QA test plan for this, and was wondering what the expected behavior is with regards to validation checks (if any?)

I'd like to accommodate the following point in my test plan:
 - ensure proper validation is implemented (if needed; to prevent invalid configurations from being sent)


And had a few questions (for devs) surrounding Max Surge:
+ What happens when a negative integer/percentage is used? is this valid? do we catch this w/ validation?
+ How about percentages greater than 100%, non-numerical values, such as `a`, or fractional integer values, like `0.5`?

Thanks for taking a look at this :)

**Comment by Josh-Diamond** [comment]
_Full test plan with detailed steps available internally upon request. Unable to proceed with most of the validation checks as a result of the concerns reported below._

---

❗RE-OPENING❗due to the following concerns:

---

**Concern 1 - Inaccurate default values for maxSurge of node pools are seen via Rancher UI:**

❌ By default, Rancher does NOT configure a maxSurge value for AKS node pools.  The field is blank in Rancher UI, and once provisioned, navigating to `edit config > node pools > maxSurge` points to `N/A`.  

✅ In Azure portal, the default maxSurge value of `1`, is configured. Upon updating node pools, the default behavior of having a maxSurge value of `1` is observed.  

💡 Requesting Rancher to default to a maxSurge value of `1`, and not `N/A`, as that is truly the value configured for this field.

---

**Concern 2 - Unable to update maxSurge values for node pools:**

❌ Once AKS cluster is configured and provisioned, there is NO way to update the maxSurge value of node pools in Rancher.

✅ In Azure portal, the maxSurge value of node pools may be updated at any time.  

💡 Requesting Rancher to support updating maxSurge values for node pools.

---

**Concern 3 - Validation checks for maxSurge values in node pools:**

❌ There is currently no validation in place to stop a user from provisioning a cluster with an invalid maxSurge value.  Rancher UI accepts (and provisions) maxSurge values in node pools which are invalid, such as: `a`, `0.5`, `# - or any special character besides %`, `-5%`,  and `101%`.  During provisioning, with these invalid configurations, an error is seen and displayed, coming from Azure portal, informing the user of the invalid configuration.  The cluster will proceed to provision and come up `active`.  The invalid configurations are seen in both Rancher and Azure portal. The issue seems rather benign until the user attempts to upgrade node pools, at which point the error returns and prevents the upgrade from occurring.

✅ As outlined in the [AKS docs](https://learn.microsoft.com/en-us/azure/aks/upgrade-cluster?tabs=azure-cli#customize-node-surge-upgrade), valid max surge values consist of integers >= 1, as well as percentages ranging from 1%-100%.  

💡 Requesting validation be added to prevent invalid use cases from provisioning through Rancher UI.

**Comment by Josh-Diamond** [comment]
Ticket #8073 - Test Results - ❌ Re-opened (again)
---

_Full test plan with detailed steps available internally upon request._ 

---

❗RE-OPENING❗due to the following concerns:

Key:
❌ = Issue
💡 = QA request

---

**Concern 1** - Inaccurate default values for maxSurge of node pools are seen via Rancher UI:

❌ Scenario 1 - 
- Provisioning downstream AKS on Rancher `v2.7.3`, then once `active`, upgrading Rancher to `v2.7-head`, then navigating to `Cluster Explorer > Edit Config > Node pools (agentpool) > maxSurge` shows the field as BLANK.  

❌ Scenario 2 -
- Provision an AKS cluster in Azure portal.  Once `active`, import the cluster into Rancher `v2.7-head`.  Once imported and `active`, navigate to `Cluster Explorer > Edit Config > Node pools (agentpool) > maxSurge` shows the field as BLANK

💡 The true default value is `1`, and this should be reflected in Rancher UI as well.

---

**Concern 3** - Validation checks for maxSurge values in node pools:

❌ Scenario 1 - 
- AKS fails to provision with defaults from Rancher UI.  Validation from Rancher UI flags `maxSurge` value of `1` as invalid.

💡 Requesting validation be added to prevent INVALID use cases from provisioning through Rancher UI. maxSurge value of `1` is valid, and should be accepted as such.

**Comment by Josh-Diamond** [comment]
Ticket #8073 - Test Results - ✅ 
---

_Full test plan with detailed steps available internally upon request._ 

---

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision downstream AKS w/ taints, labels, & maxSurge values configured for nodepools on Rancher `v2.7-head` | ✅ |
| 2. | Provision a downstream AKS cluster w/o taints, labels, or maxSurge and w/o any user configured "system" mode node pools, verify that UI no longer hangs in "saving..." state when node pool name is NOT provided | ✅ |
| 3. | Provision downstream AKS on `v2.7.3` => upgrade Rancher to `v2.7-head` => verify taints, labels, maxSurge + system mode node pool features are implemented and accessible, post rancher-server upgrade | ✅ |
| 4. | Create AKS cluster in Azure portal => Import AKS cluster into Rancher `v2.7-head` => verify taints, labels, maxSurge + system mode node pool features are implemented and accessible for imported clusters | ✅ |
