### ISSUE TITLE
(SURE-5534) Adding node pools only works for user node pools, not system node pools.

### ISSUE THREAD

**Issue by kkaempf** [rancher/dashboard#8105]
https://jira.suse.com/browse/SURE-5534

A nice to have issue for AKS - Adding node pools only works for user node pools, not system node pools.

Request description:
A user needs a feature for adding system node pools in AKS, not only user node pools

Actual behavior:
An admin is able to add node pools in AKS that are labeled as User node pools, however unable to add system node pools with rancher tools.

Expected behavior:
Deploying node pools as needed for whatever AKS demands in it's infrastructure for features in AKS

Additional notes:

*https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli*

This is scoped to AKS only

@nwmac has a PR up already.

**Comment by Josh-Diamond** [comment]
_Full test plan with detailed steps available internally upon request. Unable to proceed with most of the validation checks as a result of the concerns reported below._

---

❗RE-OPENING❗due to the following concerns:

---

**Concern 1 - Inaccurate default values for maxSurge of node pools are seen via Rancher UI:**

❌ By default, Rancher does NOT configure a maxSurge value for AKS node pools.  The field is blank in Rancher UI, and once provisioned, navigating to `edit config > node pools > maxSurge` points to `N/A`.  

✅ In Azure portal, the default maxSurge value of `1`, is configured. Upon updating node pools, the default behavior of having a maxSurge value of `1` is observed.  

💡 Requesting Rancher to default to a maxSurge value of `1`, and not `N/A`, as that is truly the value configured for this field.

---

**Concern 2 - Unable to update maxSurge values for node pools:**

❌ Once AKS cluster is configured and provisioned, there is NO way to update the maxSurge value of node pools in Rancher.

✅ In Azure portal, the maxSurge value of node pools may be updated at any time.  

💡 Requesting Rancher to support updating maxSurge values for node pools.

---

**Concern 3 - Validation checks for maxSurge values in node pools:**

❌ There is currently no validation in place to stop a user from provisioning a cluster with an invalid maxSurge value.  Rancher UI accepts (and provisions) maxSurge values in node pools which are invalid, such as: `a`, `0.5`, `# - or any special character besides %`, `-5%`,  and `101%`.  During provisioning, with these invalid configurations, an error is seen and displayed, coming from Azure portal, informing the user of the invalid configuration.  The cluster will proceed to provision and come up `active`.  The invalid configurations are seen in both Rancher and Azure portal. The issue seems rather benign until the user attempts to upgrade node pools, at which point the error returns and prevents the upgrade from occurring.

✅ As outlined in the [AKS docs](https://learn.microsoft.com/en-us/azure/aks/upgrade-cluster?tabs=azure-cli#customize-node-surge-upgrade), valid max surge values consist of integers >= 1, as well as percentages ranging from 1%-100%.  

💡 Requesting validation be added to prevent invalid use cases from provisioning through Rancher UI.

**Comment by Josh-Diamond** [comment]
No initial issues seen w/ first round of testing, but inability to update maxSurge value is blocking further testing.

Will resume testing, once [concerns w.r.t. maxSurge](https://github.com/rancher/dashboard/issues/8073) have been addressed

**Comment by Josh-Diamond** [comment]
Ticket #8105 - Test Results - ✅ 
---

_Full test plan with detailed steps available internally upon request._ 

---

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision downstream AKS w/ user configured "system" mode nodepools on Rancher `v2.7-head` | ✅ |
| 2. | Provision downstream AKS on `v2.7.3` => upgrade Rancher to `v2.7-head` => verify system mode node pool feature is implemented and accessible, post rancher-server upgrade | ✅ |
| 3. | Create AKS cluster in Azure portal => Import AKS cluster into Rancher `v2.7-head` => verify system mode node pool feature is implemented and accessible for imported clusters | ✅ |
