### ISSUE TITLE
Unable to click `continue` when specifying a new cloud credential as part of creating a new cluster.

### ISSUE THREAD

**Issue by David-VTUK** [rancher/dashboard#8145]
**Setup**
- Rancher version:  v2.7.1 
- Browser type & version: Firefox 109.0.1

**Describe the bug**
When creating a new cluster on a infrastructure provider without an existing `cloud credential` , the Rancher UI will prompt to create a new one, however, `continue` cannot be selected.

**To Reproduce**

- Remove any existing cloud credentials for a infrastructure provide (ie Harvester, DO, etc)
- Rancher -> Cluster Management -> Create
- Select a cluster type under `Provision new nodes and create a cluster using RKE2/K3s `
- Attempt to continue with the credential creation flow

**Result**
- `Continue` is greyed out, unable to proceed

**Expected Result**
- Rancher UI should guide the user into creating a cloud credential

**Screenshots**
![image](https://user-images.githubusercontent.com/5892615/218303807-b36f227f-ac1f-42d3-a6eb-1d15c2885164.png)

**Additional context**

**Comment by richard-cox** [comment]
I couldn't recreate this in 2.9-head (around 2.9.0).

![image](https://github.com/rancher/dashboard/assets/18697775/b8ff2acb-8520-401e-86c7-96c45f32aa26)

There should be more input fields when creating an azure cred. There might have been a page error causing them not to render. I think there were some updates to this area since 2.7.1 which may have fixed them

**Comment by eva-vashkevich** [comment]
I wasn't able to recreate the issue on 2.7.1  either.
