### ISSUE TITLE
Make the dashboard ~~~sizzle~~~

### ISSUE THREAD

**Issue by lvuch** [rancher/dashboard#819]
Attached is the approved mock:
https://xd.adobe.com/view/bc7e23b6-3111-4f98-b388-89e7c83a15aa-e92d/

**Comment by codyrancher** [comment]
@deniseschannon @lvuch I have a few questions about the mock

**Regarding the resources listed in the cluster of 10 gauges:**
![image](https://user-images.githubusercontent.com/55104481/87480961-3ffcc680-c5e3-11ea-92f4-f6ca5d2347ba.png)
  - Do we want them to be clickable and take you to the respective list pages?
    - Where do you want the total resources gauge to take you?
  - Are those the resources we want to display?
  - Do we mind that total resources will always be a full circle?
  - Do we want the warning/error alert to be be right justified even though the warning alert will move depending on the presence of error and the number of digits show?
  - Do we want the warning/error alert to link to anything or show anything on mouse over?

**Regarding the hardware resources listed in the cluster of 5 gauges at the bottom**
![image](https://user-images.githubusercontent.com/55104481/87481018-5c98fe80-c5e3-11ea-8e55-9122b104ae15.png)
- Do we actually want to display the two at the bottom with different resources (they repeat the ones at the top) or do we want to remove them?
- What will the green, yellow and red levels be at?
  - Do we want that to be configurable for each resource?

**Comment by deniseschannon** [comment]
**Feedback to Questions re: 10 gauges**
> Do we want them to be clickable and take you to the respective list pages?

Yes, bringing them to the respective pages would be great idea.

> Where do you want the total resources gauge to take you?

This doesn't need to go anywhere. 

> Are those the resources we want to display?

Yes, these are the resources we want to display

> Do we mind that total resources will always be a full circle?

I believe the gauge should be based on number of `active` resources out of all the resources. So if there are any resources that are not `active` it wouldn't be a full circle. 

> Do we want the warning/error alert to be be right justified even though the warning alert will move depending on the presence of error and the number of digits show?

@vincent99 What's the diff between a warning alert versus error alert for the resources? What is the difference in status?

> Do we want the warning/error alert to link to anything or show anything on mouse over?
Since clicking on the resource will bring it to the page, you should be able to see those resources.

In theory, we could have it link to the resource page with a filter on the not active status, but not sure if that even works in the list page. 

**Feedback to 5 gauges**

> Do we actually want to display the two at the bottom with different resources (they repeat the ones at the top) or do we want to remove them?

I believe there is a difference between reserved and used, but maybe it needs to be distinguished better in the headers about the diff. 
@vincent99 thoughts?

> What will the green, yellow and red levels be at? 
> Do we want that to be configurable for each resource?

@vincent99 do you have any suggestions?

**Comment by vincent99** [comment]
> I believe the gauge should be based on number of active resources out of all the resources. So if there are any resources that are not active it wouldn't be a full circle.

Yes the circle is what percent of the resources are in "normal" states.

Normal vs info/warning/error would be defined by looking up the state (from `counts`) -> resource-instance's `color` mapping for each state.  The icons could show nothing, or 

Keep in mind that any or all of the resources this page shows may not be available to the user that is logged in, so check if the type exists in schemas before showing it and either don't show the box or show "not available" or something (not "0" because you can't list them)

>>Do we actually want to display the two at the bottom with different resources (they repeat the ones at the top) or do we want to remove them?
> I believe there is a difference between reserved and used, but maybe it needs to be distinguished better in the headers about the diff.

Yes reserved and used are different.  Top 3 should probably say "X Reserved" in the title" The pods is actually the same count as the colored one above, but this one adds what the limit (110 per node normally) is and how close to it you are.  "reserved" is how much is allocated according to the scheduling.  "used" is 

> What will the green, yellow and red levels be at?
>Do we want that to be configurable for each resource?

Mostly arbitrary, you could just make them all refer to a constant for now.  75 and 90%?

**Comment by izaac** [comment]
#885

**Comment by izaac** [comment]
Rancher `master-head (07/23/2020)` _fd3e37bec_ k8s HA install.
dashboard-index -> `latest`

Opened separate issues.

Tested New Gradient boxes with the following 
- Namespaces
- Ingresses
- Persistent Volumes
- Deployments
- Stateful Sets
- Jobs
- Daemon Sets 
- Services

Also the cluster computing resources

Usage colors -> Green to Yellow (~80%) to Red (90+%) and back to Green

- Pods Reserved
- Cores Reserved
- RAM Reserved
- Cores Used
- RAM Used

Events.


Adding and removing resources of each time, Making them fail (Inactive/Error) and get them into a Pending state to check the counts.
Adding resource use to get the computing resources boxes also graph properly. 
Compared with the Ember UI count numbers where applicable.
