### ISSUE TITLE
UI inactivity notification and timeout settings: Design

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8317]
Parent Issue: rancher/dashboard#7776

We need a design to display that a browser session is idle.

See parent issue for more details

**Comment by gaktive** [comment]
This should tie into https://github.com/rancher/dashboard/issues/8207 regarding the overall modal behaviour.

**Comment by cnotv** [comment]
Bare mind of existing modals while working on the design https://github.com/rancher/dashboard/issues/8207

**Comment by edenhernandez-suse** [comment]
![image](https://user-images.githubusercontent.com/120640736/224100284-79b6e0b4-3dd7-43dd-a4e3-b549f2f4c159.png)

![image](https://user-images.githubusercontent.com/120640736/224100461-60b68a5b-8161-4fd4-8073-93bcf01e890b.png)

**Comment by edenhernandez-suse** [comment]
![image](https://user-images.githubusercontent.com/120640736/224327350-bc2d083c-bdb5-429e-a1ec-4b1a76f7c461.png)

My first idea for the setting. I only included the timeout setting, the other one (the time between the modal appears and UI is unsubscribed to the sockets) could be considered kind of a "courtesy" extra time to extend the session. We might be able to decide a reasonable time for that without an option for users.

**Comment by edenhernandez-suse** [comment]
@cnotv me too, but it's like that in the entire section :sweat_smile:

![image](https://user-images.githubusercontent.com/120640736/224352187-97bfed12-8a72-48cb-89f2-a3e9b15ac7b9.png)

**Comment by edenhernandez-suse** [comment]
After a quick sync and discussion, we have decided that the simplest solution is to provide users with a setting for the **real** timeout. A reasonable time before that, we'll show the first modal to keep the session alive. That time could be either a percentage of the total timeout (e.g. 15% of the timeout) or a fixed time for different periods (e.g. 1 min before for timeouts < 10 min, 5 min before for timeouts < 30 min, etc). 

![image](https://user-images.githubusercontent.com/120640736/224991549-a3885a19-f370-4489-a2f9-e16e74d99481.png)

**Comment by richard-cox** [comment]
RE https://github.com/rancher/dashboard/issues/8317#issuecomment-1462422338

We've lost one of the steps. When the session is 'paused' the only way to recover is to refresh the page (either manually or by clicking the button and we'll do the reload).

First Stage of Model - Everything is still working, sockets connected, etc
- At this point it's just a warning. The user needs to dismiss the modal to continue with their session. 
- If the user does not dismiss the modal within a certain amount of time (hence display of timer) the sockets will be dropped and we go to the second stage

Title: Session Expiring
Banner: Your session is expiring in <counter> <minutes|seconds|second> due to inactivity
Text: Click `Dismiss` to resume your session
Button Text: `Dismiss`

Second Stage of Model - Their session is kaput
- At this point the user needs to reload the page. 

Title: Session Expired
Banner: Your session has expired due to inactivity
Text: Click `Reload Page` to return to this page
Button: `Reload Page`

RE https://github.com/rancher/dashboard/issues/8317#issuecomment-1467956626
The default session timeout is 960 minutes (16 hours) and looks to come from the `auth-user-session-ttl-minutes`. I'm not sure we want to always run off of this? We could use it to set a sensible default though.... an hour if `auth-user-session-ttl-minutes` is over an hour --> 5 minutes before `auth-user-session-ttl-minutes` if `auth-user-session-ttl-minutes` is over 5 minutes --> off?

Title: Session Expires
Description: When enabled and the user is inactive past the specified timeout, the UI will no longer fresh page content and the user must reload the page to continue. 
Checkbox: Enable Session Expires
Text Box: Inactivity timeout (minutes)

**Comment by edenhernandez-suse** [comment]
Final design and specs in Confluence:

[Idle Modal (reduce impact of idle tabs) #7776](https://confluence.suse.com/pages/viewpage.action?pageId=1208877508)
