### ISSUE TITLE
Base User is not able to list clusters in Cluster Management page

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#8393]
**rancher - 2.7-head commit id: `70455b1 `**

- As an admin, create a base user and add `Create new Cluster` role and `Create new RKE Cluster Templates` role.
- Login as the user
- Create an RKE1 cluster
- User is not able to see the cluster in Cluster Management page
- Error in console: 

```
console.js:31 TypeError: Cannot read properties of undefined (reading 'includes')
    at S.get (provisioning.cattle.io.cluster.js:106:75)
    at S.get (resource-class.js:817:22)
    at f.bulkActionsForSelection (selection.js:72:18)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.evaluate (vue.runtime.esm.js:4597:21)
    at f.bulkActionsForSelection (vue.runtime.esm.js:4851:17)
    at f.availableActions (actions.js:41:19)
    at Tn.get (vue.runtime.esm.js:4495:25)
    at Tn.evaluate (vue.runtime.esm.js:4597:21)
    at f.availableActions (vue.runtime.esm.js:4851:17)
```

**Comment by richard-cox** [comment]
Probably related to this chunk of code, the base user may not be able to see the cluster template schema. @aalves08 can you take a look? 

```
 const clusterTemplatesSchema = this.$getters['schemaFor']('management.cattle.io.clustertemplate');
    let canUpdateClusterTemplate = false;

    if (clusterTemplatesSchema && (clusterTemplatesSchema.resourceMethods.includes('blocked-PUT') || clusterTemplatesSchema.resourceMethods.includes('PUT'))) {
      canUpdateClusterTemplate = true;
    }
```

**Comment by aalves08** [comment]
Hello @sowmyav27 . I've spun up a `rancher/rancher` version for the commit you referred to and I couldn't reproduce the issue.

Here are my steps:
- As an admin, create a base user and add Create Cluster role.
- Login as the user
- Create an RKE1 cluster (Digital Ocean one, k8s version `v1.25.6`
- Go to Cluster Management, I can see the cluster being created and also after it has provisioned without any errors on console.

![Screenshot 2023-03-10 at 11 09 36](https://user-images.githubusercontent.com/97888974/224307949-7bb4d4c4-eeb3-4258-9a84-94d09c8aa193.png)
![Screenshot 2023-03-10 at 11 10 14](https://user-images.githubusercontent.com/97888974/224307952-eae5676b-9bff-4563-8ef7-bb171037b8bd.png)
![Screenshot 2023-03-10 at 11 42 15](https://user-images.githubusercontent.com/97888974/224307956-f23a17bb-4893-42ff-bbbf-06e66cf84b6f.png)

- Can you see the cluster on Cluster Management after refreshing the page?
- If you can reproduce it consistently, can I get access to your system?

If you want, just reach out to me so that we can go over this together 🙏  Thank you

**Comment by sowmyav27** [comment]
@aalves08 Apologies. I was able to narrow it down. As a user base, along with `Create new Clusters` role, `Create new RKE Cluster Templates` role was also added to the user. And that is causing the issue. I have updated the original issue's description to reflect this step.

**Comment by aalves08** [comment]
No worries @sowmyav27 . With your updated instructions I was able to reproduce it and the fix is up for review. Ported it to master as well.

**Comment by sowmyav27** [comment]
Verified on 2.7-head commit id: `7913e28`

- As an admin, create a base user and add Create new Cluster role and Create new RKE Cluster Templates role.
- Login as the user
- Create an RKE1 cluster
- User is able to see the cluster in Cluster Management page. No errors seen in console logs
