### ISSUE TITLE
RKE2/K3s custom clusters redirect to the `Machines` tab instead of the `Registration` tab in Cluster Management once clicked

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#8513]
**Setup**
- Rancher version: `v2.7.2-rc7`
- Browser type & version: Chrome

**Describe the bug**

When navigating to Cluster Management > RKE1 custom cluster, I am redirected to the `Registration` tab as expected. However, when navigating to Cluster Management > RKE2/K3s custom cluster, I am redirected to the `Machines` tab instead of the `Registration` tab. RKE2/K3s custom clusters should emulate RKE1s behavior as opposed to what it currently is doing.

Node driver provisioned clusters, regardless of cluster type, will go to the `Machines` tab as expected. But for custom clusters, we should have RKE2/K3s align to what RKE1 custom clusters are doing to ensure consistency.

I noted as far back as v2.6.9 that this behavior is occurring.

**To Reproduce**

1. As a standard user, navigate to Cluster Management > Create > Custom.
2. Provision a downstream RKE2 custom cluster (1 etcd, 1 cp, 1 worker).
3. Validate that the cluster and nodes come up as `Active` in Cluster Management and Cluster Explorer.
4. Click on the downstream RKE2 custom cluster in Cluster Management and validate you're redirected to `Machines` tab instead of `Registration` tab.

**Result**
RKE2/K3s custom clusters redirect to the `Machines` tab in Cluster Management.

**Expected Result**

RKE2/K3s custom clusters should redirect to the `Registration` tab in Cluster Management.

**Comment by aalves08** [comment]
@markusewalker had a chat with the UX team and we do agree that the behaviour for both rke1 and rke2 should be the same/consistent.

The agreed behaviour with the UX team for both is:
- If there are no registered nodes, will default to the `registration` tab
- If there's at least one registered node, will default to the `machines` tab 

From my interpretation of this issue, it's a bit different on what you have described, since following steps `2.` and `3.`  of the repro steps I assume that the `rke2` custom cluster has a registered node, therefore as agreed with UX, the behaviour is correct.

What we consider incorrect at this point is the behaviour in the `rke1` custom cluster. If there's at least one registered node, it should default to the `machines` tab.

Will act in accordance with an upcoming PR. Thanks 🙏 

FYI @richard-cox @edenhernandez-suse

**Comment by markusewalker** [comment]
Validated that this is addressed on `v2.8-head` https://github.com/rancher/rancher/commit/90fc68836fd8d1bd2996283500f954ace40203ba.

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/90fc68836fd8d1bd2996283500f954ace40203ba

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE1 and RKE2 custom cluster and validate that you're redirected to the `Machines` tab in Cluster Management|:white_check_mark:|
|2|As a standard user, create a downstream RKE1 and RKE2 custom cluster with no registered nodes and validate that you're redirected to the `Registration` tab in Cluster Management|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE2 `v1.26.7+rke2r1` custom cluster.
2. Clicked on the cluster in Cluster Management and validated I am redirected to the `Machines` tab.
3. Repeated the above steps, but for RKE1 `v1.26.7` custom cluster and am redirected to `Machines` tab as well.
_______
**Scenario 2**
1. As a standard user, created a downstream RKE2 `v1.26.7+rke2r1` custom cluster, but did not register any machines.
2. Clicked on the cluster in Cluster Management and validated that I am redirected to the `Registration` tab.
3. Repeated the above steps, but for RKE1 `v1.26.7` custom cluster and am redirected to `Registration` tab as well.
