### ISSUE TITLE
Provisioned RKE1 Clusters are being marked as Custom on dashboard view

### ISSUE THREAD

**Issue by git-ival** [rancher/dashboard#8611]
**Setup**
- Rancher version: 2.7.2-rc7
- Browser type & version: 
  - Chrome v111.0.5563.147
  - Chrome v106.0.0.0
  - Vivaldi v5.5.2805.35

**Describe the bug**
If the user has a provisioned cluster, it will appear as a "Custom RKE1" cluster instead. If the user navigates to Cluster Management it will be labelled properly, and if they then move to the dashboard view it will be labelled as a provisioned nodedriver cluster as well. After any reloads, moving to the dashboard page will label it as a "Custom RKE1" cluster again.

**To Reproduce**
1. Login to Rancher
2. Provision a Linode, AWS or other nodedriver RKE1 cluster 
3. Reload and navigate to the Dashboard page
4. Observe that the cluster is labelled as "Custom RKE1"
5. Navigate to Cluster Management
6. Observe that the cluster is labelled as "[Cloud Provider name] RKE1"
7. Navigate back to the Dashboard page 
8. Observe that the cluster is labelled as "[Cloud Provider name] RKE1"

**Result**
The cluster is incorrectly labelled as a Custom cluster on the Dashboard page.

**Expected Result**
It should be labelled as a provisioned nodedriver [Cloud Providername ] cluster on the Dashboard page.

**Screenshots**

https://user-images.githubusercontent.com/85186645/229616280-4c53bac7-35c8-412c-8f9c-0c0c33f8a40f.mp4

**Additional Context**
- Tested via provisioning with the rancher2 provider as well as manually
- Verified against AWS and Linode provisioned RKE1 clusters
- Verified this same behavior was present in Rancher v2.7.0

**Comment by nwmac** [comment]
This issues requires an RKE1 cluster to test, so can't easily be automated at the moment

**Comment by thaneunsoo** [comment]
### Test Environment: ###
Rancher version: v2.7-head 5334be3
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: rke1 node driver cluster

----------

### Testing: ###

Tested this issue with the following steps:
1. Login to Rancher
2. Provision a Linode, AWS or other nodedriver RKE1 cluster
3. Reload and navigate to the Dashboard page
4. Observe that the cluster is labelled as "Custom RKE1"

**Result**
Now the cluster is labelled with the correct provider instead of `Custom`
![image.png](https://zube.io/files/rancher/d81f27159d385e38e917df0655b62948-image.png)
