### ISSUE TITLE
Cluster Overview - Discrepancy in resource naming between Overview Page and Cluster Explorer Nav 

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#887]
Rancher `master-head (07/23/2020)` _fd3e37bec_ k8s HA install.
dashboard-index -> `latest`

- Deploy any cluster type
- Navigate to Dashboard landing in the Cluster Overview page.
- Observe the Naming in the Overview page
- Compare how the resources naming is displayed in Cluster Nav 

Cluster Explorer Nav is using **Singular** naming
Cluster Overview Page is using **Plural**

Example with Namespace(s):

![Screen Shot 2020-07-23 at 2 36 00 PM](https://user-images.githubusercontent.com/27659/88341129-e044a080-ccf1-11ea-86a1-1cec83d9f66a.png)

![Screen Shot 2020-07-23 at 2 35 48 PM](https://user-images.githubusercontent.com/27659/88341143-e9357200-ccf1-11ea-9049-86d56a97f796.png)

**Comment by codyrancher** [comment]
I didn't change this to make everything singular. Instead I updated this so that it will display singular when it's 0 or 1 and plural otherwise. I went with this due to Vince's comment https://github.com/rancher/dashboard/pull/870#issuecomment-662401520.

If we don't like it being singular for 0 please make sure we want that to change this globally and open a new issue as this is using the labelFor method which is used all over the app.

**Comment by vincent99** [comment]
Yeah 0 should be plural in english (0 pods, 1 pod, 2 pods); `if ( count !== 1)`.

**Comment by izaac** [comment]
@codyrancher if I understand @vincent99's requirements correctly we should use plural for `0`. But that's not the case in the latest dashboard.

![Screen Shot 2020-07-31 at 9 31 11 AM](https://user-images.githubusercontent.com/27659/89056404-cff37d80-d310-11ea-8d09-c0a0ea9b6237.png)

**Comment by vincent99** [comment]
The pluralizer in type-map/labelFor is just wrong, it should be `if ( count !== 1 )`

**Comment by izaac** [comment]
Rancher version `master-head (08/13/2020)` _d19f179c4_

Validated that the pluralization is now consistent.
