### ISSUE TITLE
Add HorizontalPodAutoscaling behavior fields to UI form

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#9032]
**Is your feature request related to a problem? Please describe.**
Kubernetes added additional functionality to HorizontalPodAutoscalers to configure the autoscaling behavior. This has been stable since Kubernetes 1.23.
These new fields should also be configurable through the HPA edit form and displayed on the HPA detail page

**Describe the solution you'd like**
* Add form fields to edit the autoscaling behavior in the HPA edit form
* Add autoscaling behavior information on the HPA detail page

**Additional context**
Documentation https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior
API Reference https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerSpec

**Comment by git-ival** [comment]
Confirmed the expected Behavior-related form and detail views were visible. 

Was able to:
- Create an HPA with Behavior fields 
- Modify Behavior fields on an existing HPA
- Create an HPA outside of Rancher and view the full details in Rancher's UI


HPA Create:
![Image](https://github.com/rancher/dashboard/assets/85186645/20f43a41-c78c-4f35-8253-9a21391253d0)

HPA Detail:
![Image](https://github.com/rancher/dashboard/assets/85186645/280cf162-6385-46b7-bfe8-5af493336f97)

HPA Edit:
![Image](https://github.com/rancher/dashboard/assets/85186645/3543686d-24fe-4405-b06e-1dd8d453a045)
