### ISSUE TITLE
Cluster Tools only showing Longhorn

### ISSUE THREAD

**Issue by jmilliancourt** [rancher/dashboard#9072]
Hello,

In the Cluster Tools page, I only have Longhorn. I need to install Monitoring but I can't.

What am I missing?

Provider: Other
Kubernetes Version: v1.27.2

Versions
Rancher 	v2.7.3
Dashboard 	v2.7.2
Helm 	v2.16.8-rancher2
Machine 	v0.15.0-rancher98

![Capture d’écran 2023-06-08 à 14 58 39](https://github.com/rancher/dashboard/assets/92039783/0391f160-44be-45ab-85b1-d65a8a987c41)

**Comment by frank-at-suse** [comment]
Cluster Tools have a minimum/maximum range of compatible K8s versions specified in their Charts.yaml, i.e.:

`cattle.io/kube-version: '>= 1.21.0-0 < 1.27.0-0'`

Running v1.27 will filter out every Cluster Tool _except_ Longhorn, which specifies no max version in its Charts.yaml:

`cattle.io/kube-version: '>= 1.21.0-0'`

**Comment by Cenness** [comment]
Is there a workaround?

Or any plans to update your charts?
1.27 released on Apr 11, months ago
1.28 released on Aug 15, more than a month ago

**Comment by richard-cox** [comment]
The max kube version for 2.7.3 (with is EOM in a few days, and EOL in November) is 1.25.

For info on Rancher versions see [here](https://www.suse.com/lifecycle/#suse-rancher-prime) and the kube versions they support see the [support matrix](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-3/).

**Comment by ryzior** [comment]
hi
the problem is most likely not related with rke/k8s vs rancher version (I 'm running rke2 v 1.31 and rancher 2.11 which supports anything below 1.33 ) but I can only see Elemental and Longhorn on the Tools list .
Right after rancher got isntalled I had a pretty long list of tools there but now it is gone and this is why Im seeking some general solution instead of digging into helm charts and updating manually etc.) 
is there any solution for that ?
