### ISSUE TITLE
Loading Indicator taking 7s+ when using sidenav in Cluster Explorer

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9076]
Internal reference: SURE-6372
Reported in 2.7.3

When using Cluster Explorer in Hosted Rancher (support cloud) on 2.7.3, if the user navigates between top menu items in the sidenav, it often takes 7-15s to load

Switching between sub menu items loads immediately

Checking devtools, it looks like the biggest culprit is the fact its reloading schemas every time, which is a call taking 7s+

Important Notes:

The user has a single node K3s cluster running Rancher on Rancher Desktop on their home laptop which is the cluster they're exploring

They have a test custom cluster with 0 attached nodes in a reconciling state

@leflambeur may have more details upon request.

**Comment by richard-cox** [comment]
I've logged in to the support instance, supplementary findings below.

This issue is the same as https://github.com/rancher/dashboard/issues/9196, resolved by https://github.com/kubewarden/ui/pull/395 and made available in https://github.com/rancher/ui-plugin-charts/pull/15.

@jordojordo to confirm, is KubeWarden 1.0.6 ready for public consumption? If so, will let the owners of the support instance know they need to update

Bonus info
- The instance is pretty slow. 
  - First log in (possible init stuff happening?)
    - v1/management.cattle.io.setting 4s
    - v1/management.cattle.io.cluster 11s
    - v1/counts 10s
    - v1/userpreferences/u-aekkhgiy53 10s
  - On refresh (much faster)
    - rancherversion. 4s. 1s. 1.6s
    - everything else 200/300ms
 - legacy apps --> global configuration (/dashboard/c/_/mcapps/pages/catalogs)
   - white page error! `Cannot read properties of null (reading 'doneOverride')`  
   - user didn't haven any cluster / project roles. not sure of global roles.
   - user had no clusters
   - fine on local 2.7.5rc2 as admin

**Comment by jordojordo** [comment]
@richard-cox correct, Kubewarden `1.0.6` has been [released](https://github.com/kubewarden/ui/releases/tag/kubewarden-1.0.6) and is available from the main repo as well as the [ui-plugin-charts](https://github.com/rancher/ui-plugin-charts) repo.

**Comment by richard-cox** [comment]
Support instance has been updated and I've validated the issue no longer occurs. 

I'm gonna tag this with QA/None and close.
