### ISSUE TITLE
Add Kubectl Explain Interface

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9107]
SURE-6343

Allow users to see the equivalent of `kubectl explain` in the Rancher UI - for a given resource, be able to see the details of the resource.

**Comment by nwmac** [comment]
Check with @nwmac before starting

**Comment by gaktive** [comment]
This is more of a Q4 thing but depending on the work required, we could start in Q3.

**Comment by gaktive** [comment]
@kwwii to hash out a design.

**Comment by kwwii** [comment]
Design is here: https://xd.adobe.com/view/c78ea9cd-f9d5-423c-9ee5-049b02500279-92dd/

**Comment by gaktive** [comment]
Shell execution command can be seen here: https://github.com/rancher/dashboard/pull/8992

**Comment by kwwii** [comment]
We need to define which options are configurable, if any (it might be a simple on/off switch?).

**Comment by nwmac** [comment]
Just opening the shell like this is not good enough

**Comment by brudnak** [comment]
Not seeing `kubectl explain` UI element for global roles: https://github.com/rancher/dashboard/issues/9871

**Comment by brudnak** [comment]
# Setup


| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version starting         | v2.8-fc12e7d779577d10ded1a8e249f51727848b878e-head                                 |
| Rancher version upgraded         | not applicable / `fresh install`                                                   |
| Rancher commit link              | https://github.com/rancher/rancher/commit/fc12e7d779577d10ded1a8e249f51727848b878e |
| Installation option              | Docker                                                                             |
| Cert Details                     | `--acme-domain`                                                                    |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | not applicable                                                                     |
| Downstream K8s version           | not applicable                                                                     |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin                                                                              |
| Browser type                     | Firefox Developer Edition                                                          |
| Browser version                  | 119.0b5 (64-bit)                                                                   |
| Dashboard                        | master 702c54e96                                                                   |
| Webhook version                  | rancher-webhook:v0.4.0-rc10                                                        |
| Rancher env setup via            | https://github.com/brudnak/linode-docker-cattle                                    |

# Describe the bug

Don't see any UI elements for kubectl explain for Global Roles.

# To Reproduce

1. Start Rancher on v2.8-head
2. While logged in as admin, navigate to`Users & Authentication` >>> `Role Templates` >>> `Global`
3. Able to `Edit Configs` at this page
4. Able to `Edit YAML` here

# Result

There is no UI element apparent here to get the kubectl explain for global roles.

# Expected Result

For there to be some UI element that gives the kubectl explain info for global roles.

Especially since these two points should qualify for kubectl explain to be present for global roles.

https://github.com/rancher/dashboard/issues/9107#issuecomment-1652098717

>This API Docs link would appear in 2 places:
>any modal with a YAML editor
>any page where someone could modify the config

**Comment by nwmac** [comment]
For now, this needs to be done from the cluster explorer view. There was a bug which has now been fixed that meant no docs were shown for some RBAC resources.

Go to the local cluster and use the search icon to find a resource, e.g. 'Role', you can view the kubectl explain docs for these resources now.

**Comment by brudnak** [comment]
# ✅ PASSED

## Reproduction Environment

Reproduction not required.

## Validation Environment



| Component                        | Version / Type                                                                     |
| -------------------------------- | ---------------------------------------------------------------------------------- |
| Rancher version starting         | v2.8-c4847070c39209a65029aa3a43347e4d9bac1d12-head                                 |
| Rancher version upgraded         | n/a                                                                                |
| Rancher commit link              | https://github.com/rancher/rancher/commit/c4847070c39209a65029aa3a43347e4d9bac1d12 |
| Installation option              | Docker                                                                             |
| Cert Details                     | `--acme-domain`                                                                    |
| Docker version                   | 20.10.7, build f0df350                                                             |
| Helm version                     | v2.16.8-rancher2                                                                   |
| Downstream cluster type          | n/a                                                                                |
| Downstream K8s version           | n/a                                                                                |
| Authentication providers enabled | local                                                                              |
| Logged in user role              | admin                                                                              |
| Browser type                     | Firefox Developer Edition                                                          |
| Browser version                  | 119.0b9 (64-bit)                                                                   |
| Dashboard                        | master 15a9f8547                                                                   |
| Webhook version                  | v0.4.0-rc10                                                                        |



<a name="top"></a>

### :muscle: Test Cases

| \#  | Priority | Description & Link            | PASS/FAIL |
| --- | -------- | ----------------------------- | --------- |
| 1   | P0       | [kubectl explain ui](#test-1) | ✅ PASS    |

<details>
    <summary>🚨 1 test case... CLICK TO EXPAND! (For table links to work) ⬅️</summary>

<br>

# 1 / Status: ✅ PASS

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. Check global role kubectl explain
2. Go to the local cluster and use the search icon to find a resource, e.g. 'Role', you can view the kubectl explain docs for these resources now
3. Check kubectl explain for projects

**✅ Expected Outcome**

To be able to find kubectl explain output in the UI

**✅ Actual Outcome**

Seeing kubectl explain options for RBAC now


</details>

<hr>

</details>
