### ISSUE TITLE
E2E Tests are flakey

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9120]
Identify and fix flakey tests.

May need to add appropriate checks for elements being visible/available - tests may run fine on a fast box, but not on a slower one.

Flakey tests:

**`preferences.spec.ts` - 1) Can navigate to Preferences Page**

`AssertionError: Timed out retrying after 60000ms: Expected to find element: `[data-testid="user-menu-dropdown"]`, but never found it.`

**Comment by richard-cox** [comment]
WIP - Brief initial findings

# Timins
Baseline - https://github.com/rancher/dashboard/actions/runs/5245832081/jobs/9473832080
Disabling Recording (videos on) - https://github.com/rancher/dashboard/actions/runs/5266079336/jobs/9519532031?pr=9122
Disabling Videos - https://github.com/rancher/dashboard/actions/runs/5266241986/jobs/9519921253?pr=9122

Baseline  | Disabling Recording (videos on) | Disabling Videos
|--|--|--|
30 seconds | 23 seconds | 19 seconds 
| 13 minutes, 36 seconds | 8 minutes, 16 seconds | 5 minutes, 17 seconds 
| 3 minutes, 26 seconds | 2 minutes, 11 seconds | 1 minute, 32 seconds 
| 4 minutes, 10 seconds | 3 minutes, 9 seconds | 2 minutes, 27 seconds 
| 20 seconds | 14 seconds | 11 seconds 
| 26 seconds | 18 seconds | 13 seconds 


# Flaky test (success on retry)

Performance / Inactivity
- should reset the settings - showed inactivty modal because page took too long to load http://139.59.134.103/instance/0827f541-9f5d-4509-81a3-64ca2f852af3/others/RECORDED_VIDEO

Preferences
- Can select Hide All Type Description Boxes - 10s wait to nav to page failed as page took too long to load http://139.59.134.103/instance/66d5fa8b-983d-4bde-9ea4-3dbc0c23fa51/others/RECORDED_VIDEO

Workloads / Pods
- Should have same spec as the original pod - wait for request to fetch specific pod times out as page took too long to load http://139.59.134.103/instance/925b8f24-6c91-41a9-a8c4-f861e05ed37e/others/RECORDED_VIDEO

**Comment by richard-cox** [comment]
Given these three PRs tests should be running better now. We'll monitoring and then close this issue

https://github.com/rancher/dashboard/pull/9063
https://github.com/rancher/dashboard/pull/9123
https://github.com/rancher/dashboard/pull/9143

**Comment by richard-cox** [comment]
Tests look pretty stable, except for a few probably in dev runs. They're also running at around the 40 minute mark.  https://github.com/rancher/dashboard/actions/workflows/test.yaml.

Think we're safe to close this now
