### ISSUE TITLE
Can't edit yaml of my own installed app

### ISSUE THREAD

**Issue by liujin1993** [rancher/dashboard#9125]
**Setup**
 Rancher version: v2.7.3

**To Reproduce**
- helm install something using cmdline
- edit it in rancher ui

**Result**
can't select chart

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/31949674/f0e19b91-f8e4-4825-bfd8-21b545615ed4)

![image](https://github.com/rancher/dashboard/assets/31949674/117aedad-cd34-4060-81ec-544872923e94)

**Comment by richard-cox** [comment]
Does the helm repository and chart where the app was originally installed still exist (i.e. you can find the chart in it in the Apps / Charts list)?

**Comment by liujin1993** [comment]
> Does the helm repository and chart where the app was originally installed with still exist (i.e. you can find the chart in it in the Apps / Charts list)?

Yes, it still exist. `helm list` can see it.

**Comment by liujin1993** [comment]
> Does the helm repository and chart where the app was originally installed with still exist (i.e. you can find the chart in it in the Apps / Charts list)?

I installed app using command line instead of dashboard, so the chart not in the Apps / Charts list

**Comment by richard-cox** [comment]
Rancher under the hood uses the helm cli and just like the cli it needs to know the chart in order to do the helm upgrade to apply the changes to values.

Rancher will be able to manage any installed app if it can for the chart for it, whether installed by UI or cli. So you should be able to add the helm repo https://kubernetes.github.io/ingress-nginx in the Apps / Repositories section and then select the chart  in the dropdown shown in the edit/upgrade wizard in your screenshot.
