### ISSUE TITLE
Cluster explorer page navigation does full page reloads

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#9196]
**Setup**
- Rancher version: >=2.7.2
- Rancher UI Extensions: Kubewarden and Elemental installed
- Browser type & version: Chrome

**Describe the bug**
When navigating to different sub pages in the cluster explorer, the UI shows a complete loading screen and does a full repaint, instead of just rendering the new section.

This seems to happen only when you switch between different products, e.g. Workload to Apps/NeuVector/Kubewarden. But not form Pod to Deployment.

It may also have something to do with having extensions present. I haven't seen it yet, when there is no extension yet.

**To Reproduce**
Install the kubewarden extension and navigate between different pages in cluster explorer.

**Result**
Sometimes a full reload and repaint is peformed.

**Expected Result**
Only the changed section is repainted.

**Screenshots**

https://github.com/rancher/dashboard/assets/243056/f10a9b47-2342-4a35-b087-c4658adee485

**Comment by richard-cox** [comment]
@bashofmann could you confirm if it's a specific extension, or it happens with neither extension installed? Does it happen if you switch between non-extension products like monitoring and logging?

**Comment by bashofmann** [comment]
@richard-cox I tested it now with a fresh 2.7.4 install:

* Fresh install: navigation behaves normally, also with monitoring and logging
* Installed extensions operator: navigation behaves normally, also with monitoring and logging
* Installed elemental extension: navigation behaves normally, also with monitoring and logging
* Installed kubewarden extension: the issue appears

If the issue is present, switching back and forth between monitoring and logging works. But if I then change back to the pod list, the issue appears.

**Comment by richard-cox** [comment]
Thanks.

We think https://github.com/rancher/dashboard/issues/9196 and https://github.com/rancher/dashboard/issues/9205 are both related to the same bug. The Kube Warden extension is missing a fix that stops extensions from grabbing generic routes (which makes the UI think it's navigating through a different extension product). Good news, this should just mean we fix and release a new kube warden, rather than having to wait for a Rancher release.

**Comment by jordojordo** [comment]
This has been fixed with the release of [Kubewarden 1.0.6](https://github.com/kubewarden/ui/releases/tag/kubewarden-1.0.6) and the update can also be found within the [ui-plugin-charts](https://github.com/rancher/ui-plugin-charts) repository. Kubewarden will need to be updated to resolve this issue.

**Comment by Josh-Diamond** [comment]
Ticket #9196 - Test Results - ✅ 
---

Verified w/ HA Helm Rancher on `v2.7-5f98b0f28bc8a48366e9ced8f0a0fea3d826d90d-head`:
1. Fresh install of Rancher `v2.7-head`
2. Install kubewarden extension - (global UI plugin)
3. Provision a downstream cluster 
4. Once `active`, navigate to `Cluster Explorer > Kubewarden` and configure kubewarden for the downstream cluster
5. Once configured, navigate between `Cluster Explorer > Workloads` and `Cluster Explorer > Kubewarden`
6. Verified - only changed section is repainted; side navigation no longer re-fetches; as expected
