### ISSUE TITLE
Remove Support for AWS In-Tree Cloud Provider if Using k8s 1.27+

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9204]
Internal reference: SURE-6511

With Kubernetes 1.27 and up, the AWS in-tree cloud provider no longer works so we need to ensure that users upgrading from earlier versions are aware and have a way to migrate off of it.

From Hostbusters, @kinarashah is looking at how the upgrade works from the backend. @Sahota1225 & @snasovich are aware of the UI needs. We'll need to figure out the UX around this with the appropriate advance notifications prior to upgrade and then the behaviour during upgrade: having radio buttons disabled, proper dropdowns, banners, etc.

@mantis-toboggan-md knows the basic details.

**Comment by gaktive** [comment]
Awaiting backend on their design. Based on the current schedule, this feels at risk for Q3 as is since we don't want a lot of churn on banners.

**Comment by gaktive** [comment]
Confirmed with @Sahota1225 that this will be Q4.

**Comment by kinarashah** [comment]
We would need to fix https://github.com/rancher/dashboard/issues/9249 so nodeSelector can be updated to the desired values for RKE1 clusters.

**Comment by nwmac** [comment]
See internal confluence for UX required herre

**Comment by gaktive** [comment]
No E2E since this will be developed connecting to AWS and then tested manually by QA.

**Comment by mantis-toboggan-md** [comment]
The RKE1 side is in https://github.com/rancher/ui/pull/5064

**Comment by slickwarren** [comment]
tested on v2.8-head (a6b908d): 
* for rke1, the in-tree option is removed when 1.27 is selected
* there is now the additional option validated in a separate PR for out-of-tree / external-aws 
* upgrades from previous versions (i.e. 1.26 -> 1.27_ display an alert in the `cloud provider` section of the UI, instructing the user to supply an out-of-tree configuration

Reopening for the following use case: on upgrades, currently the existing (generic) external option is selected. Can we please make the default when upgrading rke1 clusters with an in-tree -> 1.27+ to be the `External Amazon (Out-of-tree)` option? 

Also a small change if it can be done since you're already there, the current wording has every word's first letter capitalized for In-Tree, but only Out in Out-of-tree is capitalized for external options. Can this be updated to both have the first letter capitalized? 
![image](https://github.com/rancher/dashboard/assets/16691014/b772b20b-10f3-4a93-a048-0b877e5da953)

**Comment by slickwarren** [comment]
one last part that we want added to protect customers from misconfiguring their setup. Can we add an alert for rke1 in the case that:
* a custom cluster is upgraded / set to use external-aws, if they know the cloud provider will configure node name different than ec2's default service, they should set `use_instance_metadata_hostname: false` instead of true.

**Comment by kinarashah** [comment]
Discussed with @slickwarren offline, decided on this blob to make it more explicit: 

> External Amazon enables use_instance_metadata_hostname which sets hostname-override from ec2's instance data (http://169.254.169.254/latest/meta-data/hostname) to meet the [prerequisites](https://cloud-provider-aws.sigs.k8s.io/prerequisites/). 
Users can disable use_instance_metadata_hostname if custom node-name is set for custom clusters to match the cloud provider's node name conventions. 
Configuring a Cloud Provider in your cluster without configuring the prerequisites will cause your cluster to not provision correctly. Prerequisites needed for supported cloud providers can be found in the documentation.

**Comment by kwwii** [comment]
Usability-wise, this text is much too long for the average user to read or comprehend.

**Comment by slickwarren** [comment]
here's what's currently in the UI, as a reference for length:
```
External Amazon enables use of useInstanceMetadataHostname. When useInstanceMetadataHostname is enabled, RKE will configure node name from ec2 metadata service. 

Configuring a Cloud Provider in your cluster without configuring the prerequisites will cause your cluster to not provision correctly. Prerequisites needed for supported cloud providers can be found in the documentation.
```

would the following be acceptable? 
```
External Amazon also enables use_instance_metadata_hostname which sets hostname-override from ec2's instance data to meet the [prerequisites](https://cloud-provider-aws.sigs.k8s.io/prerequisites/).
See [the documentation](https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon) for more information.
```

**Comment by nwmac** [comment]
@kwwii Is this text change absolutely necessary for 2.8.0? If so, can you confirm the exact text you think works.

**Comment by kwwii** [comment]
The changes @slickwarren is suggesting do seem to explain the situation much better and are much more specific. If we can still squeeze this in, it will save some user headaches

**Comment by slickwarren** [comment]
The text change would be great, but the main ask for the reopen was to have this message in both the fresh install and upgrade use cases. I thought that it would be easy to make the text change since it is missing from the upgrade use case.

**Comment by nwmac** [comment]
Updated fix is in: https://github.com/rancher/ui/pull/5082/files

Given timing, we will not change the banner content at this time - we will revisit later.

**Comment by gaktive** [comment]
PR is merged so back to QA @slickwarren
