### ISSUE TITLE
Extensions: support developing Rancher Desktop extension

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#9216]
- Provide support for developing Rancher Desktop as an extension with @rak-phillip 

## TODO

- [ ] rancher/dashboard#9477

## Related Issues

- rancher-sandbox/rancher-desktop#2822
- Original issue: rancher/dashboard#9070
- Structure for routes and navigation https://github.com/rancher/dashboard/issues/9307
## Related PRs
- https://github.com/rancher/dashboard/pull/9279 -> add ability to override `layouts` in shell
- PR for 9307: https://github.com/codyrancher/rancher-desktop/pull/1

**Comment by gaktive** [comment]
This will be expanded as the extension task force and @rak-phillip hammer out what work is required in separate tickets. 

This is somewhat independent on pure Rancher milestones since it ties more into Desktop. Will move to Q4 from a tracking perspective but this should be worked on in parallel with existing dashboard releases.

**Comment by rak-phillip** [comment]
I created a high-level punch list for what the offline mode needs to support in #9477
