### ISSUE TITLE
Login page link to switch to AP provider is hidden behind log in button

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9252]
**Setup**
- Rancher version:
- Rancher UI Extensions: post 2.7.5
- Browser type & version:

**Describe the bug**
- Link to switch log in page to the AP log components is hidden behind the button to log in as local user

**To Reproduce**
- Setup auth provider (github is easiests
- log out
- switch to local user view

**Result**
- see screenshots

**Expected Result**
- switch screenshots around

**Screenshots**
## Before
![image](https://github.com/rancher/dashboard/assets/18697775/872c7f91-3a68-4558-ada4-8b8c316eb0ad)

## After
![image](https://github.com/rancher/dashboard/assets/18697775/3098ade4-7625-405f-a8ed-8e720856a9d7)

**Additional context**

**Comment by richard-cox** [comment]
See https://github.com/rancher/dashboard/pull/9261#issuecomment-1620365251

**Comment by richard-cox** [comment]
Automation failed, moving to test

**Comment by ronhorton** [comment]
**Pass** verified fixed in rancher `v2.7-head commit ID 027246f `
1. navigated to hamburger > users & authentication
2. clicked on auth provider
3. enabled github oAuth
4. logged out
5. naviagated to rancher URL in incognito window
6. confirmed login options as expected

![2023-08-01_13-42-12.png](https://zube.io/files/rancher/b955ab011de4f88f1024451ede8275d2-2023-08-01_13-42-12.png)
