### ISSUE TITLE
[BUG]The Pod Security Admission configuration of the Namespace seems to be incompatible with the Labels.

### ISSUE THREAD

**Issue by DaiYuzeng** [rancher/dashboard#9288]
**Rancher Server Setup**
- Rancher version: **v2.7-head**
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream): **Local**
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:

**Describe the bug**

The Pod Security Admission configuration of the Namespace seems to be incompatible with the Labels.

**To Reproduce**

1. Go to Namespace create page.
2. Switch to `Pod Security Admission` tab, and check all.
3. Switch to `Labels & Annotations` tab, add a label.
4. Save.
5. Go to edit the Namespace just created.
6. Switch to `Pod Security Admission` tab, and uncheck all.
7. Switch to `Labels & Annotations` tab, remove the label we added.
8. Save.
9. Go to edit page, you will notice that the configuration has not been updated.

**Result**

**Expected Result**

The configurations of `Pod Security Admission` should be updated successfully.

**Screenshots**

https://github.com/rancher/rancher/assets/15041915/071f71b8-4c0f-4537-951d-5d08b31f5e5a

**Additional context**

**Comment by anupama2501** [comment]
Reproduced the issue on v2.7.5

Steps:
1. Created a downstream node driver rke1 cluster 
2. From cluster explorer >> Project & namespaces, created a Project 
3. Created a namespace ns1 in the project and enabled all the psa labels and from labels & annotations added a new label
4. Edited the namespace, unchecked all the psa labels and removed the newly added label and save.
5. Verified the psa is not disabled.

Verified on v2.7-head `027246f`
Verified on a k3s node driver cluster the issue is not seen anymore.
Verified editing the namespace, removing labels but not the psa tags, will not disable the psa.
Verified on an upgraded server, previously errored namespace works fine too.
