### ISSUE TITLE
Standard users are unable to view workloads for a downstream cluster

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#9336]
**Setup**
- Rancher version: v2.7-head (37ef305)
- Rancher UI Extensions: NA
- Browser type & version: Firefox 116.0b3 (64-bit)

**Describe the bug**

Attempting to list or navigate to a workload as a standard user, results in a `Error Resource type pod not found` message. 

**To Reproduce**

1. Log into Rancher Dashboard as the Admin user
2. Navigate to Cluster Management => Create
3. Create a new RKE2 Cluster with Digital Ocean as the cluster provider, accept all defaults
4. Navigate to Users & Authentication => Create
5. Create a new user with "Standard User" selected under Global Permissions
6. Navigate to Explore Cluster & select your newly created cluster from Step 3
7. Navigate to Workloads => Pods
8. Create a simple pod with `nginx:latest` as the image, give it a name and accept all defaults
9. Navigate to Cluster & Project Members => Project Membership
10. Click on "Add" for the Default group
11. Add the user created in Step 5 as a Member
12. Log into Rancher Dashboard as the user created in Step 5 
13. Navigate to Explore Cluster and select the cluster created in Step 3
14. Select Workloads => Pods

**Result**

We are directed to the error page with a message that reads `Error Resource type pod not found` 

**Expected Result**

A list of Pods is displayed, including the pod created in Step 8.

**Screenshots**

![image](https://github.com/rancher/dashboard/assets/835961/7fc0e0d9-c6c5-4666-867d-8d44baeec5a3)

**Additional context**

Navigating to Workloads as the user created in Step 5 will successfully list all of the workloads. Attempting to select on of these workloads will produce the error.

**Comment by richard-cox** [comment]
Note for QA. All three of these should be tested together
- https://github.com/rancher/dashboard/issues/9336
- https://github.com/rancher/dashboard/issues/9352
- https://github.com/rancher/dashboard/issues/9354

**Comment by mantis-toboggan-md** [comment]
@Josh-Diamond I _think_ that's expected behavior. I found that once the standard user/cluster member created a namespace in the cluster they could see the workload section. By default I think cluster members can't see other users' projects, per: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/cluster-and-project-roles#cluster-role-reference...so in this scenario they'd not be able to see the deployment created in the "Default" namespace. A standard user added as a member of a project with at least one namespace can see the workload section, which aligns with the repro steps outlined in this issue.

Cluster explorer nav items are only visible when the user can access the schema for that resource/one of the resources in a given section. Honestly, I'm not sure if it's intentional that a user can't see schemas for anything in the 'workload' section until they have access to a namespace in that cluster, but what the UI is showing is in alignment with what the API is giving us in that scenario so if that is a bug it would be an api/be bug.

**Comment by Josh-Diamond** [comment]
@mantis-toboggan-md thank you, you are correct!  I mistakenly added the standard user as a Cluster Member, and not as a Project Member.  Re-validating this now.

**Comment by Josh-Diamond** [comment]
Ticket #9336 - Test Results - ✅ 
---

Verified w/ HA Helm on Rancher `v2.7-1955476d97db1d030b6578a9385ae5e0e185cc0d-head`:
1. Fresh install of Rancher `v2.7-head`
2. As admin, provision a downstream RKE2 cluster - [ i spun up AWS Node driver w/ k8s `v1.26.6+rke2r1` ]
3. Once `active`, deploy a workload in the default namespace
4. Once deployment is `active`, navigate to `Users & Authentication` and create a new standard user
5. Once created, navigate to `Cluster Explorer > Cluster and Project Members > Project Membership > Default (namespace) > Add`, and add standard user created in step 4, as `Project Member`
6. Log out as Admin
7. Log in as Standard user
8. Navigate to `Cluster Explorer > Workloads > Pods`
9. Verified - Pod details page successfully renders; as expected
