### ISSUE TITLE
Auth Providers: Autofill incorrectly applies to service account distinguished name and password fields

### ISSUE THREAD

**Issue by nflynt** [rancher/dashboard#9509]
**Setup**
- Rancher version: Shown here in v2.7.4, still present in v2.7.5
- Rancher UI Extensions: None
- Browser type & version: Chrome Version 115.0.5790.170 (Official Build) (64-bit)

**Describe the bug**
When configuring any LDAP-based authentication provider, Chrome seems to be incorrectly recognizing the service account related fields as autofill targets. In dark mode, Chrome's styling obscures the field names, so this may not initially look "wrong" to a new user.

**To Reproduce**
- Setup Rancher, log in at least once, and let Chrome save the username and password.
- Head to Users and Authentication, then begin setting up any LDAP-based provider

**Result**

The autofill is incorrectly applied to the service account fields. In dark mode, the styling obscures the field name:

![rancher_autofill_service_account](https://github.com/rancher/dashboard/assets/122321752/fd671b28-55c0-4511-bd50-e343a98b83c4)

**Expected Result**

Autofill does not apply to these fields, and the field name remains unobscured:

![rancher_autofill_service_account_fixed](https://github.com/rancher/dashboard/assets/122321752/86a19616-5fce-405b-8b05-69a4dd5010cb)

**Additional context**

This applies to the initial setup flow, not to edits. Once an LDAP provider has been saved, the field is later populated with the previous values and autofill does not override in that case. This also applies to SAML providers that support an LDAP backend (Okta and Shibboleth)

**Comment by richard-cox** [comment]
There's basically a weird arms race between developers, browsers and password managers. We'll forget about the last one because it's impossible for us to win and not referenced as the culprit here.

All our standard input fields should have `autocomplete="off"` which should mean browsers won't auto populate them. However chrome and a few others ignore this. There's hacky ways to do this which change over browser release (setting odd id's, having a hidden element, etc). We should look at these again, but time box any investigation

**Comment by richard-cox** [comment]
Unfortunately taking on browser's handling of autocomplete isn't something planned at the moment.

More detail in https://github.com/rancher/dashboard/issues/5273
