### ISSUE TITLE
Service Issues from CruResource Component Updates

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#966]
**Create/Edit Page**
- ~[ ] Missing the subtype in masthead on the second screen. It should say something like  `Service: Create ClusterIP`?~ _Broken into new [ticket](https://github.com/rancher/dashboard/issues/1073)_

<img width="828" alt="Screen Shot 2020-08-05 at 2 32 15 PM" src="https://user-images.githubusercontent.com/11410997/89466354-851aa100-d728-11ea-9ccf-a013ae23f12b.png">

- ~[ ] Can the buttons be static on the bottom of the screen? So they are sticky towards the footer? When the content of the tabs change they jump up and down.~ _Broken into new [ticket](https://github.com/rancher/dashboard/issues/1074)

<img width="1040" alt="Screen Shot 2020-08-05 at 2 55 38 PM" src="https://user-images.githubusercontent.com/11410997/89468173-bfd20880-d72b-11ea-8631-6e3d71e4749c.png">

**Detail Page**

Service Detail
- [x] Hide the buttons at the bottom of the detail screen
<img width="1035" alt="Screen Shot 2020-08-05 at 2 36 51 PM" src="https://user-images.githubusercontent.com/11410997/89466684-23a70200-d729-11ea-920a-da81c5be0df8.png">

**Edit Page**

- [x] Hide the `Preview Yaml` button on edit since you are going to select to edit as form OR edit as yaml from the  action menu. 

<img width="1043" alt="Screen Shot 2020-08-05 at 2 39 08 PM" src="https://user-images.githubusercontent.com/11410997/89466865-6ff24200-d729-11ea-8414-965e699c65af.png">

**Comment by vincent99** [comment]
> Can the buttons be static on the bottom of the screen? So they are sticky towards the footer? When the content of the tabs change they jump up and down.

I hacked this into the App install pages independently and like it.  If you're going to implement everywhere the whole main body should probably become a css grid (like the outer page nav is `layouts/default`) so that it can adjust to different height content properly (and be arranged completely different for small screens easily)

**Comment by izaac** [comment]
Rancher version: `master-head (09/08/2020)` _76c26fb0f_

- Hide the buttons at the bottom of the detail screen ✅ 
- Hide the `Preview Yaml` button on edit since you are going to select to edit as form OR edit as yaml from the action menu. ✅ 

Validated these requirements are met in the latest master and dashboard index.
