### ISSUE TITLE
Clicking on "Use the default value" button breaks the app on Global Settings page => Server URL section

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#9690]
**Describe the bug**

Seeing during rancher/dashboard#8893 , default value for server-url is `null` that causes the app to break since `isHttps` validator relies on receiving a string. Two things should be considered while fixing this:

1. Adding optional chaining to the validator
2. Save button should be disabled if the value for server-url is a falsy value.

**Steps to reproduce**

1. Go to Global Settings page
2. Scroll down to server-url section
3. Click on the three dots menu and choose "Edit"
4. Click on "Use the default value" button

**Screenshots**

<img width="1656" alt="image" src="https://github.com/rancher/dashboard/assets/135728925/c5acc702-fc94-42b2-8da9-f0e232e3ec34">

**Comment by richard-cox** [comment]
The underlying full page error won't show now, but the error remains and the value isn't set to the default

The root issue is that the default value for server-url is `null`, which i'm guessing we're trying to lowercase. Possible solution... we should convert that `null` to an empty string? which means we save `""` instead of `null`, not sure of the impact

**Comment by momesgin** [comment]
@richard-cox This issue is fixed on my [other PR](https://github.com/rancher/dashboard/pull/9701) for server-url validations. I will close this when that PR is merged. I'll ping Gary to ask if we might want to include it in 2.8.0.
