### ISSUE TITLE
degraded performance

### ISSUE THREAD

**Issue by leticiabedoniaz** [rancher/dashboard#9692]
hey guys,
I use Rancher in my company to manage Kubernetes, we have many resources in specific clusters, for example +8,000 pods, +2,000 deployments and these clusters take a long time to load, which generates user dissatisfaction.

How can I improve the performance of my Rancher to reduce the slowness in accessing these resources?

I found some topics about this but they didn't work for me, as none of them had as many resources as my clusters.

Rancher version 2.6.8

**Comment by richard-cox** [comment]
We would recommend upgrading to the latest Rancher version. There have been a number of UI and API performance improvements since 2.6.8.

Most of these can be enabled by going to the burger menu --> `Global Settings` --> `Performance` tab. The one you might be most interested in is `Require Namespace / Project Filtering`. That restricts the resources fetched by the UI to the resources in the namespaces/projects filter in the header bar.

In the future we will be bringing in fully paginated requests.

Generally though, you will need to check how the API requests are performing. If these take a long time to respond, even for resources with low counts, you will need to investigate improving the performance of the Rancher instance.

**Comment by leticiabedoniaz** [comment]
I updated to version 2.7.6 but the slowness continues.
The UI freezes and doesn't even let us click on the desired tab.

**Comment by richard-cox** [comment]
Would you be able to test the Performance Setting from the comment above?

Would you also be able to look at the browsers Developer Tools network tab to see if there are any long running network requests?

**Comment by richard-cox** [comment]
No update, closing.
