### ISSUE TITLE
Handle new alpha tags at runtime

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#9734]
The UI acts  slightly differently for RC builds.  We need  to also do the same for alphas

It looks like there's one function we need to update - `isDevBuild`. We need to confirm the version strings for alphas and return true if found

This covers things like using different links but most importantly disabling the auto select of the telemetry check box when setting up rancher.  

Update: We need to do the same in rancher/ui as well to `isDevBuild`. It's probably the exact same content

**Comment by richard-cox** [comment]
For testing Alpha builds should display information as if it were a Release Candidate
- During Rancher setup the Telemetry check box should be un-checked
- References to release notes should be to https://github.com/rancher/rancher/releases/latest (home page 'whats's new' link, about page release notes link)
- home page support link should be to `https://rancher.com/support-maintenance-terms` instead of 'https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-'

**Comment by ronhorton** [comment]
@richard-cox is there QA required on this?

**Comment by richard-cox** [comment]
@ronhorton Yes please, see https://github.com/rancher/dashboard/issues/9734#issuecomment-1733289769

**Comment by ronhorton** [comment]
**Pass** verified in v2.8.0-alpha2
`During Rancher setup the Telemetry check box should be un-checked` default is opt out - **Pass**

`References to release notes should be to https://github.com/rancher/rancher/releases/latest (home page 'whats's new' link, about page release notes link)` - link is to indicated location - **Pass**

home page support link should be to https://rancher.com/support-maintenance-terms instead of 'https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-' - **Pass** when i mouse over the support link on the support page, i see the correct link. 

redirect lands on https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-6/ I spoke to UI about it, and we decided to pass this ticket and create a ticket for docs re: the redirect. That new ticket is https://github.com/rancher/dashboard/issues/9839

**Comment by richard-cox** [comment]
@cnotv This issue has already gone through QA and does not need automation in the 2.8.0 time frame. Can you concentrate on the ones that can remove the strain on QA?

**Comment by cnotv** [comment]
> @cnotv This issue has already gone through QA and does not need automation in the 2.8.0 time frame. Can you concentrate on the ones that can remove the strain on QA?

Sorry it has been taken while I was in holiday, but I was already digging into it.

**Comment by richard-cox** [comment]
@cnotv the PR with unit tests is marked as `fixes` this issue, so changes to it keep re-opening it

**Comment by cnotv** [comment]
Sorry 😓
