### ISSUE TITLE
Uneven space between items from the accounts & Api keys page

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#9881]
Setup

Rancher version: 2.8-head `01127d8`
Browser type & version: Chrome

**Describe the bug**
When we create an API key, the space between Access key and secret key is bigger comparatively with the space between secret key and bearer token.

**To Reproduce**
1. Create a rancher server on v2.8-head
2. Navigate to Profile >> Account and Api keys 
3. Create an API key 

**Result**
Space between Access key and secret key is higher compared to the space between other items on the page.

**Expected Result**
Increase the space between other items as well to maintain uniformity 

**Screenshots**
<img width="600" alt="2023-10-10_14-53-12" src="https://github.com/rancher/dashboard/assets/38144301/14444e3f-5236-4af9-b14f-bc1952138204">

**Comment by aalves08** [comment]
@anupama2501 , since we reverted the changes on the API keys part, the spacing now looks good again so I am going to close this issue.

_Recent Screenshot_
![Screenshot 2023-10-11 at 16 26 59](https://github.com/rancher/dashboard/assets/97888974/6504bc62-72de-482d-88a1-72902e6833b5)


FYI @nwmac @gaktive
