### ISSUE TITLE
Fix problem of directives not being available on extensions

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#9937]
A while ago, both `Elemental` and `Kubewarden` introduced https://github.com/rancher/elemental-ui/pull/116 (there should be an equivalent in `Kubewarden`) to mitigate the fact that extensions after a shell update didn't have certain directives needed to work properly.

What was thought as solution without side-effects has turned out not to be the case. When introducing https://github.com/rancher/dashboard/pull/9928, we've found out they weren't being applied because `Elemental` and `Kubewarden` extensions re-declare the `clean-html-directive` and that overwrites the shell version when testing on Dashboard.

Some of the dynamic views are imported before this happens, so they get the new version in the shell, where as others (e.g. static pages) pick up the version that was overwritten by the extensions.

A solution must be found to mitigate this issue and remove the need to declare directives on the extensions context

**Comment by nwmac** [comment]
The issue is that we bump shell and build extensions against a new version of shell - but we then expect the extensions to work in a version of Rancher that was not built with that version of shell.

The solution, I think is:

- Ensure we version shell properly (semver) and perhaps the extensions API version we currently support should in fact be the shell version.
- Ensure extensions have correct compatibility version for the shell/API
- Have automated tests for extensions, so we detect when things are broken

**Comment by nwmac** [comment]
@aalves08 Is there anything to do here - we updated the code so that extensions can not override the directives already provided

**Comment by aalves08** [comment]
Nothing to do here @nwmac afaik. Problem was mitigated. We can close this.
